### ISSUE TITLE
[improvement] Add hint about old docs

### ISSUE THREAD

**Issue by Jochen1980** [openhab/openhab-docs#1003]
Dear Developers,

I was browsing the docs. First I googled and then I was referred to an old Documentation version. Maybe we should add a javascript alert, popup or notification div, if the docs version is not the same like the stable version.

Best regards,
Jochen

**Comment by Confectrician** [comment]
Late to join the party but:

We have made several changes to the docs and version selectors.

Further information can be found here: https://community.openhab.org/t/important-changes-to-the-documentation-versioning/122369?u=confectrician
