### ISSUE TITLE
[RFC] Rename "Testing Release" to "Milestone Release"

### ISSUE THREAD

**Issue by EliasGabrielsson** [openhab/openhab-docs#1026]
I experience that the lingo that the community use to denote testing releases is _Milestone_ or _Milestone Builds_. Currently we are also using the phrasing _testing releases_ which for example could be found in [linux documentation](https://www.openhab.org/docs/installation/linux.html#apt-based-systems) and in the openHABian menus.

I think it's good to strive for an unify stringent notation to minimize communication confusion within the project and wonder if we should change this to Milestone releases. 

Could you also relate to this or is it just me?
Are there any other kind of testing releases beside milestone build, i.e. _release candidate_?

@BClark09 @Confectrician

**Comment by BClark09** [comment]
Hey @EliasGabrielsson,

You're correct, the testing repo also contains betas and release candidates so restricting the repo name to just milestone may not make sense in the future or indeed for older versions stored in it. 

The names `stable`, `testing` and `unstable` follow the same _maturity_ labels as the main Debian releases (we don't use experimental) which I think provide a good one word description of what to expect from the reliability of the software or its update. wdyt?
