### ISSUE TITLE
Check for broken links regulary

### ISSUE THREAD

**Issue by ThomDietrich** [openhab/openhab-docs#103]
With the current need to rewrite and restructure docs articles, it could be handy to know which links need to be changed.

http://www.deadlinkchecker.com/website-dead-link-checker.asp?u0=http://docs.openhab.org
##

**Comment by ThomDietrich** [comment]
Additionally, transform absolute docs links to relative

**Comment by BClark09** [comment]
You can also use [linkchecker](https://wummel.github.io/linkchecker/)

e.g:
```bash
sudo apt-get install linkchecker
linkchecker -F text/invalidlinks.txt --check-html --check-css --check-extern --ignore-url=^.*/font/ http://localhost:4000/
```

Another (but much less forgiving) alternative is using [html-proofer](https://github.com/gjtorikian/html-proofer#using-with-jekyll) you could even run this with a travis build!
