### ISSUE TITLE
openhab-android docs isn't up to date

### ISSUE THREAD

**Issue by mueller-ma** [openhab/openhab-docs#1048]
I added a new paragraph to the USAGE.md file in the openhab-android repo (https://github.com/openhab/openhab-android/blob/master/docs/USAGE.md#call-state), but it doesn't show up on the docs website: https://www.openhab.org/docs/apps/android.html

**Comment by wborn** [comment]
Maybe it's because the [gather-external-docs](https://ci.openhab.org/view/Documentation/job/gather-external-docs/) Jenkins build is failing @openhab/documentation-maintainers ?

**Comment by wborn** [comment]
The gather-external-docs build also commits files: 

```
git add -A
git commit -m "Updated external content (Jenkins build ${BUILD_NUMBER})"
```

Perhaps `~/.gitconfig` providing the name/email  is missing on those Jenkins Docker agents @kaikreuzer?

The [logging](https://ci.openhab.org/view/Documentation/job/gather-external-docs/346/console) shows: 

```
Run

  git config --global user.email "you@example.com"
  git config --global user.name "Your Name"

to set your account's default identity.
Omit --global to set the identity only in this repository.

fatal: unable to auto-detect email address (got 'jenkins@e5c6fce41691.(none)')
```

**Comment by ghys** [comment]
> Perhaps ~/.gitconfig providing the name/email is missing on those Jenkins Docker agents @kaikreuzer?
I'd assume so. Maybe it would be best to locally reconfigure the name & email every time in the job instead of maintaining the identity gloabally on each agent?

**Comment by wborn** [comment]
Also note that the [merge-docs](https://ci.openhab.org/view/Documentation/job/merge-docs/127/console) build seems to have the same issue.

**Comment by ghys** [comment]
I found the option in Jenkins, set it up like this:
![image](https://user-images.githubusercontent.com/2004147/65817318-f2ef6580-e205-11e9-8a6c-039fe1e6de0d.png)

It should fix this issue, testing now.

**Comment by wborn** [comment]
Great! It all seems to work now and the call state docs are now also available on the website. :smiley:

**Comment by ghys** [comment]
I'll close this then! Thanks for reporting.
