### ISSUE TITLE
Links to the JSON schemas for rules, rule templates and rule modules broken

### ISSUE THREAD

**Issue by rkoshak** [openhab/openhab-docs#1081]
The links on rule-ng.html to the JSON templates for the JSON Rules schemas are broken. The original links on the old ESH docs are:

- module types: https://www.eclipse.org/smarthome/documentation/development/rules/ModuleTypes_schema.json
- rule templates: https://www.eclipse.org/smarthome/documentation/development/rules/Templates_schema.json
- rule instances: https://www.eclipse.org/smarthome/documentation/development/rules/Rules_schema.json

It is not clear whether or not these files made the transition from the ESH site. I couldn't find them in this repo. Though it makes more sense that these files would be in one of the other repos, probably core. I'm not sure the best way to handle this.

**Comment by Confectrician** [comment]
The schemas for binding development are available under the openHAB org domain, so they get in the website build some how.

We should implement a similar workflow for these documentation files.

**Comment by Confectrician** [comment]
Hey @ghys 

Do you think https://github.com/openhab/website/tree/master/.vuepress/public/schemaswould be the correct place for those schemas too? cc @kaikreuzer

**Comment by kaikreuzer** [comment]
I would clearly say YES!

**Comment by ghys** [comment]
Oh yes, of course! ;)
We can simply open a PR to add them at that location on the website repo.

**Comment by Confectrician** [comment]
Perfect. @rkoshak do you want to take care of that?

**Comment by rkoshak** [comment]
Sure, creating the PR right now. Should be submitted in a few minutes.

**Comment by Confectrician** [comment]
This will resolve to opehab.org/schemas/SCHEMANAME.ENDING.

We will have to adapt the broken links too afterwards.

**Comment by rkoshak** [comment]
PR is created.

https://github.com/openhab/website/pull/210
