### ISSUE TITLE
Tag 2.5 release documentation

### ISSUE THREAD

**Issue by ghys** [openhab/openhab-docs#1098]
@openhab/documentation-maintainers 

We should make a 2.5.0 tag and associated branch so that I can add the 2.5 docs snapshot to the website.
Is it ok in the current state or would you like to merge the pending PRs first?

**Comment by kaikreuzer** [comment]
Good point and yes, imho ok to do it now.

**Comment by ghys** [comment]
Alright, I still included the open PRs who were clearly ready to merge, tagging now.

**Comment by ghys** [comment]
The documentation for v2.5 has been added with https://github.com/openhab/website/pull/219. Closing.
