### ISSUE TITLE
Add warnings and/or deemphasize use of PaperUI

### ISSUE THREAD

**Issue by rkoshak** [openhab/openhab-docs#110]
For some context see:

https://community.openhab.org/t/problems-with-items-things-in-habmin-paperui/14777

There are many threads on the forum of users struggling with the use of PaperUI. The problems stem from the following:
- PaperUI saves the config in an opaque DB format rather than files
- PaperUI does not appear to work with or use Items in .items files or Things in .things files
- PaperUI presents Things as if they were Items with its Control Tab
- PaperUI's capabilities are not complete when it comes to the OH use case
- PaperUI's simple interface does all sorts of things on its own

These all lead users down a path toward frustration and confusion as they run into limitations of PaperUI.

Ultimately I would suggest using Habmin as the default admin UI instead of PaperUI, but that is an issue for a different repo. But I would like to propose an article or paragraphs in the beginners tutorials and migration tutorials to warn users about these limitations and head off some of this confusion.
##

**Comment by ThomDietrich** [comment]
As you are well aware we discussed this in many forms now. I already though of another/ an additional way to make things clearer in the docs. I was going to reorganize some articles under "Configuration", with an overview article explaining the options and what they offer (Items can be defined by PaperUI or file, rules can be build in file or visually in Habmin, etc.). I was thinking about something like a [feature comparison table](https://en.wikipedia.org/wiki/Comparison_of_web_frameworks#PHP_2).

The above idea is just the first idea, I'll have to take the time to work something out. No need to discuss details just yet.

Regarding your suggestion: I think this comparison of functionality should be discussed in the manual as sketched and later on referenced in a tutorial.

**Comment by ThomDietrich** [comment]
https://github.com/openhab/openhab-docs/issues/193
