### ISSUE TITLE
Windows Service throws error 1067 on start

### ISSUE THREAD

**Issue by JPHsProjects** [openhab/openhab-docs#1142]
I followed the instructions [https://www.openhab.org/docs/installation/windows.html](https://www.openhab.org/docs/installation/windows.html) to install OpenHab2 as Service on Windows 10. When starting the service I get 
```
c:\openHAB2>net start openHab2
openHAB2 wird gestartet.
openHAB2 konnte nicht gestartet werden.

Ein Systemfehler ist aufgetreten.

Systemfehler 1067 aufgetreten.

Der Prozess wurde unerwartet beendet.
```

Only this [post](https://community.openhab.org/t/error-1067/34323/6?u=jpha) helped to resolve the issue. 

So I added the following line to `openHAB2-wrapper.conf`: 
```
set.default.JAVA_HOME=C:\Program Files\Zulu\zulu-8
```

and propose this addition to the documentation.

**Comment by edolis** [comment]
@Confectrician  I think this should be closed.
JAVA_home environment variable set up is described in the doc, the issue I had -which was similar- was that the value was not clearly explained to be set to the java version installed in prerequisites and now the doc is updated to contemplate this. Here looks like a late override of the environment variable value.
I fixed it in the doc (which refers to Zulu11 for OH3, here was 1 year ago and maybe the site was still for OH2)

**Comment by Confectrician** [comment]
Thanks for having a look at the issues @edolis 🙂
