### ISSUE TITLE
Java 11 is required for OH3 installations/development

### ISSUE THREAD

**Issue by wborn** [openhab/openhab-docs#1161]
OH3 is now built using Java 11 so it depends on Java 11 to be present for installations/development.

There are several references in the OH3 Developers/Installation documentation sections that need to be updated for this.

See: https://github.com/openhab/openhab-core/pull/1305

**Comment by Confectrician** [comment]
Hey @wborn 

Can you have a look @ #1133 in context of this issue.
We have tried to find all occurences of Java 8 wordings and i have already fixed it in several places.
Maybe you can find some occurences we didn't catch so far.

Anyway we will have fixed most of them in the first run already.
