### ISSUE TITLE
References to Joda-Time need to be updated to Java Time API for OH3

### ISSUE THREAD

**Issue by wborn** [openhab/openhab-docs#1162]
In OH3 Joda-Time has been replaced by the Java Time API.

The Rules DSL, JSR223 and Persistence documentation needs to be updated for this change.

See: https://github.com/openhab/openhab-core/pull/1342

**Comment by openhab-5iver** [comment]
Removing Joda was in [OH3 Issue Tracking](https://github.com/orgs/openhab/projects/3). Does it make sense to add the documentation to it as well?

**Comment by wborn** [comment]
I've added an Update documentation card to the board as a reminder to keep updating it.
