### ISSUE TITLE
Prism language definitions

### ISSUE THREAD

**Issue by TehTux** [openhab/openhab-docs#1168]
Can you (@ghys) please contribute your language definitions to the Prism project?

- https://github.com/openhab/openhab-docs/blob/2.5.x/.vuepress/highlight-dsl.js
- https://github.com/openhab/openhab-docs/blob/2.5.x/.vuepress/highlight-rules.js

It would be fantastic in community forums, blogs, etc. to have syntax highlighting. 🙂

**Comment by ghys** [comment]
Can you point me to an URL?

**Comment by TehTux** [comment]
Yes, of course:

Guide: https://prismjs.com/extending.html
Repo: https://github.com/PrismLibrary/Prism

I checked it out earlier and built it locally. Works great!

**Comment by TehTux** [comment]
Any news, @ghys? I can do the PR for you if you're busy. I just need your okay.

**Comment by ghys** [comment]
Sorry @TehTux I got myself busy with other things indeed ;)
If you can take care of this, by all means, that'd be great!

**Comment by Confectrician** [comment]
Hey @TehTux,

Can we close this issue from your side?
