### ISSUE TITLE
404 Page Breaks after third 'depth'

### ISSUE THREAD

**Issue by BClark09** [openhab/openhab-docs#117]
My latest change works up until the third sub-directory for example: http://docs.openhab.org/one/two/three

It looks like the header and footer isn't applying base.html as intended and I'm not entirely sure of the reasoning behind the process. Why is {{base}} used all over in the first place? Surely a working  `<script src="{{base}}/js/jquery.min.js"></script>` is the same as `<script src="/js/jquery.min.js"></script>` etc. which sets the initial level? 

What is the necessity to calculate {{base}} by breaking down the target url?
##

**Comment by BClark09** [comment]
Furthermore, to test I have removed all `{% include base.html %}` and replaced any reference of "{{base}}/*" with "/*" and the documentation works all the same, albeit slightly faster at loading.

**Comment by ThomDietrich** [comment]
I can not shed any light on these files and am more than curious why there is a problem with it now...
Maybe @kaikreuzer does know more about the reasons behind this?

Can you please create a PR?

**Comment by BClark09** [comment]
It's most probably something that I've not understood, but will be sure to create the PR when I can!

**Comment by kaikreuzer** [comment]
Note that parts of the files come from e.g. https://github.com/eclipse/smarthome/blob/master/docs/documentation/concepts/items.md and thus `{% include base.html %}` cannot be removed on them. I kept the same style in the openHAB doc files, so that it is in-line with the ESH files.

**Comment by BClark09** [comment]
Thanks @kaikreuzer, I read up on this [here](http://ricostacruz.com/til/relative-paths-in-jekyll) and understand now why it was done in ESH. 

Since openHAB docs uses it's own domain (and redirects to docs.openhab.org from the github.io site). We should be able to replace the openHAB version of base.html to: `{% assign base = '' %}`. This will still keep the docs in-line with ESH files but ensures that the path confusion doesn't occur when trying to run a 404 page from any page. Would you agree with this change?

Furthermore there were a couple of examples of pages using absolute paths anyway, for example installation/linux.md contains:
```
With openHAB 2 you can also [use the Karaf console](http://docs.openhab.org/administration/logging.html#karaf-console) to have a colored glance at the logging information.
```

This should ideally be changed to `/administration**` or `{{base}}/administration**` right?

**Comment by ThomDietrich** [comment]
Regarding the second part: I do totally agree. The article is by me and this probably happened when I simply copied the working link from my browser. It's not doing any harm currently but I can [look into that](https://github.com/openhab/openhab-docs/issues/103#issuecomment-254805795) after my paper deadline in two weeks...

**Comment by ThomDietrich** [comment]
@BClark09 As you recently worked on this topic, could you please evaluate the these news:

https://github.com/blog/2277-what-s-new-in-github-pages-with-jekyll-3-3

**Comment by BClark09** [comment]
The choice of "{{Base}}" is due to how it's done in Eclipse/Smarthome pages, this update to jekyll 3.3 looks great but it would have to change on the Smarthome side first before we made the appropriate changes here, otherwise we'll have a mis-match of link types on each page. Some pages also use "{{base}} as a way of extending a {{docu}} macro, we'd have to change these too.

From the looks of things, if we're good to change then all that is needed is a script that changes:

``{{base}}/*``

to 

``{{ "/*" | absolute_url }}``

**Comment by BClark09** [comment]
I think this issue be closed. In my opinion, it looks better as "{{base}}" as it does expanded out, and we won't have to worry about the different {{docu}} implementations.

**Comment by ThomDietrich** [comment]
Agreed.
