### ISSUE TITLE
REST API Documentation

### ISSUE THREAD

**Issue by iPata** [openhab/openhab-docs#1176]
Hi, 

I'm trying to locate the page that contains docs for the openHAB REST API. In [here](https://www.openhab.org/docs/configuration/restdocs.html#rest-api-documentation) it is specified that I must simply go to the Paper UI of my openHAB instance, go to _Add-Ons_, and then click on _USER INTERFACES_; however, this just does not exist. Has there been any change that has caused the docs to be removed from the add-ons? Or am I missing something else here?

Thank you in advance:)

**Comment by Confectrician** [comment]
Hi,

It should still be available in that Tab:
![image](https://user-images.githubusercontent.com/7161177/77407175-05fa8100-6db6-11ea-8531-433e4a3c5d7d.png)

**Comment by iPata** [comment]
Hello, thank you for the response. The tab User Interfaces was not visible to me at all when I posted this, and neither was it until I checked now. I have now identified this. Thank you :)
