### ISSUE TITLE
Editlink for echo docs is not generated.

### ISSUE THREAD

**Issue by Confectrician** [openhab/openhab-docs#1180]
cc @ghys 

We should check why the script is erroring here.

**Comment by ghys** [comment]
You mean Alexa, not the Echo control binding?
It's not erroring, there is simply no info on where the source is.
It should be added to https://github.com/openhab/openhab-alexa/blob/master/USAGE.md in the frontmatter, like it was done e.g. on https://github.com/openhab/openhab-google-assistant/blob/master/docs/USAGE.md.

**Comment by Confectrician** [comment]
A perfect. I just throw it here for documentation and didnt investigate ye.
Will prepare a PR!
