### ISSUE TITLE
"Configuration of openHAB" - not the same as the current version

### ISSUE THREAD

**Issue by bsimmo** [openhab/openhab-docs#1187]
I'm just going through my first initial setup with the stable release.
All the pictures and terminology are slightly wrong, 
I have "Pingable Network Device" and "Network Device with Running Service"
Online/Latency/Last Seen when I go to my phone as the example, a pingable device

Not what is shown in the example, https://www.openhab.org/docs/tutorial/configuration.html#configuration-of-openhab so I'm now sort of left to guess what to do, mo so bad but since this is very early on in setup...

I thought I would report it like it asks.
Ben

**Comment by Confectrician** [comment]
Thanks for the report @bsimmo 
Theres a high chance that the screenshots may be outdated due to a binding update.

**Comment by GumbyMan82** [comment]
I'm currently changing the screenshots and some text as well for this. One minor thing: Since we usually tell users to disable the simple mode, shouldn't we remove this from the documentation here?

**Comment by GumbyMan82** [comment]
@Confectrician 
Hey Jerome, I do hope you can help me. Since I also replaced screenshots, i chanbed the documentation using mit git client. What i'm missing and cannot find i
in the doc it: To which bracnh should i file the PR? 2.5.x? Master?

**Comment by GumbyMan82** [comment]
I "think" i've managed it and created a pull request. Hopefully i didn't mess anything up*fingers crossed*
