### ISSUE TITLE
Item "Call" not mentioned on Items page

### ISSUE THREAD

**Issue by mueller-ma** [openhab/openhab-docs#1188]
The Item type "Call" isn't mentioned in the Item types overview: https://www.openhab.org/docs/configuration/items.html#type
It's used in the Fritzbox TR064 binding: https://www.openhab.org/addons/bindings/fritzboxtr0641/#item-configuration

**Comment by Confectrician** [comment]
I have added the ItemTyp in #1922 but overlooked that there was an issue existing for this too.
