### ISSUE TITLE
Add Timer::isActive() to rules documentation

### ISSUE THREAD

**Issue by kaikreuzer** [openhab/openhab-docs#1207]
See https://github.com/openhab/openhab-core/pull/1450

**Comment by jimtng** [comment]
Should it go into 2.5.x or master branch of openhab-docs? 

When I went to https://www.openhab.org/docs/configuration/actions.html, selected `Version: latest`, and clicked "Edit on Github", it seems to create a branch off 2.5.x (the default). 

I was under the impression that "latest" means 3.0 and "2.5" is referring to the current 2.5.x.

**Comment by Confectrician** [comment]
Done in #1214
