### ISSUE TITLE
Need to Navigate to openHAB 2 Dashboard and Select Package before Using Paper UI to install bindings/etc.

### ISSUE THREAD

**Issue by Brandon314** [openhab/openhab-docs#1208]
Just did a upgrade to openHAB2 and was unable to install a simple binding from the PaperUI.

I had not yet navigated to the base openHAB 2 dashboard at http://openhab-device:8080 yet after upgrade and selected the Simple/Standard/Expert/Demo. Looking at the openhab.log file it gave a non-useful error when trying to install the binding.

Perhaps include some language in the instructions that the user needs to be sure to navigate to the 8080 dashboard and select the package type before underlying aspects will function (especially for upgrading users)? I would suggest the language but I'm poor at writing instructions. 

Thank you!

**Comment by Confectrician** [comment]
Package Selection and Paper UI will not be available in openHAB 3 anymore.
Therefore closing this issue.
