### ISSUE TITLE
The logback debug xml file link is missing.

### ISSUE THREAD

**Issue by zpetschek** [openhab/openhab-docs#1218]
Page: https://www.openhab.org/docs/administration/logging.html#logback-configuration-file

Link: https://github.com/openhab/openhab-distro/blob/master/launch/home/logback_debug.xml

The link returns a 404.

**Comment by wborn** [comment]
This issue can be closed as the logback section was removed in https://github.com/openhab/openhab-docs/pull/1303.

**Comment by stefan-hoehn** [comment]
Closed on behalf of @wborn
