### ISSUE TITLE
[openhabian-doc] some links wrong, seem to be correct on github

### ISSUE THREAD

**Issue by GumbyMan82** [openhab/openhab-docs#1254]
The documentation of openhabian (selection latest) contains two wrong links in the last chapter:
![image](https://user-images.githubusercontent.com/40233411/88211977-cb66ff00-cc56-11ea-9fa4-b02d82acddd6.png)

When you click on it, you are directed to a 404 page

However when I click on "Edit this page on github" the link seems to be ok:
![image](https://user-images.githubusercontent.com/40233411/88212096-f94c4380-cc56-11ea-8fd8-26d4ea0e7c4f.png)

Same is for the README in this chapter. On the webpage it refers to www,openhab.org/docs

I'm going to check for the correct links and make a PR

**Comment by GumbyMan82** [comment]
OK i'm a bit lost.
In the github page the links in the preview seem to work. 
So it might be a problem when creating the webpage out of the md here?

**Comment by Confectrician** [comment]
Yeah this is in mo to do list for way to long.
There were some new openhabain doc articles added but we did noot include them yet in the website build.

After including they should be available on the url shown in the screenshot.

**Comment by Confectrician** [comment]
This is fixed for a longrer time already.
We are fetching openhabian docs (with all their doc files) into the latest docs automatically now.
