### ISSUE TITLE
Inform 

### ISSUE THREAD

**Issue by jimmoroz** [openhab/openhab-docs#1255]
I am a newbie and practice the routine of formatting an SD card before I Flash it.

I am installing openHABian on my Raspberry pi and followed my routine (i understand it as a best practice) and was getting errors when after attempting to install the xz file in my SD card when I executed etcher.

Was told: "Let Etcher do all the work.  It will format and write"

It would be helpful to add this to the documentation Installation Guide / open HABian / Setup / second bullet under Setup.

Tried to submit this request properly but confused on if I am doing this correctly.  Please comment on the process for the future.

**Comment by Confectrician** [comment]
Hey @jimmoroz,

The information has to be added in the opnehabian github repository itself in this case.
I can open a corresponding issue over there.

When the article is updated there, we will get the new version with our next website generation.

**Comment by mstormi** [comment]
@Confectrician I think you can close this
