### ISSUE TITLE
Thing is generated in the incorrect order in the GUI.

### ISSUE THREAD

**Issue by webnar** [openhab/openhab-docs#1269]
Hi, I noticed the following issue when i generate the thing file it provides this:
Thing zwave:qubino_zmnhcd_00_000:zcontroller:node2 "Shutter Slaapkamer" **@ "Slaapkamer"** (zwave:serial_zstick:zcontroller) [ config_76_1=10, config_74_2=0, config_10_2=255, config_72_2=150, config_73_1=1, config_71_1=0, config_90_1=5, switchall_mode=255, config_110_2=32536, config_78_1=0, config_42_2=300, config_85_1=0, config_40_1=1, config_80_1=1, config_120_1=5, node_id=2 ]

But that is generating an error, it should be:
Thing zwave:qubino_zmnhcd_00_000:zcontroller:node2 "Shutter Slaapkamer" (zwave:serial_zstick:zcontroller) **@ "Slaapkamer"** [ config_76_1=10, config_74_2=0, config_10_2=255, config_72_2=150, config_73_1=1, config_71_1=0, config_90_1=5, switchall_mode=255, config_110_2=32536, config_78_1=0, config_42_2=300, config_85_1=0, config_40_1=1, config_80_1=1, config_120_1=5, node_id=2 ]

Maybe it's easy to resolve.

**Comment by webnar** [comment]
ps this is in OH 3.0 of course.

**Comment by Confectrician** [comment]
Did you find a solution for your problem?
This seems not related to the documentation from what i read.
