### ISSUE TITLE
Step by step guide to create an OH3 dev env

### ISSUE THREAD

**Issue by lolodomo** [openhab/openhab-docs#1271]
For any maintainer, we need a working step by step guide to build from scratch a new OH3 Eclipse dev environment,

**Comment by kaikreuzer** [comment]
... which essentially means updating https://github.com/openhab/openhab-docs/blob/main/developers/ide/eclipse.md.

**Comment by lolodomo** [comment]
Would it be possible to get an update ?
Thjat is frustrating to wait and not be able to contribute anymore.
One of my first question is: what is the new recommended JDK to install on Windows 10 ?

**Comment by lolodomo** [comment]
Let's try with AdoptOpenJDK distribution...

**Comment by lolodomo** [comment]
Ok, I was able to make it work in Eclipse from scratch.
The major change in the guide is how to import a project (use Maven Project).
It could be helpful to explain how to enable logs for a binding by updating the file logback.xml.
I tried adding this line and it worked:
```
  <logger name="org.openhab.binding.freebox" level="INFO" />
```

**Comment by wborn** [comment]
Is there still anything to do here @lolodomo? I fixed some issues in https://github.com/openhab/openhab-docs/pull/1645.

The logback.xml file is no longer used and the default log4j2.xml file nowadays has a [commented example logger](https://github.com/openhab/openhab-distro/blob/31fbf28730688b21a0acb9273701733a6d64a900/launch/app/runtime/log4j2.xml#L54-L57).

**Comment by lolodomo** [comment]
No, I think it is OK.
