### ISSUE TITLE
README.md links pointing to wrong URL 

### ISSUE THREAD

**Issue by The-Michael-R** [openhab/openhab-docs#1284]
The README.md of this repro links to the documentation. It points to www.openhab.org/docs/ instead of next.openhab.org/docs

**Suggested Change From:**
`The result is available at [https://next.openhab.org/docs/](https://www.openhab.org/docs/) and [https://next.openhab.org/addons/](https://www.openhab.org/addons/).
`
**To:**
`The result is available at [https://next.openhab.org/docs/](https://next.openhab.org/docs/) and [https://next.openhab.org/addons/](https://next.openhab.org/addons/).
`

**Comment by Confectrician** [comment]
Closing here, since we use next for the nexxt major version and openHAB 3 has been released meanwhile.
