### ISSUE TITLE
Document uninstallation steps - Windows 

### ISSUE THREAD

**Issue by edolis** [openhab/openhab-docs#1317]
Hi guys
I think it would be helpful confirming, in the installation page for Windows (but for other OS too maybe?), the uninstallation procedure.
I have installed OH 2.5 and now I'd like to try OH3 for instance.
I don't know the OH platform yet. I'd like to get reassured on what I should do to completely remove OH to get to a clean state first.
Some bullet points would suffice, like:

- remove service using xxx
- save conf files
- delete whole folder

these are the ones which  come to my mind, but maybe there is more I don't know, as using them is bringing me to a OH3 not working environment. Still trying to fix it.
Some official info would help.

Thanks!

**Comment by Confectrician** [comment]
Hey @edolis did you cover this yourself in pr #1327 ?
If yes i would link this issue, so it gets closed automatically when we merge your pr. 🙂

**Comment by edolis** [comment]
yes... Sorry but I am still very very fresh with GIT and quarreling with DCO. Not ure how to satisfy that bot. Now again is flagging my  pull request for accepting your changes (?!) I'm Loooost.
I have read also another issue about outdated screenshots, I hope I soon understand how to say that is fixed by this commit 
So hassly for a beginner....

**Comment by Confectrician** [comment]
Yeah dco can be a pain in the ass... i know.

I have linked this one already in another pr:
https://community.openhab.org/t/dco-check-signing-off-with-github-web-editor-explanation/83330?u=confectrician

### Don't worry about dco in general

There is now check problem i can't solve manually.-
It is always nice to have it correct while doing the pr but that's not a veto critera. 🙂 
We will get your valuable contents merged some way.

**Comment by edolis** [comment]
thank you so much, I'll read through that. 
Also in the future, if there is some miserable folk who wants to fix the signing process in Windows, please feel free to tell him to give me a buzz.
