### ISSUE TITLE
[Installation] Windows Installation page screenshots still show Java 8 paths.

### ISSUE THREAD

**Issue by rkoshak** [openhab/openhab-docs#1318]
It's a minor thing but should be consistent.

**Comment by Confectrician** [comment]
That's already part of the todo list for OH3 too. 🙂

**Comment by Confectrician** [comment]
And as i see @edolis already changed those in #1327. Will be included then. I will link this issue for auto close.

**Comment by edolis** [comment]
yes, I just did not update the last picture, pertaining the connection with console - I honestly did not get that and I am not sure it is still valid and useful for OH3.
Questions are: the user has to define an admin username and password when logging OH3-shouldn't he use them instead of openhab/habopen?
Not even sure about the client used for those screenshots. I used kitty, the pages and name of fields are different, and I remember I was not sure what I was doing and why honestly

**Comment by Confectrician** [comment]
Good question. i would have to check that for windows to be honest.
The usual way in any linux installtion is,. that you have an admin/openhab/whatever user for logging into the system and then connect to openHAB console with openhab/habopen as credentials.

I am not sure how this is solved for the windows installation.
If there is only one step we would have to change the docs there in a way that fits to the existing process.

**Comment by edolis** [comment]
> The usual way in any linux installtion is,. that you have an admin/openhab/whatever user for logging into the system and then connect to openHAB console with openhab/habopen as credentials.

Well, I don't think it's OS dependent (I know I know, I am using windows which is horrific for Linux guys, and I'l like to become a Linux guy myself but not enough time for that journey yet :) .
The question becomes, in Linux, what is the difference in use between the admin logging in the system and openhab logging in the console? Can they perform the same or different subsets of activities? Where is that explained in the documentation (for Linux or other OS?)

**Comment by Confectrician** [comment]
The "system" is meant here as the "operating system" (which is of course console based for many linux distributions).

The "console" is meant as the karaf/openHAB console which is delivered with the openHAB installation for accessing/logging/manipulating your openHAB environment.

**Comment by edolis** [comment]
mhh. But by admin I mentioned the admin to be defined in this screenshot - sorry if I was not clear. I'm referring to the difference between this admin and openhab user for console -
![Home_Openhab_3 ced2c525](https://user-images.githubusercontent.com/2226075/102694204-e21e7b80-421f-11eb-8c98-e73cafca01f1.png)

**Comment by Confectrician** [comment]
Ah ok. Yes i was on the wrong topic then.
Good question at all.

Maybe it should be possible to add this user as a console user too when registering it.
BUt that would be more likely a discussion for [openhab/openhab-core](https://github.com/openhab/openhab-core/issues) repo
