### ISSUE TITLE
Automation add-on documentation missing

### ISSUE THREAD

**Issue by wborn** [openhab/openhab-docs#1320]
A new Automation extension type was added in https://github.com/openhab/openhab-core/pull/1722.

The documentation of these add-ons doesn't seem to be added to the site so if you click on the "Documentation" button in the UI you would run into some 404s:

* https://next.openhab.org/addons/automation/groovyscripting/
* https://next.openhab.org/addons/automation/jythonscripting/

The Automation add-on type is also missing from the index (on the left) of the Add-ons page:

https://next.openhab.org/addons/

Relates to:

* https://github.com/openhab/openhab-addons/pull/8772
* https://github.com/openhab/openhab-addons/pull/9404

**Comment by Confectrician** [comment]
Please see #1325.
Should be solved already alltough it may need some time to appear in the website. 🙂
