### ISSUE TITLE
mqtt issue after upgrading from 2.5.10 to 3.0.0.1

### ISSUE THREAD

**Issue by toongielen** [openhab/openhab-docs#1366]
hi , 
i just updraded to the new OH3 and its great.

i had a mqqt broker (mosquitto) running. 
after the upgrade my broker stoped working and i can find any solution.
all the config files seems to be good . 
but is is unreachable with mqtt.fx or Broker binding.

**Comment by Confectrician** [comment]
Hey @toongielen,
This question would fit better into https://community.openhab.org/

We are just maintaining the documentation contents here.
This means here are not as much active users than in the form who could see your question and help out maybe.

So pleas ask over there and add some additional information on how you have installed your openhab environment.
