### ISSUE TITLE
[Actions] Extend explanation for executeCommandline

### ISSUE THREAD

**Issue by Confectrician** [openhab/openhab-docs#1367]
We have to provide some extended information about the executeCommandline Action.
Especially an explanation on how to deal with multiple command arguments passed as different function parameters.
We should also add a small example with multiple parameters there.

**Comment by holgerfriedrich** [comment]
Just typed this to create an issue in openhab-core before I discovered this issue.

executeCommandLine semantics have changed from OH2 to OH3:

**Regarding parameters**, see also (openhab/openhab-core#1700):

In OH2, `executeCommandLine("cat somefile")` worked as expected, actually running the command with a parameter.
In OH3, "cat somefile" is interpreted as a command, which is of course not found.
OH3 allows running `executeCommandLine("/bin/cat", "somefile")`, which finally works.

Error message when still using OH2 syntax is not very helpful, anyway:
```
[WARN ] [rg.openhab.core.io.net.exec.ExecUtil] - Failed to execute commandLine '[/bin/cat /var/log/openhab/callers.txt]'
[ERROR] [internal.handler.ScriptActionHandler] - Script execution of rule with UID 'callers-2' failed: cannot invoke method public java.lang.String[] java.lang.String.split(java.lang.String) on null in callers
```
Documentation does not describe this, see docs/configuration/actions.html#exec-actions.

**Regarding order of arguments** for the use case which includes waiting for timeout:
OH2: `executeCommandLine("/bin/cat somefile", 5000)`
OH3: `executeCommandLine(Duration.ofMillis(5000), "/bin/cat", "somefile")`

**Comment by jandechent** [comment]
I suggest you also add the required line: var Duration = Java.type("java.time.Duration"); at least this is what I had to do too.

**Comment by Confectrician** [comment]
I am not sure, if this is valid for all kinds of writing rules.

Please check
https://github.com/openhab/openhab-core/issues/2112
