### ISSUE TITLE
"Edit this page on GitHub" link broken on bindings with seperate repositories

### ISSUE THREAD

**Issue by pfink** [openhab/openhab-docs#1374]
I think the title already says everything. "Edit this page on GitHub" link does not work for for bindings that do have a separate repository, e.g. ZigBee or Z-Wave.

**Comment by Confectrician** [comment]
Indeed.

There is an explicit expression in openhab/website which should handle this.
https://github.com/openhab/website/blob/master/prepare-docs.rb#L115

But seems that the expression doesn't get called.

**Comment by Confectrician** [comment]
Found the bug.

I have changed the base branch to "main" in that script, beacaus every other link was wrong.
Probably all of those repos still use a master branch.


I will add a hardcoded fix for now.
