### ISSUE TITLE
PR lost on website update

### ISSUE THREAD

**Issue by mstormi** [openhab/openhab-docs#1376]
@Confectrician something went wrong with your website update
https://www.openhab.org/docs/configuration is an older version.
@bobadair had proofread that and his PR https://github.com/openhab/openhab-docs/pull/1323 used to be up on the website before your last update. But now it's gone.

I didn't check other parts. Possibly there's more bad/old parts and missing docs PRs ?

**Comment by Confectrician** [comment]
Hey @mstormi 

I have opened the PR and the current homepage build on 2 screens in parallel and checked **every changed line** that @bobadair intruduced in the pr.
They are 100% the same when i open the homepage.

May you point me to specific differences you have found?
Could you also please try to delete your cache and load the page again?

**Comment by Confectrician** [comment]
Addittionally you are free to hav a look @ https://github.com/openhab/openhab-docs/commits/final/configuration/index.md

This is the final branch of this repo. Our website build uses `final` as docs source when building the website.
The changes of PR #1323 are included there.

**Comment by mstormi** [comment]
The topmost change (i.e. latest commit)  you link to is right about the text I was looking for but didn't see on the final website (it still said you can import .things in UI as well which is wrong hence needs to be removed).
It's alright now on the website. So it was about caching. Probably some server-side because I had restarted my PC meanwhile.
Sorry for sounding the alarm and a merry and calm Christmas

**Comment by Confectrician** [comment]
No worries, i am glad that the problem is solved.

Thanks for the feedback and happy holidays. 🙂
