### ISSUE TITLE
[OH3] Authentication is not mentioned in Restdocs/subscription examples do not work any longer

### ISSUE THREAD

**Issue by LinqLover** [openhab/openhab-docs#1391]
The [docs for the REST API](https://www.openhab.org/docs/configuration/restdocs.html) do not mention authentication in any way and starting with openHAB 3 when you set up openHABian, your system will be password-protected by default. This means that some of the examples given in the article will not work any longer, but you will see a 401 Authentication Required error instead. As far as I have found out, this applies to all `/things`-related queries, for example, i.e. also [the `ThingStatusInfoChangedEvent` subscript example](https://www.openhab.org/docs/configuration/restdocs.html#:~:text=/things/).

---

## Information I have collected so far as a non-domain expert

Possible ways to modify the `curl` commands:
- Add argument `-u {USER_NAME}`, then enter password interactively
- Add argument `-u {USER_NAME}:{PASSWORD}`
- Add argument `-u '{API_TOKEN}:'` (usually recommended approach)

Furthermore, basic authentication needs to be enabled in the `org.openhab.restauth` settings unless an API token is used, and maybe the preference "Implicit user role for unauthenticated requests" matters, too (todo: check this - I'm not sure about this, but it does not seem to be the case for the above curl variants).

---

**Original context:** [[OH3] REST API Authentication Help RESOLVED - Setup, Configuration and Use / Scripts & Rules - openHAB Community](https://community.openhab.org/t/oh3-rest-api-authentication-help-resolved/105933/10?u=linqlover)

If no one is keen writing the docs herself or himself, please only inform me that all information listed above is correct and I can open a PR myself. :-)

BTW: In what sense is [this section about authentication](https://www.openhab.org/docs/installation/security.html#authentication-and-access-control) (stating that "openHAB does not (yet) support restricting access through HTTP(S) for certain users") still up to date for OH3, given the fact that now there is a user system in the Main UI and we can manage API tokens?
And a further question - just for curiosity: Is it already possible to create multiple users or to require authentication for every access to OH and its component, i.e. also items etc.? :-)

**Comment by Confectrician** [comment]
>If no one is keen writing the docs herself or himself, please only inform me that all information listed above is correct and I can open a PR myself. :-)

Too late. I have assigned you know and would appreciate a PR when all information is validated.

Some short infos already:

Additional users:
Yes this is possible from the openHAB console. Please check and search in our forum. It has been asked there already and there should be some explanation available.

Security section:
This is outdated too correct. (We should add an issue for that too.)
It was already mentioned here: https://github.com/openhab/openhab-docs/issues/1133#issuecomment-751404025
and here: https://community.openhab.org/t/nginx-unauthorized-api-request-with-un-pw-prompt-oh3-openhabian/111199/10?u=confectrician

I have not checked the restdocs contents yet.
They were deleted by accident and i have brought them back in ther openHAB 2 state just yesterday.
