### ISSUE TITLE
[Security] Add explanation on how to generate an api token

### ISSUE THREAD

**Issue by Confectrician** [openhab/openhab-docs#1398]
Describe the process of generating a personal api token.
Also add some screenshots showing the relevant UI areas.

_Originally posted by @Confectrician in https://github.com/openhab/openhab-docs/issues/1395#issuecomment-751717530_

**Comment by lampy2** [comment]
> 
> 
> Describe the process of generating a personal api token.
> Also add some screenshots showing the relevant UI areas.
> 
> _Originally posted by @Confectrician in [#1395 (comment)](https://github.com/openhab/openhab-docs/pull/1395#issuecomment-751717530)_

Ok, here my first try to write some new documentation. 
Managed to get the files into VS, but took me a bit more effort to get them back on github again. Think I managed:
[API tokens](https://github.com/lampy2/openhab-docs/blob/main/configuration/API%20token.md)

Please feel free to give some feedback where to improve.

**Comment by Confectrician** [comment]
Hey @lampy2 

Thanks for jumping into this.
That's already a pretty good base.

I would suggest two things and we could then already work in a pull request.

1. I am not sure about file names with whitespaces, so i would suggest to name that file `apitokens.md`
2. You should avoid making changes in the main branch of you fork and work with a branch instead

I t would work for now, but if you want to do another improvement in the future and need to update your fork,
it may make a mess in your forks main branch and a pull request will mostly fail.

Are you familiar with git and branches or do you need some more information?

**Comment by lampy2** [comment]
You're welcome, nice I can do something to contribute to this nice project. Thank you as well for the work and support.

Thanks for the hints, will update that this afternoon. 
I am completely new with git and branches, did read already a bit, but if you have some more directions this would be really helpful. There was quite some trail and error involved yesterday to get the files back to github.

**Comment by lampy2** [comment]
Hello @Confectrician, follewed some video's on youtube to better understand the principle of github and VS (not finished yet). But one thing I don't understand, now I've created a fork of openhab-docs. There are branches, e.g. main and apitokens-edit. 
To get the changed in the branch back to main, you would need a pull request, right? 
But this pull request, would I need to create that from apitokens-edit to my 'own' main branch, or to the openhab-docs main branch? Or even to a new branch in openhab-docs?
Thanks!

**Comment by Confectrician** [comment]
First of all:

Are you using visual studio or visual studio code ?
(May sound familiar, but makes a huge difference since both are unique programs not related to each other at all.
I just want to explain the correct things and this is an important information for me to do so. 🙂 )

Workflow would be as following (short verion):

I will explain a complete workflow for interested readers here, so some informatoin may be redundant for you now.
(Sorry)

1. Fork the repo
2. Open it in editor (this represents a `git clone HERESMYURL` commeand)
3.  Start new branch (e.g. `apitokens-edit`) for your improvements (started from an up to date `main` branch)
4. Make changes
5. Upload the `apitokens-edit` branch to your fork
6. Make a pull request from `yourFork/openhab-docs apitokens-edit branch` to `openhab/openhab-docs main branch`

Usually github recognises recent changes (like uploading a new branch) and already suggests to open a pull request with the correct branch settings.

**Comment by lampy2** [comment]
A, never knew there where two program's which sounded so familiar... I am using Visual Studio Code, and installed the GitHub Pull Requests and Issues extension. But if a different program or work method is easier, let me know and will use that one.

Thank you for the clear workflow, this helps. And always better to include a bit more information than making assumptions. 
When I went to the website of GitHub to check if my commit reached the website, it already suggested to make a pull request.

**Comment by Confectrician** [comment]
Visual Studio Code is my preferred editor, so everything fine already for me. :D
(But editor/ide can be a philosophical topic...)

**Comment by Confectrician** [comment]
Fixed in #1453 Thanks 👍
