### ISSUE TITLE
Links in top bar of www.openhab.org/docs do not work

### ISSUE THREAD

**Issue by MHerbst** [openhab/openhab-docs#1402]
Steps to reproduce:

- open https://www.openhab.org/docs
- click on "Download"

You can now see a small progress bar on the top of the window, but the links is not opened. If you click on the link with the right mouse button and open the link in a new tab or window, it works.

The same problem occurs in the Add-ons documentation if you try to click on one the products in the left sidebar.

I have tested it with Chrome, Edge and Firefox. Always the same behaviour.

In the console of the developer tools, I see these error messages:
![image](https://user-images.githubusercontent.com/616792/103366998-3ea55480-4ac4-11eb-8806-c73b56a8738a.png)

The last message is issued if you click on one of the links.

**Comment by MHerbst** [comment]
Seems to a problem related to my network. Using another machine in another network worked.

**Comment by MHerbst** [comment]
I have to reopen the problem because it is not really solved and others have got the same problem: 

https://community.openhab.org/t/links-on-openhab-website-do-not-work/112109/4?u=mherbst

I have made some additional tests after restarting my router:

- It does neither work in Chrome nor in Edge
- It works in Firefox but only if I use HTTP. 
- With HTTPS it also fails in Firefox

Maybe this problem is caused by Cloudflare and only in certain regions, because in the U.S. it works even with https.

**Comment by kaikreuzer** [comment]
I can confirm the issue, I see the same in Chrome...

**Comment by Confectrician** [comment]
Edge works for me
Chrome and Firefox don't

**Comment by kaikreuzer** [comment]
Looks like an issue introduced by Cloudflare caching.
I have purged the cache and the issue seems to be gone.
Not sure what caused it and whether it will come back, so let us closely watch it the next days.

**Comment by Confectrician** [comment]
Yep. I will leave this issue open for some days just in case.

**Comment by Confectrician** [comment]
Foxed in openhab/website#267
