### ISSUE TITLE
Basic UI menu on the docs website

### ISSUE THREAD

**Issue by mstormi** [openhab/openhab-docs#1407]
in the leftmost frame, pls replace

**Comment by Confectrician** [comment]
Totally forgot about this one.
Can you give me some context?
What should be removed?

The Basic UI itself is still part of openHAB so generally the link and page should stay here.
The contents may not fit anymore for everything but i am not sure about it currently.

**Comment by mstormi** [comment]
it has references to PaperUI maybe just remove those for the time being
