### ISSUE TITLE
cloud connector docs

### ISSUE THREAD

**Issue by mstormi** [openhab/openhab-docs#1408]
is there any docs menu item that points to https://www.openhab.org/addons/integrations/openhabcloud/ ?
Or where's that documented now ?
BTW if you rework add how to do it via text addons.cfg

Also the "cloud connector" link in Alexa skill docs (very bottom) is broken

**Comment by Confectrician** [comment]
It is in the addons area, because it is an addon.

I have iussued a quick PR for the wrong link.

**Comment by mstormi** [comment]
That was in the v2 docs but now I don't see that "addons area" any more nor hence my issue ? The page is there you but where's the link from the TOC ?

**Comment by Confectrician** [comment]
Hm addons have always been in their completely own area at least for 2 years (or whenever we switched to this homepage).
And we never had them included in the sidebar navigation from what i remember.

It should be available as a link from the top navigation.
(Hint: On small screens the top navigation is combined with the sidebar.)

Navigation avaiable from the `v2` docs or homepage:
![image](https://user-images.githubusercontent.com/7161177/103442896-544c8280-4c5a-11eb-9714-a330a1325426.png)

Navigation available from the `www` homepage available too:
![image](https://user-images.githubusercontent.com/7161177/103442945-b7d6b000-4c5a-11eb-81db-d66716cec0a6.png)

Responsive mobile layout for the latest page:
![image](https://user-images.githubusercontent.com/7161177/103442992-12700c00-4c5b-11eb-8ecc-42c55f375c7a.png)

I have checked both versions and for the normal layout even the `next` homepage.
I have checked the `www` homepage on Edge, Chrome and Firefox and the Addons Area link is available for me for all of them.

If you can't see or reach that area, some information about your used browser (and maybe OS) would be useful.

**Comment by mstormi** [comment]
Ok I thought by "area" you mean one link or section of the menu frame.
*That* area is there. But there should be a link inside the menu to link to integrations like there was earlier.
How is a user supposed to search for the information over there ? We should have links from the menu too
That was exactly what I couldn't find yesterday when I was looking for information how to setup openhab cloud connector.
Please add links as appropriate.

**Comment by Confectrician** [comment]
No that was a misunderstanding then.
Area was meant as a homepage area.

Maybe we should add a TIP/Note box to all articles, that need the cloud connector integration.

Another possible solution would be a reference in the sidebar like this:
![image](https://user-images.githubusercontent.com/7161177/103443620-6c73d000-4c61-11eb-8881-759f245c413e.png)
Maybe we should add that and do the TIP Box anyway.

**Comment by mstormi** [comment]
yes add the sidebar link and tip boxes in Alexa, Homekit and Google Assistant.

**Comment by ghys** [comment]
It could be added as a redirect to the "ecosystem" section of the main docs, similar to the HomeKit link that is already there.

**Comment by Confectrician** [comment]
Thought about that too and had in mind to expand the redirects file for this.

**Comment by yfre** [comment]
> yes add the sidebar link and tip boxes in Alexa, Homekit and Google Assistant.

but homekit does not need cloud connector. it works directly without cloud

**Comment by Confectrician** [comment]
@mstormi  did you mention homekit on purpose?

I ha e adapted that without asking, since i am not using homekit.

**Comment by mstormi** [comment]
Don't use it either.
But I didn't say to include it with cloud connector docs.
But whenever any sort of integration is needed then there should be links from the menu pointing to (Homekit) integrations docs.

**Comment by Confectrician** [comment]
Ok. I am leaving out homekit then.

>But whenever any sort of integration is needed

Whoever wants to look that up is free to do so.
Im am happily talking pull requests, but will not scan the whole docs for possible places to include integration links.

And to be honest.
I would rather suggest to remove any references that need some kind of integration from the general docs if found.
Everything that needs integration (or has to be handled different)  should be summarized in the integrations docs and nowhere else in my view.
