### ISSUE TITLE
Migration Tutorial: Item's Transformed Label State Used to Pick Icons

### ISSUE THREAD

**Issue by rkoshak** [openhab/openhab-docs#144]
See https://community.openhab.org/t/custom-dynamic-icons-for-number-items-when-mapped/16894/10

Unlike OH 1, OH 2 uses the label's transformed state when picking the icons, not the Item's original state.

**Comment by ThomDietrich** [comment]
@rkoshak more importantly this would need to be documented under items->icons.
Closing this ticket in favor of https://github.com/openhab/openhab-docs/issues/152
