### ISSUE TITLE
Some Add-on's Categories Missing from Add-Ons Menu

### ISSUE THREAD

**Issue by rkoshak** [openhab/openhab-docs#145]
There should be a page for each of the Add-Ons types under Add-Ons. Missing types are 

- Persistence
- Actions
- Transformations
- Misc

As a user I would expect to see a one-to-one mapping between that section and the tabs listed in PaperUI. As it is right now I have no idea where I would look to find the README contents for the XPATH transform or the InfluxDB Persistence.

**Comment by kaikreuzer** [comment]
We will have to check how we can deal with the differences between ESH and OH1 add-ons. We currently have http://docs.openhab.org/addons/1xaddons.html.
ALL current actions and persistence add-ons are there as well, since we do not have any "native" ESH ones. Especially the actions will rather be replaced by rule modules in future.

Regarding Transformations: Yes, all of them are from ESH already and we should add README.mds in the according bundles and have the documentation being automatically copied the same way as for bindings.

**Comment by ThomDietrich** [comment]
Thanks @rkoshak, I'll try to include these concerns in the upcoming new menu structure.
I'll have a go on this very soon now. Sorry for sounding like a broken record :-/

**Comment by rkoshak** [comment]
>ALL current actions 

@kaikreuzer Actually there are several actions that are missing. For example, none of the "core" Actions as listed on the wiki page are listed. 

Which raises a concern. At least in the case of Actions there are core Actions and add-on actions. I think we have a handle on how to document the add-ons through the readmes, even if the current documentation isn't quite where I and I think new users also would expect it. But I don't know we have in place a way to document these core ones in a consistent way. 

How far away are we to have rule modules? Is it worth spending the effort now to bring in the core actions documentation in some way or just wait it out.

I'm thinking a bit about Ansible's documentation. They have add-on modules as well but their documentation is unified and merged and they just have a flag on the page to indicate whether the module is a core one or a third party one.

>Sorry for sounding like a broken record :-/

@ThomDietrich I have that same record and I seem to play it all the time too. :-)

**Comment by kaikreuzer** [comment]
> But I don't know we have in place a way to document these core ones in a consistent way.

Well, probably somewhere in the "features" section, we should explain the actions and list them - ideally, we could add on this page a dynamically generated link list to all "action add-ons".

> How far away are we to have rule modules? Is it worth spending the effort now to bring in the core actions documentation in some way or just wait it out.

We already have some and we would need a way to document them. The first step probably needs to be done on the ESH side, where the current modules live. Their bundles probably should get a README.md as well (like the transformation bundles) and we would need to include those. But here again: Some modules are contained in the "core", while others might be optional on the long run. At the moment, I am still [adding all modules to the rule engine itself](https://github.com/openhab/openhab-core/pull/88/files), I think this will stay like this until 2.0 is released (and rather go for a modularization in 2.1).

On a more general context: I was wondering if it might be a good idea to include a "documentationUrl" property in the "Extension" interface of ESH and to make the Paper UI open this url, if the user clicks on an extension in that list.
I could make sure that openhab-core (where the extension information is created) fills in this property with the correct links to docs.openhab.org. This would imho be the most natural mechanism for users to find the documentation they are looking for.

**Comment by ThomDietrich** [comment]
> On a more general context: I was wondering if it might be a good idea to include a "documentationUrl" property in the "Extension" interface of ESH and to make the Paper UI open this url, if the user clicks on an extension in that list.

I was already talking about this with chris at some point: https://community.openhab.org/t/consistency-needed-for-widespread-adoption-of-openhab-2-0/13300/15
documentationUrl would be just as useful as a version number, a differentiation between native ESH, native OH2 or legacy 1.x addons, ...
This information can then also be used in other views like the PaperUI bindings listing to link the README.

**Comment by kaikreuzer** [comment]
> This information can then also be used in other views like the PaperUI bindings listing to link the README.

Not that easy, because you do not have a link from the binding back to the extension again...

**Comment by kaikreuzer** [comment]
> a differentiation between native ESH, native OH2

There should be no difference from a user perspective. Why show them differently?

**Comment by ThomDietrich** [comment]
Okay I do not want to argue about these details. I think we can agree that Legacy 1.x bindings are special and should be marked as such. Linking the documentation would be (in regards to Usability) the important detail.

**Comment by rkoshak** [comment]
> On a more general context: I was wondering if it might be a good idea to include a "documentationUrl" property in the "Extension" interface of ESH and to make the Paper UI open this url, if the user clicks on an extension in that list.

I love this idea! I thought it was already in the works, but maybe I'm misremembering that thread @ThomDietrich linked to. I don't want to lose making them findable in the current docs though so this wouldn't, in my opinion, be a replacement for making sure they are all in the docs as well.

> Okay I do not want to argue about these details. I think we can agree that Legacy 1.x bindings are special and should be marked as such. Linking the documentation would be (in regards to Usability) the important detail.

I agree that Legacy 1.x bindings are different and there should be some obvious indication of that difference. But in the long run we should not organize them separately, like we have now. As a new user I'd be confused as to what the difference even means and wouldn't understand where to look to see if the technology I want to use is supported. As an experienced user I find it annoying that I have to first look on one page to see if there is a 2.0 binding and then go look at the 1.x page to see if it is there.

Ultimately the users shouldn't have to know or care whether the add-on is 1.x or 2.0 when searching for and choosing one. Once chosen though, the docs need to be very clear how to configure and use that add-on. Marking it as 1.x versus 2.0 is a nice shorthand way to identify differences between the two and inform mid to advanced users what to expect out of the add-on but I don't think we can use this shorthand in place of fully documenting how to use each add-on. From that perspective the label begins to lose its importance

The arguments for not needing to emphasize the differences between ESH and native OH2 bindings are even stronger.

Ultimately, as a user all I care about is knowing whether my technology is supported and if so how to use it. For the most part, at the risk of using an idiom with non-native speakers, the distinction between ESH, native OH2 and Legacy 1.x is inside baseball. Developers care a lot but users not so much (so long as the documentation is sufficient for each add-on that it can be configured and used whether you know the difference or not.

**Comment by rkoshak** [comment]
Commenting from #148:

> No, all are 2.x.

OK, then this is another case where the version numbering is a bit confusing. Using the "idiot in a hurry test" when I look at the transformations page in PaperUI I see a bunch of "9"s. If I look closer I see they are version "0.9.0 SNAPSHOT" as opposed to "1.9.0 SNAPSHOT". I saw the "9"s, assumed "1.9" and came to the wrong conclusion. While I'll admit I can be an idiot sometimes and am often in a hurry, I'm sure I'm not the only one.

Anyway, I think the root of the discussion comes down to @kaikreuzer has the big picture of what is coming down the line and is planning for the near future. I only really know what is out there now. So some of the recommendations feel a little premature (i.e. marginalizing the OH 1.x bindings). But given my lack of knowledge on how soon the current balance will change, I'm willing to concede keeping them separate may be the way to go, particular if the OH 2 bindings will soon come to dominate.

**Comment by kaikreuzer** [comment]
>  the distinction between ESH, native OH2

Right, that's why I also would not show them in any way different. The version numbers should not be relevant to the user at all, I see that this has led you to some confusion. From a functional perspective, they are fully the same.

> as a user all I care about is knowing whether my technology is supported

Right, and if you do NOT find your technology on the 2.x-binding list, you know that there is no discovery support for it, nor the possibility to use it through the UI (by defining Things, Links, etc.) and that you have to go and learn about these binding config strings for items files, etc.

**Comment by ThomDietrich** [comment]
@rkoshak this has been dealt with in the meantime, correct!?
