### ISSUE TITLE
Changing Doc Versions

### ISSUE THREAD

**Issue by Ion3** [openhab/openhab-docs#1470]
By changing from "Version: latest" to a previous version, the selection drop down disappears and you have to retype the URL to get back to the latest version.

**Comment by Confectrician** [comment]
@ghys => Version selection should be included in the website repository as far as i know.
Do you have an idea. Maybe we have something leftover from the "next" page over there.

**Comment by ghys** [comment]
On 2.x websites archives the version selector is on the right side, in the page contents. I moved it on top of the sidebar in the new website.

**Comment by Ion3** [comment]
Okay, but not on the "Introduction" site. Here is no version selector on the 2.5 page version. Nevertheless; the selection 2.4, 2.3 & 2.2 all return the latest version. They should be disabled or fixed.

**Comment by Confectrician** [comment]
We have made several changes to the docs and version selectors.

Further information can be found here: https://community.openhab.org/t/important-changes-to-the-documentation-versioning/122369?u=confectrician
