### ISSUE TITLE
External docs should be gathered from the correct branches

### ISSUE THREAD

**Issue by mstormi** [openhab/openhab-docs#1476]
We've changed the default/most up to date branch of openHABian from `master` to `main` so all files you retrieve from our repo to make them available as documentation on www.openhab.org should from now on be retrieved from the `main` branch.

**Comment by Confectrician** [comment]
Already changed => https://github.com/openhab/openhab-docs/commit/199aa1fe2c9c239128d90ce162dec14dddffcf60
