### ISSUE TITLE
[Items] Are item names really not allowed to start with a number? (Question)

### ISSUE THREAD

**Issue by pavog** [openhab/openhab-docs#1481]
In the docs under [Items -> Name](https://www.openhab.org/docs/configuration/items.html#name) there is the following sentence:

> "The Item name is used to uniquely identify an Item. The name must be unique across all .items files in your openHAB configuration. The only characters permitted in an Item name are letters, numbers and the underscore character. Names must not begin with numbers. Spaces and special characters are not permitted."

**It is therefore forbidden to begin the name of an item with a number?**

In the code (openHAB-core) there is the function "isValidItemName" in "ItemUtil", which checks for the following conditions:
1. itemName != null
2. !itemName.isEmpty() 
3. itemName.matches("[a-zA-Z0-9_]*")

This is the code [ItemUtil.java#L56](https://github.com/openhab/openhab-core/blob/main/bundles/org.openhab.core/src/main/java/org/openhab/core/items/ItemUtil.java#L56):
 ```java
   /**
     * Returns {@code true} if the specified name is a valid item name, otherwise {@code false}.
     * <p>
     * A valid item name must <i>only</i> only consists of the following characters:
     * <ul>
     * <li>a-z</li>
     * <li>A-Z</li>
     * <li>0..9</li>
     * <li>_ (underscore)</li>
     * </ul>
     *
     * @param itemName the name of the item to be checked (could be null or empty)
     * @return true if the specified name is a valid item name, otherwise false
     */
    public static boolean isValidItemName(final @Nullable String itemName) {
        return itemName != null && !itemName.isEmpty() && itemName.matches("[a-zA-Z0-9_]*");
    }
```

However, the regex only checks:

> A valid item name must only consist of the following characters:
>      * a-z
>      * A-Z
>      * 0..9
>      * _ (underscore)

**However, no attention is paid to whether the item name starts with a number or not.**

In some of my projects I also use item names that start with a number and never had any problems with that.

Now I wanted to ask which of these is correct?
- Are the item names that start with a number allowed and we have to adapt the documentation?
- Are the item names that start with a number not allowed and we have to adapt the code?

**Comment by Confectrician** [comment]
Based on the mentioned code it seems that the current docs are wrong.
@kaikreuzer do you know if this is allowed by intention?

Personally i would never start an item with a number, but if its technically ok, we should adapt the docs then.

**Comment by Rossko57** [comment]
I think DSL rules do not handle Item names starting with digits.   This involves rule triggers - potentially the other rule languages may have the same issue.
example
https://community.openhab.org/t/solved-configuration-model-rules-has-errors-therefore-ignoring-it-no-viable-alternative-at-input/100387

**Comment by Confectrician** [comment]
According to this we should then raise an issue in the openhab-core repo to get docs and core code into one valid state.

**Comment by pavog** [comment]
I've been trying to find the code that validates item names for DSL rules, but I'm not sure where to look for it.
I found the function isValidItemName in the [ItemUtil](https://github.com/openhab/openhab-core/blob/main/bundles/org.openhab.core/src/main/java/org/openhab/core/items/ItemUtil.java) class.
```java
public static boolean isValidItemName(final @Nullable String itemName) {
    return itemName != null && !itemName.isEmpty() && itemName.matches("[a-zA-Z0-9_]*");
}
``` 

According to GitHub, isValidItemName is used in the following places:

- [RuleHumanLanguageInterpreter](https://github.com/openhab/openhab-core/blob/main/bundles/org.openhab.core.model.script/src/org/openhab/core/model/script/internal/RuleHumanLanguageInterpreter.java#L73)
- [DialogProcessor](https://github.com/openhab/openhab-core/blob/main/bundles/org.openhab.core.voice/src/main/java/org/openhab/core/voice/internal/DialogProcessor.java#L120)
- [ManagedItemProvider](https://github.com/openhab/openhab-core/blob/main/bundles/org.openhab.core/src/main/java/org/openhab/core/items/ManagedItemProvider.java#L120)
- [ItemDTOMapper](https://github.com/openhab/openhab-core/blob/main/bundles/org.openhab.core/src/main/java/org/openhab/core/items/dto/ItemDTOMapper.java#L56)
- [ItemUtil ](https://github.com/openhab/openhab-core/blob/main/bundles/org.openhab.core/src/main/java/org/openhab/core/items/ItemUtil.java#L77) in the function assertValidItemName which is used in
  - [AbstractLink](https://github.com/openhab/openhab-core/blob/main/bundles/org.openhab.core.thing/src/main/java/org/openhab/core/thing/link/AbstractLink.java#L49)
  - [ItemRegistryImpl](https://github.com/openhab/openhab-core/blob/main/bundles/org.openhab.core/src/main/java/org/openhab/core/internal/items/ItemRegistryImpl.java#L184)
 
I also found the function addOrRefreshModel in the [ModelRepositoryImpl](https://github.com/openhab/openhab-core/blob/main/bundles/org.openhab.core.model.core/src/main/java/org/openhab/core/model/core/internal/ModelRepositoryImpl.java#L99), which seems to validate the model against the model definition in the [Items.xtext](https://github.com/openhab/openhab-core/blob/main/bundles/org.openhab.core.model.item/src/org/openhab/core/model/Items.xtext) file.

Unfortunately, I am not sure where this function is used. Furthermore, I am not very familiar with xtext and do not know which rules are defined there (e.g. for the name).

Maybe someone else can help with my research so far and find the place(s) in the code where the name of the items is checked.

**Comment by Confectrician** [comment]
I have raised a related issue in the core repository.
Hopefully we can bring some light in the dark over there and also answer some of your questions @pavog.

**Comment by Rossko57** [comment]
Linked issue now also identifies sitemaps and persistence as services that do not like Item names beginning with digits.

**Comment by pavog** [comment]
Fixed in https://github.com/openhab/openhab-core/pull/2941

**Comment by Confectrician** [comment]
Thanks for keeping an eye on this @pavog :)
