### ISSUE TITLE
Unity ; Can't acces Animator Parameters

### ISSUE THREAD

**Issue by guedo** [openhab/openhab-docs#1493]
Hi there, I'm pretty des to Unity and I am trying to animate my character, nothing complicated, just to make him walk for the moment. I stetted up the Animator component and parameters, actually, I tried the parameters in game view by changing them manually during the game and it works but when I'm trying to access it by script my Unity just breaks... Here's my code could anyone point me what's my mistake : 

using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class PlayerController : MonoBehaviour
{
 private float speed = 2f; 
 private float turnSpeed = 100f;
 public float horizontalInput;
 public float forwardInput;

 private Animator playerAnim;

 void Star()
 {
  playerAnim = GetComponent<Animator>();
 }

 void Update()
 {
  horizontalInput = Input.GetAxis("Horizontal");
  forwardInput = Input.GetAxis("Vertical");

  playerAnim.SetFloat("Speed", forwardInput);

  transform.Translate(Vector3.forward * Time.deltaTime * speed * forwardInput);
  transform.Rotate(Vector3.up, Time.deltaTime * turnSpeed * horizontalInput);

  }
}

**Comment by rkoshak** [comment]
This has nothing to do with openHAB nor the openHAB docs. You need to ask on a Unity focused forum.
