### ISSUE TITLE
Add Search function

### ISSUE THREAD

**Issue by ThomDietrich** [openhab/openhab-docs#150]
https://github.com/openhab/openhab-docs/pull/148#issuecomment-264916793

Plugins can not be used on GitHub Pages.
One option: http://digitaldrummerj.me/blogging-on-github-part-7-adding-a-custom-google-search/

**Comment by cniweb** [comment]
I think a search function is useful. But we must have a google account for use the google search engine. Have we one?

**Comment by MHerbst** [comment]
We have an account for Google Search and I have already created a search engine. You can test it with this URL: https://cse.google.com/cse/publicurl?cx=003707250976775348452:h9hxadbatfq

@ThomDietrich I can add it to the website but where do we want to put the search field? One option would be in the menu at the right with an expandable edit field.
Or in the left sidebar on top of the menu items. I would configure the search function so show the results as  overlay.

**Comment by ThomDietrich** [comment]
Sounds fantastic. I was not able to do a search (no progress after an empty "Loading" page) but I'm sure that's just a small problem.
I like both your options. It would feel more natural to have it in the header, on the top right. Is the horizontal space sufficient for it? Looking forward to that PR! 🎉

**Comment by MHerbst** [comment]
>  It would feel more natural to have it in the header, on the top right. Is the horizontal space sufficient for it?
We can try it. On my website I am using an "expandable" input box. It gets wider when you click into it. But I am not sure whether this is possible with the Google search. We will see :-)

**Comment by MHerbst** [comment]
I have just created the PR for Google Search. Probably the look & feel needs some tweaking. I especially don't like that I had to put the magnifying glass symbol in the menu into a separate li-tag to avoid a line break. Please feel free to improve the styling :-)

**Comment by kubawolanin** [comment]
Should this issue be closed? BTW. I've added small fix for the placeholder in #257

**Comment by Confectrician** [comment]
> Should this issue be closed?

Bump.
Implemented a long time ago.
