### ISSUE TITLE
unable to start Designer on MAC

### ISSUE THREAD

**Issue by jsieberg** [openhab/openhab-docs#151]
I decided to continue with openHAB for my automation plans, but I struggle with the basic installations. 
I develop JSF applications with Eclipse but the Designer ( on Eclipse ) will not work.
I downloaded multiple versions 0.7 and 0.8 
I have another Eclipse Installation on my Mac for JSF development. May be this is the problem. 
I was able to install the Smarthome Eclipse Development, but even this has many errors and I can not solve them with a project cleanup. 

MACOS Sierra 10.12.1
I run on SE Runtime Environment (build 1.8.0_66-b17)
Can somebody please help!!

Thanks

[1481058977381-log.txt](https://github.com/openhab/openhab-docs/files/635155/1481058977381-log.txt)

**Comment by kaikreuzer** [comment]
I guess the problem is
```
The platform metadata area could not be written: /private/var/folders/s_/b8sy6d_57j72m7cxyqh16m7r0000gn/T/AppTranslocation/20A63B29-BFCF-4015-8A7C-FEE44EBB0111/d/Eclipse SmartHome Designer.app/Contents/MacOS/workspace/.metadata.  By default the platform writes its content
under the current working directory when the platform is launched.
```
Try to launch it from a place where your user has write permissions.
For further support, please rather use our forum at https://community.openhab.org/ instead of the issue trackers - thanks!

**Comment by jsieberg** [comment]
Hallo Herr Kreuzer,

Danke für die Hilfe.
Ja die Fehlermeldung hatte ich auch gelesen. Die Designer.app liegt aber in
einem Verzeichnis mit Schreibrechten.
Ich konnte mir behelfen indem ich die Designer.app entpackt und in einzelne
Verzeichnisse geladen hatte.
Nun konnte ich die Designer application starten.

Danke und Gruß
Jürgen Sieberg ( OpenHAB Beginner ! )

Kai Kreuzer <notifications@github.com> schrieb am Mi., 7. Dez. 2016 um
08:57 Uhr:
