### ISSUE TITLE
Items/Icons Better description of dynamic icons

### ISSUE THREAD

**Issue by ThomDietrich** [openhab/openhab-docs#152]
https://github.com/openhab/openhab-distro/issues/343

It seems, that the details and functionality of dynamic icons is still pretty unclear. Should receive it's own article, possibly next to the iconsets article.

**Comment by ThomDietrich** [comment]
Additionally make restrictions of icon files clearer:

https://community.openhab.org/t/solved-custom-icons/12228/23

**Comment by ThomDietrich** [comment]
Furthermore:

> See https://community.openhab.org/t/custom-dynamic-icons-for-number-items-when-mapped/16894/10
> Unlike OH 1, OH 2 uses the label's transformed state when picking the icons, not the Item's original state.

@rkoshak ping. You wanna take on this task?

**Comment by rkoshak** [comment]
I'll take it. Probably won't get to it today but perhaps tomorrow afternoon.

Does it deserve its own article or should it be added to the icons page or the Items page or the Sitemap page? 

As an article it would only make up a few sentences.

Is this another one that needs to go to ESH and pulled in from there?

**Comment by ThomDietrich** [comment]
The ticket was aimed at this: http://docs.openhab.org/configuration/items.html#icons

The details are already there. It's just a bit messy. The whole article needs a rework but I'm afraid there is no time for that...

Do as much as you like. if you could add a [TOC](https://github.com/openhab/openhab-docs/blob/gh-pages/installation/linux.md), that would be great.

**Comment by Confectrician** [comment]
Hey @ThomDietrich,

Whats the word here?
There is a merged PR from 17 Jun.
Can this issue be closed or is there still something to do?

**Comment by ThomDietrich** [comment]
Yes. This was mostly tackled in #250 and #404, some open issues not closely related are still documented in #402 😄
