### ISSUE TITLE
The logo of the BTicinoSmarther binding is missing in the docs

### ISSUE THREAD

**Issue by hypetsch** [openhab/openhab-docs#1524]
If I am right and the file name of the logo is taken from the name of the binding, then the reason is that the image in the repo is called `bticino.png` but the binding is called `bticinosmarther`.

**Comment by Confectrician** [comment]
Ok then we should give it a try with the correct nemaing. :).

**Comment by Confectrician** [comment]
The Pull request will close this issue, please check the result and comment here if the logo is still missing.
We can then reopen and do a further research.
