### ISSUE TITLE
Wrong documentation?

### ISSUE THREAD

**Issue by muenkel** [openhab/openhab-docs#1529]
In the documentation at [https://www.openhab.org/addons/bindings/zwave/#when-things-don-t-go-as-planned](https://www.openhab.org/addons/bindings/zwave/#when-things-don-t-go-as-planned) you'll find the following:

"… To include or **exclude** a device in the network, set the controller into include mode, and press the appropriate button on the device to place the device into include mode."

I think, that this is wrong or at least confusing for the exclusion of a device. I've tried it without success. 

It would be fine, if the options to exclude a device would be described with a little more detail in this place.

Thanks.

**Comment by Confectrician** [comment]
Hi @muenkel

this has to be clarified directly in the zwave binding repository.

I have opened https://github.com/openhab/org.openhab.binding.zwave/issues/1572 to move it over there and hopefully get a solution.
When a solution is found and contributed, the binding docs will be updated with one of our next homepagebuilds.
