### ISSUE TITLE
openHAB pronunciation

### ISSUE THREAD

**Issue by ThomDietrich** [openhab/openhab-docs#153]
There should be a pronunciation information on the starting page of docs.

* https://en.wikipedia.org/wiki/International_Phonetic_Alphabet
* http://www.i2speak.com
* http://www.ipachart.com

Maybe an easier solution would be nice ;)

**Comment by BClark09** [comment]
We're supposed to spell H.A.B?! [I would have gone with](https://www.youtube.com/watch?v=5l2ND1kiBn0):

"ˈəʊpən ˈhæb "
or 
"oh pen hab (as in **hab**it)"

**Comment by ThomDietrich** [comment]
Exactly ;) The example was wrong. I've removed it to avoid confusing :sweat_smile:

**Comment by ThomDietrich** [comment]
@BClark09 do you want to take this on?

**Comment by BClark09** [comment]
Yes! Assign me away!

**Comment by ThomDietrich** [comment]
@kaikreuzer maybe not an issue for today: Do you agree that a bigger part of the openhab org members  should have the ["Read" permission](https://help.github.com/articles/repository-permission-levels-for-an-organization)? That would for example allow Ben to "Have an issue assigned to them".  

@BClark09 Even without having your avatar up there, Flame on! 🔥

**Comment by kaikreuzer** [comment]
I have added all "openHAB Contributors" at https://github.com/openhab/openhab-docs/settings/collaboration - this has simply been missed when setting up this repo.

Issue is now assigned to @BClark09 :-)
