### ISSUE TITLE
https://www.openhab.org/docs/installation/rasppi.html

### ISSUE THREAD

**Issue by mstormi** [openhab/openhab-docs#1530]
That page is old and should not be maintained any longer. It's superseded by openHABian.
I'd do a PR but I don't find the menu document that has the link to this page ("Raspberry Pi" in the left-side menu on ww.wopenhab.org/docs)

**Comment by Confectrician** [comment]
It can be found here:
https://github.com/openhab/openhab-docs/blob/main/.vuepress/docs-sidebar.js

Removing line 42 should do the trick.
https://github.com/openhab/openhab-docs/blob/main/.vuepress/docs-sidebar.js#L42

Probably the build for the PR will fail.
Removing pages can produce some problems, but we can check that in the PR then.

**Comment by mstormi** [comment]
There must be another file that contains the link text ("Raspberry Pi") as that one is not in the .js
I don't feel comfortable messing around in there.
Could you please do it ?

**Comment by rkoshak** [comment]
It pulls the link text from the page itself. The JS just has the path to the file, in this case installation/raspi.html.

The actual text is defined at the top of that file.

```
---
layout: documentation
title: Raspberry Pi
---
```
It's that "title" that defines the text that get's used for the link.

Removing line 42 from the .js file will remove it from the sidebar. If this file is indeed redundant then the .md file should be removed too. 

However, has anyone made sure that all the information that is still there is reflected elsewhere? For example, file locations and the like? The Linux installation page has them listed but the openHABian page does not. I didn't see anything else that might be lost but I only did a quick scan.

**Comment by Confectrician** [comment]
Rich is right here.
When we do not want to specifiy the link, we just add it without any description.
It will then get the title parameter from the page as link text.

If we want to overwrite it, we can use the extended syntax with square brackets and a name that will be used instead of the title.

**Comment by mstormi** [comment]
I want to delete it. So cut out the line ?

**Comment by rkoshak** [comment]
And also delete the .md file installation/rasspi.md. We don't want orphaned pages hanging around.
