### ISSUE TITLE
Version selector and "latest" version

### ISSUE THREAD

**Issue by ivanxx** [openhab/openhab-docs#1535]
I think the actual "latest" version should be numerically listed in the selector drop down menu.

At this moment (3.0 version being latest) you see a list comprised by: latest, 2.5, 2.4, 2.3, etc. Looking at that list you can't tell a 3.0 version has been released, and there's a chance you end up looking at "latest" docs thinking they are for what you believe is "latest" (2.5 at this time).

Possible solutions include specifying the numeric version after the "Latest" word  eg. "Latest (3.0)", or simply adding the numeric latest to the list and making "Latest" and numeric latest point to the same set of docs.

**Comment by Confectrician** [comment]
cc @ghys 

Good idea from my view.
We could add this dynamically and fetch the current version in our artifactory or distro releases.

**Comment by Rossko57** [comment]
As a related issue ...
"Latest" docs may describe new features found e.g. in a milestone release but not in the current stable release?  We certainly had events like that with OH2.

Current stable release should I think be the the default docs version offered.

**Comment by Confectrician** [comment]
We had this discussion already somewhere here and the result ended in keeping the latest docs as default.

Anyway i have discussed adding a "proper hint" with @ghys  already.
We should show the user which version of the is shown currently and maybe add a link to the current stable docs directly.

**Comment by Confectrician** [comment]
We have made several changes to the docs and version selectors.

Further information can be found here: https://community.openhab.org/t/important-changes-to-the-documentation-versioning/122369?u=confectrician
