### ISSUE TITLE
QNAP installation missing in menu

### ISSUE THREAD

**Issue by andreasbenzing** [openhab/openhab-docs#1541]
While looking for openHab on NAS, I stumbled over https://www.openhab.org/docs/installation/qnap.html and found it's missing in the menu on the left.

Since I couldn't find where the menu is located, I couldn't open a MR.

**Comment by Confectrician** [comment]
It has been removed on purpose.

We could not validate the maintenance state of the qnap repository and so were not able to get a final statement if the qnap package is working with openHAB 3.

**Comment by andreasbenzing** [comment]
In that case I suggest to either create a note on the QNAP page or remove it from the documentation. Otherwise this is confusing for people who end up on the page after searching for "qnap openhab" or similar.

**Comment by Confectrician** [comment]
If you are able to check the package for a valid openHAB 3 installation i am happy to reintroduce the sidebar entry.
It was meant as a temporary workaround.

If it is only available for openHAB 2 we should

- remove it here completely indeed (fully agree)
- add a redirect to v2 qnap docs in the openhab/website repository to prevent google searches from landing in a 404 page

Are you able to provide some tested informatoins for openHAB 3 in theory?

**Comment by andreasbenzing** [comment]
Unfortunately, I don't have a QNAP available for testing. I came across the page looking which NAS to choose.
