### ISSUE TITLE
Possibility: add asciinema demos to articles like Linux.md

### ISSUE THREAD

**Issue by ThomDietrich** [openhab/openhab-docs#157]
https://asciinema.org

Example: https://asciinema.org/a/96303

**Comment by BClark09** [comment]
This is fantastic! Copy and paste on-top is a brilliant feature.

**Comment by ThomDietrich** [comment]
Indeed :) I think it will be pretty nice to have a hands on demo of what's described in the following text, just as in the saying: "A picture is worth a thousand words"

**Comment by BClark09** [comment]
https://asciinema.org/a/96340 :)
