### ISSUE TITLE
Versions <= 2.4 do not work

### ISSUE THREAD

**Issue by pfink** [openhab/openhab-docs#1572]
When I select documentation versions <= 2.4, I'm redirected back to "latest". This should be either fixed, or the non-working links should be removed from the dropdown.

**Comment by Confectrician** [comment]
Just as in information:

I am not up to date to the latest changes, but we are still working on https://community.openhab.org/t/important-changes-to-the-documentation-versioning/122369 so this may be solved with one of the next changes then anyways.

**Comment by Confectrician** [comment]
Hey @pfink can you tell us the domain you  are using the docs with for this?

The version selector on next.openhab.org and www.openhab.org should not show the old versions anymore.
The v2.openhab.org docs still show the old version selector, but changes are not finally done over there.

Just want to make sure we did not forget to remove something in the current stable and development docs versions.

**Comment by pfink** [comment]
Now it looks better, version selector on the left side disappeared now or has been replaced. But I discovered on [this page](https://v2.openhab.org/docs/developer/) that there is still a version selector on the right side with dead links.

**Comment by Confectrician** [comment]
Thanks for the feedback.
Yes this is still in refactoring and will be replaced with a proper solution next days. 👍🏼
