### ISSUE TITLE
OH2 install instructions

### ISSUE THREAD

**Issue by mstormi** [openhab/openhab-docs#1608]
Just came across #1607 and that reminds me that the openHABian instructions need to be changed for OH2, too.
Essentially in order to get OH2, users need to set `clonebranch=stable` in `openhabian.conf` AFTER flashing but BEFORE you boot, else it'll install openHAB3. 
See https://www.openhab.org/docs/installation/openhabian.html#openhabian-conf how to edit `openhabian.conf`.

Also correct the link in "either by plugging an Ethernet cable or configuring the Wi-Fi, and boot!"
* remove the word "the" from the link text
* remove the dash from wi-fi of the link target so it becomes
https://v2.openhab.org/docs/installation/openhabian.html#wifi-based-setup-notes

**Comment by Confectrician** [comment]
File reference for OH2: https://github.com/openhab/openhab-docs/blob/final-2.5.x/installation/openhabian.md

Should we add a Warning box or something like that to get this important information visible in a popular way?

**Comment by mstormi** [comment]
> File reference for OH2: https://github.com/openhab/openhab-docs/blob/final-2.5.x/installation/openhabian.md

isn't the latest openhabian.md pulled in at some point in time so this is always the current document (valid for OH3) ?
If no, what's the source for this ? or is it a copy taken on day X and is it static now ?

> Should we also add a Warning box or something like that to get this important information visible in a popular way?

yes please

**Comment by Confectrician** [comment]
From the title i expected that we only want to change oh2 instruction in the oh2 related website version.
With the referenced file we only change the contents that are visible on https://v2.openhab.org/docs/installation/openhabian.html
This doens't get fetched anymore. (Side note: this will be the same for the openhab 3.0.x docs from today on.)

The contents of https://www.openhab.org/docs/installation/openhabian.html are getting fetched from the openhabian repository. (But from my view they should only include the latest/stable version related instructions)

**Comment by mstormi** [comment]
> From the title i expected that we only want to change oh2 instruction in the oh2 related website version.

right so please proceed
