### ISSUE TITLE
Metrics Grafana metrics example download link doesn't work 

### ISSUE THREAD

**Issue by robnielsen** [openhab/openhab-docs#1613]
The [Grafana ](https://www.openhab.org/addons/integrations/metrics/#grafana) section provides a link to download the dashboard. It includes a link that doesn't work with the website (https://www.openhab.org/addons/integrations/metrics/doc/dashboard.json)

**Comment by robnielsen** [comment]
This issue is also referenced at  https://github.com/openhab/openhab-addons/issues/10916

**Comment by Confectrician** [comment]
The issue has to be solved in the openhab-addons repository.
We will then get the updated readme page automatically.
