### ISSUE TITLE
Sitemap sliders section mentions switchSupport but only switchEnabled is supported

### ISSUE THREAD

**Issue by obones** [openhab/openhab-docs#1616]
In OH3, one can edit a sitemap in the classic UI, especially to add sliders.
The interface allows setting a "Switch enabled" toggle, which translates to `switchEnabled` in the code section

In the documentation for sitemap sliders, `switchEnabled` is not described but `switchSupport` is which seems equivalent and is described like this:

> * Classic UI: If specified, a short press on the "up" or "down" button switches the item "on" or "off" (0 or 100) respectively.
> * Android app: If specified, a short press on the item row (except the slider itself) switches the item "on" or "off".

I believe the documentation should be updated to reflect the new name of the parameter.

On top of this, it was discovered through [discussion](https://community.openhab.org/t/slider-in-sitemap-switchenabled-does-not-seem-to-have-any-effect/124341) that activating `switchEnabled` would actually send ON/OFF commands to the item it is linked to. But the documentation for the Classic UI part hints that it would send values 0 and 100.
I believe it would be nice if the wording was clarified to indicate what the code is really doing, either sending values or sending commands. This would make it clear that the `switchEnabled` option has no effect on rollershutters which do not know how to deal with ON/OFF commands.

**Comment by Confectrician** [comment]
I think we simply have to remove the classic ui part.
Classic UI is no longer a port of openHAB since openHAB 3.0.

I am also not aware of any implementation done in Basic UI.
So only the Android App part is still valid.
