### ISSUE TITLE
Remove CalDAV from incompatibility list

### ISSUE THREAD

**Issue by ThomDietrich** [openhab/openhab-docs#163]
With one exception, documented in wiki:
https://github.com/openhab/openhab/issues/4917
https://github.com/openhab/openhab/wiki/CalDAV#note-for-openhab-2

**Comment by ThomDietrich** [comment]
Same goes for insteonplm
https://github.com/openhab/openhab/issues/3922#ref-pullrequest-197174009

**Comment by cniweb** [comment]
Note for openHAB 2 in openHAB 1 wiki removed.

**Comment by Confectrician** [comment]
Can this issue be closed?
