### ISSUE TITLE
{Wiki Edit} apt-transport-https is it supported by default in new systems

### ISSUE THREAD

**Issue by MDAR** [openhab/openhab-docs#1638]
Hi

I am in conversation with Michal @ DietPi about adding openHAB to their software menu.

It seems they would prefer to set a different set of ports, which I understand is fairly easy.

Michal has commented that the need to install `apt-transport-https` is redundant as 
> this is a transitional dummy package only, as HTTPS support is natively integrated into APT.

https://github.com/MichaIng/DietPi/issues/3857

Should that line be removed from the Linux install guide, or does it do no harm to have it there for older systems?

https://www.openhab.org/docs/installation/linux.html#package-repository-installation

**Comment by MichaIng** [comment]
It does not harm to have that package installed, but it is simply obsolete and I see this being part of guides and scripts addressing modern Debian and Ubuntu versions much too often 😉.
