### ISSUE TITLE
Certificate for docs website not trusted by browser

### ISSUE THREAD

**Issue by metbril** [openhab/openhab-docs#164]
When accessing the docs website through https://docs.openhab.org instead of http://docs.openhab.org, the browser (Safari for iOS, Firefox for Mac) shows a message that the website cannot be trusted. This is due to the fact that the site is using the Github certificate instead of one from openHAB.org.

**Comment by kaikreuzer** [comment]
This is due to https://github.com/isaacs/github/issues/156.
We might consider using cloudflare to resolve this, but I didn't yet find the time to look into this in more detail.

**Comment by ThomDietrich** [comment]
If an installation on a dedicated instance is planned, we should talk about thereby possible plugins. e.g. https://github.com/openhab/openhab-docs/issues/150 (Search function).

**Comment by kaikreuzer** [comment]
Not really planned atm. Already having too many servers that we need to monitor and regularly reboot - happy for everything that is hosted on Github instead...

**Comment by ThomDietrich** [comment]
Fine by me, I'd just like to know what to plan for ;)

**Comment by konklone** [comment]
You could also pay $13/month and put it onto a service like [surge.sh](https://surge.sh). It'd be better than CloudFlare, as with CloudFlare the connection would still be unencrypted between CloudFlare's CDN and GitHub's CDN.

**Comment by kaikreuzer** [comment]
> the connection would still be unencrypted between CloudFlare's CDN and GitHub's CDN.

That does not really matter as we are anyhow only talking about publicly available content.

**Comment by konklone** [comment]
It's about more than privacy - it's also about preventing [malicious code from being injected into unprotected traffic](https://arxiv.org/abs/1602.07128). The link between GitHub and Cloudflare would make an attractive central point for a [coordinated attack](https://medium.com/@karthikb351/airtel-is-sniffing-and-censoring-cloudflares-traffic-in-india-and-they-don-t-even-know-it-90935f7f6d98#.s65tcm1vm) against all visitors of GitHub Pages sites that have CloudFlare in front.

**Comment by rtvb** [comment]
@ThomDietrich Why did you close this issue? It is not resolved yet?

**Comment by kaikreuzer** [comment]
FTR: I have meanwhile successfully migrated the foundation's website to Cloudflare, see https://www.openhabfoundation.org/ (with the help of @MHerbst), which is also hosted on Github Pages.

I think this would be a good (and free) compromise for docs.openhab.org as well. So if you agree, I could would move the site's DNS records to Cloudflare as well.

**Comment by rtvb** [comment]
Please see comment https://github.com/openhab/openhab-docs/issues/164#issuecomment-269642824 re. injections.

**Comment by kaikreuzer** [comment]
That's what I meant with "good compromise". I don't really think that injections are an issue for us as all content is publicly hosted, not confidential and not security critical. We survived with http all over the years and switching to https is mainly necessary for making Chrome happy.

**Comment by ThomDietrich** [comment]
Sorry @rtvb I was sweeping through issues today and thought the topic was settled as the last info was to stay on GitHub. I've read the concerns and studied the articles you both linked. That's indeed an unpleasant topic we should consider when the only reason for moving over to another hosting service is https. Which alternatives would you suggest?

**Comment by konklone** [comment]
> That's what I meant with "good compromise". I don't really think that injections are an issue for us as all content is publicly hosted, not confidential and not security critical.

While using CloudFlare is helpful, that argument doesn't make sense. Malicious code injections don't have to relate to the content being served. They can forcibly enlist the user's computer into a botnet, for DDoS or otherwise, or can serve code that takes advantage of unpatched vulnerabilities. 

Your website also doesn't have to be specifically targeted -- code injection logic could be applied to unencrypted traffic at large.

You may still view using CloudFlare as an acceptable mitigation, but you should not argue that your website's non-confidential content somehow lowers the risk involved in code injection.

**Comment by kaikreuzer** [comment]
> but you should not argue that your website's non-confidential content somehow lowers the risk involved in code injection.

You are right, this arguing was not correct. My main argument is indeed that it is not worse than using http.

**Comment by MHerbst** [comment]
Ther certificate is OK now, so this issue could be closes  @ThomDietrich
