### ISSUE TITLE
Documentation points to JCenter, but it seems to be gone

### ISSUE THREAD

**Issue by 0815fox** [openhab/openhab-docs#1647]
https://www.openhab.org/docs/developer/buildsystem.html#adding-dependencies states:

> Generally all dependencies should be OSGi-bundles and available on JCenter.

However, JCenter seems to have gone. Is there any replacement? Is it mvnrepository.com now?

(Asking this because I am a newcomer on binding development and also unexperienced in the java/maven ecosystem.)

**Comment by kaikreuzer** [comment]
Thanks for pointing this out - I have created https://github.com/openhab/openhab-docs/pull/1669 to replace JCenter by Maven Central, which is the global reference for any dependency in the Java ecosystem.
