### ISSUE TITLE
[Admin/Bundles] naming convention of an addon

### ISSUE THREAD

**Issue by ThomDietrich** [openhab/openhab-docs#165]
Add the following description to "Advanced Functionality", wherever fitting.
https://community.openhab.org/t/addons-cfg-proper-way-to-discover-the-name-of-an-addon/17107/3

**Comment by Confectrician** [comment]
> wherever fitting
I would suggest http://docs.openhab.org/administration/bundles.html

If you agree you can assign me and i will add a section about that.

**Comment by ThomDietrich** [comment]
👍 sounds right. Here we go...
