### ISSUE TITLE
[Concepts/ESH] Introduce "Trigger Channels"

### ISSUE THREAD

**Issue by ThomDietrich** [openhab/openhab-docs#166]
What/Why/When/How?
https://community.openhab.org/t/astro-binding-issue/2011/43

**Comment by ThomDietrich** [comment]
@kaikreuzer Who may we ping for that? Can possibly be copied over from ESH?

**Comment by kaikreuzer** [comment]
Should probably be a part of the "Things concept" page to mention them in general. How to create rules that make use of them, probably needs to go to the rule section (we already have examples there, don't we?)
Sorry, I don't know anybody, who could be pinged... Probably leaves mainly me, but I am not sure how much I can add during the next days...

**Comment by ThomDietrich** [comment]
Ran into this today. With the nice coverage of possible triggers for rules, this one is missing from http://docs.openhab.org/configuration/rules-dsl.html

We should cover "Channel-based Triggers", should only be a few lines of information. @openhab/documentation-maintainers who wants to give it a shot?

Example 1: https://community.openhab.org/t/astro-binding-issue/2011/43
Example 2: https://github.com/openhab/openhab2-addons/blob/da3d85f71471a60b848e9c09826dec35a8f5507c/addons/binding/org.openhab.binding.amazondashbutton/README.md#full-example
Definition: https://github.com/eclipse/smarthome/blob/master/docs/documentation/development/bindings/thing-definition.md#channels
