### ISSUE TITLE
Netatmo 1.x binding is missing from the list of compatible 1.x bindings

### ISSUE THREAD

**Issue by robnielsen** [openhab/openhab-docs#167]
The OH1 netatmo binding works with OH2, but is missing from the list of compatible 1.x bindings. One thing to note is that it requires enabling legacy 1.x bindings to see it in the paper ui.

**Comment by ThomDietrich** [comment]
@robnielsen thanks for pointing that out. Is the 1.x binding still relevant in comparison to the 2.0 binding?
http://docs.openhab.org/addons/bindings/netatmo/readme.html

**Comment by robnielsen** [comment]
@ThomDietrich, yes it is. The 2.0 binding is still missing a bunch of functionality that the 1.x binding has.

**Comment by ThomDietrich** [comment]
@kaikreuzer

**Comment by robnielsen** [comment]
Here's a few:

- Ability to set unit system
- Ability to set pressure units
- Min/Max and Sum types

**Comment by kaikreuzer** [comment]
As pointed out in the other issue, we should change [this title](http://docs.openhab.org/addons/bindings.html#legacy-1x-bindings) anyhow to just call it "1.x Bindings" and in [here](http://docs.openhab.org/addons/bindings.html#further-1x-bindings) we could add a new list of all legacy 1.x bindings.

**Comment by robnielsen** [comment]
@kaikreuzer. So what makes a binding legacy? I'd hope this would only happen once a 2.0 binding is as full featured as the 1.x, otherwise the 2.0 should be a beta binding or something similar.

**Comment by Confectrician** [comment]
Hey @openhab/documentation-maintainers 

I think this could be closed or am i wrong?

**Comment by ThomDietrich** [comment]
For sure.
