### ISSUE TITLE
Emphasize that karaf is only reachable from the local host by default

### ISSUE THREAD

**Issue by ShaunCurrier** [openhab/openhab-docs#168]
The documentation [here](http://docs.openhab.org/administration/console.html) does not really emphasize that the karaf ssh interface is only accessible internally on localhost by default.  One would have to either have this be obvious to them (it wasn't to me) or to have some non-beginner knowledge and pay special attention to the code example (which shows `ssh openhab@localhost -p 8101`) to realize this.

I suggest that the main paragraph that explains how to access karaf should emphasize this fact and emphasize that `ssh openhab@localhost -p 8101` can be run from an already-open terminal to their openhab machine.

**Comment by ThomDietrich** [comment]
Thanks @scurrier03. Looking at the article I can totally agree. Will look into this in the next couple of days.

**Comment by ThomDietrich** [comment]
We should also mention, that the first connection will be the trigger to generate the internal karaf remote console key and can take a few seconds and even timeout on slower systems (RPi2/3). https://github.com/openhab/openhab-linuxpkg/issues/15#issuecomment-272630590

**Comment by splatch** [comment]
> The documentation here does not really emphasize that the karaf ssh interface is only accessible internally on localhost by default. 

Documentation does say that in later part
> By default openHAB binds its shell to localhost only due to obvious security reasons. 

We can reorganize documentation so this sentence will be present in first paragraph making no confusion to inpatient readers. :-)

**Comment by ThomDietrich** [comment]
Yes I think that's what we have to take from the issue. Yes it's there but obviously should be mentioned where the "impatient reader" (perfect choice of words :smiley:) does find it.

**Comment by scurrier03** [comment]
Agree on both counts :)

**Comment by chriscolden** [comment]
Details should be added to the documentation on changing the default ssh port.

I've had a go at documenting it in the tutorials section of the community forum.
https://community.openhab.org/t/howto-change-ssh-port-on-openhab2/23669/5

**Comment by ThomDietrich** [comment]
All mentioned here should be settled. Please review the new content at http://docs.openhab.org/administration/console.html
