### ISSUE TITLE
Allow readme.md in addition to README.md?

### ISSUE THREAD

**Issue by MHerbst** [openhab/openhab-docs#169]
I was missing the documentation for the Yamaha Receiver binding on docs.openhab.org After checking the maven pom file that is used to generate the documentation the reason is clear: the readme file of the Yamaha Receiver binding is written in lower-case. Github accepts it, but not the pom file.

We can either modify the pom file and allow readme.md or change readme.md to README.md.

**Comment by ThomDietrich** [comment]
Thanks @MHerbst. I'll look at this and all the other tickets opened the last couple of days shortly.

**Comment by kaikreuzer** [comment]
>  or change readme.md to README.md.

I'd actually vote for this, because README.md is what is usually used on Github.

**Comment by ThomDietrich** [comment]
I didn't see https://github.com/openhab/openhab2-addons/pull/1633 before, that's great work @kaikreuzer ;)
