### ISSUE TITLE
Testing documentation

### ISSUE THREAD

**Issue by svilenvul** [openhab/openhab-docs#17]
I would like to contribute to the testing documentation. 
I think it might be difficult for new binding developers to set up and run integration test in openHAB (Eclipse SmartHome too)

Currently we have [Testing Eclipse SmartHome](https://www.eclipse.org/smarthome/documentation/development/testing.html). It is a good staring point, but I would like to go with a different approach - something more like "HelloTest" bundle for beginners. I would like to make a step-by-step developer guide:
- create a bundle with the binding skeleton
- add Groovy and Maven support
- write simple test
- create Eclipse test configuration 
  - how to  use the UI
  - how run the test 
  - how to export the configuration to a file 
- create Maven/Tycho test configuration
  - choose the correct packaging type
  - how to add extra dependencies and why is this needed (maybe create some dependency problem first and show how to debug it )
  - how to enable logging

I think this can be added to ''Developers -> Basics -> Write a simple test'' page for example. 
Please, let me know what do you think about this idea. 
##

**Comment by ThomDietrich** [comment]
@svilenvul can this ticket be closed?
