### ISSUE TITLE
Devolo MT 2650 does not receive setpoint

### ISSUE THREAD

**Issue by jsieberg** [openhab/openhab-docs#170]
I'm using Raspi with openhab2 and ZME-UZB1. 
Cyrus Sensor and Green switch are working fine. 
I selected the Devolo heating control because it delivers the current temperature. 
I get the temperature but the set point is never set.  I read this already in chats of 2015 and hope that this is solved.
The z-wave device list lists the MT 2650! So it should work.
What is wrong? is there a wrong setup?
I see E5 error on the Devolo thermostat. 
I can see the error in log file 
"unsupported command 8 for command class CLIMATE_CONTROL_SCHEDULE".
This is weird. Is MT 2650 supported or not?

**Comment by ThomDietrich** [comment]
Discussed/Solved in https://community.openhab.org/t/devolo-mt-2650-does-not-receive-setpoint/19015
