### ISSUE TITLE
How to use Scripts

### ISSUE THREAD

**Issue by NCC1701M** [openhab/openhab-docs#1716]
I've search for quite a time but I couldn't find any information about how to use the Scripts I can add under the *Scripts* tab.

![image](https://user-images.githubusercontent.com/7260053/147701309-ca6b0fa7-4bc1-4708-b9bf-4a308ca582a2.png)

Is there a way I can reference scripts in my rules like e.g. a function?

**Comment by Confectrician** [comment]
Scripts are a rule too in background.

So you could for example define something like: "Increase my rdaio volume by 1 point"

Example:
![image](https://user-images.githubusercontent.com/7161177/147703240-eb74f675-72ac-464e-8e29-3dd6efa6afa6.png)

Script content:
![image](https://user-images.githubusercontent.com/7161177/147703273-39462a3c-e475-4aa0-beca-6b903fe5410a.png)

You could then use this script within "regular" rules in the `then` Area.

Example:
![image](https://user-images.githubusercontent.com/7161177/147703429-4bcdf6ba-9e37-4c5e-99f1-9f0f1696a548.png)

with configuration:
![image](https://user-images.githubusercontent.com/7161177/147703482-e766d318-15b2-4094-97f7-1836f728b36f.png)

In general, that's it already.
If you have reoccuring tasks, that you want to execure at different places a script could be generated and used several times.

Hope this helps. :)

**Comment by NCC1701M** [comment]
Thanks for your answer.

But I think the whole "Scripts" topic needs more documentation

**Comment by Confectrician** [comment]
So i will leave this issue open then.

Maybe someone is interested in starting some content and explanations about the scripts part.
I have provided a good base with the contents above. 🙂

**Comment by Confectrician** [comment]
He @rkoshak just a question.

Are we able to solve this issue parallel to #1855 with tas `1d`?

If it aims for the same content, i would close this one and reference to the rules documentation reworking.

**Comment by rkoshak** [comment]
I think so. It's also briefly discussed in the Getting Started Tutorial. 

The multiple uses of the term "script" is really unfortunate but I don't have a better name for any of them.

I think this can be closed.
