### ISSUE TITLE
Add

### ISSUE THREAD

**Issue by buzink** [openhab/openhab-docs#172]
Please add thetext below to the bottom of the page http://docs.openhab.org/installation/openhabian.html as this is the only step of the linux manual (http://docs.openhab.org/installation/linux.html) that is not preconfigured in openhabian.

"Java Network Permissions

The Java Virtual Machine hosting openHAB is restricted in it’s permissions to interact on network level for security reasons. Some openHAB addons, like the Network or AmazonDash bindings, need elevated permissions to work. If needed, grand these permissions by executing the following command:

setcap 'cap_net_raw,cap_net_admin=+eip cap_net_bind_service=+ep' `realpath /usr/bin/java` "

**Comment by ThomDietrich** [comment]
Hello @buzink,
I believe that is not correct. The mentioned step is part of openHABian: https://github.com/openhab/openhabian/blob/master/openhabian-setup.sh#L339
Could you please recheck if what you are looking for is covered by that?

**Comment by buzink** [comment]
You're right. Thanks.
