### ISSUE TITLE
Status of https://openhab.github.io/

### ISSUE THREAD

**Issue by martinvw** [openhab/openhab-docs#1724]
Somehow a user ended up on the documentation at https://openhab.github.io/addons/bindings/heos/

However this seems outdated, could we take it offline or make it redirect 

Thanks

**Comment by Confectrician** [comment]
I don't even know where this is coming from.
I will check it together with @kaikreuzer. (cc @ghys)

Probably it is our base organization repository or the website one, which is providing some github pages.

**Comment by Confectrician** [comment]
I have found it @martinvw 

https://github.com/openhab/openhab.github.io

I knew about this repo but i wasn't aware that it still exists.

I will claim maintainer rights and add a redirect to our current documentation.

**Comment by martinvw** [comment]
Awesome!

**Comment by Confectrician** [comment]
Yep works fine. I have tested the path building with the heos page (works like a charme) and will now also add the 404 live redirects.
