### ISSUE TITLE
Make "advanced" tutorial a "Z-Wave + HABmin" tutorial?

### ISSUE THREAD

**Issue by kaikreuzer** [openhab/openhab-docs#174]
Looking at http://docs.openhab.org/tutorials/advanced/installing.html, this is not really for "advanced" users (e.g. people that want to use all features of openHAB, i.e. similar to openHAB 1 expert users), but it mainly speaks about HABmin, which is not necessarily the tool that all advanced users want or should use (while of course being a valid option).

As I doubt that we will be able to update the tutorial in time for the 2.0 release, I wonder if we should simply rename it to make it clear that it is explaining the use of HABmin? Or we remove it as a tutorial completely and move the content to the [HABmin user guide](http://docs.openhab.org/addons/uis/habmin/readme.html)?

**Comment by bodiroga** [comment]
Hi Kai!

I don't think that I'm the right person to talk about the openHAB documentation, but reading that link I realized that that tutorial is old and outdated. HABmin can be installed through the Paper UI without any hassle (you don't need to download any .jar file from the github repository) and it doesn't need the ZWave binding to be installed, so, I'm pretty sure that you can delete (or at least hide) it ;)

Many thanks for your hard work!

**Comment by ThomDietrich** [comment]
I'll talk to Christian, the author of the other tutorial (https://github.com/openhab/openhab-docs/issues/191), about how this can best be integrated.

**Comment by gitMiguel** [comment]
@Confectrician I'll start from from the oldest ones. This issue is stale.

**Comment by Confectrician** [comment]
I will close this one immediately.
Having OH3 in the back we shoudl wait for significant changes and provide a well explained tutorial based on the newest environment.
