### ISSUE TITLE
Describe changing the HTTP(S) port

### ISSUE THREAD

**Issue by kaikreuzer** [openhab/openhab-docs#175]
This is a very regular question, and I didn't see this covered yet in the documentation (while it was afair there in the initial version of docs.openhab.org). Should probably go somewhere under "Configuration" (where?).

**Comment by ThomDietrich** [comment]
Hey Kai, there is indeed no fitting place to put this information in the current docs structure.
I feel like this should be mentioned somewhere under http://docs.openhab.org/installation/index.html
If the menu name would have been chosen differently, this topic could be addressed in http://docs.openhab.org/installation/nginx.html
@BClark09 what do you think?

**Comment by BClark09** [comment]
It might be better to assign this instruction into "Configuration" as @kaikreuzer  said. I'd think the best approach would be to have a new page called "System" inside here, which can cover topics about the additional optional choices a user can make. 

As well as changing the local port, other common configurations in here can include changing the locale or anything else mentioned on the same page:

![image](https://cloud.githubusercontent.com/assets/8983584/21963154/235bff04-db2d-11e6-9b87-94ff5e284726.png)

**Comment by ThomDietrich** [comment]
We are once again trapped in the discussion about what is covered by "Installation" and "Configuration". You probably remember that I was looking for better words for these two big documentation categories. The first was supposed to cover installation and set up of the openHAB distribution on the **outside**, the second was supposed to describe how to configure your home automation system **inside** openHAB. There is a third option "Advanced Functionality", which could also cover topics like these.

I'm not strictly against changing strategies, we just have to find a consistent solution. Maybe we should further discuss this after next week.

**Comment by kaikreuzer** [comment]
Why is it a changing strategy to put it under Configuration?
To me, the installation/setup is what you have to do **outside** in order to make openHAB "being there and startable" at all. Changing the port is something that has effects **inside** of openHAB, just as locale, what add-ons are there, etc. It is nothing that everybody has to be pointed to during the installation, it is rather "advanced configuration" for people that want to do something special.

**Comment by ThomDietrich** [comment]
"advanced configuration" as in "advanced functionality"?
My intention is to leave the part of docs that's called "Configuration" to only talk about home automation setup: things and items definition, sitemaps, rule building, yada yada. The HTTP port is clearly a technical matter. We have to be careful to not mix too many different worlds. Did you take the time to read issue 160? It's an interesting perspective.

**Comment by kaikreuzer** [comment]
> "Configuration" to only talk about home automation setup: things and items definition, sitemaps, rule building, yada yada

What about the other configurations that you find in the Paper UI under "Configuration->System"? Locales, Persistence, JSON Storage, Legacy-Addon configuration, Linking mode, access control / security, etc? To me this is all clearly a configuration aspect.

**Comment by kaikreuzer** [comment]
I have now added information on how to change the port AND how to bind only to a certain interface to the new "security" page, see https://github.com/openhab/openhab-docs/pull/218 - I think this is a good place for now.

**Comment by BClark09** [comment]
Can this issue be closed now? I think one new action that may need to be raised from the above conversation is that a variable be made for the binding interface.

**Comment by ThomDietrich** [comment]
@BClark09 Sounds about right. Can you create one?

**Comment by BClark09** [comment]
Whilst looking into it, it seems that we already have one! $OPENHAB_HTTP_ADDRESS is the environment variable you can set to do this.

Is it worth editing the docs to mention it? I think so.
