### ISSUE TITLE
Link in "tip" header not rendered

### ISSUE THREAD

**Issue by mueller-ma** [openhab/openhab-docs#1760]
On https://www.openhab.org/docs/installation/openhabian-debug.html there's a tip box with a link in the title. The markdown link isn't rendered as link:

![grafik](https://user-images.githubusercontent.com/22525368/154517389-0158394a-e9ad-4e6c-b159-83f5a95c2fbc.png)

On GitHub the link is rendered correctly: https://github.com/openhab/openhabian/blob/main/docs/openhabian-DEBUG.md

**Comment by Confectrician** [comment]
I have probably solved it in the openhabian code base.
Let's see if it works.

**Comment by mueller-ma** [comment]
On the website it's still broken.

**Comment by Confectrician** [comment]
The "stable" website has not been updated for the openhabian docs.
This will likely happen on the next openhabian release.

https://next.openhab.org/docs/installation/openhabian-debug.html
Is newer and has a fixed version in place.

**Comment by Confectrician** [comment]
The "stable" website has not been updated for the openhabian docs.
This will likely happen on the next openhabian release.

https://next.openhab.org/docs/installation/openhabian-debug.html
Is newer and has a fixed version in place.
