### ISSUE TITLE
karaf / bindings / file locks

### ISSUE THREAD

**Issue by thales-man** [openhab/openhab-docs#1774]
OH3.2.1, RPi4 4gb, RfxComm, Aeotec ZWave Gen5+ (USB3 ports). Raspbee II (GPIO)

I've been reporting issues with bindings where I now think a more fundamental problem may exist. I'm getting binding errors occurring on Z-Wave, ZigBee (deConz), and RfxCom bindings. A restart can fix this, but the breaks are getting more frequent. Checking the status this morning I was confronted with this:

=============================================
 openhab.service - openHAB instance, reachable at http://openhabian:8080
   Loaded: loaded (/lib/systemd/system/openhab.service; enabled; vendor preset: enabled)
  Drop-In: /etc/systemd/system/openhab.service.d
           └─override.conf
   Active: active (running) since Sun 2022-03-06 06:22:39 GMT; 19min ago
     Docs: https://www.openhab.org/docs/
           https://community.openhab.org
 Main PID: 1709 (java)
    Tasks: 195 (limit: 4915)
   CGroup: /system.slice/openhab.service
           └─1709 /usr/bin/java -XX:-UsePerfData -Dopenhab.home=/usr/share/openhab -Dopenhab.conf=/etc/openhab -Dopenhab.runtime=/usr/share/openhab/runtime 

Mar 06 06:41:27 openhabian karaf[1709]: RXTX fhs_lock() Error: opening lock file: /var/lock/LCK..ttyUSB0: File exists. It is NOT mine
Mar 06 06:41:27 openhabian karaf[1709]: RXTX fhs_lock() Error: opening lock file: /var/lock/LCWarning: The unit file, source configuration file or drop-ins 
K..ttyACM0: File exists. It is NOT mine
Mar 06 06:41:36 openhabian karaf[1709]: RXTX fhs_lock() Error: opening lock file: /var/lock/LCK..ttyUSB0: File exists. It is NOT mine
Mar 06 06:41:36 openhabian karaf[1709]: RXTX fhs_lock() Error: opening lock file: /var/lock/LCK..ttyACM0: File exists. It is NOT mine
Mar 06 06:41:36 openhabian karaf[1709]: RXTX fhs_lock() Error: opening lock file: /var/lock/LCK..ttyUSB0: File exists. It is NOT mine
Mar 06 06:41:36 openhabian karaf[1709]: RXTX fhs_lock() Error: opening lock file: /var/lock/LCK..ttyACM0: File exists. It is NOT mine
Mar 06 06:42:06 openhabian karaf[1709]: RXTX fhs_lock() Error: opening lock file: /var/lock/LCK..ttyUSB0: File exists. It is NOT mine
Mar 06 06:42:06 openhabian karaf[1709]: RXTX fhs_lock() Error: opening lock file: /var/lock/LCK..ttyACM0: File exists. It is NOT mine
Mar 06 06:42:06 openhabian karaf[1709]: RXTX fhs_lock() Error: opening lock file: /var/lock/LCK..ttyUSB0: File exists. It is NOT mine
Mar 06 06:42:06 openhabian karaf[1709]: RXTX fhs_lock() Error: opening lock file: /var/lock/LCK..ttyACM0: File exists. It is NOT mine

=============================================

It's a general question as to whether anybody has an idea what might be causing this? But it looks to me like this might need a code fix.

**Comment by rkoshak** [comment]
This belongs in the openhab-addons or openhab-core. This repo is strictly about the docs, not the code.

**Comment by Confectrician** [comment]
@kaikreuzer may you transfer this one? I am not able to transfer issues to core or addons repository.

**Comment by Confectrician** [comment]
Thanks for the feedback and no worries about the wrong place.
We would have lead you to the right place in any way, to get the problem known to the needed contributors.
