### ISSUE TITLE
Warning: apt-key is deprecated. Manage keyring files in trusted.gpg.d instead (see apt-key(8)).

### ISSUE THREAD

**Issue by dilyanpalauzov** [openhab/openhab-docs#1782]
https://www.openhab.org/docs/installation/linux.html#package-repository-installation suggests executing:

> Add the openHAB Stable Repository to your systems apt sources list:
> echo 'deb https://openhab.jfrog.io/artifactory/openhab-linuxpkg stable main' | sudo tee /etc/apt/sources.list.d/openhab.list

But doing so prints:
> root@raspberrypi:~# wget -qO - 'https://openhab.jfrog.io/artifactory/api/gpg/key/public' | sudo apt-key add -
> Warning: apt-key is deprecated. Manage keyring files in trusted.gpg.d instead (see apt-key(8)).
> OK

**Comment by Confectrician** [comment]
https://www.openhab.org/download/ does state the same, so we should have a general update in all palces where we provide install instructions.
