### ISSUE TITLE
Define open tasks for openHAB 2.0.0 GA release

### ISSUE THREAD

**Issue by ThomDietrich** [openhab/openhab-docs#179]
I hope to find the time in the next couple of days to define what, in my opinion, are the crucial parts of docs that need contributions till the release of openHAB 2.0 at the end of January.

Everyone who's reading this and willing to help: That's amazing, Thank you! Please let me know in which area and how much you think you will be able to help out. Of course you can also point out things that need some attention. It would be great to have more documentation at the moment openHAB 2 is announced to the public. Together we can do it ;)

Here are a few candidates I want to contact in the community forum:

* https://community.openhab.org/t/openhab2-deinstalls-itself-step-by-step/18625/5
* https://community.openhab.org/t/frequently-asked-questions-faqs/17727/6
* https://community.openhab.org/t/first-time-setup-questions-oh2/19465/15
* https://community.openhab.org/t/astro-binding-issue/2011/74
* https://community.openhab.org/t/continued-documentation-discussion/20116

**Comment by ThomDietrich** [comment]
@kaikreuzer I'm finished sorting out, adding and labeling issues.

**Comment by kaikreuzer** [comment]
I guess this can be closed...
