### ISSUE TITLE
 Starters guides related to openHAB 2 

### ISSUE THREAD

**Issue by svilenvul** [openhab/openhab-docs#18]
Migrated from: https://community.openhab.org/t/starters-guides-not-directly-related-to-openhab-2/11348/1

svilenvul wrote:
> In the company, that I work for (MusalaSoft), I have prepared some basic guides in form of wiki pages about OSGi, Equinox, p2 and Tycho for newcomers, that are going to work with Eclipse SmartHome and openHAB in order to help them with the first steps.

>We would like to share them with the open source community. But I could find the best place, as they are not directly related to openHAB.

>I will try to give a short overview, what we have:
- OSGi introduction page
- overview of OSGi Declarative Service specification
- OSGi coding tasks
- Tycho and dependency resolution process
- what is p2, Installable Units, update-site
- info about some basic Equinox commands and core bundles

>The articles contain a lot of links to external resources.
>@kaikreuzer, please advise us, how we can proceed further.

kaikreuzer wrote:
> All the topics you suggest are relevant for developers and not that much for users, right?
So in general, I think the Developer Guide is a good place for this - it anyhow is currently still pretty empty :wink:

>We could introduce a new main menu entry (something like "Prerequisites") with entries for OSGi, Tycho, p2 etc. Feel free to suggest a suitable menu structure, but I definitely do not mind to have such things also part of the documentation (although not directly related to openHAB).

>Cheers,
Kai

Feel free to join the discussion.

**Comment by kaikreuzer** [comment]
Contributed through #45, #66 and #76 - thanks!

**Comment by kaikreuzer** [comment]
(I closed this issue, but further PRs about OSGi/Tycho related topics are of course still welcome!)
