### ISSUE TITLE
Windows: Update the whole article

### ISSUE THREAD

**Issue by FrederikNT** [openhab/openhab-docs#180]
Missing description how to update to a new nightly build on a windows based system.

At a minimum a list of folders,files which needs to get replaced or which one don't would be really helpfull. In a future state a update scipt would be great :)

NoTechi

**Comment by ThomDietrich** [comment]
Hey @FrederikNT thanks for your input.

If you feel able to, help by you would be great. You could simply post paragraphs of text here in the comments.

**Comment by ThomDietrich** [comment]
I've renamed this ticket to address the need for a complete update of the article. This is mostly a writing task for someone running openHAB on Windows I believe/hope.

Have a look at the linux article to get some inspiration :)

Possible content:
* Meeting the prerequisites
* Installation
* Upgrade
* Backup
* Differences and restrictions compared to the more common Linux setup (?)
* ...

**Comment by Confectrician** [comment]
Could be closed in my opinion.
The main reasons for this issue should be adressed by one of the last windows.md commits.
