### ISSUE TITLE
Migration Tutorial: Clarify the Necessary Changes

### ISSUE THREAD

**Issue by rkoshak** [openhab/openhab-docs#183]
See the discussion [here](https://community.openhab.org/t/rules-problem-read-by-the-system-at-all/19759/12).

Bullet points instead of paragraphs and eliminate unnecessary information. For example, it doesn't matter that the org.openhab classes have moved to org.eclipse.smarthome because you don't have to import those classes at all any longer.

**Comment by watou** [comment]
Thanks very much, Rich, for considering my comments.

**Comment by ThomDietrich** [comment]
@rkoshak will you be able to attend to this issue?

**Comment by rkoshak** [comment]
Yes but it will probably be a week or so. I'm about to be on travel and I'm still short on time at home. I'll try to get it in earlier but can't promise anything right now.

**Comment by kaikreuzer** [comment]
@rkoshak Note that openHAB 2 is going to be the official successor of openHAB 1 on next Monday - so there will be a huge number of readers of this migration tutorial. It would be great to address at least the most important parts of it before that!

**Comment by Confectrician** [comment]
Hey @rkoshak,

I am browsing through some older issues for cleanign up the repo a bit.
Can we close this issue or is it still under progress?
