### ISSUE TITLE
Dead hyperlink in sitemaps.html

### ISSUE THREAD

**Issue by dilyanpalauzov** [openhab/openhab-docs#1838]
https://www.openhab.org/docs/ui/sitemaps.html#icons contains:

> openHAB allows a set of icons to be assigned to the different states of an Item and therefore to be presented in a Sitemap. Please refer to the documentation on “Item configuration” (https://www.openhab.org/docs/ui/items.html) for details.

https://www.openhab.org/docs/ui/items.html does not exist

**Comment by rkoshak** [comment]
This is already fixed in latest.

**Comment by Confectrician** [comment]
This is a pretty simple fix. I have issued a PR directly.

Please note that it may take some time to appear, after merging/closing here.
The stable version website is not build just in time.

**Comment by lolodomo** [comment]
Can be closed?
