### ISSUE TITLE
Rules: more references for Xtend

### ISSUE THREAD

**Issue by ThomDietrich** [openhab/openhab-docs#184]
Example: http://jnario.org/org/jnario/jnario/documentation/20FactsAboutXtendSpec.html

**Comment by rkoshak** [comment]
Does it make sense to point to forum postings?

Is this in addition to or in place of the discussion we had about adding a Rules DSL section to the FAQ?

**Comment by ThomDietrich** [comment]
The link was more of a first reminder.
The idea here is to give more professional help for programmers. Thinks *like* the above could be helpful.
