### ISSUE TITLE
Add Section Heading: Add-ons - Bindings - Non-Native 2.0 Bindings

### ISSUE THREAD

**Issue by fringefilmsoz** [openhab/openhab-docs#188]
Add section for 2.0 Bindings not included in the Paper UI installation configuration. Suggest below the Native Bindings section.

Only entry I'm aware of is:

[MySensors](https://github.com/tobof/openhab2-addons/wiki/Installation)  This Binding integrates with the DIY Arduino based [MySensors](http://www.mysensors.org) repository.

**Comment by ThomDietrich** [comment]
Please enlighten me why this binding is not included.

**Comment by fringefilmsoz** [comment]
Sorry @ThomDietrich I'm really not sure. MySensors is a major DIY sensors platform.

@tobof the author of the binding would be the person to answer. I'll hit up the MySensors forum and ask Tim to reply.

**Comment by kaikreuzer** [comment]
> Please enlighten me why this binding is not included.

A very simple reason: It is not yet part of openHAB, the PR is still in the review queue: https://github.com/openhab/openhab2-addons/pull/1243

Once merged it will be listed.

**Comment by Gelisob** [comment]
came back to give openhab another try since I saw the release video. Went through all the installation etc. Found out that MySensors still are not getting love and are not in the addons list, sigh.. ohwell, maybe back in the future then. Could we get an update when there's change in this?
