### ISSUE TITLE
Specify to not have a keyboard plugged in during setup

### ISSUE THREAD

**Issue by TangoOversway** [openhab/openhab-docs#1880]
On the [OpenHABian setup page](https://www.openhab.org/docs/installation/openhabian.html) a keyboard and monitor and headless use is mentioned 3 times:

1. In **Features**, while listing features, one item states: `Hassle-free setup without a display or keyboard, connected via Ethernet or Wi-Fi`
2.  In **Raspberry Pi prepackaged SD card image** it states: `openHABian is designed as a headless system, you will not need a display or a keyboard.`
3. In **Where is the graphical user interface?** (under **Did my Installation succeed? What to do in case of a problem?**), it states: `An RPi is not (well, not necessarily) to be used with a keyboard and display.`

The last one is the strongest wording, but even then, the "not" (for use of a keyboard) is amended with "not necessarily." And now days there is the Pi 400 and Raspbian itself comes with a GUI, so we can conclude that now Pis are often used on a desktop with a keyboard and monitor (and often a mouse). I use Pis in my workshop to control devices and they have either touchscreen interfaces or a small monitor and an accompanying mouse (and maybe a keyboard, depending on the device).

However, the openHab setup does not work with a keyboard plugged in. I found this out through experience. While it might be a good idea to suggest that the setup be keyboard agnostic (as opposed to anti-keyboard), the wording in these three places basically says and implies "keyboard and monitor are optional." Many people prefer to have a keyboard and monitor attached to systems during setup.

As long as oH will detect a keyboard and behave differently if one is attached, and that will prevent the install from working properly, when the keyboard and ability to run headless is mentioned, extra wording to clarify that that a keyboard should not be attached needs to be included.

(Note: I use low price keyboard/mouse combinations that connect wirelessly to a USB dongle and my experience is that a lot of software doesn't detect a keyboard if the keyboard is turned off, but openHab had issues and detected the keyboard with the USB dongle plugged in and the keyboard turned off.)

**Comment by Confectrician** [comment]
@mstormi do you want to transfer this issue to the openhabian repository?

**Comment by Confectrician** [comment]
Transferred to: https://github.com/openhab/openhabian/issues/1742

**Comment by mstormi** [comment]
> And now days there is the Pi 400 and Raspbian itself comes with a GUI, so we can conclude that now Pis are often used on a desktop with a keyboard and monitor (and often a mouse).

Err - no. "We" (as in "yourself plus all developers") cannot. Your GUI use case definitively only applies to few people. It isn't representative.

Well, thing with the wording you quote is, it still *should* work with a kbd plugged in but under some (unknown, not always) conditions it does not. Problem with that is that's something beyond our control and even sight as it happens inside Raspi OS.
We don't know what they changed or will change about it and when.
I consider the current wording to be correct and in line with that current situation.

> As long as oH will detect a keyboard and behave differently if one is attached, and that will prevent the install from working properly, when the keyboard and ability to run headless is mentioned, extra wording to clarify that that a keyboard should not be attached needs to be included.

Nope. Additional, very explicit wording *is* part of the current docs:
https://www.openhab.org/docs/installation/openhabian.html#raspberry-pi-prepackaged-sd-card-image

> On the [OpenHABian setup page](https://www.openhab.org/docs/installation/openhabian.html) a keyboard and monitor and headless use is mentioned 3 times:

Nope. You should be reading the full docs.


PS: @Confectrician did you intentionally close this issue after transferring? Just asking, given my response there's no need to reopen

**Comment by Confectrician** [comment]
I closed the issue on intention yes.
No automation or sth like that.

If a regular GitHub transfer would have worked, the issue wouldn't be availble her either.
Therefore i like to add a final status, so that further discussion may take place in the right place.
