### ISSUE TITLE
Establish fixed term placeholders for the openHAB folders

### ISSUE THREAD

**Issue by ThomDietrich** [openhab/openhab-docs#189]
Quoting https://community.openhab.org/t/help-im-ready-to-give-up/20006/39

Having one OS specific doc page that defines variables that are then used in the doc is another way:
For example:
debian/apt: `$CONFIG = /etc/openhab2/`
RH: `$CONFIG = /etc/somewhere/openhab2/` (example only)
non-pkg install: `$CONFIG = /opt/openhab2/conf/` (replace /opt/openhab2 with you install folder)
windows `$CONFIG = c:\programfiles\openhab2\conf` (example only)

and the in the doc it could say "edit `$CONFIG/sitemaps/_default.sitemap`"
instead of saying "edit your default sitemap".

----

This could nicely be integrated into http://docs.openhab.org/installation/linux.html#file-locations and should then be used in the community forum.

**Comment by kaikreuzer** [comment]
Definitely makes sense to come up with such placeholders.
We actually even have them already technically in place, see [here](https://github.com/openhab/openhab-distro/blob/master/distributions/openhab/src/main/resources/bin/oh2_dir_layout#L6-L10).

Having the `OPENHAB_` prefix might be a bit annoying to always type in the docs & discussions, though - but it would definitely be the correct way of referencing, wdyt?

**Comment by ThomDietrich** [comment]
I would second starting off with these. We just need to agree on one style.

An examples with all kinds of variations:

* `$OPENHAB_CONF/items/test.items`
* `$CONF/items/test.items`
* `$conf/items/test.items`
* `<conf>/items/test.items`
* `<openhab_conf>/items/test.items`
* `<CONF>/items/test.items`
* `<OPENHAB_CONF>/items/test.items`

Attention: angle brackets are interpreted as html tags outside `code fences`.
The dollar sign notation would actually be usable if the underlying system (e.g. openHABian) would be configured accordingly. That's a big plus.

**Comment by kaikreuzer** [comment]
So you vote for `$OPENHAB_CONF/items/test.items`?
Would be fine for me.

**Comment by ThomDietrich** [comment]
Yep :)
What do the others think?

**Comment by ThomDietrich** [comment]
One addition, we should also define a default placeholder for the openHAB hosts IP address.

**Comment by rtvb** [comment]
For the technically challenged users using forward slashes in the docs , but then replacing them with backslashes for windows needs to be addressed somewhere.

**Comment by ThomDietrich** [comment]
Good point @rtvb. I'm currently investing my free time into openHABian. After the last few changes I'll be back on docs! That's probably in about 2-3 weeks

**Comment by ThomDietrich** [comment]
For orientation: https://github.com/openhab/openhab-linuxpkg/blob/master/resources/etc/profile.d/openhab2.sh

**Comment by BClark09** [comment]
Yeah I like the sound of that! 

> Having the OPENHAB_ prefix might be a bit annoying to always type in the docs & discussions, though - but it would definitely be the correct way of referencing, wdyt?

> The dollar sign notation would actually be usable if the underlying system (e.g. openHABian) would be configured accordingly. That's a big plus.

A copy and paste job for our automatic users would probably be a good thing!

**Comment by Stefan300381** [comment]
Hi there,

wow, old issue. I am new to OpenHab and have just read the installation instructions (git clone of openhabian to linux arm device) followed by the tutorial. Unfortunately I fell into the same trap, meaning I couldn't find the config folder. Via google I found the answer: There is no folder named conf in my installation, but everything can be found under /etc/openhab2

So I highly suggest to change the tutorial and add a statement about "different" names and locations of config files. This is the tutorial I am speaking about:

http://docs.openhab.org/tutorials/beginner/sitemap.html

best regards

Stefan

**Comment by bgilmer77** [comment]
Hi @Stefan300381, I feel your pain.  I had exactly the same experience when I first tried to learn about openHAB.  I have created Pull Request #603 which I hope addresses your problem.  Let's hope people looking through the tutorial in the future will not have to share our frustrations...

**Comment by ThomDietrich** [comment]
@BClark09 it seems like there is no explicit placeholder for the "add-ons" folder. Can you confirm that? What do we make of it?

**Comment by bgilmer77** [comment]
+1

**Comment by BClark09** [comment]
Ah yes, the `addons` folder is located in `$OPENHAB_HOME/addons` but it would be no problem to add a `$OPENHAB_ADDONS` environment variable to linuxpkg?

**Comment by bgilmer77** [comment]
Ahh!  There’s the answer - $OPENHAB_HOME. FWIW, what other variables exist?  Where could I look to see for myself?

**Comment by bgilmer77** [comment]
No opinion on whether we need an ADDONS variable.

**Comment by BClark09** [comment]
The variables are used (and set if not defined in) in `https://github.com/openhab/openhab-distro/blob/master/distributions/openhab/src/main/resources/bin/oh2_dir_layout`

In linuxpkg installs, the easiest way to see the list is by using `openhab-cli info`, which it gets from `/etc/profile.d/openhab2.sh`

```
Directories: Folder Name      | Path                        | User:Group
             -----------      | ----                        | ----------
             OPENHAB_HOME     | /usr/share/openhab2         | openhab:openhab
             OPENHAB_RUNTIME  | /usr/share/openhab2/runtime | openhab:openhab
             OPENHAB_USERDATA | /var/lib/openhab2           | openhab:openhab
             OPENHAB_CONF     | /etc/openhab2               | openhab:openhab
             OPENHAB_LOGDIR   | /var/log/openhab2           | openhab:openhab
             OPENHAB_BACKUPS  | /home/pi/backup             | root:root
```

**Comment by ThomDietrich** [comment]
@BClark09 `$OPENHAB_HOME/addons` is technically correct. The intriguing question is... is that better than yet another placeholder? Pretty unsure about it. We also reference the items folder as `$OPENHAB_CONF/items` and not with its own placeholder. Wdyt?

**Comment by bgilmer77** [comment]
I would say we do not need another placeholder.  I was just missing the pointer to OPENHAB_HOME.  Others?

**Comment by BClark09** [comment]
Yep, `$OPENHAB_HOME/addons` is a good reference to have. For me, having it's own placeholder implies that we can move it somewhere else, and this is not the case. 

Sidenote: It's not the case for `$OPENHAB_RUNTIME` either, but this environment variable is used in Karaf so it should be referenced at least in `cli info`. It'd be my preference for the docs to reference `$OPENHAB_RUNTIME` as `$OPENHAB_HOME/runtime` for this reason.

**Comment by ThomDietrich** [comment]
> this is not the case

Convinced me.

> It'd be my preference for the docs to reference $OPENHAB_RUNTIME as $OPENHAB_HOME/runtime for this reason.

Sounds good. Could you (to summarize this issue) give a final list of all placeholders? Locations, and others like hostname or port

**Comment by BClark09** [comment]
Sure, for the docs I would use:

<table>
    <tr>
        <th>Placeholder</th>
        <th>Example on UNIX/MacOS</th>
        <th>Example on Windows</th>
        <th>Apt/Yum Packages</th>
    </tr>
    <tr>
        <td>$OPENHAB_HOME</td>
        <td>/opt/openhab</td>
        <td>C:\\openhab</td>
        <td>/usr/share/openhab2</td>
    </tr>
    <tr>
        <td>$OPENHAB_USERDATA</td>
        <td>/opt/openhab/userdata</td>
        <td>C:\\openhab\userdata</td>
        <td>/var/lib/openhab2</td>
    </tr>
    <tr>
        <td>$OPENHAB_CONF</td>
        <td>/opt/openhab/conf</td>
        <td>C:\\openhab\conf</td>
        <td>/etc/openhab2</td>
    </tr>
    <tr>
        <td>$OPENHAB_LOGDIR</td>
        <td>/opt/openhab/userdata/logs</td>
        <td>C:\\openhab\userdata\logs</td>
        <td>/var/log/openhab2</td>
    </tr>
    <tr>
        <td>$OPENHAB_BACKUPS</td>
        <td>/opt/openhab/backups</td>
        <td>C:\\openhab\backups</td>
        <td>/var/lib/openhab2/backups</td>
    </tr>
    <tr>
        <td>$OPENHAB_HTTP_PORT</td>
        <td colspan="3" align="center">8080</td>
    </tr>
    <tr>
        <td>$OPENHAB_HTTPS_PORT</td>
        <td colspan="3" align="center">8443</td>
    </tr>
    <tr>
        <td>$OPENHAB_USER</td>
        <td colspan="3" align="center">openhab*</td>
    </tr>
    <tr>
        <td>$OPENHAB_GROUP</td>
        <td colspan="3" align="center">openhab*</td>
    </tr>
</table>
* not necessarily used in manual installations.

**Comment by Confectrician** [comment]
Should we add the general table somewhere in the docs too and close this issue afterwards?

**Comment by ermartens** [comment]
From a reader point of view it would be comfortable to follow 2 links:
first to a page named placeholders/filelocations, where he can choose his OS/Appliance:
# File Locations

| Operating System | 
| ------ | 
| Linux |
| Windows |
| Mac OS X |
| openHABian |
| Docker |
| Synology DiskStation |

The second link would take him to the relevant section on the existing page Installation/OSxyz/File Locations.

The list of placeholders should be available in the Developer Guide, possibly a new Section "Documentation" and it should also be placed in the generated skeletons. (/tools/archetype/binding/src/main/resources/archetype-resources/README.md)

**Comment by Confectrician** [comment]
Finalized in #1387
