### ISSUE TITLE
1.x Bindings note

### ISSUE THREAD

**Issue by ThomDietrich** [openhab/openhab-docs#190]
1.x Bindings are differently used than ESH/OH2 bindings. The main differences are
1. they do not know the concept of things and channels
2. items using them need to be set up in configuration files
3. binding configuration https://community.openhab.org/t/mqtt-openhab2-configuration/20283/2

These three rules plus whatever else is needed should be mentioned here: http://docs.openhab.org/addons/bindings.html#legacy-1x-bindings

From https://github.com/openhab/openhab-docs/issues/167:
> we should change [this](http://docs.openhab.org/addons/bindings.html#legacy-1x-bindings) title anyhow to just call it "1.x Bindings" and in [here](http://docs.openhab.org/addons/bindings.html#further-1x-bindings) we could add a new list of all legacy 1.x bindings.

**Comment by kaikreuzer** [comment]
@ThomDietrich Beware that you use the term "legacy binding" differently than it is done in the Paper UI (resp. the openhab-addons-legacy.kar).

There, it is defined as " 1.x bindings for which there is already a 2.x version available", i.e. not all 1.x bindings are referred to as legacy, but bindings for which there isn't any 2.x equivalent yet, are considered as regular add-ons.

**Comment by ThomDietrich** [comment]
Oh, I did not know that 😅  thanks!

**Comment by ThomDietrich** [comment]
Example case: https://community.openhab.org/t/itead-switches-and-sockets-cheap-esp8266-wifi-mqtt-hardware/15024/49

**Comment by sihui62** [comment]
https://community.openhab.org/t/itead-switches-and-sockets-cheap-esp8266-wifi-mqtt-hardware/15024/53?u=sihui

**Comment by sihui62** [comment]
PR [#247](https://github.com/openhab/openhab-docs/pull/247) created

**Comment by ThomDietrich** [comment]
Might still be needed: #275
