### ISSUE TITLE
Tutorial: Transfer Getting Started Tutorial from community forum

### ISSUE THREAD

**Issue by ThomDietrich** [openhab/openhab-docs#191]
https://community.openhab.org/t/setting-up-openhab2-from-scratch/20080

This tutorial could be the replacement for both the "Demo Setup" and the "Beginner" tutorial.

**Comment by ThomDietrich** [comment]
Add a list of further tutorials and examples to give the user perspective https://github.com/openhab/openhab-docs/issues/205.
Result could be similar to https://wiki.python.org/moin/BeginnersGuide/Programmers

**Comment by DocFraggle** [comment]
Hi Thomas,

https://github.com/openhab/openhab-docs/pull/207

Regards, Christian
