### ISSUE TITLE
openHABian: Corrections

### ISSUE THREAD

**Issue by ThomDietrich** [openhab/openhab-docs#192]
This will be a fun week.

**Comment by ThomDietrich** [comment]
Manual installation tested on RPi0: https://community.openhab.org/t/oh-on-the-raspberry-pi-zero/10997/15

**Comment by ThomDietrich** [comment]
This issue has served its purpose :)

**Comment by Confectrician** [comment]
>This issue has served its purpose :)

Should we close it then?

**Comment by ThomDietrich** [comment]
Weird. Yes :)
