### ISSUE TITLE
Configuration: main overview article

### ISSUE THREAD

**Issue by ThomDietrich** [openhab/openhab-docs#193]
This article needs to be filled with information before 2.0 GA. Would otherwise be a bit embarrassing to have an empty article in this prominent spot :)

The article should shortly mention the technical background of configuration (jsondb vs. files), then explain that there are multiple ways to set up bindings, things, items, ... The article needs to clear out the misconception, that Paper UI can be used in the whole process.

I would like to see something like a possibility matrix, as it is quite popular, e.g.:
https://en.wikipedia.org/wiki/Comparison_of_web_frameworks#PHP_2

|   | files | Paper UI | HABmin | ... |
|---|---|---|---|---|
| Define items | 🆗 | 🆗 | 🆗 |   |
| Define sitemaps | 🆗 |   |   |
| Define rules | 🆗 | 🆗 (experimental) |   |
| ... |  |   |   |

Many discussions in the forum could be a starting point for what to write here, e.g. https://community.openhab.org/t/recommended-way-to-backup-restore-oh2-configurations-and-things/7193/44

**Comment by xylo** [comment]
I think that's a good idea.

You can add the following:

|                               | files | PaperUI | HABmin |
|-------------------------------|-------|---------|--------|
| Edit z-wave device properties |       | buggy   | works  |
| Stable regarding upgrades     | yes   | no      | ?      |

**Comment by ThomDietrich** [comment]
@xylo I've uploaded a first version of the article. Please have a look. #253

**Comment by xylo** [comment]
Looks good. :)

**Comment by ThomDietrich** [comment]
No it does not 😅  The article is just a first draft and the details in the table are not completely correct.

**Comment by xylo** [comment]
As a first draft, it looks pretty good.  Sorry, that I cannot contribute much, but I used only the PaperUI, habpanel, and a bit of HABmin so far.  And my first issue is already included.  Since yesterday I know that my second issue regarding upgrade stability is no longer relevant.  Upgrades can keep the local database now.

**Comment by ThomDietrich** [comment]
Ah yes, the second issue. I didn't include it because it's not really a capability or feature but a question of the underlying technology. I was meaning to answer you on that question here. Nice you got your answer.
Thanks for your "like" ;)
