### ISSUE TITLE
Documentation for UI add-ons is missing on the website

### ISSUE THREAD

**Issue by domoticaDude** [openhab/openhab-docs#1935]
Link for documentation points too https://www.openhab.org/addons/ui/cometvisu in http://openhab:8080/settings/addons/ui-cometvisu

**Comment by Confectrician** [comment]
Habot:

A page exists in another path: https://www.openhab.org/docs/ui/habot/
We could add a redirect in the website repository.

Basicui

Could also be redirected.
The sitemaps article should be fin, since it is completely dependent on this.

WDYT?

**Comment by Confectrician** [comment]
CometVisu:

I have noe idea which location would be good here.
We have nothing really useful in our docs.

Maybe we could add a simple page wioth some explanation and link to external sources.
Any cometvisu user available who can help us with some research and informations about it?

**Comment by kaikreuzer** [comment]
> Any cometvisu user available who can help us with some research and informations about it?

I'd say that @peuter as the maintainer of that UI should be the perfect match. 😄

**Comment by peuter** [comment]
You have a match ;-)

Where do I have to add something to get that a page https://www.openhab.org/docs/ui/cometvisu/? I don't see the existing "ui/habot" and "ui/habpanel" in this repository.

Currently the only specific documentation is the readme the in the sources of the cometvisu-binding but that is more developer centric and not really useful here.

I would like to create a simple description of the cometvisu with some deep links into our own documention at https://www.cometvisu.org/CometVisu/en/latest/manual/.

You just have to tell me where I can make a pull request for that page (and be a little patient until I find enough time to do so)

**Comment by wborn** [comment]
Maybe it is also possible to put the docs for optional UI add-ons in the openhab-webui repo (similar to the docs for openhab-addons)? Then you can update these docs in the same PRs that changes or adds functionalitiy. :slightly_smiling_face: 

It may also be confusing to users that these optional UI add-ons are not listed as a category in the side bar on the left on https://www.openhab.org/addons/ 

Neither can you find these optional add-ons:

![ui-addons](https://user-images.githubusercontent.com/12213581/205255855-c58e904a-82ee-415a-bb4f-347961ca673b.png)

**Comment by Confectrician** [comment]
Hm that sounds fair enough and is in line with my general plans on mid term.
I made some thoughts about this too yesterday and i am not happy with missing the entire ui addons in that area.

If we integrate this as a prper addon category, we should also clean up the ui section of the docs a bit and move the sites or remove duplicates.

@peuter 

I think it doesn't make much sense to start somethign without kowing where to place it.
If you want to start anyways the addon repository should be a good place on the first step.
You may have a look at the openhab-addons repository and check how it is done over there.

General documentation is done in the readme file of the bundle.
Images are uploaded in a subfolder named `doc`.

So in your case you would have to rename the readme to something based on its purpose, like development.md

**Comment by wborn** [comment]
It does seem to be already available when reading documentation in Main UI itself when you click "more" at the top of the page.

This content gets loaded from: https://github.com/openhab/openhab-docs/tree/final/_addons_uis


![Screenshot from 2022-12-15 22-46-29](https://user-images.githubusercontent.com/12213581/207974178-3634e1f5-7162-4d6b-8a7e-e6ff776f2855.png)

**Comment by wborn** [comment]
> It does seem to be already available when reading documentation in Main UI itself when you click "more" at the top of the page.

The intro will show immediately after https://github.com/openhab/openhab-webui/pull/1587 is merged. That will also make it more likely that users click the "more" button to continue reading.

**Comment by Confectrician** [comment]
That's a improvement for sure already.
Anyway we should also do the other discussed improvements and bring this up in the addons category.

**Comment by wborn** [comment]
> Anyway we should also do the other discussed improvements and bring this up in the addons category.

There's now https://github.com/openhab/website/pull/377 which adds docs for them.

**Comment by Confectrician** [comment]
Thanks for your efforts @wborn!

**Comment by wborn** [comment]
Now that UI add-ons docs are available some documentation could be further deduplicated:

E.g. replace:

* https://www.openhab.org/docs/ui/habot/#habot  
  with  
  https://www.openhab.org/addons/ui/habot/

* https://www.openhab.org/docs/configuration/habpanel.html  
  with  
  https://www.openhab.org/addons/ui/habpanel/doc/habpanel.html (needs some fixing to get the images loaded)
