### ISSUE TITLE
Paper UI: Describe functionality

### ISSUE THREAD

**Issue by ThomDietrich** [openhab/openhab-docs#198]
A short list of functions would be enough. Do not write a fully blown user manual that will be outdated in two months.

**Comment by kaikreuzer** [comment]
Ideally should be contributed to https://github.com/eclipse/smarthome/blob/master/extensions/ui/org.eclipse.smarthome.ui.paper/README.md

**Comment by Confectrician** [comment]
Paper UI will be gone with openHAB 3.
Closing this issue therefore.
