### ISSUE TITLE
Help: How to post a problem, How to contribute a solution

### ISSUE THREAD

**Issue by ThomDietrich** [openhab/openhab-docs#199]

**Comment by rkoshak** [comment]
In what context? How to post a problem to the forum and how to provide a solution to a problem?

If so should it be written up in the FAQ first?

**Comment by ThomDietrich** [comment]
Some of these tickets were thought more for myself than others.
This was meant to address the "Help" area here: http://docs.openhab.org/appendix/help.html

There I would like to see a short motivation to contact the forum. Not critical atm. This is btw also related to forum templates

**Comment by Confectrician** [comment]
Bringing this one up again.

Maybe we could provide a genereated url structure for the community faq thread here?

**Comment by Confectrician** [comment]
https://community.openhab.org/t/howto-make-changes-minor-corrections-to-the-documentation/110817/3?u=confectrician

**Comment by Confectrician** [comment]
We have several threads and a whole documentation are in the community forum to cover this meanwhile.
