### ISSUE TITLE
Apps: Decorate the iPhone article

### ISSUE THREAD

**Issue by ThomDietrich** [openhab/openhab-docs#200]
Update: Android part is finished. iPhone still needed

http://docs.openhab.org/addons/uis/apps/android.html
http://docs.openhab.org/addons/uis/apps/ios.html

Please contribute some content for these articles. A feature list, two screenshots, whatever you think is needed.

@digitaldan are you free to do that?

**Comment by DocFraggle** [comment]
Tested with Firefox and Chrome

**Comment by dome2048** [comment]
I'm very much a novice at GitHub, so please forgive the question, but am I correct that no one is working on this? If so, I'll figure out how to do a pull request to get this done.

**Comment by ThomDietrich** [comment]
Hey Dome :wave:
Correct, great to here! Your help is very much appreciated. Regarding details please contact @digitaldan and check out the iOS app repo:

https://github.com/openhab/openhab.ios
