### ISSUE TITLE
QNAP: Add a few details

### ISSUE THREAD

**Issue by ThomDietrich** [openhab/openhab-docs#201]
https://github.com/openhab/openhab-docs/pull/148#issuecomment-265747892

@thopiekar would you be able to add details to this sad looking article: http://docs.openhab.org/installation/qnap.html

**Comment by thopiekar** [comment]
Sorry for the late reply @ThomDietrich but I'm currently very busy due to my internship in the Netherlands.

It looks like we are using markup as language for our docs, isn't it? Am I allowed to move the pictures I use in my QNAP repo into here?

Regards

**Comment by ThomDietrich** [comment]
Yes sure. If you are unsure about pictures and formatting, give me some paragraphs and image links and I'll add the formatting for you (if this better suits your busyness ;) )
