### ISSUE TITLE
JsonDB storage description

### ISSUE THREAD

**Issue by ThomDietrich** [openhab/openhab-docs#202]
http://docs.openhab.org/administration/jsondb.html

A short introduction into jsondb would be enough. The process of how a user could (if ever needed) edit the db file manually would be good too. Most info can probably be taken from the community forum thread https://community.openhab.org/t/replacement-of-mapdb-by-jsondb/17498

@cdjackson would you take this on?

**Comment by AngelosF** [comment]
@ThomDietrich: 
Chris wrote a more detailed explanation of the JsonDB here: https://github.com/openhab/openhab-docs/pull/282

I think that we should drop my PR (https://github.com/openhab/openhab-docs/pull/281) and use his ([282](https://github.com/openhab/openhab-docs/pull/282))

**Comment by ThomDietrich** [comment]
What a coincidence :astonished: Why did you both decide to write something **in the same hour**? Hahaha what a shame :(

I don't think we should drop your content! You have many great things in there, like a good headlines structure, screenshots and examples. It would be great to have both!

My suggestion would be, that we first merge @cdjackson's article. After that you can step in and "sneak" in all the little details of your article. Wdyt?

**Comment by cdjackson** [comment]
I’m not sure it was quite “the same hour” as I committed it during lunch, but as I was typing directly into github (since I was at work) I did the PR when I got home, but certainly the same day :)

For me is fine anyway - sorry it was a bit slow coming from your original request - I had 2.5 weeks in India and just returned last week...

**Comment by ThomDietrich** [comment]
No problem at all. We are all here for the fun of working for others for free :sweat_smile: 

I was in India just two month ago. Hope you enjoyed it ;)

**Comment by cdjackson** [comment]
:)

Yes - loved India - did a trip from Delhi through Rajasthan - really great place :)

**Comment by chmorgan** [comment]
Should this one be closed now that #282 was merged? I'm only asking because I'm looking to get into openhab hacking and stumbled upon this one and if it is closed its making it more difficult to identify issues that are still open.

**Comment by AngelosF** [comment]
I will update this PR to introduce some small enhancements to the jsonDB docs entry (on top of what 282 introduced)
I will do this soon :)
Welcome to openHAB hacking ! 👍
