### ISSUE TITLE
Initial Setup: How to reset

### ISSUE THREAD

**Issue by ThomDietrich** [openhab/openhab-docs#204]
https://community.openhab.org/t/a-single-distro-from-now-on/19903/40

>Actually, the package selection does nothing else than creating the file `userdata/etc/org.openhab.addons.cfg`. So if you delete this file and set a different package in `conf/services/addons.cfg` it will create a new file with the addons specified of that package. But there really isn't a need to switch package, because you can simply change the installed addons yourself at any time and for your personal needs.

**Comment by halfbaked** [comment]
@ThomDietrich PR here https://github.com/openhab/openhab-docs/pull/371

**Comment by Confectrician** [comment]
There is only one package (standard) left in openHAB 3
