### ISSUE TITLE
Tutorials: Give a list of Tutorials and Examples

### ISSUE THREAD

**Issue by ThomDietrich** [openhab/openhab-docs#205]
Right at the starting page of the Tutorials section or in one subcategory: http://docs.openhab.org/tutorials/

Incomplete Examples List:

* https://community.openhab.org/t/about-the-tutorials-examples-category/15581

* https://community.openhab.org/c/setup-configuration-and-use/tutorials-examples

* [Example 1](https://community.openhab.org/t/washing-machine-state-machine/15587/1), [Example 2](https://community.openhab.org/t/power-consumption-of-lights-and-more/15642/1), [Example 3](https://community.openhab.org/t/speedtest-cli-integration/7611/1), [Example 4](https://community.openhab.org/t/influxdb-grafana-persistence-and-graphing/13761), ... we should select more examples from the forum

* german blogs:
  * http://onesmarthome.de/category/openhab-2
  * https://klenzel.de/kategorie/technik/hausautomatisierung/openhab (OH1!)
  * http://www.marcsblog.de/tag/openhab (OH1!)

* english blogs:
  * http://hackaday.com/tag/openhab - http://hackaday.com/tag/home-automation
  * http://www.makeuseof.com/tag/getting-started-openhab-home-automation-raspberry-pi (OH1!)
  * http://www.makeuseof.com/tag/openhab-beginners-guide-part-2-zwave-mqtt-rules-charting (OH1!)

**Comment by kaikreuzer** [comment]
I would limit the links to official openHAB resources only (i.e. mainly content on the forum).

The other references are better placed in an article at an independent place like Wikipedia :-)

**Comment by ThomDietrich** [comment]
This was just a first approach to find as **much** as possible. Sadly there are not as many good external ressources for openHAB 2 yet. onesmarthome is quite nice.

We could remove all of them, yes.
However I believe they will serve a good cause. They broaden the selection for users and do not hide other valuable sources (which can become more and more over time). Additionally I think it's encouraging to use a product/software if a certain acceptance is presented. External articles and blogs dedicated to openHAB will show that. I had this page in mind as an example: https://wiki.python.org/moin/BeginnersGuide/NonProgrammers

You decide.

**Comment by kaikreuzer** [comment]
> You decide.

Maybe at a later point, not now. And maybe at a different place, let's see.

**Comment by ThomDietrich** [comment]
@kaikreuzer this goes hand in hand with the restructuring of the forum. A topic we didn't touch yet :zipper_mouth_face:

**Comment by kaikreuzer** [comment]
@ThomDietrich We forgot to remove the demo tutorial before the launch - I think this is pretty confusing now and should be removed asap.
As we would be left with only 2 options on that page, would you want to rather replace the demo tutorial link with a link to the examples & tutorials on the forum?

**Comment by ThomDietrich** [comment]
I didn't even have the time to worry about that ^^ yes you are right.
I do not really have much time right now. Let me come up with something quick...

**Comment by ThomDietrich** [comment]
Going for the two options page. Just looks better actually... stay tuned.
