### ISSUE TITLE
Add to Linux Manual/Windows/Mac/Docker installation instructions to create environment variables

### ISSUE THREAD

**Issue by rkoshak** [openhab/openhab-docs#2074]
Given the assumption made https://github.com/openhab/openhab-core/pull/3591 that most installs of OH will have $OPENHAB_USERDATA set it seems reasonable to add to the installation instructions where that is not the case how to set that environment variable. $OPENHAB_CONF and $OPENHAB_LOGS should be added too.

**Comment by kaikreuzer** [comment]
Asking the user to do it manually is probably not the right way.
Maybe my comment was a bit off - my point was mainly that these variables are all set when openHAB is started (in the various scripts) and I thought that they are also always automatically set for every openHABian installation.

With regards to https://github.com/openhab/openhab-core/pull/3591, I plan to do a second PR, which adds a call to the upgradetool in the update script(s). By this, the variables are automatically used and there is no need for the user to define it.

**Comment by rkoshak** [comment]
My understanding is that the start script that set the variables only set it for the OH process, not globally for the user. Maybe I wasn't understanding but will the upgrade tool be able to set these environment variables on it's own or does it run inside OH? Because it's invoked from the command line I assumed that it ran standalone and the only environment variables available to it are the ones already set in the command line.

They are indeed set for every openHABian installation as well as for apt and yum installs and inside the Docker Container. However for Windows and Mac and manual Linux where the installation instructions are "unzip the file" there's nothing to set it for the user's shell.

Maybe instead of changing the installation instructions it makes more sense to add a comment to the upgrade tool that when invoking the tool manually for manual installs of OH the directory argument should be used or $OPENHAB_USERDATA defined?

**Comment by kaikreuzer** [comment]
@rkoshak Maybe https://github.com/openhab/openhab-distro/pull/1532 answers your questions. For all "manual" installations, where $OPENHAB_USERDATA is usually not set, the users are expected to do their openHAB updates through the existing update script. By calling the upgrade tool from within there, everybody should be served.
Ideally, openHABian should also be adapted to call the upgrade tool automatically (/cc @openhabian-maintainers).

**Comment by mstormi** [comment]
Err you got me left handed, hadn't heard about that tool so far.
What is it for, is it mandatory and when do you think openHABian should call it?

**Comment by rkoshak** [comment]
That sounds perfect. I did a spot check and calling the script appears in the Linux and Windows Installation instructions. I assume they are in all the rest where it matters.

Since openHABian uses apt and the apt upgrade calls the script automatically I'm not sure there's anything that needs to be done there. However, this script and the upgrade tool could be included into the restore feature of openHABian which theoretically should allow one to restore the configs from an earlier OH on to a newer OH version without first restoring the configs to the same version and only then upgrading.

**Comment by kaikreuzer** [comment]
> Since openHABian uses apt and the apt upgrade calls the script automatically 

Ah, right, then you can simply forget my comment from above again, @mstormi! 😇 

>  this script and the upgrade tool could be included into the restore feature of openHABian

I never tried this feature and I am not sure how it works - but from what you say, it indeed sounds to me as if the update script should be called after such a restore as well. So that might be a question for @mstormi then.

**Comment by mstormi** [comment]
> I never tried this feature and I am not sure how it works

It just runs `openhab-cli restore`.

So the question is merely *when* to (also) start the upgrade script.
We would not want that to happen on any regular use of restore, would we.

**Comment by rkoshak** [comment]
The way that the Docker images figure out if an upgrade is taking place is by keeping a copy of $OH_USERDATA/etc/version.properties somewhere else and checking that copy against the version in that file in the actual $OH_USERDATA/etc/version.properties. If they differ the container upgrade process is performed. 

I think right now that only involves saving a backup, clearing the cache, and replacing the contents of $OH_USERDATA/etc with the new files.

I'm guessing that a call to this upgrade script needs to be added to that now too. 

The Docker image can do this easily because there is an entrypoint script which runs before OH is started. 

I only list this as an example of how it's done, not a suggestion that this is how it should be done in openHABian.

> I don't know under which conditions we need to call it, is it anytime we have a v3 config and the binaries are v4 ?

I imagine it should run any time the version for the configs differ from the version of OH. One could make it so it only runs if the version of the configs is less than the version of OH. The tool only exists in OH 4 but I suspect it's going to be continuously updated as OH 4 grows as a very nice way to handle breaking changes between versions in a way that's transparent to the end users (unless they have file based configs).

> We would not want that to happen on any regular use of restore where someone just restores his config from backup, would we.

I've not looked too closely into the tool yet but I would hope it's idempotent. If there's nothing to change it changes nothing. So except for a few waisted cycles running the tool on configs that are already at the current version shouldn't matter. That needs verification though.

> And on the other hand, if there was a need to run it because someone restores a v3 or lower config on an OH4 system, this should also take place if one directly used openhab-cli.

That's a reasonable approach. Does the feature of openHABian that restores the backup you've placed in the boot partition during that first start use openhab-cli? I think it just calls the restore.sh script itself so I imagine it's that script that needs to be updated (the .bat file too?). That should hit *all* the distros except Docker (which already has a mechanism to handle this).

I think we've veered pretty far from this Issue though. Should I open a new one on openhab-distro and another one on openhab-docker to call the upgrade tool as part of the already existing upgrade process?

**Comment by rkoshak** [comment]
I think the original intent of the issue has long since become addressed so I'm going to close it.
