### ISSUE TITLE
Athentication and encryption addendum

### ISSUE THREAD

**Issue by lsiepel** [openhab/openhab-docs#211]
The page that describes the reverse proxy based on NGINX is very helpfull, but is missing one final piece. It doesn't describe how to skip basic authentication for clients on the local network the way OH1 did.

        location / {
                proxy_pass                            http://localhost:8080/;
                proxy_set_header Host                 $http_host;
                proxy_set_header X-Real-IP            $remote_addr;
                proxy_set_header X-Forwarded-For      $proxy_add_x_forwarded_for;
                proxy_set_header X-Forwarded-Proto    $scheme;

                **satisfy  any;
                allow 192.168.1.0/24;
                deny   all;**

                auth_basic                            "Username and Password Required";
                auth_basic_user_file                  /etc/nginx/.htpasswd;
        }

**Comment by BClark09** [comment]
Hi @lsiepel Good Spot! I've made appropriate changes in the above PR!
