### ISSUE TITLE
JDBC add-on documentation links not working

### ISSUE THREAD

**Issue by mherwege** [openhab/openhab-docs#2172]
This issue has been reported before, but has been closed (https://github.com/openhab/openhab-docs/issues/817). The issue still remains though.

The JDBC add-on consists of multiple add-ons. The add-on ID has the form:` jdbc-h2` where `h2` is an example of a specific database, there are multiple possibilities. Each of these versions is listed separately in the UI add-on store. When the UI creates the documentation link, it uses the `https://www.openhab.org/addons/persistence/` endpoint and adds `jdbc-h2` (the add-on ID) to it resulting in `https://www.openhab.org/addons/persistence/jdbc-h2/`. This link does not exist, it should redirect to `https://www.openhab.org/addons/persistence/jdbc/`.

I see two possible solutions to this:
1. Add redirects for each JDBC database on the documentation site. I don't know if that is easy to do.
2. Create specific logic for the JDBC persistence service in the UI code. I can do this, but I don't like exceptions like this poluting the code.

Would 1 be an option?

See also https://github.com/openhab/openhab-core/issues/3868#issuecomment-1848899824

**Comment by florian-h05** [comment]
1 is an option and I clearly prefer it over 2.

You can add redirects in the website repo:
https://github.com/openhab/website/blob/main/.vuepress/_redirects
