### ISSUE TITLE
Clarify and update the REST API documentation with regards to authentication

### ISSUE THREAD

**Issue by datMaffin** [openhab/openhab-docs#2202]
Hello,

I stumbled upon this part of documentation:

> Starting with version 3, openHAB supports password protection for sensible contents such as parts of the semantic model.

The reason why I think this needs to be updated/clarified, is that I do not see any way of having different authentication on **parts** of the semantic model (or items).

I already asked the person committing this documentation ( https://github.com/openhab/openhab-docs/pull/1395#discussion_r1443733312 ) and it is unclear as to whether this is correct.

As far as I understand (reading docs, and playing around with the software), the authentication of the REST API works in the following way:

- Sensitive stuff (Things, Channels, creating Items, Scripts) can only be changed by an "Admin" user. Therefore one needs authentication of any "Admin" user.
- Not sensitive stuff (reading changing Item state) are by default accessible without any authentication.
- If the "API Security -> Implicit User Role" is disabled, then authentication of "Admin" or "Users" user is needed.

I.e., Users will always have access to all the Items. This statement also seems consistent with various explanations on the forums:
- https://community.openhab.org/t/restricting-access-to-oh3-overview-and-pages-to-selected-users-other-than-visibleto/134874/5
- https://community.openhab.org/t/openhab-app-exposes-direct-access-to-items-for-any-user-security-risk/136962/2

On the REST API side, differentiation between different users is not possible. And the kind of access seems static for "Admin" and "Users" users.

The WebFrontend of OpenHAB seems to use this REST API to communicate with the server. And the kind of things **displayed** in the WebFrontend can be changed depending on the exact user "visibleTo". However, again, the underlying REST API does not.

Is this all correct?

I would also like to contribute a PR to update this part of the documentation.

---

_Other stuff I have been thinking about (don't care that much about that currently):_

About the "WebSocket" API:
- does the "WebSocket" API get used by the WebFrontend? 
  - And if not, is it possible to disable it?
- Does it really ALWAYS require authentication, or is it similarly divided like the REST API?
  - If it ALWAYS needs authentication, then only an Admin user will do, right?

Are there additional (other than REST API and WebSocket) interfaces active **by default** for people in the LAN to interact with the OpenHAB server?

**Comment by rkoshak** [comment]
Based on my understanding, yes what you've said is correct. 

> does the "WebSocket" API get used by the WebFrontend?

I think the intent is to use WebSocket in place of the SSE stream eventually. But I have not strictly followed that work and maybe misunderstand it's intent.

> Are there additional (other than REST API and WebSocket) interfaces active by default for people in the LAN to interact with the OpenHAB server?

There's the language server protocol. Individual add-ons sometimes open their own ports and have their own APIs.
