### ISSUE TITLE
 Internal dependency - lib folder

### ISSUE THREAD

**Issue by magx2** [openhab/openhab-docs#2205]
On page https://www.openhab.org/docs/developer/buildsystem.html#internal-dependency we can find this information:

> Internal dependency
> 
> In two cases libraries can be added to the /lib directory:

As I found [here](https://community.openhab.org/t/addon-with-lib-folder-openhab-3-0/107827) since version 3 `lib` folder is no longer supported. Is it correct?

**Comment by stefan-hoehn** [comment]
@J-N-K As you mentioned in the forum that this is not valid anymore, do you mind updating the page?
