### ISSUE TITLE
excessive list indentation in mainui sidebar help doc

### ISSUE THREAD

**Issue by jimtng** [openhab/openhab-docs#2243]
<img width="237" alt="image" src="https://github.com/openhab/openhab-docs/assets/2554958/72296a60-aded-4d04-90f3-37a846284305">

**Comment by stefan-hoehn** [comment]
What exactly is your point here?
cc: @florian-h05

**Comment by jimtng** [comment]
Sorry I thought it was obvious. We need to reduce the indentation so the text doesn't have to wrap so much. I just haven't figured out how to do it, so I posted it here hoping someone could figure it out.

**Comment by stefan-hoehn** [comment]
Ah, you mean the CSS-Style here? Yep, makes sense to me. 
@florian-h05 As this is taken from the openhab-docs, do we apply our own style in the UI or does it use the CSS from the openhab-docs? If it is the latter we would have the challenge to find a style that would work for both.

**Comment by jimtng** [comment]
Good point! I think this should just be adjusted in webui, not in the openhab-docs. It's only so narrow in the developer bar / help bar.

**Comment by florian-h05** [comment]
This has to be done in the UI, see context.vue.

**Comment by jimtng** [comment]
I couldn't figure out the CSS to do it.

**Comment by florian-h05** [comment]
I have created a PR, see https://github.com/openhab/openhab-webui/pull/2423.
