### ISSUE TITLE
Update Demo tutorial

### ISSUE THREAD

**Issue by kaikreuzer** [openhab/openhab-docs#226]
The demo tutorial on http://docs.openhab.org/tutorials/demo.html is not matching the current distro anymore and thus would need to be updated.

@ThomDietrich Is this already planned some where? If not, I can try to take care of it.

**Comment by ThomDietrich** [comment]
I was hoping to make it redundant with @DocFraggles tutorial. Would rather include the list with further resources. 
(on the phone)

**Comment by kaikreuzer** [comment]
Ok, you refer to https://github.com/openhab/openhab-docs/issues/205, right?
Fine for me - although I think that the demo setup should be described somewhere as well. Maybe I do a short YouTube video for it and link it on http://docs.openhab.org/configuration/packages.html#demo-package-sample-setup.

**Comment by ThomDietrich** [comment]
That's an excellent idea!
