### ISSUE TITLE
Install Doc Correction

### ISSUE THREAD

**Issue by DrPepper124** [openhab/openhab-docs#229]
On Page 
http://docs.openhab.org/installation/linux.html#installation
Change
sudo apt-get update && sudo apt-get install oracle-java8-jdk
To
sudo add-apt-repository ppa:openjdk-r/ppa
sudo apt-get update
sudo apt-get install openjdk-8-jre

**Comment by ThomDietrich** [comment]
Hello @DrPepper124,
I've just done the needed changes but went with another repository. Please have a look.

**Comment by Confectrician** [comment]
Is this still relevant?
I think we reworked many parts of the linux article meanwhile.
