### ISSUE TITLE
Website build failing?

### ISSUE THREAD

**Issue by jlaur** [openhab/openhab-docs#2319]
I'm currently waiting to see how openhab/openhab-addons#16889 will be [rendered](https://next.openhab.org/addons/bindings/energidataservice/#channels), but haven't seen an update for a few days.

I then noticed that this build has been failing for some time, I'm wondering if related?
https://ci.openhab.org/job/gather-external-docs/

**Comment by jlaur** [comment]
@Confectrician - FYI. I don't know who can fix this?

**Comment by jlaur** [comment]
@florian-h05 - do you think #2299 could be related somehow? I'm only asking because last successful build was 30.05.2024 05:44, and that PR was merged the next day.

**Comment by florian-h05** [comment]
In fact the website build in general was working, just the update external content job failed.
My fix was just merged, the next distro build should trigger the update external content job and then everything should be fine.
Let's keep this issue open until we are sure it is working again.

**Comment by jlaur** [comment]
Fixed by #2321.
