### ISSUE TITLE
openHAB Cloud Connector: enhancing the documentation

### ISSUE THREAD

**Issue by lolodomo** [openhab/openhab-docs#239]
I installed openHAB Cloud Connector only yesterday and I got difficulty to understand that it is normal that no items appear in "Items" frame when I logged to my account (https://myopenhab.org).

I think the documentation should more clearly explain that only items that are defined in the "expose" configuration settings will appear in this place, that this setting is required only to expose these particular items to external services and that **it is not necessary to set this setting to have a remote access to all items with Basic UI or HABdroid.**

In addition, you should explain that you can access UIs from the WEB (Basic UI using https://myopenhab.org/basicui/app and Classic UI using https://myopenhab.org/classicui/app) using myopenhab account to authenticate.

PS: remote access and control seems to work well with good reactivity to commands.

**Comment by lolodomo** [comment]
And please mention that there is an exception for Paper UI: right URL is https://home.myopenhab.org/paperui/index.html and not https://myopenhab.org/paperui/index.html

**Comment by watou** [comment]
If same code as old my.openhab.org, "home" was added to pass all URIs, whereas original only passes a subset (recalling comment from @belovictor).

**Comment by kaikreuzer** [comment]
Note that the cloud connector add-on is at https://github.com/openhab/openhab2-addons/blob/master/addons/io/org.openhab.io.openhabcloud/README.md (not here in docs) - you might want to create a PR with your suggestion there.

Note that myopenHAB is ONLY a reference instance, while the connector add-on is meant for ANY cloud instance, so the documetation should not have any references to myopenhab.org urls.

**Comment by Confectrician** [comment]
Done in openhab/openhab2-addons#4104
