### ISSUE TITLE
Docs: RRD conversion (format is dependent on platform)

### ISSUE THREAD

**Issue by holgerfriedrich** [openhab/openhab-docs#2395]
This issue is related to OH5 preparations. A lot of users will need to migrate their setup to 64-bit.

**RRD database format is dependent on the platform, i.e. during migration from 32-bit to 64-bit system those databases need special treatment.**
It seems that an xml export / import is necassary.

See for example https://blog.remibergsma.com/2012/04/30/rrdtool-moving-data-between-32bit-and-64bit-architectures/

As this is the default database format, we need to support users during migration. **This is about documentation of the necessary steps.** In addition, we should implement some tooling in the openHABian tool.

**Comment by rkoshak** [comment]
Is this something that upgradeTool could do?

**Comment by holgerfriedrich** [comment]
There is actually no need to convert data. We are using RRD4J database format, which is _not_ dependent on platform.
This is also mentioned as one of the main selling points of RRD4J:
https://github.com/rrd4j/rrd4j#why-rrd4j
> Why RRD4J?
> Portable files, RRDTool files are not


I just imported data from my old backups and could still visualize it on my 64-bit system.

Sorry for the confusion.
