### ISSUE TITLE
[huesync][binding][logo] Add logo for huesync binding to repository

### ISSUE THREAD

**Issue by pgfeller** [openhab/openhab-docs#2407]
Depends on PR \#16516 **[huesync] [Hue Play HDMI Sync Box Binding](https://github.com/openhab/openhab-docs/pull/2408)**

**Comment by stefan-hoehn** [comment]
Patrick, I think the above link to the binding isn't correct. It should link to https://github.com/openhab/openhab-docs/pull/2408

**Comment by lsiepel** [comment]
The related PR has been merged: https://github.com/openhab/openhab-addons/pull/16516
