### ISSUE TITLE
Code highlighting, formatting style, Icons

### ISSUE THREAD

**Issue by ThomDietrich** [openhab/openhab-docs#248]
While working on the docs page the last couple of weeks, I encountered a few flaws in some docs styling aspects. I've finally found the time to look into these problems and prepared a rather big change last week, addressing most of these. The most prominent and one that I would like to fix as soon as possible is the highlighting issue:

![grafik](https://cloud.githubusercontent.com/assets/2870104/22182682/bff3f708-e0ab-11e6-8bf7-39ae1ebae1c4.png)

Another is font presentation issues:

![grafik](https://cloud.githubusercontent.com/assets/2870104/22182701/3ce3c982-e0ac-11e6-9b28-fc72c14e42ae.png)

Other aspects I've taken care of are updates of the included components like materialize and material-icons. **If** I find the time, I'll finalize these changes this evening and create a PR.
@kaikreuzer any comments this far? Would you have the time to take a quick look?

Best Regards, Thomas

**Comment by kaikreuzer** [comment]
If you have found room for improvement and even solutions to it, why should I comment in any way? Looking forward to any updates. The only comment is one you might expect yourself: It would be nice to have the same adaptions made at the ESH documentation to keep these in sync. Thanks!

**Comment by ThomDietrich** [comment]
While everyone is getting ready for the release of binaries I've been looking into code highlighting 🌈 
@kaikreuzer @BClark09 which of those styles do you like better? I chose one which fits nicely and one that creates contrast.

![sample_jekyll-github](https://user-images.githubusercontent.com/2870104/27616211-54628864-5bae-11e7-9c08-2ae7f7d2e4d7.png)
![sample_tomorrow_night_eighties](https://user-images.githubusercontent.com/2870104/27616212-54638ef8-5bae-11e7-8dbb-1bc6ea7911c3.png)

**Comment by BClark09** [comment]
Nice! My vote would be for the first, I really like both but the first fits the general page much better.

**Comment by kaikreuzer** [comment]
I agree with @BClark09!

**Comment by ThomDietrich** [comment]
Wonderful. I tested a dozen and liked these two, I'll go with the first one.

**Comment by Confectrician** [comment]
Styling is done by vuepress in the new page, so we should check for issues on a clean base and improve them on the website repo.
