### ISSUE TITLE
404 when clicking [beginner’s tutorial!] link on linux.html

### ISSUE THREAD

**Issue by xMTinkerer** [openhab/openhab-docs#254]
Hey guys!
   I got a 404 when clicking the [beginner's tutorial] link on this page:
http://docs.openhab.org/installation/linux.html#package-repository-installation

It brought me to this page:
http://docs.openhab.org/tutorials/beginner/1sttimesetup.md

Which doesn't exist.

**Comment by BClark09** [comment]
Whoops that was my fault. Submitted a new PR.
