### ISSUE TITLE
Header logo link

### ISSUE THREAD

**Issue by paulianttila** [openhab/openhab-docs#258]
Should openHAB logo link in the header go back to openHAB main page (www.openhab.org) rather than docs.openhab.org index page? If not, then header probably should have a link to openHAB main page (www.openhab.org).

**Comment by MHerbst** [comment]
Linking he log in the header to the openHAB main page would be very confusing. A click on the log normally brings you to the home page of a site (in this case docs.openhab.org).
But I agree with you that a link to would be fine.  

I am planning to a add footer line (#223) for links to imprint and privacy. Would could a link to the openHAB website to this line.
