### ISSUE TITLE
Non default port in example

### ISSUE THREAD

**Issue by rtvb** [openhab/openhab-docs#26]
The example uses port 8011 instead of the default 8080. For clarity and consistency the documentation should always use the same.

http://docs.openhab.org/tutorials/advanced/installing.html
##

**Comment by kaikreuzer** [comment]
I agree, this has also been discussed already [here](https://community.openhab.org/t/documenting-openhab-2/10568/51?u=kai).

@bipphilippe Will you take this into consideration?

**Comment by ThomDietrich** [comment]
Solved in the meantime. Could be related to https://github.com/openhab/openhab-docs/issues/175.
