### ISSUE TITLE
Updating the openHAB Runtime: File missing

### ISSUE THREAD

**Issue by LKuech** [openhab/openhab-docs#260]
Hi.

The section "Updating the openHAB Runtime" (http://docs.openhab.org/installation/windows.html#updating-the-openhab-runtime)

is missing to mention that the file "**userdata\etc\version.properties**" needs to be delete as well.
Otherwise openhab will continue to search for artifacts of the older version.

**Comment by ThomDietrich** [comment]
Thank you! We will take care of that ;)
Related to #180 #244 #262

**Comment by gitMiguel** [comment]
@Confectrician stale.
