### ISSUE TITLE
Old file features/bindings.md causes 404 errors

### ISSUE THREAD

**Issue by MHerbst** [openhab/openhab-docs#267]
The page features/bindings can be found via Google. But the links on the rendered page causes 404 errors because they are pointing e.g. to http://docs.openhab.org/features/bindings/exec/readme.html.

The site seams to contain some more invalid links caused by the move from ../features to ../addons at least Google complains about some invalid links.

**Comment by ThomDietrich** [comment]
I've created redirects for the important pages some might have linked in the forum or similar.

So... sounds like a Google problem!? They should have updated their index by now.

**Comment by MHerbst** [comment]
Most of the 404 reported by Google are really obsolete. The remaining 404 came from this page: http://docs.openhab.org/features/bindings.html. For example the links to Exec, Feed, Global Cache are not valid.

What about replacing http://docs.openhab.org/features/bindings.html by a redirect to http://docs.openhab.org/addons/bindings.html? Would solve the problem and the "old" list is no longer shown.

**Comment by ThomDietrich** [comment]
Oh wait. This page should not exist anymore. Well that explains everything.

**Comment by ThomDietrich** [comment]
Oh :disappointed: after #148 I forgot to "revert revert" this one: https://github.com/openhab/openhab-docs/commit/ec9f9856299de1c613785b7ef156cc547a25f1bc

**Comment by ThomDietrich** [comment]
I hope this resolves it. Thanks @MHerbst !
