### ISSUE TITLE
Clarify binding config section that not all bindings create a cfg

### ISSUE THREAD

**Issue by rkoshak** [openhab/openhab-docs#275]
This is on the Items doc. See: https://community.openhab.org/t/will-binding-cfg-files-be-automatically-created/21040/8

**Comment by ThomDietrich** [comment]
With the above PR, We've added this part:

> After installing a legacy or regular 1.x binding, an individual <binding_name>.cfg file is created in the /services folder. If such a file is not available, please add it manually. 

I guess that's it?

**Comment by ThomDietrich** [comment]
Aaaah sorry. Overlooked "This is on the Items doc."

So part of #250 then? :smiley:

**Comment by ThomDietrich** [comment]
Addressed in #494, which concentrated on the Syntax chapter. The Binding part of the Items article still needs to see a big overhaul.
