### ISSUE TITLE
All links on the front page appear not to work

### ISSUE THREAD

**Issue by rkoshak** [openhab/openhab-docs#276]
404 errors are generated.

Also, the featured technologies probably needs to be updated. See:https://community.openhab.org/t/main-frontpage-www-openhab-org-needs-an-update/21396/2

**Comment by BClark09** [comment]
Looks like an issue for https://github.com/openhab/openhab.github.io, 

http://www.openhab.org/features/supported-technologies.html should be http://www.openhab.org/technologies.html

**Comment by MHerbst** [comment]
> Looks like an issue for https://github.com/openhab/openhab.github.io,

Yes, but in this repo the issue tracker it not activated.

**Comment by kaikreuzer** [comment]
> Yes, but in this repo the issue tracker it not activated.

Right, we only accept PRs there.
We should do the same on other repos, too 😆
