### ISSUE TITLE
Invalid links

### ISSUE THREAD

**Issue by MHerbst** [openhab/openhab-docs#278]
Page http://docs.openhab.org/concepts/guidelines.html contains an invalid link to http://docs.openhab.org/concepts/guidelines.html. 

I think the correct target would be http://docs.openhab.org/developers/development/ide.html

On page http://docs.openhab.org/addons/uis.html all links in section "App" are invalid. They must be changed to "../addons/**uis**/apps/..."

Page: http://www.openhab.org/technologies.html links to http://docs.openhab.org/addons/bindings/gcal/readme.html which no longer exists.

**Comment by ShaunCurrier** [comment]
I think your first point intends to say that the IDE Setup link is wrong.  I can confirm.

I also confirm that the App links are invalid.

I'm unclear which of the links on the technologies page is broken.  I can't find anything related to "gcal" on that page.  Which image did you click?

**Comment by ShaunCurrier** [comment]
I fixed these issues in #353 except for the last part dealing with http://www.openhab.org/technologies.html.  I think that problem might need to get routed elsewhere.

**Comment by kaikreuzer** [comment]
> I'm unclear which of the links on the technologies page is broken. I can't find anything related to "gcal" on that page. Which image did you click?

I think this does not exist anymore since I regenerated that page one or two weeks ago.
Many thanks for fixing the rest, @ShaunCurrier!

**Comment by MHerbst** [comment]
> I think this does not exist anymore since I regenerated that page one or two weeks ago.

@kaikreuzer 's assumption is correct. I have checked the and they are OK now. Thanks for fixing the links @ShaunCurrier

**Comment by ThomDietrich** [comment]
Can the issue be closed then?

**Comment by MHerbst** [comment]
I wanted to wait until the PR was merged before closing this issue.

**Comment by ThomDietrich** [comment]
Well then ;)
