### ISSUE TITLE
Migration Tutorial needs to reference 1.9 bindings with a trailing 1

### ISSUE THREAD

**Issue by rkoshak** [openhab/openhab-docs#288]
The migration tutorial was written before the convention of appending a 1 to the end of the 1.9 binding names (e.g. mqtt1). The "Text only" section needs to update to include this fact and take it into account in the example.

**Comment by watou** [comment]
Please make sure it's made clear that 1.x binding feature names end with a "1" appended, for the purpose of installing a 1.x binding.  Other uses of the binding ID do not have a "1" appended.

**Comment by rkoshak** [comment]
I tried to update the patch but it is telling me the file cannot be edited.

**Comment by AngelosF** [comment]
I made the comment below on your forked commit (maybe I should have wrote it here :)) (I am still learning github)

Maybe use version 1.x since after the release of openHAB 2.0.0, the snapshot versions of the bindings have been bumped up to 1.10.
Some users may use OH2 <2.0.0 where you have 1.9 and some OH2 > 2.0.0 where you have 1.10 for the "old" bindings

**Comment by rkoshak** [comment]
I'd rather do that in a separate Issue as it has implications across the docs, not just this one section of the Migration Tutorial.

**Comment by AngelosF** [comment]
True.
A google search of:
```
"1.9" +site:docs.openhab.org
```
gives me 2 relevant results: Your migration tutorial and http://docs.openhab.org/addons/bindings.html

I will open up another issue on this small change

**Comment by rkoshak** [comment]
Already done. Feel free to implement it. I'm probably going to be signing off for the day in a few minutes to go take some more medicine and sleep a bit.

**Comment by AngelosF** [comment]
I saw the issue that you posted. It's fine.  I will prepare a PR for the bindings.html doc entry.

Get well !

**Comment by watou** [comment]
> http://docs.openhab.org/addons/bindings.html
> I will open up another issue on this small change

Please review open PRs because binding.md is fully reworked there! :-)

**Comment by rkoshak** [comment]
I give up trying to edit that file. I'll try again later or if someone else can figure it out that's great too.

**Comment by Confectrician** [comment]
We are reworking the tutorial for openHAB 3 and have removed the complete existing Tutorial.
Closing this issue therefore.
