### ISSUE TITLE
Items: Add use of 'autoupdate'

### ISSUE THREAD

**Issue by metbril** [openhab/openhab-docs#291]
The docs entry for items currently does not provide any explanation of the feature to add `autoupdate=false` to the binding definition. 

http://docs.openhab.org/configuration/items.html 
or
https://github.com/openhab/openhab-docs/blob/gh-pages/configuration/items.md

More info:
https://github.com/openhab/openhab1-addons/wiki/Samples-Item-Definitions

**Comment by ThomDietrich** [comment]
@rkoshak

**Comment by ThomDietrich** [comment]
Should be part of #250

**Comment by ThomDietrich** [comment]
@metbril do you think this is solved?

**Comment by metbril** [comment]
@ThomDietrich You did a lot of hard work on that topic! 

I think the autoupdate documentation will suffice for now. At least, people can be aware of the feature and we can safely refer or point out to it when needed.

**Comment by ThomDietrich** [comment]
Wonderful :)
