### ISSUE TITLE
Sitemaps: iOS app only supports HTML codes for valuecolor 

### ISSUE THREAD

**Issue by metbril** [openhab/openhab-docs#292]
In Sitemap page add a [known issue](https://github.com/openhab/openhab.ios/issues/112) that the iOS app currently only supports HTML color codes for valuecolor.

So #ff0000 instead of 'red'

iOS repo issue:
https://github.com/openhab/openhab.ios/issues/112

Community discussion
https://community.openhab.org/t/openhab2-valuecolor-not-changing-in-ios-app/14831/2

Repo doc
https://github.com/openhab/openhab-docs/blob/gh-pages/configuration/sitemaps.md

Direct link to docs section
http://docs.openhab.org/configuration/sitemaps.html#colors

**Comment by ThomDietrich** [comment]
Did you open an issue there? Can't find it...

**Comment by rtvb** [comment]
I hadn't yet. Done now.

https://github.com/openhab/openhab.ios/issues/112

**Comment by ThomDietrich** [comment]
Just replied on the other issue. I'll leave this on pending for a few more days. Maybe it will be solved by then :)
