### ISSUE TITLE
Links to add-on documentation in Paper UI are broken

### ISSUE THREAD

**Issue by MHerbst** [openhab/openhab-docs#295]
Due to a change in the documentation structure (commit https://github.com/openhab/openhab-docs/commit/5be5bc2fb9d83777fc1116def6c5c5a45999a31c  @kaikreuzer ) it seems that all links to add-on docs are broken. The add-ons are using URLs like this:
```
http://docs.openhab.org/addons/bindings/allplay/readme.html
````
But the URLs have changed to:
```
http://docs.openhab.org/addons/bindings/oh2/allplay/readme.html
```
... and there seem to be no redirects.

BTW: The links in the search results are currently also wrong until Google has reindexed everything :-(.

**Comment by watou** [comment]
This could be addressed by using [this Jekyll plugin](https://github.com/jekyll/jekyll-redirect-from) and a small change to the build process.

**Comment by ThomDietrich** [comment]
I'm not sure if we really need to address that. I've added redirects in the past but for the main articles. Do we need every bindings old URL? Google will update quickly and links posted in the forum or somewhere else will loose their importance quickly. The user will see our 404 page and can go from there.

**Comment by kaikreuzer** [comment]
@watou & @ThomDietrich I think you are missing the severity of this issue: 

The links mentioned by @MHerbst are used in the openHAB Distro (Paper UI -> Addons) to link to the documentation of the according add-ons.
ALL OF THOSE LINKS ARE NOW BROKEN FOR ALL USERS. As openHAB 2.0.0 is out there, we cannot change these links.
I wasn't aware that @watou's refactoring changed these links, this should not have happened.

**Comment by watou** [comment]
> I think you are missing the severity of this issue:

No I am not;  I've submitted now two PRs to address it.  As I was not aware that PaperUI had a documentation link for 2.x bindings.

Will #297 allow users to access OH1 binding docs?

**Comment by kaikreuzer** [comment]
> No I am not;

Right, this comment was rather meant for @ThomDietrich as he suggested not to fix it :-)

> Will #297 allow users to access OH1 binding docs?

Once merged, I can do the necessary adaptions in the distro. Currently, there simply is no link to docs in the PaperUI for 1.x add-ons.

**Comment by ThomDietrich** [comment]
I was in fact not aware of that. Great you found a solution!
