### ISSUE TITLE
"Accessing the Console" should indicate localhost required

### ISSUE THREAD

**Issue by jeffsf** [openhab/openhab-docs#298]
http://docs.openhab.org/administration/console.html

While it is prudent that Karafe console access be tightly controlled on an IoT device that may be exposed by inexperienced users, the current documentation does not clearly indicate that the Karafe console's ssh access appears to only bind to localhost.

Current text:

> If openHAB runs a service, the console can be accessed using ssh to the openHAB host on port 8101. The default username/password is openhab/habopen. Be aware, that the first connection attempt may take a few seconds longer.

Suggested text (assuming the "intent" statement is correct):

> If openHAB runs a service, the console can be accessed using ssh from the openHAB host on localhost: 8101. It is intentionally not available from remote hosts due to security concerns. The default username/password is openhab/habopen. Be aware that the first connection attempt may take a few seconds longer.

(Note that the identified page _does_ indicate how to bind to all interfaces, but well below the fold)

Suggested additions:
* How to change the username/password credentials
* How to install certificates for password-less authentication

Perhaps indicate that an ssh timeout may on first login
```$ ssh -p 8101 openhab@localhost
The authenticity of host '[localhost]:8101 ([127.0.0.1]:8101)' can't be established.
RSA key fingerprint is <redacted>.
Are you sure you want to continue connecting (yes/no)? yes
Warning: Permanently added '[localhost]:8101' (RSA) to the list of known hosts.
Password authentication
Password: 
Received disconnect from UNKNOWN: 2: Session has timed out waiting for authentication after 120000 ms.
```

**Comment by ThomDietrich** [comment]
Hello @jeffsf thanks for reporting that issue and already suggesting a solution!
The idea of adding this warning was already posted here https://github.com/openhab/openhab-docs/issues/168, we will take care of all mentioned aspects shortly!

It would be an amazing help if you could create the appropriate Pull Request for all mentioned changes! ;) Would you be up for that?

**Comment by jeffsf** [comment]
First part is "easy" (once I figure out how to preview the .md pages), so yes on that.

I'll have to figure out how to "answer" the two bulleted points and confirm that they work before I get out a pull request for the "Suggested additions"

**Comment by ThomDietrich** [comment]
Will answer in PR
