### ISSUE TITLE
Custom 404 page

### ISSUE THREAD

**Issue by rtvb** [openhab/openhab-docs#30]
If you open a non existing page like http://docs.openhab.org/somepage/ a 404 page with GitHub branding is shown. This should be replaced with a OH branded one.

**Comment by kaikreuzer** [comment]
Good idea! Could you come up with a PR for this?

**Comment by rtvb** [comment]
I will give it a try.

**Comment by kaikreuzer** [comment]
Any success?

**Comment by rtvb** [comment]
Not yet. Due to personal circumstances I have not been able to do much
computer work in my spare time lately. I'd still like to contribute, but
if someone else can fix this issue shortly, I don't mind.
