### ISSUE TITLE
Sitemaps: Lightgray missing in color table

### ISSUE THREAD

**Issue by metbril** [openhab/openhab-docs#304]
In several demos I have seen use of 'lightgray' ('#d3d3d3') as valuecolor. However this color code is missing in the table in the docs. If this is a standard agreed color it should be included. If not, the official examples should not use it.

Unfortunately have not found an example to point to. Perhaps we should check at least the demo config for the use, too.

Repo ref
https://github.com/openhab/openhab-docs/blob/gh-pages/configuration/sitemaps.md

Docs ref
http://docs.openhab.org/configuration/sitemaps.html#colors

Related to https://github.com/openhab/openhab-docs/issues/292

**Comment by ThomDietrich** [comment]
Will be part of #53

**Comment by ThomDietrich** [comment]
Hey,
please pay attention to http://docs.openhab.org/configuration/sitemaps.html#colors

> It is generally expected that valid HTML colors will be accepted (e.g. “green”, “lightgrey”, “#334455”), but a UI may only accept internally defined colors or work with a special theme. The given color names are agreed on between all openHAB UIs and are therefor your safest choice.

So to answer your question and to potentially update this table, we need to bring @digitaldan in. The given table limits the wide selection of colors to a few that are supposedly also supported by the Android and iOS apps. @digitaldan could you shed some light on that? Which colors are supported, which are not? What needs to be changed in this table or the apps to fulfill the claim of the second sentence? Best!
