### ISSUE TITLE
Migration: CallType no longer exists

### ISSUE THREAD

**Issue by watou** [openhab/openhab-docs#305]
[Page](http://docs.openhab.org/tutorials/migration.html#rules)

[Needed content from here](https://community.openhab.org/t/fritzbox-tr064-binding-creation-of-esh-event-failed/10064/12?u=watou):

> CallType does not exist anymore, you will have to adapt your rule to StringListType instead. Without having tested it, it should be something like:
> val incCall = fboxIncomingCallResolved.state as StringListType
> val callerNumber = incCall.getValue(0)

**Comment by Confectrician** [comment]
We are reworking the tutorial for openHAB 3 and have removed the complete existing Tutorial.
Closing this issue therefore.
