### ISSUE TITLE
Clarification: Item Type Group in the Frame element of a sitemap

### ISSUE THREAD

**Issue by AngelosF** [openhab/openhab-docs#306]
We should add a clarification to the http://docs.openhab.org/configuration/sitemaps.html#element-type-frame that Item Type Group cannot be used in the Element Type Frame.

Potentially, add an example on how to correctly display a Group within a Frame:
```
Frame {
        Group item=gGroup_Name
}
```

The following does not work:
```
Frame item=gGroup_Name
```

Ps: https://community.openhab.org/t/automatic-frame-generation-from-group-items/22117

**Comment by kaikreuzer** [comment]
I wasn't even aware that you can define a "normal" item for a frame. What does that do? How is that rendered? I am not sure that this actually makes much sense at all... The frames are really only meant to do some visual separation with a title, nothing more than that.

**Comment by AngelosF** [comment]
It just renders the item info in the "header" of the frame
Example:
```
Frame item=WU_Temp
```

With item definition:
```
Number	WU_Temp		"Temperature [%.2f °C]"		<temperature>	(Weather,gInflux)	{weather="locationId=HomeR, type=temperature, property=current"}
```

Will result to:
![frame_item](https://cloud.githubusercontent.com/assets/25465966/22684309/7e5fc81e-ed24-11e6-879f-91814817d4ed.png)

**Comment by kaikreuzer** [comment]
That's what I was wondering - showing some item status simply does not make sense for the frame. I would rather suggest to remove this "feature" completely.

**Comment by AngelosF** [comment]
I also agree...
Should I close this issue then or we should "re-use" to remove from the sitemaps docs entry the option to use item in the Frame element syntax?

**Comment by kaikreuzer** [comment]
For me ok to re-use as the title is about a "clarification" :-)
