### ISSUE TITLE
ZoneMinder docs missing

### ISSUE THREAD

**Issue by kubawolanin** [openhab/openhab-docs#308]
Environment: Latest SNAPSHOT

Steps to reproduce:
1. In PaperUI go to Add-ons / Bindings
2. Scroll down to ZoneMinder binding
3. Click on ZoneMinder binding's title

Expected result:
ZoneMinder's docs are displayed on http://docs.openhab.org/addons/bindings/zoneminder/readme.html

Actual result:
Error: 404
The page you were looking for was not found!

Notes:
* Tried also http://docs.openhab.org/addons/bindings/oh2/zoneminder/readme.html
* The binding is missing on the [Bindings list](http://docs.openhab.org/addons/bindings.html) as well

**Comment by kaikreuzer** [comment]
Now available at http://docs.openhab.org/addons/bindings/zoneminder/readme.html
