### ISSUE TITLE
Things: enhance configuration document

### ISSUE THREAD

**Issue by stephenbonar** [openhab/openhab-docs#312]
The configuration document for things is currently a stub and needs some content. I'm going to start writing a document for it to submit as a PR and I plan to cover the following at a minimum:

* Introduction
* Discovery based configuration
* File based configuration
    * Highlighting the fact that some bindings (for example, Z-Wave) do not currently work properly with things files
    * Basic syntax
    * A few key examples

Is there anything else anyone would like to see covered?

**Comment by hakan42** [comment]
An example where you put a Thing into a specific Location would be nice.

For example "Foo" @ "Garden"

**Comment by ThomDietrich** [comment]
Reopening for the second iteration.

Open ToDos:

* Bridges: https://github.com/openhab/openhab-docs/pull/321#issuecomment-283495822
* Item Linking: https://github.com/openhab/openhab-docs/pull/321#issuecomment-283589128
* Syntax clarification: https://github.com/openhab/openhab-docs/pull/321#issuecomment-284740728

**Comment by jeffsf** [comment]
Strongly suggest that the text and examples conform with the current syntax as discussed in https://community.openhab.org/t/current-and-correct-documentation-of-syntax-for-things-and-items-needed/24864

Any and all examples should be checked to see that
* They check as "correct" in Designer
* They properly load into a clean, running instance of openHAB, release version

Further strongly suggest that linked references to the syntax documents, as well as how to find them "manually" should be provided.

Each component of the syntax in the description should clearly state what characters are acceptable and not. "Alphanumeric and underscore" is insufficient, especially in light of character sets that contain alphanumeric characters that are not "[a-zA-Z0-9]" Limitations on component length should be indicated, if present in the underlying data structures.

**Comment by ThomDietrich** [comment]
@jeffsf and @stephenbonar Would one of you like to work on the second iteration?
