### ISSUE TITLE
you meant "tool" :)

### ISSUE THREAD

**Issue by genesisfactor** [openhab/openhab-docs#314]
on page: http://docs.openhab.org/administration/index.html, you're missing the "l" in tool

As a base technology openHAB uses Apache Karaf, a modern and polymorphic container able to host different kinds of applications. The Karaf Console is a powerful **too** 

> you mean TOOL, right :)

to interact with the core of your openHAB installation.

**Comment by ThomDietrich** [comment]
Yes... No... Maybe... That's confidential.

:smile: Thanks @genesisfactor I've fixed that just now!
Any interest to help add content to this or any other page?

**Comment by genesisfactor** [comment]
lol.  I haz ur secrets now.

I literally just OpenHab 2 yesterday.  :).  I'd love some help figuring out
a few things myself, but would be happy to enhance any page I can.

At risk of turning this into a bug report or a conversation thread....

One thing i noticed: i created a panel HABPanel in my new install.  I saved
my panel.  Then i made it a static ip address for a different address.
Now my panel is gone, though it is the same device.  How is HAPanel work
supposed to work (is this a bug or the desired behavior)?

I was almost done in OH1.x with a set of scripts that does near real time
updates (3 to 6 second delay) of a rooted wink hub without polling
aprontest (.  It can be sent over serial (or ssh).  While the wink hub does
its part perfectly, my challenge was getting Openhab to read and store the
values.  I'd love a better understanding of porting that over...maybe
making a wink hub part of Openhab2 Discovery...

**Comment by ThomDietrich** [comment]
Sorry can't help here. I'm personally not working with Habpanel... You will be happy with the answers you will receive in the community forum, promise it ;)

**Comment by genesisfactor** [comment]
Sweet deal.  I'll see how i can contribute!
