### ISSUE TITLE
[Configuration/Items] Correct bad information

### ISSUE THREAD

**Issue by watou** [openhab/openhab-docs#318]
The [following paragraph](http://docs.openhab.org/configuration/items.html) is replete with incorrect information and advice:

> If you need to use legacy openHAB 1.x bindings then you need to enable this feature through the PaperUI menu by turning on “Include Legacy 1.x Bindings” found at /configuration/services/configure extension management/. After downloading the legacy .jar files, they need to be placed in the /addons/ folder. If further configuration is required then you will need to create an openhab.cfg file in /conf/services/ and paste the appropriate binding configuration into this. For all other native openHAB2 bindings, configuration is done through a bindingname.cfg file in the same location.

The use of the word "legacy" is incorrect; the use of openhab.cfg is incorrect; the use of the directory "conf" is unhelpful on installs with no such directory, the distinction from openHAB 2 bindings is incorrect.

I would highly prioritize a correction to this document as it is almost certainly causing frustration among users.

**Comment by ThomDietrich** [comment]
Good catch! I believe that's a concern for https://github.com/openhab/openhab-docs/pull/250 ?

**Comment by watou** [comment]
Thanks for the link to @rkoshak's  #250.  It's not easy to tell what that PR is about given the title.

**Comment by ThomDietrich** [comment]
No doubt about that :)

**Comment by watou** [comment]
Hi @ThomDietrich could you please reopen this issue since I cannot find any treatment of the contents of this issue in #250 or the related issue?  I think it's important to not let these errors remain in the documentation.
