### ISSUE TITLE
[Configuration/Items] Correct bad information

### ISSUE THREAD

**Issue by watou** [openhab/openhab-docs#319]
Please do not close this issue until the subjects it describes are addressed and merged.  This is a copy of the now closed issue #318.  If @rkoshak is working on this, please assign this issue to him.  Thanks!

---

The [following paragraph](http://docs.openhab.org/configuration/items.html) is replete with incorrect information and advice:

> If you need to use legacy openHAB 1.x bindings then you need to enable this feature through the PaperUI menu by turning on “Include Legacy 1.x Bindings” found at /configuration/services/configure extension management/. After downloading the legacy .jar files, they need to be placed in the /addons/ folder. If further configuration is required then you will need to create an openhab.cfg file in /conf/services/ and paste the appropriate binding configuration into this. For all other native openHAB2 bindings, configuration is done through a bindingname.cfg file in the same location.

The use of the word "legacy" is incorrect; the use of openhab.cfg is incorrect; the use of the directory "conf" is unhelpful on installs with no such directory, the distinction from openHAB 2 bindings is incorrect.

I would highly prioritize a correction to this document as it is almost certainly causing frustration among users.

**Comment by rkoshak** [comment]
I'm on travel until March 4th and won't have a chance to work on anything until then. I welcome anyone else taking this. Otherwise it will have to wait.

**Comment by Confectrician** [comment]
I think we can close this one, since any 1.x reference needs to be removed for openHAB 3 anyway.
