### ISSUE TITLE
Smart Home Designer Documentation

### ISSUE THREAD

**Issue by psyciknz** [openhab/openhab-docs#326]
As part of the documentation for Smart Home Designer, a note that the configuration will not be loaded if (in windows) you use a UNC path.  

The user must map a drive to the openhab configuration directory (on linux via apt =  /etc/openhab2).

Also as a newly installed linux system, I had no idea what directories I needed to share.  I was lucky to have an openhabian system with a samba config I could copy.  Unsure if there's some more help that could be given to get samba working, I'm fairly happy in linux running 3 systems at home, but getting windows to connect to the shares was pretty difficult.

**Comment by ThomDietrich** [comment]
All this should be documented here: http://docs.openhab.org/installation/linux.html#network-sharing !?

**Comment by psyciknz** [comment]
So it is....but I was looking for help in http://docs.openhab.org/installation/designer.html#setup page - and there's no reference back to that installation page - given at the point I'm using Smart Home I have an already running OpenHab system, and may or may not have required the docs to get to that point.

**Comment by ThomDietrich** [comment]
That's a fair point... but even then one of the first sentences states:

> In order to configure your openHAB setup, you will need a mounted network share to your configuration.

**Comment by ThomDietrich** [comment]
@psyciknz I've tried to improve upon your concerns. Could you please review the changes?

https://github.com/openhab/openhab-docs/pull/329/files?short_path=b5c1eed#diff-b5c1eed5c2541b9dad67534a0ece2a36

**Comment by psyciknz** [comment]
Hi, reviewed it directly.  Looks good, and obvious enough that skim readers should also pick up on it.
