### ISSUE TITLE
IO/System Integration articles 404 from menu

### ISSUE THREAD

**Issue by ThomDietrich** [openhab/openhab-docs#330]
@watou could you please have a look? http://docs.openhab.org/addons/io.html

**Comment by watou** [comment]
Not sure what caused it, but I will submit a PR.

**Comment by watou** [comment]
@ThomDietrich PR #332 submitted.

**Comment by kaikreuzer** [comment]
@watou @ThomDietrich There is still a 404, if you navigate from the entries on http://docs.openhab.org/addons/io.html.

**Comment by watou** [comment]
@kaikreuzer #332 only changed non-generated content and removed generated content that shouldn't have been added.  I was leaving the checking in of new generated content to you.  This would mean `git add addons/io`.  I can submit a PR with my generated content there, or you could on your next re-gen of the site.  What do you prefer I do now and in future PRs?

**Comment by watou** [comment]
Added #338 so your normal "updated generated content" script ought to work after it's merged.

**Comment by kaikreuzer** [comment]
Ah, sorry @watou, I must have missed that somehow - I had content regenerated locally, but I didn't correctly push it to giithub. Just updated everything now and the issue is indeed solved. Many thanks!
