### ISSUE TITLE
OpenHAB core-to-binding API documentation

### ISSUE THREAD

**Issue by brharoh** [openhab/openhab-docs#333]
Either I did not find the API documentation between the openHAB 2 core and any bindings, or it is practically non-existent.  Should such an essential part not be well documented to assist binding developers who are going to make openHAB more universal? 
I took a tool to analyze the relationships between core and my binding code which was modelled after the Stiebel Eltron binding and got the attached graph.  I am putting this graph into the public domain in case it is of help for others.  But I am still quite at a loss what these functions do.
My understanding of a core-to-binding API documentation is 
- a list of the (abstract) functions and the functions in the Interface files which the binding must implement
with a description what each of these functions does and whether the binding developer must actually implement it (requirement) or may implement it (optional)
- descriptions of the function parameters
- a description of the return value where applicable
If such an API description had existed, it would have saved me a tremendous amount of time.  At least the Stiebel Eltron binding developer had already done a great job when he identified the relevant functions.
![hierarchy](https://cloud.githubusercontent.com/assets/25861134/23091805/d040aea8-f5be-11e6-848d-c46525015928.gif)

**Comment by kaikreuzer** [comment]
Hm, what you have documented are the old openHAB 1 APIs, which are not really used anymore - the documentation for "new" bindings is at https://www.eclipse.org/smarthome/documentation/development/bindings/how-to.html (which is being linked to from the [openHAB Developer Guide](http://docs.openhab.org/developers/development/bindings.html).
I agree that some class diagrams might be helpful for this as well, but the new APIs are mainly designed in a way that all you need to worry about are very few classes, which have well defined methods, that are also documented.

**Comment by ThomDietrich** [comment]
Never understood why the javadoc is not the goto place for this topic. I've checked the tutorial and the next few pages and it's hardly mentioned anywhere. The few links that are there point to the source code on github...
https://www.eclipse.org/smarthome/documentation/javadoc/index.html
