### ISSUE TITLE
OpenHAB 2 Installation Instructions

### ISSUE THREAD

**Issue by brharoh** [openhab/openhab-docs#334]
Here is a description of my experiences during a new installation of openHAB 2.  Maybe it is useful for who
[OpenHAB2-IDE-Installation.pdf](https://github.com/openhab/openhab-docs/files/784893/OpenHAB2-IDE-Installation.pdf)
ever maintains the openHAB 2 documentation web pages.

**Comment by ThomDietrich** [comment]
Thanks @brharoh, from what I am able to see, this should all be covered in docs by now. If one or two points are missing from your point of view, **please** comment and reopen the issue! Thanks for your contribution ;)
