### ISSUE TITLE
Sitemaps: Setpoint incorrect

### ISSUE THREAD

**Issue by chiefymuc** [openhab/openhab-docs#335]
In the Setpoint syntax, the  does not have "" for 'minValue', 'maxValue' and 'step'.

This is incorrectly reflected in the documentation.

Example:

It should be:
`Setpoint	item=Volume label="Volume" icon="audio" minValue=0 maxValue=50 step=1`
NOT
`Setpoint	item=Volume label="Volume" icon="audio" minValue="0" maxValue="50" step="1"`

**Comment by ThomDietrich** [comment]
Thanks @chiefymuc,
I'll take this as a sign to finally work on #53 and other open sitemap issues.

**Comment by ThomDietrich** [comment]
Done.
