### ISSUE TITLE
IDE Setup for Eclipse Neon not working.

### ISSUE THREAD

**Issue by dmcwhinnie** [openhab/openhab-docs#34]
Tried getting the IDE setup for the first time, and it appears Eclipse Neon has been released, and this is breaking the Oomph install process.

May want to add a clarification note to IDE setup step 3, indicating Product Version Mars needs to be selected.  It is in the screen shot, but I just took the default which is now "Neon".  Once I went back and select Mars everything worked as expected.

Image of selection attached. 

![ide2](https://cloud.githubusercontent.com/assets/13082529/16358403/bdcbf04a-3ad7-11e6-850c-867fbbbbcec5.png)

 I was going to edit and make a Pull request, but it was saying I didn't have push rights.

**Comment by kaikreuzer** [comment]
Right, this is a known issue: https://github.com/eclipse/smarthome/issues/1662

Feel free to create a PR to add a warning to the documentation, but I'd hope to rather fix the installation for Neon.

**Comment by dmcwhinnie** [comment]
Think I figured out GitHub...

PR here: https://github.com/openhab/openhab-docs/pull/35

**Comment by kaikreuzer** [comment]
You did - thanks!
