### ISSUE TITLE
Sitemaps: "Default" item example and screenshot

### ISSUE THREAD

**Issue by chiefymuc** [openhab/openhab-docs#341]
I think this would be very helpful to understand. Took me a while to get it :)

**Comment by ThomDietrich** [comment]
On it. Will be part of #53. Thanks!

**Comment by colski** [comment]
the conf part on this page http://docs.openhab.org/tutorials/beginner/sitemap.html

seems to be a different path in the openhabian case.  .. for me it is at /etc/openhab2/sitemaps or /etc/openhab2/items respectively.

**Comment by ThomDietrich** [comment]
the exact location of "conf" depends on your installation. For Linux these are the interesting locations: http://docs.openhab.org/installation/linux.html#file-locations

This misunderstanding will be part of #189

**Comment by ThomDietrich** [comment]
Default is covered by now http://docs.openhab.org/configuration/sitemaps.html#element-type-default

The comment by @colski will be covered by #189.

Thanks!
