### ISSUE TITLE
Cloud Connector doc is not able to be browsed to from the menu

### ISSUE THREAD

**Issue by ShaunCurrier** [openhab/openhab-docs#344]
http://docs.openhab.org/addons/io/openhabcloud/readme.html

Both docs search and google search can locate the above docs URL, but this doc page is not able to be found by navigating the docs menu, making it inaccessible and nonexistent to many.

**Comment by ThomDietrich** [comment]
@watou

**Comment by ShaunCurrier** [comment]
I made some general comments on #332 [over here](https://github.com/openhab/openhab-docs/pull/332#issuecomment-282096112), giving my opinion on the question of menu structure.

But addressing this issue specifically, and regardless of what is determined in #332, couldn't the case be made that the Cloud Connector is special and perhaps deserving of elevated position in the docs which reflects its status as belonging to the OpenHAB project and being the most widely used cloud connection?  At the very least, it is not a third party offering, but is currently classified as such in the docs.

**Comment by ShaunCurrier** [comment]
Tangentially relates to my proposed improvements to Cloud-related docs in general on the [openHAB community forums](https://community.openhab.org/t/improving-openhab-cloud-related-documentation/23714).

**Comment by Confectrician** [comment]
Replaced by #1408
