### ISSUE TITLE
The instructions for changing the Karaf ssh password is incomplete

### ISSUE THREAD

**Issue by rkoshak** [openhab/openhab-docs#345]
See https://community.openhab.org/t/change-karaf-password/23576 . 

At some point after the doc was written, password encryption has enabled in Karaf (this is a good thing). However, this now means the sed command at the bottom of http://docs.openhab.org/administration/console.html is only valid if you have never logged in to the console as the openhab user before. Once you log in that nice plaintext "habopen" gets replaced with `{CRYPT}<hex formatted SHA-256 hashed password>{CRYPT}`.

I'm not real good with sed nor in a place were I can experiment right now. 

Suggest someone who is good with sed either fix the command so it works in both cases or replace the instructions to manually open the file for editing and replace "habopen" or "{CRYPT}...{CRYPT}" with the new password. Then immediately log in (to encrypt the password).

If no one runs with this, I'll come back second or third week of March when some time frees up.

**Comment by ThomDietrich** [comment]
You are absolutely right. openHABian uses the slightly more vague 
```shell
sed -i "s/openhab = .*,/openhab = $sshPassword,/g" /var/lib/openhab2/etc/users.properties
```
which workds just fine.

**Comment by ShaunCurrier** [comment]
I ran `sed -i "s/openhab = .*,/openhab = $sshPassword,/g" /var/lib/openhab2/etc/users.properties` on my system and I was able to replace the hash, but found that the hash is not regenerated upon next login with the new password.  So what is the correct procedure for changing after initial login?

[This karaf doc](https://karaf.apache.org/manual/latest/security) says it should work otherwise:  
> With encryption enabled, the password are encrypted at the first time an user logs in. The encrypted passwords are prefixed and suffixed with {CRYPT}. To re-encrypt the password, you can reset the password in clear (in etc/users.properties file), without the {CRYPT} prefix and suffix. Apache Karaf will detect that this password is in clear (because it’s not prefixed and suffixed with {CRYPT}) and encrypt it again.

**Comment by ThomDietrich** [comment]
The hash is regenerated the next time openhab ist restarted (as far as I remember)

**Comment by ShaunCurrier** [comment]
I tested this by restarting today. It proved to be true.

**Comment by ThomDietrich** [comment]
@rkoshak this should be settled. Please review the new content of http://docs.openhab.org/administration/console.html
