### ISSUE TITLE
demo.sitemap link is broken

### ISSUE THREAD

**Issue by ShaunCurrier** [openhab/openhab-docs#348]
In the following docs page, the demo.sitemap link is broken.  It 404's.
http://docs.openhab.org/configuration/sitemaps.html

The broken link on that page:
https://github.com/openhab/openhab-distro/blob/master/features/openhab-demo-resources/src/main/resources/sitemaps/demo.sitemap

**Comment by ShaunCurrier** [comment]
Looks like this is probably the preferred link these days:
https://github.com/openhab/openhab-distro/blob/master/features/distro-resources/src/main/resources/sitemaps/demo.sitemap

**Comment by ThomDietrich** [comment]
Thanks!
