### ISSUE TITLE
Astro binding description is incomplete or cut off

### ISSUE THREAD

**Issue by ShaunCurrier** [openhab/openhab-docs#354]
On this page:
http://docs.openhab.org/addons/bindings.html

`The Astro binding is used for calculating`

**Comment by watou** [comment]
The source README.md must have its description paragraph all on one line.  Please re-open the issue or submit a PR against 

https://github.com/openhab/openhab2-addons/blob/master/addons/binding/org.openhab.binding.astro/README.md

Thanks!

**Comment by ShaunCurrier** [comment]
OK will do.

I assume it's the same for netatmo's problems in the same page.

**Comment by ThomDietrich** [comment]
@ShaunCurrier I've talked about this with @watou before. Most of these READMEs need to be edited to have a clear introduction sentence. We also need to take care of Binding READMEs which begin with a list or an image. I wanted to look into this but am swamped with other projects and ideas right now. Feel free to take this on!!

**Comment by AngelosF** [comment]
Close this Issue?

This looks ok to me:
https://github.com/eclipse/smarthome/blob/master/extensions/binding/org.eclipse.smarthome.binding.astro/README.md

**Comment by Confectrician** [comment]
Yep. thanks.
