### ISSUE TITLE
Wrong command stated

### ISSUE THREAD

**Issue by Boby71** [openhab/openhab-docs#363]
Link: http://docs.openhab.org/addons/io/homekit/readme.html

It says: 
"To do this, you can issue the command smarthome homekit clearPairings from the OSGi console."
But that doesn't work, because there is a colon missing.

Correct would be: 
"To do this, you can issue the command smarthome:homekit clearPairings from the OSGi console."

**Comment by ThomDietrich** [comment]
Change submitted. Please be aware that all articles below add-ons are replicated from the various addons repositories.

Issue tickets are always welcome, if you feel confident about a change, you can also create the PR directly.
Thanks!

**Comment by Boby71** [comment]
Never thought of changing myself because I didn't want to ruin anything, but I guess there's no real risk - I'll do it next time, thanks.
