### ISSUE TITLE
Logging level documentation is outdated and factually incorrect

### ISSUE THREAD

**Issue by jeffsf** [openhab/openhab-docs#367]
http://docs.openhab.org/administration/logging.html

Improperly identifies how to change logging levels, where, and the use of the Karaf console. 

No, I'm not going to guess as to what it should be as to where and how to set logging levels. Enough of the blind leading the blind already.

**Comment by ThomDietrich** [comment]
Hey @jeffsf,
I get that incorrect documentation can be frustrating but please bare with us. What exactly are you complaining about? A command like the following does the job for just fine:
```
log:set DEBUG org.openhab.binding.zwave
```

**Comment by rtvb** [comment]
I think the documentation is quite clear. There is only one thing that is not documented properly. And that is that if you set the log level to DEFAULT that is only kept in the current session. After a restart of the openHAB service the previous log level is set. So setting to DEFAULT does not remove the entry from the configuration file. The only way to achieve this is to manually edit the configuration.

**Comment by jeffsf** [comment]
http://docs.openhab.org/administration/logging.html#config-file
does indicate that log configuration is to be done in `org.ops4j.pax.logging.cfg`

It does not indicate that changes from the console are not “sticky” across reboots. I have read that it does not somewhere in the Community or docs, but can’t find it at the moment. However, [Chris Jackson states that it _does_ persist across restarts](https://community.openhab.org/t/oh2-z-wave-refactoring-and-testing-and-security/21653/492).  Which is it? 

Completely in contrast to the above, http://docs.openhab.org/developers/development/logging.html
describes an XML-based approach and states that

>The configuration file for openHAB is placed in the openhab-distro/lauch/home/logback_debug.xml file.

There is no such file present

**Comment by ThomDietrich** [comment]
Hey @jeffsf, a short answer (I'm at work):

* Console vs. file:
http://docs.openhab.org/administration/logging.html#defining-what-to-log states:

> Note that the log levels set using the log:set commands are not persistent and will be lost upon restart. To configure those in a persistent way, the commands have to be added to the configuration file.

* "`openhab-distro/lauch/home/logback_debug.xml`" - This is openHAB 1.x information and needs to be removed. A link to the logging article should be added.

@rtvb DEFAULT is not special in the sense that logging settings via console are volatile.

**Conclusion:** To me the whole topic seems to boil down to the fact that the documentation should make relation between config file and console clearer: Runtime settings via console, persistent changes via config file.
Besides that, the base principle seems reasonable to me, do you agree?

**Comment by Confectrician** [comment]
I have checked the files history, which had many changes since this issue was last updated.
The problems described here should be solved and we should move on with #622 and check what is left to do here.
