### ISSUE TITLE
rules-ng 

### ISSUE THREAD

**Issue by halfbaked** [openhab/openhab-docs#368]
The docs concerning the  Next Generation Rules (though still useful) appear out of date. I got started using the rasberry pi openhabian image openhab 2.0.0-1, and with that version the option to include experimental repositories does not exist. It is however possible to find the experimental rules extension simply enough in the Add On section under Misc.

**Comment by ThomDietrich** [comment]
http://docs.openhab.org/configuration/rules-ng.html

Hello @halfbaked, thanks for reporting this.
@kaikreuzer besides updating the installation instructions how do we want to deal with the topic? Is new information available regarding the feature? Should we mention the [famous PR 1783](https://github.com/eclipse/smarthome/pull/1783) or [this page](https://github.com/steve-bate/openhab2-jython)?

**Comment by kaikreuzer** [comment]
I would suggest to fix the installation instructions and leave 1783 out of scope for now - if all goes well, this will be merged in a few weeks and once this feature is available, we can revisit the docs.

**Comment by ThomDietrich** [comment]
:+1: @halfbaked would you by any chance like to create a corresponding Pull Request?

* The article you want to edit is https://github.com/openhab/openhab-docs/blob/gh-pages/configuration/rules-ng.md
* You can edit the file directly on GitHub via the pen symbol to the top right
* Pay attention to our sign off requirement: https://github.com/openhab/openhab-docs/blob/gh-pages/CONTRIBUTING.md#sign-your-work

**Comment by halfbaked** [comment]
Happy to contribute... leave it with me.

**Comment by halfbaked** [comment]
https://github.com/openhab/openhab-docs/pull/370

**Comment by halfbaked** [comment]
PR accepted
