### ISSUE TITLE
XPath needs work

### ISSUE THREAD

**Issue by metbril** [openhab/openhab-docs#369]
The documentation of the XPath transformation is nearly empty so it needs some serious work. 

http://docs.openhab.org/addons/transformations/xpath/readme.html

**Comment by Confectrician** [comment]
I am not able to see the compelte history of the corresponding doc file, since it was last moved with the openHAB 2 to openHAB 3 transformation.

Additionally the given issue description does note make any indication on which i can see if this topic is still needed.
