### ISSUE TITLE
Recommendation for using SNAPSHOT over official release

### ISSUE THREAD

**Issue by wborn** [openhab/openhab-docs#376]
The documentation suggests installing a SNAPSHOT version is better because openHAB 2 is still under development. I doubt these statements still fully apply now that there is a final 2.0 release. 

See for instance:

* http://docs.openhab.org/installation/index.html#setup-variants :
```
Because openHAB 2 is still under development, it is recommended for experienced users to use the latest snapshot.
```

----

* http://docs.openhab.org/installation/macosx.html :
```
In this chapter, we have chosen to download the latest nighty build, as openHAB 2 is in a beta phase
```

**Comment by ThomDietrich** [comment]
Absolutely correct, we've missed that despite heavily updating the (maybe most important) linux article frequently.
