### ISSUE TITLE
Iconsets

### ISSUE THREAD

**Issue by halfbaked** [openhab/openhab-docs#382]
There seems to be a gap in the docs around icons and icon sets generally. In the items section we have the following:

>Icons
>OpenHAB provides you a set of basic icons by default. However if you wish to use custom icons you need to place them inside the /conf/icons/classic/ folder. These icons will be used in all of the openHAB frontends. >The images must be in .png or .svg format, and have a name with only small letters and a hyphen or underscore (if required). The PaperUI interface (or via the classicui.cfg or basicui.cfg files) allows you to define whether you use Vector (.svg) or Bitmap (.png) icon files.
>As an example, to use a custom icon called heatpump.svg the correct syntax is <heatpump>

There is enough info to muddle through, but it lacks a proper overview of how iconsets and bundles fit together. Is there only one iconset called classic? Why is it called classic and not default? A legacy reason maybe? 

Asking a user to put the custom icons in /conf/icons/classic is a little unintuitive. 

We can find a link somewhere to the section is titled icons (classic) in the Add-ons section. It's placement seems a little obscure. The filename is "readme". 
http://docs.openhab.org/addons/iconsets/classic/readme.html

I can readily imagine the reasons why the qualifier "classic" is found on a lot of the docs, and obviously there is a plan for the flexibility to swap out one iconset for another, but it is a little jarring
experience to the uninformed like myself.

If we can pull together some good info from Kai or others on the subject, I'd be happy to attempt to work it into the documentation.

**Comment by ThomDietrich** [comment]
Hello @halfbaked, I've just finished a big overhaul of the Items article and with that of the Icons chapter.
http://docs.openhab.org/configuration/items.html#icons

Could you please reevaluate your concerns? Thanks!
