### ISSUE TITLE
issue with latest image and rpi3 install..it Fails

### ISSUE THREAD

**Issue by levimadeley** [openhab/openhab-docs#387]
i downloaded openhabianpi-raspbian-20170318-git9767b24-crc9616e8a1.img.xz
flashed to sd card using etcher.
followed instructions like a good little pleb(lol)
eth connection - power - hdmi
connects and tries to download some dpkg packages - comes up with "failed"
and asks for login, so i put in default login/passwords
login ok,
and thats it. some more notes that it failed.
rebooted tried again 2 more times, including redownloading and reflashing sd.
so i edited the conf file to try wifi, 
same.. grrr.
gave up, went with netinstall which is progressing nicely atm, just thought you should know abt the problem.

**Comment by ThomDietrich** [comment]
Hello,
please discuss issues like these in the community forum openHABian thread: https://community.openhab.org/t/openhabian-hassle-free-rpi-image/13379

You should not work with the netinst image. We had a few problems in the past and will not continue it. Please retry with the raspbian based image. There are known issues with the setup, please just give it a second chance.

Closing the issue, please contact the community thread for more assistance. Thanks.
