### ISSUE TITLE
Add to the Install Docs (?) how to change the default ports

### ISSUE THREAD

**Issue by rkoshak** [openhab/openhab-docs#393]
I was trying to answer [this](https://community.openhab.org/t/how-to-change-default-port-on-mac/29842) question and realized I couldn't find this information in the docs anywhere.

I expected it to be in the installation docs and then tried the Advanced Functionality and Configuration and couldn't find them there.

I remember there used to be several ways to do it including editing the start scripts and such. But now I don't know if any of those work. I'm pointing the user to edit  `/{openhab_home}/userdata/etc/org.ops4j.pax.web.cfg` for now knowing no better way.

The "best" way needs to be documented.

I recommend in the installation instructions only because that is the first place I thought to look and that is the place the users will be when they first encounter the problem.

I'd also like to add it to the FAQ posting once I know the proper way to do it.

**Comment by BClark09** [comment]
For people using the apt-get installation, you should use the `/etc/default/openhab2` file. But for everyone else, changing the OPENHAB_HTTP_PORT and OPENHAB_HTTPS_PORT environment variables is all that is needed.

**Comment by BClark09** [comment]
Forgot to mention, this is currently described in the docs [here](http://docs.openhab.org/installation/security.html#webserver-ports)

**Comment by ThomDietrich** [comment]
Hard to say if this position can be found easily... obviously not by most. Maybe move this one section over to somewhere around http://docs.openhab.org/installation/linux.html#java-network-permissions

@BClark09 Let's do something to clear things up a bit...

**Comment by BClark09** [comment]
That'd be fine, but I guess it was put there because the statement applies across all operating systems. If it's moved to Linux, then additional instructions for each operating system need to be added.

**Comment by ThomDietrich** [comment]
Yes but currently it's phrased for Linux, doesn't make sense then.

**Comment by BClark09** [comment]
Ah, so would moving only the apt sentence be appropriate? Keeping the environment variable statement where it is, or do you think it's best to move it to each install type? If the latter then we could add a quick how to set env vars which would be a little more helpful?

**Comment by ThomDietrich** [comment]
How about a mix of your suggestions. Remove the Linux specific part; Add a hint "check the platform articles for details"; Add a section to all of these.

Did you see the linuxpkg PR?

**Comment by BClark09** [comment]
Sounds like a plan! :smiley:

**Comment by ThomDietrich** [comment]
Wonderful. Who wants to go at it? @rkoshak??

**Comment by rkoshak** [comment]
The current location of the docs (Security and Remote Access) is not an intuitive location. I'm more familiar with the docs than most and I never even thought to look there for this information. 

(As an aside, what are the thoughts on a search function, do we already have an enhancement issue?)

Now just to be clear, what we are recommending doing is:

- moving the Linux specific parts from the existing doc where it is to the Linux Install
- add a hint to check the platform install article for details to the existing doc location
- add a section to all the platform install articles with the instructions to set the environment variable or edit /etc/default/openhab2 as appropriate for that platform
- adding a sentence or two explaining how to set an environment variable for that platform
- not part of this issue but add a link to the docs to the FAQ in the forum

Correct?

**Comment by ThomDietrich** [comment]
Search function already exists :) http://docs.openhab.org/search?q=port+8080

List: sounds about right! Would be amazing if you can look into this. The [PR from before](https://github.com/openhab/openhab-linuxpkg/pull/49) should play along nicely with this.

**Comment by rkoshak** [comment]
I'm blind. `<smacks head>`

I'll get started this weekend. Shouldn't take too much assuming I can successfully figure out how to switch branches. ;-)

**Comment by ThomDietrich** [comment]
@rkoshak  as discussed in https://github.com/openhab/openhab-distro/pull/443 it would be amazing if your addition covered the newly added interface option while you are at it. Thanks!

**Comment by rkoshak** [comment]
Update, I think everything is done here except for adding the #443 info.

**Comment by Confectrician** [comment]
Then we could close this one, as there is an existing issue for the left topic?

**Comment by rkoshak** [comment]
The only problem I see is that #443 is actually on the openhab-distro repo, not this one. I don't know if that issue would be in scope for the updates here.

**Comment by Confectrician** [comment]
Ok i am confused now.
Are we talking about

#443 

or are we talking about 

 openhab/openhab-distro#443

I was looking for jsr223 stuff now but it seems the reference was just wrong.

**Comment by rkoshak** [comment]
Sorry, its openhab-distro#443. The missing part of the docs is that you can set environment variables to change the ports OH listens on.
