### ISSUE TITLE
Links to ESHD in the Migration Tutorial should point to the OH2 docs, not the ESHD Download Page

### ISSUE THREAD

**Issue by rkoshak** [openhab/openhab-docs#399]
The Migration Tutorial should reference the OH2 ESHD docs instead of going straight to the ESHD download page. This keeps our docs internally self-referential and allows us to provide additional information to the user that might be missing from the ESHD download page.

**Comment by rkoshak** [comment]
This issue is still relevant but it's a minor update. I'll try to update it later tomorrow.

**Comment by Confectrician** [comment]
We are reworking the tutorial for openHAB 3 and have removed the complete existing Tutorial.
Closing this issue therefore.
