### ISSUE TITLE
Binding menu has many duplicates

### ISSUE THREAD

**Issue by kaikreuzer** [openhab/openhab-docs#401]
The left menu comes with many duplicate entries for bindings (whenever there's a 1.x and 2.x version):

<img width="171" alt="screen shot 2017-06-16 at 23 45 53" src="https://user-images.githubusercontent.com/3244965/27245836-0ef8a7e0-52ee-11e7-8fc9-62dfd6174c9b.png">

This isn't really helpful and rather confusing (looks like a bug to the user).
I wonder if we should keep this long list at all - I would actually say no.
@ThomDietrich wdyt?

**Comment by ThomDietrich** [comment]
Looking into it.
The problem is, that we can not remove the entries completely as the articles will not have an anchor in the menu, which can be seen as a bad design. In fact we had the page without the submenu entries just a few weeks ago and users were complaining about this.
Please give me a few days to look into the page design in general. There needs to to be some fundamental changes as I already promised in #248 - I'm short in time these couple of months. I will invest one evening this weekend to look into this.

**Comment by kaikreuzer** [comment]
@ThomDietrich The more 2.x bindings are merged (latest addition: DMX) the more annoying this issue gets. I really think that the menu looks considerably broken and I would rather prefer to NOT show it than to leave it like this. Wdyt?

**Comment by ThomDietrich** [comment]
You are absolutely correct, this needs to be dealt with!

It's actually pretty easy. I did this in two minutes:

![grafik](https://user-images.githubusercontent.com/2870104/30506568-5017ee76-9a7d-11e7-86b7-a47e3e48bc58.png)

With a few more minutes I should be able to make it pretty and only show for bindings who actually have two versions. Would you be satisfied with this?

(Regarding the problem of the menu being pretty long on the smartphone. Would you agree that is an issue we can postpone till the new design is in discussion?)

Best!

**Comment by kaikreuzer** [comment]
> With a few more minutes I should be able to make it pretty and only show for bindings who actually have two versions. Would you be satisfied with this?

With the extra few more minutes (i.e. only add it where relevant), this would be ok for me yes.
Although I would actually also suggest to remove the "legacy" and "manual" ones from the menu as they are not really "official" and also do not appear in the standard selection of the main list. Wdyt?

With these improvements, all further steps can wait for the redesign, yes.

**Comment by ThomDietrich** [comment]
@kaikreuzer I've already made some progress when I realized, that the list is pretty much duplicate free after removing all "legacy" and "manual" - for which I agree to remove.

![grafik](https://user-images.githubusercontent.com/2870104/30516256-0b48ac96-9b3a-11e7-8152-4de3a8c32876.png)

After scanning the list twice, the Tellstick binding is the only duplicate left. I wonder if the 1.x binding can be moved to legacy!? With a list without duplicates we can then also discard the added version info. agreed?

**Comment by ThomDietrich** [comment]
Hey Kai,
the merge is okay but what do you think about Tellstick?

**Comment by kaikreuzer** [comment]
Yes, I guess it should be moved to legacy, this was probably only forgotten. I'll create a PR for it.

**Comment by kaikreuzer** [comment]
FTR: https://github.com/openhab/openhab1-addons/pull/5310

**Comment by ThomDietrich** [comment]
Thanks ;)
