### ISSUE TITLE
Move "Syntax highlighting for extenal editors" from openhab1-addons wiki

### ISSUE THREAD

**Issue by kubawolanin** [openhab/openhab-docs#408]
There's an article about syntax highlighting presets for various editors:
https://github.com/openhab/openhab1-addons/wiki/Syntax-Highlighting-for-external-editors

It would be worth to move it to docs + mention [openhab-vscode](https://github.com/openhab/openhab-vscode) as well ;-)

**Comment by ThomDietrich** [comment]
By all means. Let's do that.
I'm not quite sure where this content would fit best in the existing menu structure. How about next to the SmartHome Designer article: http://docs.openhab.org/installation/index.html - we could even extend this one.
The new article could be headlined "Editors", "External Editors" or something similar. Wdyt?

**Comment by Confectrician** [comment]
Agree.
I think that Editors in general should be separated from the installation Process.
They can be useful during the whole lifecycle of OpenHab so there's no reason to arrange them in the installation area.

I think configuration would be a good place.
We would have information there about how to configure things and which tools can help a user with that configuration.

**Comment by ThomDietrich** [comment]
You are absolutely right. That's how the menu structure was supposed to be organized. The SmartHome Designer is listed under installation because at that time I saw setting it up as one of the first (installation) steps before actually using openHAB.
@kubawolanin you've opened the issue. Does this also mean, that you want to work out the PR or is the task free to choose?

**Comment by kubawolanin** [comment]
@ThomDietrich I can certailny grab this one, but no sooner than in next week. 
So for anyone concerned - feel free to submit a PR, I can provide my insights later on :)

**Comment by ThomDietrich** [comment]
I'll try a quick edit today so there is a reference to your extension after the 2.1 release. No promises.

**Comment by Confectrician** [comment]
I am working on a quick n dirty import of the wiki article now.
(+ first addition of a vs code section)
Smart Home Desigenr not included atm, but thats a smaller update, when the Editors page itself is existing.

2 Questions.

Is the Navi position fine for you?
![image](https://user-images.githubusercontent.com/7161177/27932663-e631c664-629e-11e7-8fe8-0a634b1be283.png)

Can someone organize the old __currently broken__ screenshots or should i just remove them for now?
