### ISSUE TITLE
Documentation on Tags in the Items article should be more explicite

### ISSUE THREAD

**Issue by rkoshak** [openhab/openhab-docs#411]
In particular, the fact that the tag needs to be before the { }. I was only able to find this information in the ImperiHome readme.  It was not in the other binding's readmes which use tags.

**Comment by ThomDietrich** [comment]
Related to #402

**Comment by Confectrician** [comment]
Related:
http://docs.openhab.org/configuration/items.html#item-definition-and-syntax
> Items are defined in the following syntax. The parts of an Item must be defined in this order.
This is not only important for tags, it is important for all Item Syntax Elements.

I think the items article is clear enough for the syntax.
Maybe it would be better to add a hint to the Anchor above @ the Tag Docs on related Binding readmes.

**Comment by LightIsLife** [comment]
@ThomDietrich is this issue still pertinent? Seems to be captured in the docs already....let me know if I am missing anything. [Docs](http://docs.openhab.org/configuration/items.html#item-definition-and-syntax) read now:

Items are defined in the following syntax. The parts of an Item must be defined in this order. Besides the itemtype and itemname all parts are optional.

```itemtype itemname "labeltext" <iconname> (group1, group2, ...) ["tag1", "tag2", ...] {bindingconfig}```


For my this addresses the issue from OP

**Comment by ThomDietrich** [comment]
Indeed. 

I wonder if we can do anything about: http://docs.openhab.org/configuration/items.html#tagging
At the moment there is really not much more to say. I'd hope that would change soon. Till then we can close this issue if you think the chapter is acceptable for now.

**Comment by LightIsLife** [comment]
Ah, missed the special chapter.... I see..... that is confusing: it does not say a lot, the link to the Hue integration does not really help (instructions there are not very clear) and the text at the top of the items chapter is likely to be missed as there is this special tagging section. Would suggest to either delete the special section on tagging (less desirable) or re-write with something like:

Tagging is still a new feature under development. Tags are currently only used by specific I/O add-ons, for example the [Hue Emulation](http://docs.openhab.org/addons/io/hueemulation/readme.html). Tags have no functions unless a the README file of an add-on or integration explicitly discusses their usage. Tags can only be placed at one specific location in the item definition:
```itemtype itemname "labeltext" <iconname> (group1, group2, ...) ["tag1", "tag2", ...] {bindingconfig}```
Note: ```itemtype``` and ```itemname``` are mandatory, all other parts of this definition are optional.

Your thoughts? I volunteer to prepare the PR if this works

**Comment by ThomDietrich** [comment]
You've probably seen my open PR #494 regarding the Items article? I've just added a quick chapter on tagging while I was at it. Please check it out, hope you are satisfied ;)

**Comment by LightIsLife** [comment]
@ThomDietrich saw your work on the item article (and thanks much for it). 
The addition on tagging sound good, except that you may want to consider adding the full definition to #494: 

itemtype itemname "labeltext" <iconname> (group1, group2, ...) ["tag1", "tag2", ...] {bindingconfig}

Or expand your example to include all elements. The exact position of this tag has been a regularly discussed question in the forum.

**Comment by ThomDietrich** [comment]
https://github.com/openhab/openhab-docs/blob/cb0bbdacaeb40681db5978f9082296b7205b14f9/configuration/items.md#item-definition-and-syntax

DRY - do not repeat yourself ;)

**Comment by LightIsLife** [comment]
Sure, either way is fine. To use a colloquialism, there are many ways to skin a cat. My personal preference is to make more self-sustained modules, and include in a section on tags the placement too. But there are always trade-offs. It is easier to read but more difficult to maintain.

**Comment by ThomDietrich** [comment]
I don't want to put off your suggestion lightly. Let's see how it goes. If you ever feel like this detail is missing (or I), let's discuss it again!!
