### ISSUE TITLE
Restructuring styles/navigation for small screens

### ISSUE THREAD

**Issue by Confectrician** [openhab/openhab-docs#412]
While reading through the issues and especially #401 i decided to add this suggestion.

Browsing the docs in its current design on a phone is a mess, especially while reading trough a binding documentation, since the navigation stays opened.
Even if the in #401 mentioned duplicates get removed in that list it will be still very long.

Maybe it would be more comfortable to have this large Navigation in an off-canvas element
or at least collapsable.

Of course this could be conflicting with the existing off canvas element for the main navigation,
but i think that users who are browsing the _User Manual_ Area (especially on phone), dont want to switch to the Tutorial or Dev Guide.
They are looking for a specific content regarding to their current needs/work.
So in my view the side nav should have priority there on small screens.

**Comment by ThomDietrich** [comment]
Hey @Confectrician and thanks for your input. I had the same thoughts as well, sadly didn't have the time yet to do the structural changes needed. The basic structure if the page is currently not ideal, especially in light of the functionality and help of the used framework Materialize. If you have any experience with web design I'd be happy to work on this together.

**Comment by Confectrician** [comment]
Hi,

I have some kind of experience with web-design.
Nothing professional, but i worked with sass/css and ofc other web stuff several times.
Currently i am digging into jekyll since i have never worked with it, to get an impression of how the docs are build and to be able to take a look under the docs "surface".

Changing the navigation to an off-canvas menu would be no big deal, but as you mentioned already in the other issue, there are maybe structural changes coming anyway.
So i would give this topic some time, before we have to make the changes several times due to other structural edits.

For me the important thing was to write it down here first and have it marked somewhere and a place to talk about it.

Greetings
Jerome

**Comment by Confectrician** [comment]
Maybe something like this could be a first Workaround.
![image](https://user-images.githubusercontent.com/7161177/27509886-c8eb26b4-5906-11e7-8e50-995aa81028f6.png)

But as i recognized while looking at the page on mobile emulation, there are some more things that could be more comfortable on a smartphone.

This:
![image](https://user-images.githubusercontent.com/7161177/27510005-a0506884-5908-11e7-9304-e5214881e4d0.png)

is way more readable than the current style:

![image](https://user-images.githubusercontent.com/7161177/27510011-d60be67e-5908-11e7-903b-a8eecaf7d5a0.png)

There are different other things, where the view on mobile devices is not really useable,
So maybe looking at the Navigation is here the wrong way and going for a responsive mobile first design could be the better way.

Of course this is all spoken based on a documentation, that should be useable on all kinds of devices.
If the aiming is more related to Desktop Users, mobile first design has a much lower priority.
In this case i can just speak from my view, which is the one from a user that often looks up things quickly  on a mobile device.

**Comment by Confectrician** [comment]
Not valid anymore since we have switched to vuepress.
