### ISSUE TITLE
Update `Install->Windows` for 2.1.0 download links

### ISSUE THREAD

**Issue by AngelosF** [openhab/openhab-docs#419]
Update the link for 2.1.0 Stable Release
Change from:
```
https://bintray.com/openhab/mvn/download_file?file_path=org%2Fopenhab%2Fdistro%2Fopenhab%2F2.0.0%2Fopenhab-2.0.0.zip
```

To:
```
https://bintray.com/openhab/mvn/download_file?file_path=org%2Fopenhab%2Fdistro%2Fopenhab%2F2.1.0%2Fopenhab-2.1.0.zip
```

Snapshot download link is ok

**Comment by AngelosF** [comment]
Note: For now (!?) the snapshot link is ok since it still uses the 2.1.x naming (`openhab-2.1.0-SNAPSHOT.zip`)
I assume that soon (!?) this will change (to 2.2.0 ?) and we will have to update again the link for the Snapshot download.

**Comment by kaikreuzer** [comment]
Correct, by tonight we also should have a 2.2.0-SNAPSHOT available.

**Comment by kaikreuzer** [comment]
2.2.0 snapshots are now available. Created https://github.com/openhab/openhab-docs/pull/421.
