### ISSUE TITLE
Eclipse IoT Marketplace Integration Page is missing in the Side Navigation

### ISSUE THREAD

**Issue by Confectrician** [openhab/openhab-docs#424]
Hi,
 I was looking for some other things and noticed that the Eclipse IoT Marketplace Integration Page from PR #415 is missing in the Navigation.
I simply wanted to add it with a PR, but didn't know where to mention it.

The article itself is stored within the _configuration_ folder of this repo,
but maybe _addons_ would be a better playce for the .md and the navigation entry.

Wdyt?

(Rookie question aside:
Is an edit in the navigation possible by quick editing it within github in the browser?
I am not sure because of the jekyll thingy i have never worked with before^^)

**Comment by ThomDietrich** [comment]
Hey @Confectrician, good catch. You are right and this entry should be added.
The article is linked [here](http://docs.openhab.org/addons/io.html) *inside the article* and adding the menu entry at the right position is [easy](https://github.com/openhab/openhab-docs/blob/gh-pages/_includes/user-menu.html#L129-L130). Please create the PR 😉 

Regarding the rookie question: No problem there. You can change files as you wish. Every file change will be one commit. Afterwards you can open the pull request. Jekyll only comes into play after the PR was merged. Did that answer your question?

P.S. Please also fix this grammar error [here](http://docs.openhab.org/addons/io.html): "that can be browsed and installed to openHAB"
