### ISSUE TITLE
Addons: exec-binding default parameters missing

### ISSUE THREAD

**Issue by hannibal85** [openhab/openhab-docs#425]
Hey,

while migrating from openhab 1.x to 2.1 I struggled a little bit with the documentation of the exec binding.

> The command Thing requires the command to execute on the shell. **Optionally** one can specify:
>
>    a transformation to apply on the execution result,
>    an interval, in seconds, the command will be repeatedly executed,
>    a time-out, in seconds, the execution of the command will time out, and lastly,
>    a boolean parameter to make the command execute immediately every time the state of the input channel has changed.

Because I just want to use the `run` channel I skipped all the parameters ending with the exec command running every minute. 
It took me some time troubleshooting to find out that I have to specify `interval=0` to prevent the script from running every minute.

So I think it would make the documentation more clear for beginners to mention ...
... the default values that are used if a parameter isn't specified
... this special case what `interval=0` means

What do you think?

Greetings,
Sebastian

**Comment by wborn** [comment]
This issue is in the wrong repo and is addressed by https://github.com/openhab/openhab2-addons/pull/4532.

**Comment by Confectrician** [comment]
openhab/openhab2-addons#4532 got merged.
