### ISSUE TITLE
{{LatestVersion}} and {{SnapshotVersion}} variables

### ISSUE THREAD

**Issue by BClark09** [openhab/openhab-docs#430]
Perhaps added to base, or have javascript automatically calculate them, using these variables keeps things up to date quickly/automatically. Especially when using download links:

e.g:

```markdown
Download openHAB {{LatestVersion}} [here](https://bintray.com/openhab/mvn/download_file?file_path=org/openhab/distro/openhab/{{LatestVersion}}/openhab-{{LatestVersion}}.zip)
```

**Comment by BClark09** [comment]
Now that we have versioned docs, I think this can be closed also?

**Comment by ThomDietrich** [comment]
It was a good idea but yes now we have versioned docs AND try to avoid mentioning of version numbers as much as possible...
