### ISSUE TITLE
Padding lost on documentation homepage

### ISSUE THREAD

**Issue by kaikreuzer** [openhab/openhab-docs#431]
Somehow the padding got lost here, making the page look slightly broken:

![bildschirmfoto 2017-07-06 um 11 14 00](https://user-images.githubusercontent.com/3244965/27895471-30371fbe-623d-11e7-8393-1fb3d085ad0d.png)

I assume that wasn't by intention?

**Comment by Confectrician** [comment]
Maybe padding-related too:
![image](https://user-images.githubusercontent.com/7161177/27902183-1956fbd2-6235-11e7-8c75-89f36c358ffb.png)

**Comment by ThomDietrich** [comment]
Wasn't by intention, check!
I didn't see that because my screen is wider.
@Confectrician that's unrelated. This happens because of the general structure of the page.
