### ISSUE TITLE
Commandline-only openHAB server setup instruction

### ISSUE THREAD

**Issue by 130s** [openhab/openhab-docs#439]
I'm writing a script that allows install and set up openHAB server with demo addons without any interaction on web-based UI, in order to test my apps on CI where no GUI-interaction is basically available. Here being able to setup everything via commandline is very beneficial. I don't think I've run across any tutorial for doing that so far.

- If one exists, I appreciate you point me there (found a [3rd party page](https://www.engimusing.com/pages/openhab-installation-using-the-command-line) though).
- If not, I'm willing to contribute writing one. Where would be the best folder for doing so?

Btw, in #438 I'm agreeing with the idea of deprecating an old demo setup page http://docs.openhab.org/tutorials/demo.html, where there are still some info that I appreciate for the commandline-only installation purpose, including the following. These info should also be reserved somewhere.:
- link to a tarball of addons.
- description about the folders on the file system that openHAB uses.

**Comment by kaikreuzer** [comment]
Sounds like a great idea, I would be happy to see such a tutorial! And no, we currently do not have anything like that, so your help would be highly appreciated.
I'll leave the details of the how and where to @ThomDietrich, though :-)

**Comment by ThomDietrich** [comment]
I agree, a nice idea!

I wonder about the exact nature of your tutorial. If you want to specifically talk about how to set up openHAB without GUIs from a CI then it sounds like a great addition to the ["Tutorials & Examples" forum category](https://community.openhab.org/t/about-the-tutorials-examples-category/15581). 

However what would be interesting: The [Basic Tutorial](http://docs.openhab.org/tutorials/beginner/index.html) is currently not finished, contains way too many pictures and is too GUI focused for my taste. How would you feel about adding your thoughts and further improvement to this tutorial?

What do you think?
