### ISSUE TITLE
WAF (Wife Acceptance Factor)

### ISSUE THREAD

**Issue by shakerb** [openhab/openhab-docs#441]
A friendly suggestion: please drop the "WAF" in your Introduction page - "... And here is where openHAB shines: It is very stable, has apps for all different end devices, allows voice interaction, etc, so once installed, it has a very high WAF...".

A 1950's term, it smacks of gender stereotyping, and distracts from the otherwise good intro for a great product. 

Thank you.

**Comment by AngelosF** [comment]
I have to agree with you :)

I don't know where is (if there is) a repo for https://www.openhab.org/introduction.html

In docs.openhab.org the WAF term appears only in http://docs.openhab.org/addons/bindings/caldav-command1/readme.html

An issue should be raised also in https://github.com/openhab/openhab1-addons/tree/master/bundles/binding/org.openhab.binding.caldav-command

**Comment by BClark09** [comment]
I also agree!

The repo for the website is found at: [openhab/openhab.github.io](https://github.com/openhab/openhab.github.io)

**Comment by kaikreuzer** [comment]
Thanks @shakerb, I have removed that part!

**Comment by AngelosF** [comment]
just a note: I added:
https://github.com/openhab/openhab1-addons/issues/5248
&
https://github.com/openhab/openhab1-addons/pull/5249

**Comment by ThomDietrich** [comment]
Good catch. Thanks @shakerb and @AngelosF
