### ISSUE TITLE
Favicon has white background

### ISSUE THREAD

**Issue by mueller-ma** [openhab/openhab-docs#445]
and I dont know why.  openhab-docs/_iconsets/classic/icons/favicon.ico seems to have a transparent background

**Comment by ThomDietrich** [comment]
Good question, I've thought about this as well. The reason might be, that the background of a browser tab is not known to us and colors might mix poorly. Just think about this firefox addon as an example: https://addons.mozilla.org/de/firefox/addon/colorfultabs

Let's learn from others:

![grafik](https://user-images.githubusercontent.com/2870104/28246457-a5ab9916-6a1a-11e7-95f6-00e57eb049d9.png)

Seems like a few icons have white backgrounds (e.g. google, owncloud, Wikipedia) while others do not (e.g. GitHub), some icons just do not have empty space to fill (e.g. Facebook, Firefox).

Interestingly the openHAB community has a transparent icon.

I'm seeing four solutions to this: 

1. Leave as is
2. Remove the surrounding white but leave the insides
3. Remove the white background completely
4. Go with the new [android app icon](https://github.com/openhab/openhab.android/blob/master/screenshots/icon.png) (That was a surprise to me)

@kaikreuzer @BClark09

**Comment by mueller-ma** [comment]
I have the firefox dark theme and the github icon is very bad readable. IMO the android icon might not fit perfectly because of the cast shadow which is very android like.
We should wait for https://community.openhab.org/t/openhab-logo-update/31242.

**Comment by BClark09** [comment]
> I have the firefox dark theme and the github icon is very bad readable.

Also these sorts of icons (when you bookmark a page for example) get rather lost in other UIs for example in some versions of IOS, where any transparency is filled with black.

Out of the first three, two would be most appropriate although it'd probably be cleaner to just round off the four corners instead of trying to wrap round the icon.

**Comment by Confectrician** [comment]
Is this still up to date with our new logo?
If not, the issue could be closed.

**Comment by ThomDietrich** [comment]
Depends. The new logo is now once again without the white filling (option 2). Do we want to leave it like this?

**Comment by Confectrician** [comment]
My opinion:

I think in most cases the actual logo will fit fine, especially because it is some more minimalistic with thinner lines compared to the old one.
I would leave it like it is for now.

**Comment by kaikreuzer** [comment]
I created it with the transparent background, but also noticed that on dark backgrounds (and people use all different kinds of skins) it is difficult to see. So I have already updated the community forum favicon this way:

![bildschirmfoto 2017-10-26 um 10 52 06](https://user-images.githubusercontent.com/3244965/32043741-ec606c94-ba3b-11e7-82e3-92798a5ecee1.png)

I think this is better, so I would also suggest this for the docs and the webapps. I can create PRs in the next days.

**Comment by ThomDietrich** [comment]
Exactly my point and I would also go that way. Please do ;)

**Comment by mueller-ma** [comment]
Thanks @kaikreuzer

**Comment by kaikreuzer** [comment]
All done!

<img width="205" alt="screen shot 2017-10-27 at 18 09 44" src="https://user-images.githubusercontent.com/3244965/32113894-0ee00ec6-bb42-11e7-8ecf-dc80996e56b3.png">
