### ISSUE TITLE
[Proposal] Automatically deploy Tutorials & Examples to the docs

### ISSUE THREAD

**Issue by kubawolanin** [openhab/openhab-docs#448]
I've discovered that Discourse (forum engine that openHAB Community uses) has a great feature that allows you to get raw post's content 

Let's take this great on-going tutorial post on advanced HABPanel usage written by @ghys:
https://community.openhab.org/t/30755

We could easily deploy this content dynamically by taking the latest content of it from here:
https://community.openhab.org/raw/30755

Thoughts? CC: @ThomDietrich

**Comment by ThomDietrich** [comment]
Hey @kubawolanin, .... WOW!!
I never even considered this to be possible. I always thought it would be amazing to include some tutorials&examples in the openHAB docs while leaving them open for discussion (and improvement) in the community.

Some community articles are already linked here: http://docs.openhab.org/tutorials - they could easily be mirrored to the documentation articles. I'd make sure to define a template that mentions the original community author and a link to the community forum.

Including some articles could be part of #62. I wanted to look into this soon and could include one two postings for testing purposes.

**Comment by ThomDietrich** [comment]
Side note: In case you didn't know, Discourse threads can be configured as "wiki threads" , making the first posting writable by all users. That could be something we could start opening up for some tutorials to allow easy contributions.

**Comment by ghys** [comment]
> Discourse threads can be configured as "wiki threads"

I think it's a great feature, I've made the post referenced above by @kubawolanin a Wiki thread as I like the idea of it being a "working document" - easily editable when anyone just thought about something to add, spots an error or feels like adding a new chapter.

**Comment by kubawolanin** [comment]
> The list behind the link above already lists a few nice examples. Is this list in line with what you'd think is a good selection?

Absolutely! [This page](http://docs.openhab.org/tutorials/) is the best place for that kind of content. 
I'm now thinking of dynamically fetching list of compelling tutorials dynamically for it.
We could perhaps replace `Here are just a selected few of the existing tutorials and examples` with a dynamic list generated from here:
https://community.openhab.org/c/tutorials-examples.json

(I recommend you a Chrome extension called [JSONView](https://chrome.google.com/webstore/detail/jsonview/chklaanhfefbnpoihckbnefhakgolnmc) that formats the json files for your convenience ;-))

**Comment by Confectrician** [comment]
That would be a great improvement to the static docs page.

Maybe something like the "Top 10 trending tutorials" or sth like that would be also really nice.
So a visitor would be able to see the variety of usescases and solutions.

**Comment by BClark09** [comment]
>dynamic list generated

>I recommend you a Chrome extension called JSONView

>Thoughts?

"You da real MVP" ;)

**Comment by ThomDietrich** [comment]
I don't know what the fuzz is all about. Firefox/Palemoon has a JSON viewer builtin 😃 

![grafik](https://user-images.githubusercontent.com/2870104/28494320-0756c93c-6f2b-11e7-960b-28514270803f.png)

Back to the topic: I'm not so sure about the "Top 10 trending tutorials". The list should be a meaningfully ordered list of selected tutorials. The json and the raw view of a thread will still be useful for that. But before we drift off into detailed discussions: I'll look into a first implementation of this feature, then we can look into additional cleverness 😉 Deal?

**Comment by Confectrician** [comment]
> I'm not so sure about the "Top 10 trending tutorials". In my opinion the list should be a meaningfully ordered list of selected/promotional tutorials.

I thought about this as an **additional** thing, that would be interesting maybe.
But you are right, thats not a topic for this issue. :)

**Comment by Confectrician** [comment]
Hey @ghys,

from my understanding this issue is already covered through our showcase section.
Wdyt? Should we close this one?
