### ISSUE TITLE
JSR233 Docs references contradictory paths

### ISSUE THREAD

**Issue by rkoshak** [openhab/openhab-docs#449]
>Scripts should be placed in the ‘USERDATA/automation/jsr223’ directory. For example, in Linux installations created with a package installer, the directory would be /etc/openhab2/automation/jsr223.

That is the conf folder, not the USERDATA folder. So either the USERDATA needs to be changed to CONF or the path should be changed to /var/lib/openhab2/automation/jsr233.

I do not know which is correct or I'd just make the change myself.

**Comment by kaikreuzer** [comment]
It must be CONF, not USERDATA!

**Comment by ThomDietrich** [comment]
Actually it should be `$OPENHAB_CONF` 😃 

* Proposal: #189 
* Truth: https://github.com/openhab/openhab-linuxpkg/blob/master/resources/etc/profile.d/openhab2.sh

Would you please update your PR?

**Comment by Confectrician** [comment]
Should be solved with the many edits placed on the files history.
