### ISSUE TITLE
Recommendation of Zulu

### ISSUE THREAD

**Issue by BClark09** [openhab/openhab-docs#451]
The [main installation page](http://docs.openhab.org/installation/index.html#prerequisites) mentions that Zulu's only disadvantage is that it's not available as a package for most systems default repos, but it's very simple to install in each:

 - [Deb based linux](http://zulu.org/zuludocs-folder/Content/ZuluInstallationGuide/PrepareZuluPlatform/AttachAPTRepositoryUbuntuOrDebianSys.htm)
 - [RPM based linux](http://zulu.org/zuludocs-folder/Content/ZuluInstallationGuide/PrepareZuluPlatform/AttachYumRepositoryRHEL-SLES-OracleLinuxSys.htm)
 - [Windows](http://zulu.org/zuludocs-folder/Content/ZuluInstallationGuide/InstallingZulu/InstallationWindowsUsingZuluMSIFile.htm)
 - Mac [GUI](http://zulu.org/zuludocs-folder/Content/ZuluInstallationGuide/InstallingZulu/InstallOnMacOSXUsingDMGPkgThroughGUI.htm) or [CLI](http://zulu.org/zuludocs-folder/Content/ZuluInstallationGuide/InstallingZulu/InstallOMacOSXUsingDMGPkgThroughCLI.htm)

Should we update the docs to use Zulu? Particularly for Linux, should we start detailing the instructions of Zulu instead of Webupd8's openjdk?

**Comment by ThomDietrich** [comment]
The main installation page already states 

> Zulu is currently the recommended Java platform for openHAB

but I'd say yes to changing the disadvantages section and to update the linux article. In the Linux article we could just link the official Zulu instructions. We don't need to duplicate content from another source unrelated to openHAB. Wdyt?

**Comment by BClark09** [comment]
> We don't need to duplicate content from another source unrelated to openHAB.

Absolutely, I can do that but probably during the weekend. Could you assign this issue to me please?
