### ISSUE TITLE
Documentation Correction

### ISSUE THREAD

**Issue by cygtoad** [openhab/openhab-docs#456]
Greetings,

At this URL:  http://docs.openhab.org/administration/index.html

is the following text:
________________________________
Contributions Wanted

Help improve the openHAB 2 documentation! If you'd like to leave corrections, additons or comments for this article or any other part of this website, please drop a word at:
________________________________

The word additions is spelled incorrectly.  It's nit picky, but hey, you asked.

Cygtoad

**Comment by ThomDietrich** [comment]
:rofl: that's like a meta contribution helping others to contribute

Thanks! I'll correct it.
