### ISSUE TITLE
Onkyo Binding Documentation Suggested Edits

### ISSUE THREAD

**Issue by cygtoad** [openhab/openhab-docs#462]
I am an OpenHab newbie, but I work in IT and have a degree in writing, so I wanted to contribute a little to the documentation.
I was able to get my Onkyo reciever to work with Openhab, well mostly, with the documentation located here: http://docs.openhab.org/addons/bindings/onkyo/readme.html

Generally it is well written, but here are some suggested edits:
_________
Edit 1:
In the Thing Configuration section of the documentation all of the code sniplets refer to the Thing ID as: myOnkyo.  

onkyo:onkyoAVR:myOnkyo [ipAddress="192.168.1.100", port=60128]

There is an unexplained disconnect between the Thing ID called out later in the code for demo.items and demo.sitemap where the Thing ID is defined as: avr1

As a newbie I expected to be able to paste it all into the expected text files, change the IP address and have it work, but it doesn't.  Anywhere it appears;

onkyo:onkyoAVR:myOnkyo
should be changed to: 
onkyo:onkyoAVR:avr1

Add a line that explains: "In the code avr1 refers to the user defined unique id of your Onkyo device.  A second device could be called avr2."
_________

Edit 2:
When cutting and pasting the code in the demo.sitemap section, I found there are some carriage returns which prevent the file from working.  I didn't discover these until I used the Ellipse designer and it called one of them out.
Those carriage returns are located between lines: 6&7, 14&15, 29&30.

_________

Edit 3:
This one, I am still struggling with.  In the bindings configuration section there is a reference to a parameter for a CallBack URL.  Generally I know what a callback URL in web development is, but the documentation is vague on what functionality the Callback URL provides and what URL should be plugged in here.  Is it the URL of the Openhab install?  Is it the URL of the Onkyo receiver?  What the heck is it supposed to do? 

I hope these edits help.

Matt

**Comment by ThomDietrich** [comment]
Hello @cygtoad ,
thanks for your help. I'll add these improvements soon!

**Comment by Confectrician** [comment]
Hey @ThomDietrich,

I looked through the issues and found this one.
As i had time and motivation, i jumped in an added a quick fix PR.

I did nothing for topic 3, since i don't have enough knowledge of the callback functionality in this specific case.
Maybe we can add that later or leave it as it is written in the readmes table already.

**Comment by ThomDietrich** [comment]
Hey guys!
First off, sorry @cygtoad for ignoring the issue for too long. My time is limited right now. Thanks @Confectrician. I'll check the PR to see if I can help with topic 3 next.

@cygtoad you mentioned you'd like to continue help improve the documentation. Are you still interested and if so, please let us know how you imagine that could look like. It is always an easy option to find a binding with a horrible documentation to work on. There are also some core articles you could help with, with both wording or technical details.

Best! Thomas

**Comment by Confectrician** [comment]
I have adressed 2 of the 3 given topics in a now merged PR ( openhab/openhab2-addons#2860 ) and opened a new issue for the outstanding topic in the openhab2-addons repo.
See: openhab/openhab2-addons#2925

Since all topics are resolved or moved t the correct repo, i will close this issue now.
