### ISSUE TITLE
openhab-docs gitter chat room

### ISSUE THREAD

**Issue by ThomDietrich** [openhab/openhab-docs#474]
The gitter chat is for openHAB documentation improvement discussion ONLY.
If you are looking for help with openHAB or for guidance with a problem (also because of documentation gaps) please contact the openHAB community forum: https://community.openhab.org

The issue tracker is still the number one place for improvement coordination. If you found an error in documentation or room for improvement, please file an issue ticket or a pull request. Thanks ;)

@svilenvul @LightIsLife @Confectrician @bgilmer77 @ghys @whopperg @AngelosF @cniweb @BClark09 @sihui62 @halfbaked @ShaunCurrier @stephenbonar @kubawolanin @mueller-ma @jeffsf @bdleedy @metbril @paulianttila @DrPepper124 @lolodomo @MHerbst 
You are some of the contributors of the last couple of months. If you wish to join the chat (no obligations attached) please follow this link: https://gitter.im/openhab/openhab-docs
I did most probably forget to mention someone. Whoever is interested to join, go for it.

**Comment by BClark09** [comment]
You would prefer slack to gitter then?

**Comment by ThomDietrich** [comment]
No preference. I'm already using slack for three teams but gitter is also fine. Which would the others prefer?
(For whom doesn't know it: Gitter offers better integration with a repo, we could e.g. reference issue tickets and PRs directly)

**Comment by bgilmer77** [comment]
@ThomDietrich can we close this?

**Comment by mueller-ma** [comment]
I read some days ago an article about github introducing chat rooms. Maybe better than gitter

**Comment by ThomDietrich** [comment]
@mueller-ma I also read about that and am interested to check it out. I'll open a chatroom and close the issue :)
