### ISSUE TITLE
Redirect all pages from http to https

### ISSUE THREAD

**Issue by MHerbst** [openhab/openhab-docs#477]
We were informed by Google that the website will be marked as "unsafe" in the near future. 
Therefore we should redirect all pages to their https equivalents.

BTW: also the canonical links should use https instead of http:
```
<link rel="canonical" href="http://docs.openhab.org/" />
```

This is orignal message (in German):

> **Chrome blendet unter http://docs.openhab.org Sicherheitswarnungen ein**
> 
> An den Inhaber von http://docs.openhab.org,
> 
> ab Oktober 2017 erscheint in Chrome (Version 62) die Warnung "NICHT SICHER", wenn Nutzer auf einer HTTP-Seite Text in ein Formular eingeben oder eine HTTP-Seite im Inkognitomodus besuchen.
> 
> Unter den folgenden URLs auf Ihrer Website befinden sich Texteingabefelder wie < input type="text" > oder < input type="email" >. Diese lösen die neue Chrome-Warnung aus. Anhand der Beispiele sehen Sie, wo die Warnungen angezeigt werden, und können so entsprechende Maßnahmen zum Schutz der Nutzerdaten ergreifen. Diese Liste ist nicht vollständig.

**Comment by bgilmer77** [comment]
FWIW, redirecting from http to https is only part of the solution.  You have to have a valid certificate on the https server or the client will get all sorts of warnings.  Google won't be happy either.

I have experience using [letsencrypt.org](https://www.letsencrypt.org), a free and open project sponsored by the LINUX Foundation, on Debian systems.  If it would be appropriate, I could write an article on how to get free certificates and how to install certbot on an openHAB system, if that would be useful.  Please advise if doing something other than writing an article would be the best way to address this issue.  I am still learning about the best way to make contributions to openHAB.

**Comment by ThomDietrich** [comment]
@bgilmer77 that's a great idea... sadly already addressed in two ways:

* http://docs.openhab.org/installation/security.html#nginx-letsencrypt
* http://docs.openhab.org/installation/openhabian.html#features

**Comment by bgilmer77** [comment]
Understood.  And not sad at all - glad there is good coverage already in the documentation.

**Comment by Confectrician** [comment]
While browsing through the issues i checked random docs articles and all seem to work with https.
Seems we have a valid ssl certificate for the docs subdomain.

Are there any arguments against redirecting the docs from http to https?

**Comment by bgilmer77** [comment]
If there are no technical blockers, I would strongly encourage us to move to https for everything about the documentation.

**Comment by Confectrician** [comment]
Felle free to test to yourself.
Every page i have choosen, worked fine.

The only thing that would interest me, is if this is a github pages ssl certificate (see [here](https://github.com/blog/2186-https-for-github-pages)) or one, that has been set up by the foundation for our domain.

**Comment by ThomDietrich** [comment]
It's a certificate created for "sni166795.cloudflaressl.com" with "*.openhab.org" as one of many SAN entries.

Yes we can activate the redirect. Does anyone know the easiest method for that? Normally I'd define a webserver side rewrite but that's not possible.

**Comment by Confectrician** [comment]
seems that it isn't that easy with a custom domain.
https://www.jonathan-petitcolas.com/2017/01/13/using-https-with-custom-domain-name-on-github-pages.html

Don't know if we would fit into the fre cloudflare pricing model.

**Comment by kaikreuzer** [comment]
I don't really understand the issue - when I enter the documentation through https://docs.openhab.org/, all subsequent pages are automatically called with https.
So I assume that we only have to adapt all external links to directly use https?

**Comment by Confectrician** [comment]
This will solve the issue for many cases of course, but if you enter `docs.openhab.org` directly through the browsers adress bar, it will not get redirected.
I think i am not the only one who is using the docs frequently and doesn't enter them without a link.

I don't know where the domain is hosted, but maybe the domain provider has a setting which redirects automatically to https.

**Comment by ThomDietrich** [comment]
I'd agree with @Confectrician. Normally you'd define some webserver settings for this kind of stuff. In our case there seems to be a nice alternative:

https://gist.github.com/konklone/9968713#gistcomment-1600385

**Comment by kaikreuzer** [comment]
Ok, adding a piece of javascript to always do the redirect of course makes sense.
My "don't understand" was rather referring to any certificate discussion - imho there is no action required.

**Comment by ThomDietrich** [comment]
I'm creating a PR as we speak

**Comment by ThomDietrich** [comment]
Everyone,
I've just merged the first PR wrt this issue and it seems to work quite well. All pages below http://docs.openhab.org/developers are redirecting your browser to https.

I'll give this a few days to be tested, then create the PR to effect all pages. Please test!

**Comment by bgilmer77** [comment]
@ThomDietrich I just clicked through all of the left-hand menu items using both Firefox and Safari in their most current versions and all of the links were delivered using https.

**Comment by kaikreuzer** [comment]
Works well for me, too 👍
