### ISSUE TITLE
Add notification actions to documentation

### ISSUE THREAD

**Issue by metbril** [openhab/openhab-docs#479]
The documentation is currently missing proper documentation for sending notifications from rules through the official openHAB mobile apps. At least, I have not been able to find it.

The wiki used to have it listed here: https://github.com/openhab/openhab1-addons/wiki/Actions but that page https://my.openhab.org/docs/notifications is now 404.

- `sendNotification(<user>, <message>)`
- `sendBroadcastNotification(<message>)`
- `sendLogNotification(<message>)`

I am not sure where it should be, since it is only valid when using the openHAB Cloud instance from the Foundation.

Possible pages to add to:

http://docs.openhab.org/addons/io/openhabcloud/readme.html
http://docs.openhab.org/addons/actions.html

**Comment by ThomDietrich** [comment]
@maziman wdyt?

**Comment by Confectrician** [comment]
> since it is only valid when using the openHAB Cloud instance from the Foundation

In this case i would prefer:
http://docs.openhab.org/addons/io/openhabcloud/readme.html

**Comment by metbril** [comment]
_Sorry for not responding sooner, but my github notifications are not working, I am not getting any email from them._

Would you accept a PR for that page? I am happy to contribute.

**Comment by marziman** [comment]
I am not completely sure if OH cloud is the right place. Just because OH cloud is in the chain, it doesnt need to be the "right place".
Can you explain shortly would you have in mind?

Thanks alot
BR Mehmet

**Comment by marziman** [comment]
But: Of course your effort is important and we will find a home for it!
Thanks for your support..

**Comment by metbril** [comment]
My intention is to add sufficient documentation for using above **actions** in rules e.g.

```
rule "Demo"
when
    Item Demo_Item received command
then
    sendBroadcastNotification('Demo item received command ' + Demo_Item.state.toString)
end
```

This documentation used to be available through the old wiki and the my.openhab.org site (which is offline now).

My first guess would be to add it to the actions page (like the mail action) and if needed refer and link to the openHAB Cloud.

**Comment by ThomDietrich** [comment]
That indeed sounds like a good plan and would fit nicely in this list http://docs.openhab.org/addons/actions.html

Only problem we need to solve: The list in the second half of the page is automatically generated from all `README.md`'s found here: https://github.com/openhab/openhab1-addons/tree/master/bundles/action

**Comment by Confectrician** [comment]
> My first guess would be to add it to the actions page (like the mail action) and if needed refer and link to the openHAB Cloud.

Big +1, this is a proper way to keep articles clean and focused on their topic.

**Comment by metbril** [comment]
The source for http://docs.openhab.org/addons/actions.html is https://github.com/openhab/openhab-docs/blob/gh-pages/addons/actions.md. 

The page consists of Core actions (fixed text) and Installable actions (generated). In which section should we include the notifications?

**Comment by Confectrician** [comment]
To get the activity back here:

I would suggest to add a short `Notification Actions` section somewhere before the `Installable Actions`

**Comment by ThomDietrich** [comment]
Hey @Confectrician,
thanks for triggering he issue.
Yes. Let's put it e.g. before "HTTP Actions"? Are you going to work on it?

**Comment by Confectrician** [comment]
From what i read in the first post @metbril wanted to do something and just didn't know the right place.
I would say we wait some time and see if he answers this issue again.

Otherwise, i will assign that issue to me.

**Comment by ThomDietrich** [comment]
Hey guys, we are going to promote this part of the documentation soon, see: https://github.com/openhab/openhab.android/pull/509

Anyone able to submit a PR in the next couple of days?

**Comment by Confectrician** [comment]
PR incoming this Week. :+1:

**Comment by Confectrician** [comment]
Ok its not that easy, since i cant get it to work right now for my installation.

**Comment by bgilmer77** [comment]
I have notifications working on my installation through myopenhab.  @Confectrician do you want to do the PR, or would you like me to put something up there to shoot at?

@ThomDietrich BTW, I am also using Prowl.  There are a number of notification add-ons available.  I guess you only want to address notification through myopenhab?

**Comment by Confectrician** [comment]
Please do the PR @bgilmer77.

Maybe i will get mine to work, when documentation is there. 😄

**Comment by bgilmer77** [comment]
Okay - I will work on this tomorrow.

@Confectrician , one quick thing since I have you here - @ThomDietrich was wanting to do some clean up before the new release.  I have some time this week and could dig into this.  Was the assignment to go through the add-ons and 'de-lint' as many of them as we can with one PR per add-on?  I never got conformation of this and don't want to start into this without knowing that this was the assignment.

**Comment by Confectrician** [comment]
There was no real conclusion.

-> Please have a look at the related TeamDiscussion.
I will bump it now.

**Comment by bgilmer77** [comment]
@metbril I have created the PR #587.  Does this address your issue?  There is additional information on the wiki that I did not put into this PR.  Let me know if you think we need more here or if the references to documentation elsewhere is sufficient.

**Comment by ThomDietrich** [comment]
@bgilmer77 Prowl is in the list below, here: http://docs.openhab.org/addons/actions.html#installable-actions
Not sure what you meant when mentioning it.

@Confectrician Hahaha touché

> Maybe i will get mine to work, when documentation is there. 😄

**Comment by bgilmer77** [comment]
@ThomDietrich My question was about whether you want to stay completely focused on just OH Cloud notifications.  That was my assumption when I wrote the PR.  At this point, don't worry about my mention of Prowl above.

**Comment by ThomDietrich** [comment]
Yes :) Okay

**Comment by mueller-ma** [comment]
Currently the docs are not mentioning the possibility to send icon and severity: `sendNotification("Message", "switch", "high")` sends a notification with the icon `switch` and the severity `high`.
Icon and severity are shown in the notification list in the Android App and will be shown in the notification when https://github.com/openhab/openhab-cloud/pull/175 is merged. The severity will be used as notification channel on Android 8+ devices.

**Comment by Confectrician** [comment]
> Edit: The Android app features are not available in the stable version yet.

That's no problem. Docs are always on snapshot state in default, so we can add this information already.

**Comment by Confectrician** [comment]
Des sendNotification need 4 parameters then?
Seems the email adress for the destination is missing in your comment.

**Comment by mueller-ma** [comment]
Sry, my example is wrong. Yes, it takes four parameters and the email must be the first one. Broadcasts take 3 arguments: `sendBroadcastNotification("broadcast", "switch", "high")`.

**Comment by Confectrician** [comment]
Another question:
is it possible to leave the icon or severity out? 

What was the correct way to write the notification command then?

`sendNotification("mail", "Message", "high")`
`sendNotification("mail", "Message", "switch")`

I just wanted to start with adding something, but if there are many different possibilities now, we may rewrite the whole section instead of just adding examples over examples.

**Comment by maniac103** [comment]
@Confectrician Not sure whether you figured it out in the meantime already, but the complete list of variants is:
- sendNotification(String userId, String message)
- sendNotification(String userId, String message, String icon, String severity)
- sendLogNotification(String message)
- sendLogNotification(String message, String icon, String severity)
- sendBroadcastNotification(String message)
- sendBroadcastNotification(String message, String icon, String severity)

The former variants (without icon & severity) just call the latter variants, passing null as icon and severity.

**Comment by Confectrician** [comment]
Thanks for sharing this @maniac103.

May i encourage you to help us with a Pull Request for this?
I am a bit busy with vscode currently, but can help of course if there are any questions regarding the contribution process. :slightly_smiling_face:

**Comment by maniac103** [comment]
Sure, I'll make a PR.

**Comment by maniac103** [comment]
Done: https://github.com/openhab/openhab-docs/pull/824

**Comment by mueller-ma** [comment]
@metbril @Confectrician The PR by @maniac103 has been merged, so this issue can be closed.

**Comment by Confectrician** [comment]
Thanks @mueller-ma

**Comment by kevin71246** [comment]
What are the possible severity string values for Android? 
https://www.openhab.org/docs/configuration/actions.html indicates:
severity: String containing a description of the severity of the incident

Also, having an icon & clarification on what's accepted would be nice.  Like only the openhab icons, or an uploadable png or whatever?  Whats the format?

Thanks!

**Comment by mueller-ma** [comment]
> Like only the openhab icons

Only openHAB icons. With openHAB 2.5 the server chooses the format for you. If you have an icon in both png and svg, the svg icon is taken.

> What are the possible severity string values for Android?

Any string can be used as severity. The app creates [notification channels](https://medium.com/exploring-android/exploring-android-o-notification-channels-94cd274f604c) based on the severity.
