### ISSUE TITLE
Add menu entry for dashboard, copy external article

### ISSUE THREAD

**Issue by ThomDietrich** [openhab/openhab-docs#480]
An article on the dashboard was provided by @paulianttila with PR https://github.com/openhab/openhab-core/pull/185/files

A menu entry could be added alongside the "Configuration - Initial Setup" page. The dashboard is not really related to "Configuration", neither are some of the other menu entries. Maybe another top level entry is needed...

Related to #62

**Comment by ThomDietrich** [comment]
https://github.com/openhab/openhab-core/blob/master/bundles/org.openhab.ui.dashboard/README.md

@kaikreuzer The document is rather technical. Do we need it on docs.openhab.org?

**Comment by kaikreuzer** [comment]
I wouldn't say that we need exactly this document, if you think it is too technical.

But the feature in itself is something that many users asked for and which I think is pretty useful - so yes, it should be covered by docs.openhab.org.

Btw, would also make sense to use this to e.g. add a tile for FrontTail in openHABian.

**Comment by ThomDietrich** [comment]
You are right of course, we need some part of the documentation introducing the dashboard. Be it this single article or as a part of another article. After some reconsideration: I guess the README with a bit of added introductional yada yada would be acceptable 👍 

I saw the two examples and thought the same thing (frontail and nodered, both are provided by openHABian). So far openHABian is not touching openHAB itself, I'm hesitant to start with it now.
Regarding frontail: It was a spontaneous and fun idea at first but got quite famous over the last couple of months. Do you see any chance it making it's way to be an installable UI?

**Comment by kaikreuzer** [comment]
> Do you see any chance it making it's way to be an installable UI?

Is it in Java and packable as an OSGi bundle? If so, why not.

**Comment by ThomDietrich** [comment]
Nope far from it. That's why I'm doubting it. Frontail is powered by Nodejs and a few dependencies.

**Comment by kaikreuzer** [comment]
That's what I thought, so forget about it...

**Comment by ThomDietrich** [comment]
Okay topic settled, I've opened Issue https://github.com/openhab/openhabian/issues/212 for it.

Back to the issue, I'll add the README to #516
