### ISSUE TITLE
Skeleton readme outdated?

### ISSUE THREAD

**Issue by cweitkamp** [openhab/openhab-docs#482]
Referring openhab/openhab2-addons#2552

@maintainers Please assign me to this one.

> It appears the doc/readme on generating an OH2 skeleton is outdated.
> 
> It currently states claims only a single parameter is needed, when 2 are actually required:
> 
> For this, go into your git repository under git/openhab2-addons/addons/binding and call the script create_openhab_binding_skeleton.sh with a single parameter, which is your binding name in camel case (e.g. ‘ACMEProduct’ or ‘SomeSystem’)
> 
> Usage: create_openhab_binding_skeleton BindingIdInCamelCase BindingIdInLowerCase

**Comment by ThomDietrich** [comment]
Okidoki 👍
