### ISSUE TITLE
The Mobile Version of the Docs Site Is Broken

### ISSUE THREAD

**Issue by rkoshak** [openhab/openhab-docs#487]
I do a lot of my support work on the forums from my phone. Here are my observations for what needs to be fixed for the mobile version that gets sent to phones and tablets. Screenshots are not working on my phone right now (no idea why) but I'll post some as soon as I figure that out.

Posting this issue to capture the problems. Most of these are structural and I've no idea how to fix them.

I'm using Chrome on Android.

- Hamburger menu at upper left doesn't work. I can click on it and get the list of links but it comes over grayed out and I cannot click on any of the links. For example, if I want to go to the tutorials, I have to scroll down to the big Tutorials icon on the main page. The upper left menu is broken.

- There is no Search function anywhere. On the main web site, it appears to be a part of the header. But since the header is different for the mobile version it gets lost.

- On mobile, the left-hand menu from the main page with the over all TOC shows up at the top of the page. Without a search function, this means one must tap Add-ons, tap Bindings, scroll down through the list of 200+ bindings to find the one you want and tap on it. Then you have to scroll past ALL of that list of 200+ bindings again to get to the actual text of the binding's readme. The binding's actual readme often ends up taking up only the bottom 25% of the entire page that gets returned.

These are the big annoyances right now.

**Comment by ThomDietrich** [comment]
Heyho, I/we are aware of that. Without wanting to go into detail right now, all of this will be dealt with soon... You can expect more details in 2-3 weeks. Thanks for the list!

**Comment by rkoshak** [comment]
I figured it was, just didn't see an Issue for it. Glad it's being worked. Is there an Issue open that I missed? If so we can close this one and point at that one.

**Comment by Confectrician** [comment]
> Is there an Issue open that I missed?

Not directly.

Here are some (minimal) related ones:
#431 #412 

There were some discussions on how to improve the mobile look in general and rework the complete styles on long term.
Maybe that's why there have been no quick fixes yet.

**Comment by ThomDietrich** [comment]
> Maybe that's why there have been no quick fixes yet.

Exactly. I had a discussion with Kai recently and in response to that I'll propose something soon. Don't want to say anything prematurely, so please give me a few days to order my thoughts, then I hope to start an active discussion ;)

**Comment by rkoshak** [comment]
Cool. Feel free to close this issue if it makes sense. It looks like everything is well in hand and covered.

**Comment by ghys** [comment]
I was a little frustrated by this for some time so I decided to take a look and ended up with #639.
I only saw this discussion before committing.
Even if something else is in the works, hoping it can be merged :) - it does the job in the meantime and it's a relatively small fix!
