### ISSUE TITLE
Sitemaps: Add MapView Sitemap element

### ISSUE THREAD

**Issue by ThomDietrich** [openhab/openhab-docs#492]
(Derived from https://github.com/openhab/openhab-docs/issues/53)

All details needed can be found in this diff: https://github.com/eclipse/smarthome/pull/277/files#diff-10aa8fe84e9119cfe8cac6ea022ff706

The probably most time consuming task here is probably to create a screenshot :)

**Comment by ThomDietrich** [comment]
Addition: While on it, please create all mismatching images (e.g. the temperature Text element should read 21.5°C)

**Comment by Confectrician** [comment]
@ThomDietrich 

I have read your comment above 3 times now and i simply don't get it.
Could you explain this for me again?

Does ist simply mean that all screenshots should be based on the same sitemap and the same current values?

**Comment by ThomDietrich** [comment]
Hey @Confectrician,
yes I should have made myself more clear :) The sitemap used to create the screenshots is part of the sitemaps article. It is appended at the end of the article as a comment (It ain't stupid if it works 😄). See: https://github.com/openhab/openhab-docs/blame/gh-pages/configuration/sitemaps.md#L653

Regarding the temperature: As you'll see, the temperature is hardcoded with "21.3 °C". However, [later on](http://docs.openhab.org/configuration/sitemaps.html#element-type-setpoint) I used the temperature item to show an example for the setpoint sitemap element. The example uses a step resolution of 0.5 degree, which is meaningful but one might wonder how 21.3°C can be achieved with such an element. Long story short: If we change the screenshot to show 21.5°C, the problem will not come to mind.

**Comment by Confectrician** [comment]
You can assign me.
PR is nearly incoming^^

I would suggest to edit all temperature related screenshots too, to keep a common thread during the complete article.


Additionally:
Is there a reason for sorting the element types in an alphabetical order within the table and not sorting it in the later content?!

Should i just append the MapView as last element type?
