### ISSUE TITLE
Mycroft skill

### ISSUE THREAD

**Issue by mortommy** [openhab/openhab-docs#495]
An openHAB [Mycroft](https://mycroft.ai/) skill is available:
https://community.openhab.org/t/mycroft-openhab-skill/33475
Should be integrated in the [System Integration](http://docs.openhab.org/addons/io.html) page?
Thank you.

**Comment by ThomDietrich** [comment]
Definitely! I have no experience with Mycroft but it's great you've added openHAB support for it! Let's add it to the official documentation

We can start without further hesitation. In fact a pretty similar work is currently done for the Amazon Alexa skill. See for some details: https://github.com/openhab/openhab-docs/issues/481

Here's a quote that also fits here:

> The openHAB project is heavily distributed among dozens of project repos. That is a good thing. Each project is part of openHAB but self-contained for one specific topic, e.g. to host all code related to the openhab-alexa skill. if changes to the skill and its features are planned, the repo should be the one and only place these changes need to be applied. Therefore the README/USAGE document should reside there as well ;)

That means: Ideally you'd provide a `README.md` ore separate `USAGE.md` dedicated to the end user in your repository and we will copy it over to the documentation page on a regular basis (script based). This way you are in charge to (and easy able to) update the document.

If you agree, I'd suggest you open a Pull Request against your own Repo and link it here. This way you are giving all of us a chance to join the review and improvement process, similar to the [alexa skill PR](https://github.com/openhab/openhab-alexa/pull/44).

What do you think?

**Comment by mortommy** [comment]
ok, thank you.
So first of all I'll create the usage.md file, using as example the one already available for Alexa.

**Comment by kaikreuzer** [comment]
@ThomDietrich As you know, I am against using the official documentation as a kind of wiki that links to external stuff that is not under control of the community - the system integration page currently only list stuff that is also available under the openHAB github organisation.

@mortommy Please don't take that comment negatively - your mycroft skill sounds awesome and it really is a great addition to openHAB, which I would love to see listed. So my question would rather be: Would you be ok with moving the skill to the openHAB github organisation and you being the official maintainer of it? This would make it an "official" part and make sure that the community can collaborate on it. Please let me know, what you think!

**Comment by mortommy** [comment]
Hi @kaikreuzer ,
for me it is ok, I'm glad to have the project in openHAB github, it gives the opportunity to my work to grows up with the community contribution.

**Comment by kaikreuzer** [comment]
Cool, I have created https://github.com/mortommy/mycroft-skill-openhab/issues/12 for the further steps!

**Comment by kaikreuzer** [comment]
@mortommy FYI: Something went wrong with your initial commit to https://github.com/openhab/openhab-mycroft - it had all the old history including merge commits in it. I just cleaned it up, so please pull the current version from the repo. To additional notes:
1. The "github_handle" in the commit message is meant as a placeholder to put in your handle.
2. Please make sure to always add a message to your commit that explains what it is about - this makes it much much easier later to find why and when some change been done.
Thanks! And now it is time to add it to the official docs :-)

**Comment by ThomDietrich** [comment]
Hey @kaikreuzer,
I had the organization idea in my mind but wanted to go step after step. Anyhow. I was away for a few days and am quite happy to see all of this sorted out.

@mortommy Let's continue. The document to copy over to documentation ([under this part](http://docs.openhab.org/addons/io.html#undefined)) should contain typical setup and usage instructions. One example for a part not meaningful for the documentation is the Versions Change Log, which you could move to `changelog.txt`. Another option would be to manage two files, one explaining the project with all contribution details on the repository, one specific for the documentation. What do you think?

**Comment by mortommy** [comment]
Thank you @kaikreuzer , sorry for that.
@ThomDietrich I'll have a look to the typical setup and instructions. Thank you.

**Comment by mortommy** [comment]
Hi,
I added the usage.md file. Could be a good start?

**Comment by ThomDietrich** [comment]
Looks good! https://github.com/openhab/openhab-mycroft/blob/master/USAGE.md

I'll try to get the copying process working today or in the next couple of days, then we can start the integration and fine tuning process :) Thanks for your quick response!
