### ISSUE TITLE
[Sitemaps] Element Type ‘Chart’: begin/end wrong?

### ISSUE THREAD

**Issue by hreichert** [openhab/openhab-docs#503]
Page:
http://docs.openhab.org/configuration/sitemaps.html#element-type-chart
Source:
https://github.com/openhab/openhab-docs/blob/gh-pages/configuration/sitemaps.md#element-type-chart

Regarding to this:
> Chart [item=<itemname>] [icon="<iconname>"] [label="<labelname>"] [refresh=xxxx]
> [period=xxxx] [service="<service>"] [begin=yyyyMMddHHmm] [end=yyyyMMddHHmm]

and

> begin / end represent the beginning and end of the time axis of the chart. Valid values are in the format: "yyyyMMddHHmm" (yyyy = year, MM = month, dd = day, HH = hour (0-23), mm = minutes).

I defined a Chart in in my sitemap:
`Chart item=gChart begin=201701010000 end=201801010000`

Following error occurs:

> [WARN ] [.e.s.m.c.i.ModelRepositoryImpl:92   ] - Configuration model 'demo.sitemap' has errors, therefore ignoring it: [8,27]: no viable alternative at input 'begin'

I looked at the model sources, [Sitemap.xtext](https://github.com/eclipse/smarthome/blob/master/bundles/model/org.eclipse.smarthome.model.sitemap/src/org/eclipse/smarthome/model/Sitemap.xtext) and found no references to begin/end:
```
Chart:
    'Chart' (('item=' item=ItemRef) & ('label=' label=(ID | STRING))? & ('icon=' icon=Icon)? &
    ('service=' service=(STRING))? & ('refresh=' refresh=INT)? & ('period=' period=ID) &
    ('labelcolor=[' (LabelColor+=ColorArray (',' LabelColor+=ColorArray)* ']'))? &
    ('valuecolor=[' (ValueColor+=ColorArray (',' ValueColor+=ColorArray)* ']'))? &
    ('visibility=[' (Visibility+=VisibilityRule (',' Visibility+=VisibilityRule)* ']'))?);
```

I think the ChartProvider does support the begin/end attributes, because this works as expected:
http://localhost:8080/chart?groups=gChart&begin=201701010000&end=201801010000

**My questions:**
* What is wrong? The documentation or the implementation?
* If the implementation is wrong: Where should I open a ticket? Eclipse Smarthome?

**Comment by hreichert** [comment]
Anyone?

**Comment by LightIsLife** [comment]
@hreichert maybe you have more luck discussing this in the forum first? Can't help you here personally as I never used this feature, but I would think that the forum may be the better place to start this discussion and get more guidance/input

**Comment by hreichert** [comment]
@LightIsLife Thanks for your reply. I don't want to use this feature either, but I discovered that there is something wrong here while working on other chart related stuff. As I think that just the documentation is wrong, I opened the issue here.

**Comment by ThomDietrich** [comment]
Hello @hreichert,
at first read I also wasn't sure about the right answer. Your decision to open an issue here was right. Now I think before removing the feature from docs it would be worth reporting the issue at eclipse/smarthome.
