### ISSUE TITLE
[comfoair binding] add undocumented features

### ISSUE THREAD

**Issue by binderth** [openhab/openhab-docs#521]
see: http://docs.openhab.org/addons/bindings/comfoair1/readme.html
This one needs an update for the table within item configuration:

ewt_temperature = READ
ewt_temperature_low = READ
ewt_temperature_high = READ
ewt_speed = READ
ewt_mode = READ
bypass_mode = READ
filter_reset = WRITE | 1 - filterhours will be reset to 0
filter_error = READ
error_reset = WRITE | 1 - error messages will be reset

(see https://community.openhab.org/t/comfoair-add-filter-reset-in-binding/25337/7 - the configuration can be seen here: https://github.com/openhab/openhab1-addons/blob/master/bundles/binding/org.openhab.binding.comfoair/src/main/java/org/openhab/binding/comfoair/handling/ComfoAirCommandType.java

**Comment by udo1toni** [comment]
You can add this information through https://github.com/openhab/openhab1-addons/blob/master/bundles/binding/org.openhab.binding.comfoair/README.md.

You have to fork, update the file and request a pull. Don't forget to sign the pull request by adding the line 'Signed-off-by: <your name> <your email-address>' to the github pull request comment.

Take a look at other pull requests, if my description is not clear enough...

**Comment by ThomDietrich** [comment]
Please let us know after you've done the change so we can close the issue here. Thanks for your help!

**Comment by binderth** [comment]
pew. I never forked or signed or pull requested anything! ;)
But I'll work me through it... ;)

**Comment by Confectrician** [comment]
Hey @binderth,

If you need some advice/help in starting with the GitHub Fork/Sign/Pull Request things, feel free to contact me in the community board. 😄

**Comment by Maurits28** [comment]
I created the pull request here:
[https://github.com/openhab/openhab1-addons/pull/5577](url)

**Comment by Maurits28** [comment]
The pull request is merged. This issue can be closed.

**Comment by Confectrician** [comment]
Thanks for pointing to the merge.
