### ISSUE TITLE
sitemap article, missing details

### ISSUE THREAD

**Issue by ThomDietrich** [openhab/openhab-docs#53]
Hello busy bees,
the sitemaps article is almost done. I've created pull request https://github.com/openhab/openhab-docs/pull/54 to merge the article in it's first version. I would like to point out a few open questions:
- these three [sitemap elements](https://github.com/eclipse/smarthome/tree/master/extensions/ui/org.eclipse.smarthome.ui.basic/src/main/java/org/eclipse/smarthome/ui/basic/internal/render) have been left out, can somebody comment on them? List (NPE in BasicUI), Mapview, Page (I didn't try them, found out about them only now.)
- A few links in the document are not final, don't worry, I will soon create the needed articles, first as dummys though.
- I am personally not using the Charts element (InfluxDB+Grafana+ImageRenderer ❣) I would like to ask one of you guys to [update the article](https://github.com/ThomDietrich/openhab-docs/blob/patch-5/features/sitemap.md#element-type-chart) (new PR or as comment here) on this one element and to provide a screenshot. Beware, that all screenshots were created with the sitemap definition embedded at the end of the article as a comment. Be sure to update it. Thanks ;)
- The [slider](https://github.com/ThomDietrich/openhab-docs/blob/patch-5/features/sitemap.md#element-type-slider) and the [colorpicker](https://github.com/ThomDietrich/openhab-docs/blob/patch-5/features/sitemap.md#element-type-colorpicker) are two other elements I never used. Thanks to anyone adding missing information (see comments in the code).
- A native English speaker is invited to touch up my text. If you find real problems, please lecture me about them ;P 
##

**Comment by kaikreuzer** [comment]
> these three sitemap elements have been left out

- Page: This is not a valid widget (see the "real" list [here](https://github.com/eclipse/smarthome/blob/master/bundles/model/org.eclipse.smarthome.model.sitemap/src/org/eclipse/smarthome/model/Sitemap.xtext#L14))
- MapView: shows an OpenStreetMap map for a Location item. Try [this](https://github.com/eclipse/smarthome/blob/master/distribution/smarthome/conf/sitemaps/demo.sitemap#L9).
- List: Good question, I think no UI supports this and nobody uses it. Just leave it away for now.
- The widget that is missing is "Default": This let's the system choose the widget type for the UI automatically based on the item type (see [here](https://github.com/eclipse/smarthome/pull/1535)).

Btw, almost all content of the page is NOT specific to openHAB, but rather describes the ESH feature. So what I would like to ask all of you is to always ask yourself, what part of the documentation could be added to ESH directly (and then automatically imported to the openHAB docs as it is done already with some concepts and features).

In this case here, I could imagine that you extract some of the content to describe the general concept of sitemaps (and add that to https://www.eclipse.org/smarthome/documentation/concepts/index.html) and keep the configuration parts to openHAB (possibly rather in the "configuration" section). I know that this isn't always easy, but imho it is necessary for not duplicating any information (which will on the long run mean a lot of overhead for the maintenance).

**Comment by ThomDietrich** [comment]
Thanks kai, I'll look into that.

I still need somebody to read over the paragraphs on charts, slider and colorpicker. Would you or rkoshak have the time?

@rkoshak: If you feel like it ;)
> A native English speaker is invited to touch up my text. If you find real problems, please lecture me about them ;P

**Comment by BClark09** [comment]
I just read through these sections, and it seems well written to me! Hope you don't mind but I had some minor comments:

### Slider

> This type presents a value as a slider or percentage bar like UI element and allows manipulation.

Consider:
This type presents a value as a user-adjustable control which slides from left (0) to right (100).

> `switchSupport` is a parameter without assignment. If specified a short press on the “up” or “down” button/arrow in the classic (web) frontend switched the item on/off completely.

Consider:
`switchSupport` is a parameter without an assignment. If specified, a short press on the "up" or "down" button switches the item "on" or "off" completely (ClassicUI only).

### Charts

> When charting a group of items make sure every label is unique.

Consider:
When charting a group of item, make sure that every label is unique.

Also, the end of these bullet points are sentences but do not end in a period/full-stop. The other lists that present sentences do this.

**Comment by rkoshak** [comment]
Just now seeing this. Here are my recommended changes (mostly minor)

**Sitemaps**

> The definition of sitemaps happens **declaratively** in a file with a clear syntax, described below.

> For easy editing, the openHAB Designer **provides** full IDE support for these files.

> The openHAB runtime comes with a demo configuration package containing a **demo.sitemap**, which should let you easily understand possible elements and structures.

At least in the GitHub preview it treats the demo.sitemap as a link. The demo.sitemap in the next sentence is not treated as a link.

**Concepts**
> A set of different element types supports a user-friendly and clear presentation.
Remove "counted"

> The example above contains Frame, Text **and** Switch elements **among** others.

> Elements present information, allow interaction and are highly configurable based on the system state.
Remove "will", "or status data"

> As can be seen in the example, an important design decision was, to have a descriptive text next to an icon on the left side and the status or interaction element(s) on the right.

Replace with "As shown in the example, each element generates a descriptive text next to an icon on the left side and a status and/or interaction elements on the right."

> In the shown example item, label and valuecolor are parameters.

> All parameters are optional, some are however needed to result in a meaningful user interface.
Remove "Almost" or add a sentence explaining which parameters are required. I don't think there actually are any. `Text` I think is a perfectly valid sitemap entry.

> The Frame element type is often used in combination with element blocks.
Remove  "and a bit special in that matter", I don't think it adds clarity.

> In the above example, multiple frames are defined and some elements are not visible on the main view but are accessible behind their parent element. **These are indicated by the ">" control icon.**

Consider making this its own section, perhaps just before the Dynamic section. Lots of people on the forum miss this capability.

> For the technically interested: The sitemap definition language is an Xtext **Domain Specific Language.**
 It's a good idea to spell out acronyms on their first use in a document.  I'm also not certain that widely in use DSL is.

> `sitemap <sitemapname> label="<title of the main screen>"` **{**

Also consider adding the closing curly brace.

Add a sentence explaining that the `<sitemapname>`  must match the name of the file.

**Element Types:**

Consider ordering the table alphabetically.

> Concentrates all elements of a given group in a nested block.

> Adds a time-series chart object for displaying **persisted** data.

Consider a link to the persistence article

> Displays a video **stream** given a direct URL.

Remove "by"

**General remarks on parameters**

Add a bullet point:

* Parameters must be supplied in the order described above
* Setting a value for label or icon on the sitemap will override the values defined in the .items file

** Element Group**
Add **There is no way to override the parameters, change the default element type, change the order, use dynamic tags, or insert other elements (e.g. Chart, Image, Webview, etc) in the subframe generated by using the Group element. Please see the Blocks section above under Concepts for how to create a subframe with full control over its contents and appearance.**

**Element Chart**

> Despite the chart refresh option, charts do not appear to refresh properly according to this setting

For the official docs we should either find out this is the case and state it definitively or remove the statement. Our docs should not be wishy washy with the language. If it is confirmed to be true reword to **The chart refresh option is not yet implemented.**

**Element Type 'Webview'**

Ad a warning that webviews do not work with the phone apps nor through myopenhab.org.

**Element Type 'Video'**

> Allows to integrate a video presentation into a your sitemap. Not all video encodings (formats) are supported, you may need to transcode your video. The video has to be reachable directly via URL. An embedded or protected video is not supported.

Does anyone know what the supported encodings are? The only thing I do know for sure is MJPG.

** MAPPINGS**

> Mappings is an optional parameter for the **S**witch and **S**election element types.

Scrub whole document to make sure the case matches when referring to an Element name.

**Color**
> Below you can find a list of standard colors and their respective RGB color code.

It would be cool if the table text matched the color that the row describes.

It looks great!

**Comment by watou** [comment]
I just noticed [MapView](https://github.com/eclipse/smarthome/pull/277) is still not documented.  I worry that an issue like this with so many other issues in it might be better broken out so as to be workable?

**Comment by ThomDietrich** [comment]
For me it would be okay... I just didn't work on the issue yet :cry: I'll put it onto my todo list!

**Comment by michel53** [comment]
"For the technically interested: The sitemap definition language is an Xtext DSL."
The "Xtext DSL" link 
https://github.com/openhab/openhab1-addons/blob/master/bundles/model/org.openhab.model.sitemap/src/org/openhab/model/Sitemap.xtext
leads to a 404 error.

**Comment by ThomDietrich** [comment]
Thanks @michel53 !
