### ISSUE TITLE
Logging: Add example for logging variable/Item state

### ISSUE THREAD

**Issue by ThomDietrich** [openhab/openhab-docs#534]
https://community.openhab.org/t/specifying-the-number-of-decimal-places/35319/4
http://docs.openhab.org/administration/logging.html#create-log-entries-in-rules

```java
logInfo("BR1-temp.rules", "Bedroom 1 Temperature: Measured : %1$.1f°C Target: %2$.1f°C Min: %3$.1f°C State: %4$s", BR1_Temp.state,BR1_Tgt_Temp.state ,BR1_Min_Temp.state ,BR1_Temp_State.state)
```

Also: The "subpackage" description is a bit weak. Instead of "Demo" we should motivate something that the user can actually refer to, like "My Custom Rule" or "heating-control.rules"

Last thing that comes to mind: We should figure out if this part of the article also needs a reference/place in the rules-dsl article...

**Comment by bgilmer77** [comment]
This whole article should be expanded as well, but let's take it in bite-sized pieces

**Comment by bgilmer77** [comment]
@ThomDietrich I am happy to take a crack at this.  Please clarify what the code-fenced text is in your first comment.  Is this an example to use in place of the Demo one in the current article?  FWIW, I like "heating-control.rules".

Finally, just so I understand what is going on here, do I understand correctly that the line above, or the lines from the article could be put into a rule causing logging to occur when the line is executed?  I know one can do that, but this is the point you want to illustrate - correct?

**Comment by bgilmer77** [comment]
Just created PR #546 to address this.

**Comment by Confectrician** [comment]
Can we close this issue, since there is a according PR which has already been merged?
Or are there still things to discuss?

**Comment by bgilmer77** [comment]
Seems to me like it makes sense to close it.
