### ISSUE TITLE
Iconset Page broken (in eclipse smarthome repo)

### ISSUE THREAD

**Issue by Confectrician** [openhab/openhab-docs#541]
Hi,

The classic iconset seems broken for some Icons, but this seems to be a problem of the parent Repository.
I have already opened the related issue eclipse/smarthome#4456 in the corresponding Repository.
![image](https://user-images.githubusercontent.com/7161177/31962092-e68d8cb0-b8fc-11e7-831e-95d2501e6c24.png)

## This is just a reference, for people who may want to report this issue here
Discussion should be better placed in the reference issue and changes have to be contributed there anyway.

**Comment by kaikreuzer** [comment]
The question mark is there to indicate that this iconset is lacking the according required icon, it is no t a bug of the documentation page.
