### ISSUE TITLE
[Editors Page] Add LSP to VS Code section

### ISSUE THREAD

**Issue by Confectrician** [openhab/openhab-docs#545]
Since the VS Code extension, will support Language Server Protocol in the next time, 
we should add some info about this to the corresponding section in the [Editors Page](https://github.com/openhab/openhab-docs/blob/gh-pages/configuration/editors.md) 

Especially the requirements should be mentioned.
- Correct Server configuration in VS Code
- LSP AddOn installed with Paper UI

Related:
[VS Code Repo Readme](https://github.com/openhab/openhab-vscode#validating-the-rules)
[Corresponding Question in the community](https://community.openhab.org/t/visual-studio-code-openhab-extension/30205/104?u=confectrician)

We should finish the PR and merge it when those changes are in the stable build.

@kubawolanin do you want to add it yourself?
I can do that PR too.
If you have any wishes about the wording, throw it in here.

I would mainly use your Readme text and add one or two sentences for the users to explain the benefits from LSP for them and what this is.

**Comment by Confectrician** [comment]
Additionally we could remove the *manual* installation part and replace it with the installation through marketplace, since the extension is listed there meanwhile.

Or do we need both ways of installing the extension?
Wdyt?

(I have already changed Line 37, which said that marketplace is missing currently.)

**Comment by kubawolanin** [comment]
Hey @Confectrician,
Thank you for posting the issue. It's great you remember about it 😄 

While it's great to have the tool mentioned on Editors page, I do believe that we should rather reference its README (check) and [direct link to it](https://marketplace.visualstudio.com/items?itemName=openhab.openhab) on the Marketplace.

I would see the Editors page as a quick reference guide for where you actually can work on your textual configurations. Not necessarily a comprehensive guide for VSCode etc.
For that I'd rather see VSCode README incorporated in Docs separately :-)

If you're already modifying the file then please proceed with those suggested changes.
I have a few minor bugs and enhancements for the extension on my radar.

Thank you!

**Comment by Confectrician** [comment]
> While it's great to have the tool mentioned on Editors page, I do believe that we should rather reference its README (check) and direct link to it on the Marketplace.

Already done 20min ago in my feature branch. 😄 

> If you're already modifying the file then please proceed with those suggested changes.

Ok.
I will mention the rule validation, add some explanation and link it directly to the corresponding readme anchor in the vscode repo for further instructions..

**Comment by ThomDietrich** [comment]
Sounds like this is resolved?

**Comment by Confectrician** [comment]
PR is incoming next days, when i have found time for adding the content of the last comment.
