### ISSUE TITLE
Network binding description needs updated, contains incorrect Thing definitions 

### ISSUE THREAD

**Issue by ScheissSchiesser** [openhab/openhab-docs#547]
For instance: `pingdevice` is not a valid Thing. It is concerning that there is not complaint from Openhab about this.

The correct definition is `network:device:<somename>`

I gleaned this information from finding the device through Paper UI. Trying to define the Thing manually gives no error for `pingdevice`, but that definition doesn't appear to actually do anything.

**Comment by Confectrician** [comment]
All Binding documentations are grabbed automatically from external openHAB repos.
The correct place for this correction would be https://github.com/openhab/openhab2-addons/blob/master/addons/binding/org.openhab.binding.network/README.md
So the PR has to be in https://github.com/openhab/openhab2-addons/

---
Additionally i want to mention the following:
I have read through the readme now and it mentions 2 thing types -> `pingdevice` and `servicedevice`
First one seems obviously wrong according to the description above.
Nothing told about the second one yet.
When we correct the article anyway we should be sure about other possible changes which could have been made meanwhile.

**Comment by ThomDietrich** [comment]
Please be aware, that the README was recently updated for the brand new Network binding version only available in the latest openHAB 2.2 snapshot. This situation is not ideal and we are working on a solution.
Till then please see here for the openHAB 2.1 stable version of the binding:
https://github.com/openhab/openhab2-addons/blob/ed8ce5e3e4cfeadae11cf76c0e3e586c23b0e0d3/addons/binding/org.openhab.binding.network/README.md

**Comment by ScheissSchiesser** [comment]
Ah, I see. I won't submit my pull request then. 

I think setting up docs.openhab.com such that one can select a binding version or openhab version would be helpful. No idea how feasible that it.

Perhaps a message at the top of the README stating the version of the binding would at least deter people from creating issues like this one.

**Comment by ThomDietrich** [comment]
exactly what is in planning. If you have basic web development experience or would like to learn, you are invited to help! Just contact me and we can discuss details ✌️

**Comment by ScheissSchiesser** [comment]
I would love to help. I would qualify my web development skills as "extremely basic," but I am willing to learn.
