### ISSUE TITLE
The example in Network binding is not correct

### ISSUE THREAD

**Issue by ItIsFelix** [openhab/openhab-docs#548]
Where: http://docs.openhab.org/addons/bindings/network/readme.html

```
Full Example
demo.Things:
network:pingdevice:devicename [ hostname="192.168.0.42" ]
```
should be 
```
Full Example
demo.things:
Thing network:pingdevice:devicename [ hostname="192.168.0.42" ]
```

**Comment by Confectrician** [comment]
One note from my side:

This doc page is generated automatically from https://github.com/openhab/openhab2-addons/blob/master/addons/binding/org.openhab.binding.network/README.md and the correction has to be in the https://github.com/openhab/openhab2-addons/ repository.

(But from your GithUb profile, it looks like you already have recognized that. 😄 )

**Comment by bgilmer77** [comment]
I have filed a PR in openhab2-addons to address this, #2825.

**Comment by ThomDietrich** [comment]
Wonderful.
