### ISSUE TITLE
items configuration article

### ISSUE THREAD

**Issue by ThomDietrich** [openhab/openhab-docs#55]
This is a placeholder for the work on the [items.md](http://docs.openhab.org/configuration/items.html) article. If you are willing to work on this task, please leave a message.

**Comment by ThomDietrich** [comment]
Note: The sitemap article contains a lot of references to items (labels, icons, etc....). All of them are currently marked with a "TODO" note in source code. Please update these links when the items article is finished.

**Comment by pabloNZ** [comment]
I'll start working on this and get a draft based on the OH wiki article and the discussion in the community forum put together.

**Comment by pabloNZ** [comment]
Pull request is pending. I have kept it in the concepts folder rather than moving it to the configurations folder where it might be better suited. It's a combination of my notes/community posts/ESH wiki/OH1.x Wiki articles so should cover most points.

**Comment by ThomDietrich** [comment]
Closing because PR https://github.com/openhab/openhab-docs/pull/68
Please do not forget about the sitemap links
