### ISSUE TITLE
Infinite loop for a MQTT message OPENHAB2

### ISSUE THREAD

**Issue by alzameelan** [openhab/openhab-docs#554]
i'm changing now from Openhab1 to Openhabe2, i have a lot of items which use MQTT message to control my home, i've tried to write them in the items file in the items folder, but it seem that something went wrong.
Here is an example i write it to to test if it works: items.items

   Group test

Switch test "test sensor" (test) {mqtt=">[ideaal:test:state:*:Switch ${itemName}; zustand ${state}],>[ideaal:test:command:*:Switch ${itemName}; zustand ${command}]"}
Switch Switch1 "test Switch1" (test) {mqtt=">[ideaal:myhome/bedroom/switch1:command:ON:1:test1],>[ideaal:myhome/bedroom/switch1:command:OFF:0:test2],>[ideaal:myhome/bedroom/switch1:state:ON:1:test3],>[ideaal:myhome/bedroom/switch1:state:OFF:0:test4"}
Switch Switch2 "test Switch2" (test) {mqtt=">[ideaal:myhome/bedroom/switch2:command:ON:1:test4],>[ideaal:myhome/bedroom/switch2:command:OFF:0:test5],>[ideaal:myhome/bedroom/switch2:state:ON:1:test6],>[ideaal:myhome/bedroom/switch2:state:OFF:0:test7]"}

here is my sitemap:

sitemap Test label="Test"{

Frame label="test"{
Switch item=test
Switch item=Switch1
Switch item=Switch2

}

}

when i subscribe the topic test : mosquitto_sub -h localhost -t test
i got an infinit loop from Mqtt messages,
but when i subscribe the other topics there is no message come: mosquitto_sub -h localhost -t myhome/#

so can you help me to solve the problem !

**Comment by Confectrician** [comment]
Hi @alzameelan,

This place is for handling the documentation homepag of openHAB.
Related to this, you won't reach the whole openHAB community.

I would suggets you to register @ community.openhab.org
and ask your question in the forum.
You will reach more people who can possibly help you. :smiley: 

Best Regards
Confectrician

**Comment by alzameelan** [comment]
@Confectrician  
thank you very much, i will write my problem there
