### ISSUE TITLE
Installation -> Docker uses --user flag which causes container to not be able to create groups

### ISSUE THREAD

**Issue by abbviemr** [openhab/openhab-docs#558]
The tutorial in the forum as well as the manual itself reference the --user switch which causes the current container image to fail to start (not able to create group).

    docker run \
        --name openhab \
        --net=host \
        -v /etc/localtime:/etc/localtime:ro \
        -v /etc/timezone:/etc/timezone:ro \
        -v /opt/openhab/conf:/openhab/conf \
        -v /opt/openhab/userdata:/openhab/userdata \
        -v /opt/openhab/addons:/openhab/addons\
        -d \
        --user=<uid> \
        --restart=always \
        openhab/openhab:<version>-<architecture>-<distributions>

This is the error from the docker logs:

    NEW_USER_ID=1008
    NEW_GROUP_ID=1008
    echo 'Starting with openhab user id: 1008 and group id: 1008’
    Starting with openhab user id: 1008 and group id: 1008
    id -u openhab
    Create group openhab with id 1008
    echo ‘Create group openhab with id 1008’
    groupadd -g 1008 openhab
    groupadd: Permission denied.
    groupadd: cannot lock /etc/group; try again later.

I supplied the USER_ID and the GROUP_ID environment variables which were correctly picked up. Removing the --user flag caused the container to start correctly and the files created on the volumes had the correct user ID (1008 in my case).

I suggest changing the documents to:

    docker run \
        --name openhab \
        --net=host \
        -v /etc/localtime:/etc/localtime:ro \
        -v /etc/timezone:/etc/timezone:ro \
        -v /opt/openhab/conf:/openhab/conf \
        -v /opt/openhab/userdata:/openhab/userdata \
        -v /opt/openhab/addons:/openhab/addons\
        -d \
        -e USER_ID=<uid> \
        -e GROUP_ID=<gid> \
        --restart=always \
        openhab/openhab:<version>-<architecture>-<distributions>

I'm using CentOS with SELinux enabled and openhab 2.1 / amd64 / debian image.

Here is the link to my post: https://community.openhab.org/t/running-openhab-2-in-docker/14267/53?u=mathiasringhof

**Comment by martinrunge** [comment]
The same is true for the launch with systemd:
I succeeded with the following "/etc/systemd/system/openhab2.service":


    [Unit]
    Description=openHAB 2
    Requires=docker.service
    After=docker.service
    
    [Service]
    Restart=always
    ExecStart=/usr/bin/docker run --name=%n --net=host --tty \
      -v /etc/localtime:/etc/localtime:ro \
      -v /etc/timezone:/etc/timezone:ro \
      -v /opt/openhab/conf:/openhab/conf \
      -v /opt/openhab/userdata:/openhab/userdata \
      -v /opt/openhab/addons:/openhab/addons \
      -v /opt/openhab/.java:/openhab/.java \
      -e USER_ID=<uid of openhab> \
      -e GROUP_ID=<gid of openhab> \
      openhab/openhab:2.2.0-amd64-debian
    ExecStop=/usr/bin/docker stop -t 2 %n ; /usr/bin/docker rm -f %n
    
    [Install]
    WantedBy=multi-user.target

**Comment by Confectrician** [comment]
Do you want to add the PR yourself @martinrunge ?

**Comment by martinrunge** [comment]
You ask me to open a new issue for that instead of commenting an already closed one, right?

**Comment by Confectrician** [comment]
No, thats's why I reopened this one already. :)

I was asking if you want to do the change yourself and file a Pull Request.

**Comment by martinrunge** [comment]
Yes, just recognized it myself. Pull Request is on its way.

**Comment by wborn** [comment]
The reference to the --user flag was removed with https://github.com/openhab/openhab-docs/pull/856.

**Comment by Confectrician** [comment]
>The reference to the --user flag was removed with #856.
