### ISSUE TITLE
RULES: Use of the UNDERSCORE (_) is not permitted in RULE file names.

### ISSUE THREAD

**Issue by KidSquid1** [openhab/openhab-docs#561]
On the RULES page it should be mentioned that you can not use the UNDERSCORE _ character in filenames of rules.  Using the character causes OH to skip the file and does not provide any feedback in the logs.

I spent many nights reviewing the code to see why the rules were not firing, my syntax was correct but the file name prevented OH from processing the file.

If any other characters are not permissible in the file name outside of the basic (/?&%...etc) then they should be listed on the rules page as well.

**Comment by bgilmer77** [comment]
I have verified @KidSquid1s issue.  Unfortunately, the log entry for a rule with or without an underscore in the filename are exactly the same - the log reports that the rule has been loaded.

**Comment by Confectrician** [comment]
Sorry i cant confirm that behavior.

I have a rules file which is named: `wohnzimmer_multimedia.rules`
This file is loaded fine and all rules are working fine for weeks now.
I resaved the file and tested it again. Everything is ok.

We should investigate this behaviour a bit more, before changing the docs now.

**Comment by bgilmer77** [comment]
Hum. I have a file, pingMe.rules. Works fine. I rename it ping_me.rules, it loads, but fails to execute.

**Comment by KidSquid1** [comment]
Could this be OH version related? I’m on 2.2 Snapshot Build 1072

**Comment by Confectrician** [comment]
I am on `openHAB 2.1.0-1 (Release Build)`

**Comment by bgilmer77** [comment]
I am on 2.10 release build.

**Comment by bgilmer77** [comment]
Very strange - when @KidSquid1 first posted this bug, I activated a test rule I call pingMe.rules.  Here is the contents of that file:

```java
rule "pingMe"

when
	// Every 1 minute...
	Time cron "0 0/1 * * * ?"
then
       // Place the following entry in my log file
	logInfo("pingMe.rules","pingMe just pinged me.")
end
```
This rule worked perfectly when the filename was `pingMe.rules`.  I renamed the file to `ping_Me.rules`.  The log shows that the rule was loaded without any error, but it failed to execute.

Today I did exactly the same thing, as far as I know, and the rule works with either filename.  So as of now, my findings match @Confectrician.

FWIW, I experienced a lot of what appeared to be random rule behavior on OH1.  I never fully chased the problem to a conclusion, but it appeared that sometimes I would need to stop OH and restart it for rules to take effect.  Just prior to the release of OH2, I think a change was pushed out that fixed the issue.  The behavior of rules had been 100% solid for me in OH2 up until I checked out the underscore issue yesterday.

Anyway, at this point the underscore does not seem to prevent the rule from running.  @KidSquid1, would you please use my rule and see if you still have a problem with the underscore in the filename?

I am traveling but will be back tomorrow, and I can put the 2.2 SNAPSHOT on my development system and see what happens.

**Comment by bgilmer77** [comment]
BTW, I am going to close the PR I created to address this issue.  It is not because I think discussion is finished - it is because I made a mistake in creating the commit that is included with the PR.

If we find that the underscore character is truly not permitted, then I will create a new, cleaner PR to address this.

**Comment by Confectrician** [comment]
@ThomDietrich

Do you know anything about changes regarding the rules in the snapshot version?

Maybe we should ask back in the community forum or in the eclipse smarthome repo to clarify this.

**Comment by KidSquid1** [comment]
Ok, have grabbed your rule and can report the following:

Rule without the underscore in the name....

`2017-11-11 20:20:51.978 [INFO ] [el.core.internal.ModelRepositoryImpl] - Loading model 'pingme.rules'
2017-11-11 20:20:52.011 [INFO ] [el.core.internal.ModelRepositoryImpl] - Refreshing model 'pingme.rules'
2017-11-11 20:21:00.005 [INFO ] [.smarthome.model.script.pingMe.rules] - pingMe just pinged me without an underscore.
2017-11-11 20:22:00.001 [INFO ] [.smarthome.model.script.pingMe.rules] - pingMe just pinged me without an underscore.
`

Rule with the underscore in the name....

`2017-11-11 20:24:46.828 [INFO ] [el.core.internal.ModelRepositoryImpl] - Refreshing model 'ping_me.rules'
2017-11-11 20:25:00.005 [INFO ] [.smarthome.model.script.pingMe.rules] - pingMe just pinged me with an underscore.`

So this indicates in this situation that the underscore is not an issue.....

Yet my original rule of:

`
rule "Holiday Mode On"
when
    Channel 'astro:sun:home:set#event' triggered START
then
if (VIR_HolidaySwitch.state==ON)
{
    HolidayRemote1.sendCommand(ON)
    FntPatioPlug.sendCommand(ON)
    WalkGatePlug.sendCommand(ON)
    GarageHolidaySwitch.sendCommand(ON)
}
end

rule "Holiday Mode Off"
when
    Time cron "0 1 0 1/1 * ? *" 
then
if (VIR_HolidaySwitch.state==ON)
{
    HolidayRemote1.sendCommand(OFF)
    FntPatioPlug.sendCommand(OFF)
    WalkGatePlug.sendCommand(OFF)
    GarageHolidaySwitch.sendCommand(OFF)
}	
end`

Runs fine when the file is named sunsetholiday.rules, yet will NOT run when named sunset_holiday.rules

Could it be something with ASTRO?

**Comment by Confectrician** [comment]
That is a really weird behavior.

I would ask you to post this behavior with a link to this issue in the community forum.
We can reach more people there and maybe clarify what's going on here.

Additionally I would close the issue for now since we don't need to change the documentation before we have clarified this.

If there's need for a change we can of course reopen it at any point.

Regards 

Jerome

**Comment by ThomDietrich** [comment]
Hey guys! I just did a quick test myself. Both `amazondashbutton.rules` and `amazon_dashbutton.rules` work just fine. I am on the latest snapshot just like you @KidSquid1. The problem must lie somewhere else. It might in addition to the community also help to open an issue in the eclipse smarthome repo. After all the goal is not to solve this only for you but all others to follow...

**Comment by KidSquid1** [comment]
I have posted this to the eclipse repo as per @ThomDietrich  suggested.
[https://github.com/eclipse/smarthome/issues/4532](url)

My original posting in the OH forum is here as well
[https://community.openhab.org/t/astro-rule-weirdness/35709/13](url)

**Comment by ThomDietrich** [comment]
Saw your issue over in the smarthome repo. You have posted the whole file and suspected it could be related to astro. The least you should do is reduce the content of the file to a minimum, maybe figure out which part of the file makes the difference. I think the chances are low that someone will pick up the issue as it is right now...
