### ISSUE TITLE
broken links (io vs. ios folder)

### ISSUE THREAD

**Issue by CWempe** [openhab/openhab-docs#564]
some links are broken inside the documentation.

I am pretty sure this is because the folders got renamed by @ThomDietrich in 7c2579f33561e3d2f4553e113cf1713a0850a43e

example:
In http://docs.openhab.org/addons/ios/alexa-skill/readme.html the are some links to `/io/homekit/readme.html` etc.

The same might apply to `persistence(s)`.

Maybe someone can run a script to find and fix these errors.

**Comment by ThomDietrich** [comment]
I was thinking about adding some CI magic for this. Running a tool once will always lead to this situation at some point :-/
I'll look at it. Thanks!!
