### ISSUE TITLE
Continuous checking for broken links and the remark style

### ISSUE THREAD

**Issue by ThomDietrich** [openhab/openhab-docs#565]
Hey everyone.

I was thinking about a way to automatically generate **broken links** and **markdown lint** statistics, e.g., after every commit to gh-pages. I've been looking at various Github integrated [Code Quality](https://github.com/marketplace/category/code-quality) tools, however none of them seems to offer this kind of freedom. Most of them are specialized to e.g. run a python linting. I am looking for an online tool because I specifically do not want to set up a dedicated service for this kind of continuous thing.

The result of such an integration could e.g. be some report plus a nice little badge in the README, informing about the count of errors.

Does anyone know of a good solution for the use case?

Alternative: We have a process in place to retrieve and include external content, like binding READMEs. Executing the above tests and including their output as part of that process would be easy. The check results could e.g. be piped into a file in the repo. It's something... Wdyt?

Linked to #564  #103 #101

**Comment by Confectrician** [comment]
Just as an idea:
What about google webmaster tools?
They can report crawling issues automatically.
One issue could be, that we get informed about this with some delay but at least we get informed.

Of course some tool that solves this task before updating the docs would be better.

**Comment by ThomDietrich** [comment]
Not sure about how thorough their report is but I'm anyhow looking for more than any single service will be able to offer. I've hacked together a script to do the alternative approach described above. About to open PR...

**Comment by ThomDietrich** [comment]
Note to self: Add info when the badges where last updated.

Also: Maybe replace linkchecker by: https://github.com/stevenvachon/broken-link-checker
The situation is unclear as the linkchecker project was just forked by a new community. Broken-link-checker is a nodejs application and would go nicely alongside remark

**Comment by gitMiguel** [comment]
@Confectrician stale issue.

Hi, @ThomDietrich, looks like you have multiple open issues. Can you take look  and hopefully update or close some of them. Thanks.

**Comment by Confectrician** [comment]
I would also appreciate @ThomDietrich s help here again. 🙂 
We have the broken link checker script in place, but don't use it frequently.
I think @ghys also provided something similiar (or even the same solution?!).

I would call broken link checking still as a nice to have feature.
