### ISSUE TITLE
Linter relies on OSx-only utility - does not appear to work on Ubuntu/Debian

### ISSUE THREAD

**Issue by bgilmer77** [openhab/openhab-docs#567]
Running npm-install produces the following error:
```java
optional  Skipping failed optional dependency /chokidar/fsevents:
notsup  Not compatible with your operating system or architecture: fsevents@1.1.3
```
It appears that fsevents is a OSx-only utility.

Running `npm-install --no-optional` results in a clean install, but running `npm run-script lint-md` produces the following, in part:
```java
npm err! Linux 4.4.0-98-generic
npm err! node v4.2.6
npm err! npm v3.5.2
...
npm err! Failed at the openhab-docs@0.0.0 linty-md script 'remark.'.
```

**Comment by Confectrician** [comment]
The complete script doesn't exist anymore, so no need to solve anything here.
