### ISSUE TITLE
jekyll config file error

### ISSUE THREAD

**Issue by bgilmer77** [openhab/openhab-docs#570]
Running `jekyll serve` in the openhab-docs directory produces the following:
```java
Configuration file: openhab-docs/_config.yml
   Deprecation: The 'plugins' configurationoption has been renamed to 'plugins_dir'.
   Please update your config file accordingly.
```
Editing the `_config.yml` file as directed appears to correct the error.

**Comment by Confectrician** [comment]
I think that i had this warning, while using the vagrant version.
It currently doesnt appear for me, while using jekyll nativ on my pc.

can you give some information about your environment?

**Comment by ThomDietrich** [comment]
Can't say that I saw this warning recently...

**Comment by bgilmer77** [comment]
A little more detail:
Ubuntu 16.04 LTS
jekyll 3.0.1

But, I do not get the error running:
MAC OSx High Sierra
jekyll 3.6.2

But...
I have yet to verify that I have exactly the same repo cloned from GitHub in both environments.

That's all for now.

**Comment by Confectrician** [comment]
Outdated since we are using vuepress now.
