### ISSUE TITLE
Configuration: Add a link to the "demo" example configuration

### ISSUE THREAD

**Issue by ThomDietrich** [openhab/openhab-docs#578]
https://github.com/openhab/openhab-distro/tree/master/features/distro-resources/src/main/resources

Even if the user didn't select the Demo starting package, he/she might want to look at the example files at some point. There should be a link to them somewhere in configuration.

How about http://docs.openhab.org/configuration/index.html and/or http://docs.openhab.org/configuration/packages.html

Better ideas?

@BClark09 for many Linux packages ([*](https://community.openvpn.net/openvpn/wiki/HOWTO#Gettingthesampleconfigfiles)) it is common to provide example configuration files through some location under `/usr/share`. Wdyt?

**Comment by Confectrician** [comment]
> How about http://docs.openhab.org/configuration/index.html and/or http://docs.openhab.org/configuration/packages.html

I would vote for `and`

**Comment by BClark09** [comment]
Providing them through the Linux packages would be no problem! And I'd agree that `/usr/share/openhab2` (`$OPENHAB_HOME`) would be the most appropriate place for them.

**Comment by ThomDietrich** [comment]
Fine with me. @kaikreuzer wdyt?

**Comment by kaikreuzer** [comment]
I even wonder if we should move them to the docs completely and remove the demo packaging - especially one we have the home builder merged, which should then become the starting point for new setups (while currently people probably often choose the demo setup as a start).

**Comment by ThomDietrich** [comment]
@kaikreuzer let's do that!

With "to the docs" you mean out of the distro into the docs repository? Having them available in docs sounds good to me but as we also need them for @BClark09 and many users will still like to access them directly, how about https://github.com/openhab/openhab-conf-demo

**Comment by kaikreuzer** [comment]
Hm, good questions. I think for @BClark09 it would probably be ideal if they are still part of the distro (as this is the input for the apt packaging) - we could package them in `runtime/demofiles` or somewhere else; Then every user would have them available without having to do a git clone or something similar technical... I would want to avoid creating a new repo for that.

**Comment by BClark09** [comment]
Adding them to `runtime/demofiles` would be perfect. It would copy over in apt/yum automatically.

**Comment by ThomDietrich** [comment]
Fine with me. Imho "demofiles" is a bit unspecific. Consider something with "conf", "config" or "example".

I'll leave this issue open till after the change, then work on appropriate docs changes.

**Comment by kaikreuzer** [comment]
Ok, so let's first get the home builder merged & documented and the demo packaging removed.

> Consider something with "conf", "config" or "example".

Anything is fine for me, please name your favorite :-)

**Comment by BClark09** [comment]
"example" has my vote. `openhab/runtime/conf/` and `openhab/runtime/config/` imply they have some sort of functionality.

**Comment by Confectrician** [comment]
+1 for example. 

I agree with bclark. conf or config could be misunderstood.

**Comment by bgilmer77** [comment]
+1 example

**Comment by kaikreuzer** [comment]
I expected @ThomDietrich to mean democonf/democonfig instead of demofiles as he said "with". So it was about replacing the word "files", not about the absolute name.
"example" by itself is not telling much either - I'd rather go for "sampleconfig" or similar.

**Comment by bgilmer77** [comment]
Ah - I missed that part Kai.  I would prefer sampleconf or sample-conf (or sample_conf?).

**Comment by ThomDietrich** [comment]
@kaikreuzer Thank you. Yes 😄

```regex
(sample|example|demo|)[-_ ](conf(ig|))
```

Any combination is fine with me. The word "demo" is by now maybe not the best fit. "example" or "sample" would both fit, however in the community we already eastablished the term "example". For the second part I'd have liked "config" better but as the distribution is served with the "conf" folder, that might be the better choice. Hence my vote goes to: `example-conf`

**Comment by kaikreuzer** [comment]
Ah, glad to see that we sometimes do NOT misunderstand each other ;-)

`example-conf` sounds good to me.

**Comment by bgilmer77** [comment]
+1 example-conf

**Comment by iceburg1991** [comment]
+1 example-conf , sounds good and logic.

**Comment by kaikreuzer** [comment]
> move them to the docs completely and remove the demo packaging

I didn't really make it to address this in time and I feel that removing the demo package now is too risky and will render many screenshots outdated immediately.
So I hope you do not mind if I leave it in place in the 2.2 release after all; let's do the change in 2.3.0-SNAPSHOT then.

What I'd like to add though is the Home Builder to some package. I think the "Standard" package is the only candidate as "Simple" does not support items&sitemaps anyhow and "expert" is rather for people who anyhow already have their full setup. Would you agree?

**Comment by kaikreuzer** [comment]
You can simply vote on https://github.com/openhab/openhab-distro/pull/609 :-)
