### ISSUE TITLE
Redirects for subdirectories without index.html

### ISSUE THREAD

**Issue by ThomDietrich** [openhab/openhab-docs#583]
It's not uncommon to browse a URL like: http://docs.openhab.org/addons/bindings/
It is then a surprise to end up on a 404 page. An appropriate `redirect` should be created:

http://docs.openhab.org/addons/bindings/index.html -> http://docs.openhab.org/addons/bindings.html

**Comment by Confectrician** [comment]
Just throwing this on to find it later:

https://help.github.com/articles/redirects-on-github-pages/

**Comment by Confectrician** [comment]
Outdated, since we are using vuepress now.
