### ISSUE TITLE
MySQL to JDBC/MySQL MIgration Section 

### ISSUE THREAD

**Issue by jrieder** [openhab/openhab-docs#585]
In section https://docs.openhab.org/addons/persistence/jdbc/readme.html#migration-from-mysql-to-jdbc-persistence-services

A) The following comments should be added as the item manangement tables are different in the native mysql persistance compared to jdbc/mysql persistance:

"Rename in the existing MySQL Database the managetable from "`Items`" to "`items`""

B) Parameter "`reconnectCnt`" seems to be taken into account also by the jdbc/mysql persistance. Thus this parameter might get problems at migration. So if this parameter was set in the `mysql.cfg` file it should be kept and set to `reconnectCnt=0` in the `jdbc.cfg` file to avoid any issues

**Comment by Confectrician** [comment]
Hi @jrieder,

Thanks for filing this issue.

For users who are possibly willed to take this issue and improve the docs:

Some parts of our documentation are grabbed from external ressources and generated into the addons folder automatically from time to time.

For the jdbc readme, the original file can be found here:
https://github.com/openhab/openhab1-addons/blob/master/bundles/persistence/org.openhab.persistence.jdbc/README.md

A possible Pull Request has to be done in the openhab1-addons repo.
