### ISSUE TITLE
Add MQTT 101 to Tutorials list

### ISSUE THREAD

**Issue by ThomDietrich** [openhab/openhab-docs#589]
https://community.openhab.org/t/mqtt-binding-v1-11-getting-started-101/33958

http://docs.openhab.org/tutorials/index.html#community

@Confectrician @bgilmer77 @kubawolanin this would be a good chance to add other Tutorials as well. Please post links to community threads you'd like to see in the list.
It would be amazing if someone other than me opened a PR for this. ;)

Thanks!

**Comment by Confectrician** [comment]
I have looked through the Tutorials and Examples area of the community board.
There are some additional interesting topics, but i would say that those are more complex and maybe confuse new users, so i don't want to suggest them.

But:
I would say we could change the list order a bit.
Washing Machine State Machine is a great topic, but also very complex.
There is not only openHAB and washing machines. There are energy measurements and there is a lot of engineering in this thread.

Maybe we should start with some basic things like the type conversions and the design patterns on the first list elements.
Type conversion is a small concept which is presented for different things.
Every beginner can find useful information there.
Design patterns will bring a list of threads and a new user could scroll through it and find a topic that is related to one of the problem he/she had already maybe.

Wdyt?

**Comment by Confectrician** [comment]
Push,

I just asked myself, why this simple issue is not solved yet...
I would still have your opinion on my last post here.

cc @ThomDietrich, @bgilmer77

**Comment by ThomDietrich** [comment]
Hey Jerome,
short answer: because I'm (sadly) not active right now...

Long answer: By all means, please feel free to add a PR for this simple issue.
It is a good idea to rearrange the list. The counter-arguments against the washing machine tutorial make sense I guess. On the other side I am against the Type conversions and design patterns. First because the type conversions are anyhow part of docs now and secondly because both of them are very boring :-)
The tutorials list should start with some fun and well documented examples I'd say. My speedtest tutorial is imho one of those but there are many interesting ones out there. Maybe you want to go through the list of popular tutorials...

One tutorial you could add is my Heating Boilerplate. It is not really at it's ideal state but already useful.

**Comment by bgilmer77** [comment]
So if @Confectrician you want to propose a new order, that would be great. I will be sure to look at it.

**Comment by Confectrician** [comment]
Closing this one now.
An OH2 Mqtt Binding was introduced meanwhile and we should focus on improving that binding with docs.
