### ISSUE TITLE
xtend Syntax highlighting missing

### ISSUE THREAD

**Issue by ThomDietrich** [openhab/openhab-docs#59]
I was sad to learn, that syntax highlighting in the freshly created sitemap article is not working. Other than on github in preview, GitHub pages + Jekyll does not seem to support the xtend syntax. https://jekyllrb.com/docs/templates/#code-snippet-highlighting

Why not use Java? Because there can always be misinterpretations...

``` java
visibility=[Battery_Level<30]
visibility=[TV_Power==ON]
visibility=[Day_Time=="Morning", Day_Time=="Afternoon", Temperature>19]
```

As you can see, one small < will f up everything.

To get `xtend` we would need pygments https://haisum.github.io/2014/11/07/jekyll-pygments-supported-highlighters

Any ideas?
##

**Comment by ThomDietrich** [comment]
@kaikreuzer I think this is building platform related, so you need to make a decision.

**Comment by kaikreuzer** [comment]
What are the decision options...?

**Comment by ThomDietrich** [comment]
* live with java or javascript or php syntax highlighting for Xtext/Xtend language (the same mess as in the forum)
* switch over to pygment, which is supported by jekyll and which supports xtend:

> Alternatively, you can use Pygments to highlight your code snippets. To use Pygments, you must have Python installed on your system, have the pygments.rb gem installed and set highlighter to pygments in your site’s configuration file. Pygments supports over 100 languages

**Comment by kaikreuzer** [comment]
So the drawback would be that people who want to work on the documentation need a bigger zoo of tools installed locally to make it work, right? Not ideal if we want to keep the barrier for contributions low (especially for the start).

**Comment by ThomDietrich** [comment]
Not really. You don't have to use it. Editors who do not support xtend will just ignore it:

![2016-08-05 15_19_21-start](https://cloud.githubusercontent.com/assets/2870104/17437789/0c0259c6-5b20-11e6-8b36-deceaa4c7163.png)

Others already do, the github online editor [for example](https://github.com/ThomDietrich/openhab-docs/blob/patch-5/features/sitemap.md).

If one of the contributors actually wants to install jekyll, yes one additional package has to be installed. I personally think a local jekyll installation is not needed to write up an article. That's the beauty of standard markdown.

I presume correct syntax highlighting on docs.openhab.org is the important thing.

**Comment by ThomDietrich** [comment]
After seeing some random syntax highlighting behavior I discovered that, on top of jekyll, there is highlight.js included. I didn't see that before. While I don't exactly know why... that could be a good thing as the discourse community forum also uses highlight.js. By extending highlight.js by a Xtend/Xtext language definition, both worlds should be covered. This should be rather easy as a similar language definition can be copied and modified.

https://highlightjs.readthedocs.io/en/latest/language-contribution.html

I might find the time to look into this in the next few months but any **volunteers are more than welcome**.

**Comment by BClark09** [comment]
Does a pull request have to be sent to highlight.js and wait for it to be included or can there be internal definitions? If the former, sending an xtend pull request may be a good thing but won't it need approval from Eclipse?

Ideally we'd need to separate sitemap, items and rules?

**Comment by ThomDietrich** [comment]
Hey, I still believe that extending highlight.js would be a nice solution.
Implementation is probably not as complicated...
I see a bigger problem in the acceptance of the pull request and the integration (in jekyll and) in discourse. You can check the project github page to see PRs lurking around for a few months now (there are merged ones as well) and who knows how often discourse updates their included highlight.js...

> Ideally we'd need to separate sitemap, items and rules?

This is another aspect that can probably not be pushed into highlight.js. We could look into hosting a forked version ourselves...

**Comment by ThomDietrich** [comment]
@BClark09 just to clarify. Did you consider implementing this or did you just ask out of interest?

**Comment by BClark09** [comment]
Hi @ThomDietrich, sorry! It was merely interest so far. If I'm honest, I didn't really find a direction I could take with it.

**Comment by ThomDietrich** [comment]
This was solved partly long ago.

Highlighting is working, a explicit openHAB DSL highlighting scheme is probably too complicated to implement AND inject in other systems (Discourse, Jekyll, ...)
