### ISSUE TITLE
Items/Commands: Mention REFRESH

### ISSUE THREAD

**Issue by ThomDietrich** [openhab/openhab-docs#590]
Each Item type defines a set of accepted commands. These are for example ON, PLAY, 5 or "Hello". There are also not-so-obvious commands, most importantly (the only one!?) REFRESH: 

```
Light.sendCommand(ON)
Sensor.sendCommand(REFRESH)
```

While at it, we should check if all Item Types and accepted Commands are mentioned.
See:
* https://github.com/eclipse/smarthome/blob/master/bundles/core/org.eclipse.smarthome.core/src/main/java/org/eclipse/smarthome/core/library/items/SwitchItem.java#L45
* https://github.com/eclipse/smarthome/search?q=acceptedCommandTypes.add
* https://github.com/eclipse/smarthome/tree/master/bundles/core/org.eclipse.smarthome.core/src/main/java/org/eclipse/smarthome/core/library/types
* https://github.com/eclipse/smarthome/tree/master/bundles/core/org.eclipse.smarthome.core/src/main/java/org/eclipse/smarthome/core/types

Has to go to: 

* link from here: http://docs.openhab.org/configuration/rules-dsl.html
* link from here: http://docs.openhab.org/configuration/items.html#type
* mention here: http://docs.openhab.org/concepts/items.html
* by editing here: https://github.com/eclipse/smarthome/blob/master/docs/documentation/concepts/items.md

Happy Hacking!

cc @kaikreuzer

**Comment by Confectrician** [comment]
Seen in https://community.openhab.org/t/type-conversions/32684

`MyColorItem.sendCommand(INCREASE)`

probably there is `DECREASE` too.

**Comment by Confectrician** [comment]
LIst of all accepted ones in the post eclipse smarthome world:
https://github.com/openhab/openhab-core/search?q=ACCEPTED_COMMAND_TYPES
