### ISSUE TITLE
HomeBuilder article

### ISSUE THREAD

**Issue by ThomDietrich** [openhab/openhab-docs#591]
Hello @kubawolanin,

we just realized that HomeBuilder does not yet have a place in the openHAB documentation.

It would be important to have an article about it in the documentation for the 2.2 release.

1. Could **you** please update and extend the usage article: https://github.com/openhab/openhab-core/blob/master/bundles/org.openhab.ui.homebuilder/USAGE.md I would ask you to add a header like [here](https://github.com/openhab/openhab.android/pull/509/files). Also if you want to include images, please do so by putting them into the relative folder `images/abc.png`. In many repositories these files are located under a `doc` folder, see: https://github.com/openhab/org.openhab.ui.habpanel/tree/master/doc
2. **I** will take all steps needed to include the file(s) in the docs structure. I suggest to:
   - Link the article in the Configuration menu before "Paper UI": http://docs.openhab.org/configuration/index.html
   - Mention HomeBuilder in the "Initial Setup Packages" as @kaikreuzer recently added it to the Standard package: http://docs.openhab.org/configuration/packages.html
   - Link the article here: https://github.com/openhab/openhab-distro/wiki/Draft-for-openHAB-2.2-Release-Notes#2x-add-ons

Wdyt?

cc @kaikreuzer 

Note to self: Also include Android article.

**Comment by kubawolanin** [comment]
Hey @ThomDietrich, thanks for reminding me.
I've submitted my PR with the changes to HomeBuilder docs. I'd appreciate your feedback.
No images at the moment.

Cheers
