### ISSUE TITLE
How to consult the logs should be added to beginner tutorial!

### ISSUE THREAD

**Issue by Kattihatt** [openhab/openhab-docs#593]
So I've been fiddling with openhab2 for like eight hours today. Might say more about me than the lack of documentation really, but the second I joined the IRC-channel, they told me to check the logs. Being oblivious of how to since I hadn't ran into any log files they told me about:
"ssh openhab@localhost -p 8101
habopen
log:display"

Not working blindfolded, it took me ten minutes to figure out what was wrong and to realize that I needed to fix some things I didn't know were broken. This should be mentioned in the overview or somewhere in the beginning of the beginners tutorial so we novices are able to troubleshoot properly!

**Comment by bgilmer77** [comment]
@Kattihatt I agree.  Coming from a Debian sys admin background, one of the first things I did when I was getting started was to go looking for the logs in /var/log, but of course...

Anyway, you have a good suggestion.  Let me see if I can create a PR to address your comment.

**Comment by Confectrician** [comment]
Maybe we can reuse some of the logging article parts or refer to them.
So that we have a really basic understandable starting point of logs and refer for more generic thigns to the corresponding docs page.

**Comment by bgilmer77** [comment]
It needs to be REALLY REALLY simple.  Leave out EVERYTHING except the most basic instructions about how to access a log.  And include a pointer to more complex article on logging.  My two cents.

**Comment by ThomDietrich** [comment]
Hello @Kattihatt I think @bgilmer77 made an excellent point. All too often do we who might have more background with Linux systems forget to explain basics not everyone knows magically.

A side note: Do you use openHABian? You should know that it brings a web frontend (openHAB Log Viewer) to access the logs. That might be something to look out for!

My suggestion: Mention to check the logs if step X doesn't work two-three times in the Basic tutorial. Do not describe how but link the logging article. As we all know the (best) way how to access logs depends on the platform and this is nicely captured in the original logging article. Don't try to introduce some half-baked version of that inside the Tutorial.
@Kattihatt would you have felt comfortable with that? 

Btw. which IRC channel? 😲

**Comment by Confectrician** [comment]
> Don't try to introduce some half-baked version of that inside the Tutorial.

👍

**Comment by bgilmer77** [comment]
I am looking into reviving work on this PR.

My suggestion would be to add the following to the installation/index.html page in the last section under "Help".

"You may also want to look at this article on [logs](http://docs.openhab.org/administration/logging.html).  Inspecting the logs may reveal information that is helpful to you as you work with openHAB." 

Any objections?
