### ISSUE TITLE
Logging: Add openHABian log viewer (frontail) as an option

### ISSUE THREAD

**Issue by ThomDietrich** [openhab/openhab-docs#597]
Many (especially new) users start off with openHABian and would hence have access to the frontail log viewer. Sadly they don't know that. Other users don't know about the option.

We should mention it in documentation.

**Comment by ThomDietrich** [comment]
Yes this should still be done. If you'd like, please add a PR for: https://github.com/openhab/openhab-docs/blob/gh-pages/administration/logging.md

Regarding your issue: Not sure what you mean by running it in the terminal. The whole point is, that frontail provides a webinterface, you simply need to browse its webpage on port 9001

**Comment by Confectrician** [comment]
According to the discussion in #671 the openHABian article would be the better place for this.
