### ISSUE TITLE
Typo in beginners tutorial

### ISSUE THREAD

**Issue by Stefan300381** [openhab/openhab-docs#605]
Hi,

The tutorial http://docs.openhab.org/tutorials/beginner/sitemap.html1 states:

One last thing to do is setting the default sitemap for the “Basic UI” via “Paper UI”. Browse to “Configuration -> Services” in Paper UI and click the “Configure” button of Paper UI

Actually the last two words are wrong. It should be “Basic UI” instead of “Paper UI”, as shown in the screenshot below the statement mentioned above.

Stefan

**Comment by Confectrician** [comment]
Fixed a long time ago in #606
