### ISSUE TITLE
Enhance beginner tutorial

### ISSUE THREAD

**Issue by joergkling** [openhab/openhab-docs#61]
In work by  @joergkling

1.2 Tutorial (Beginner)
1.2.1 Overview
1.2.2 User interfaces 
1.2.3 Installing an Extension
1.2.4 Working with Extension
1.2.5 Working with rules and script
1.2.6 Looking at the Logs
##

**Comment by ThomDietrich** [comment]
Hello Jörg, 
that's quite a part. Good luck!
After talking to a few frustrated users over the last few weeks, I want to turn your attention to one of the first sentences in the beginner tutorial:

> [PaperUI]... It does not (yet) cover all aspects, so you still need to resort to textual configuration files, but it already offers the following...

While I was happy to see this warning in there, I think it this should be streched more. A lot of users start fresh with openHAB, thinking they can do everything with PaperUI. This is the vision for the near future but sadly not the current state. 
Users going through the tutorial should understand the migration process to 1. accept missing parts and 2. know how to work around them.
If you can think of a way, it would be great if you can cover that.

**Comment by joergkling** [comment]
Hi Thomas,

yes, I was involved in some of these discussions and this is why drive this issue. 

Main objective is to get rid of the emty pages and give new users some guidance to do the first steps. Remember, this is the beginners guide. Migration and more enhanced topics should be handled somewhere else.

**Comment by ThomDietrich** [comment]
"migration process" as in "openhab2 is shifting to a new approach and still under heavy development" rather than "migrating from 1.8 to 2.0beta" ;)
Sounds good.

**Comment by kaikreuzer** [comment]
> A lot of users start fresh with openHAB, thinking they can do everything with PaperUI. This is the vision for the near future but sadly not the current state. 

I think even on the long run, we will have these two co-existing concepts: The "full-power" textual configuration as known from openHAB 1, which will stay in place and on what we should also concentrate for now to explain to people in the documentation.
Most of these parts are also possible through the UI by now though and we should try to build this (while implementing the missing parts) in parallel in the documentation - I don't know how to structure it best, but I could imagine something like "how to do it through the Paper UI" and "how to do it through configuration files" to toggle between the two options for the same feature.

What we also need to decide is how to deal with the ["simple linking mode"](https://github.com/eclipse/smarthome/blob/master/bundles/core/org.eclipse.smarthome.core.thing/ESH-INF/config/config.xml#L10) - this is currently the default when installing the distro, but it is really only meant to enable a quick start for people as they do not have to manually create items for their things. But I also see that this leads to some wrong conclusions from beginners as they do not really learn about the duality between items and things. So any suggestions on how to best deal with this (in the distro as well as in the docs) is welcome!
