### ISSUE TITLE
Update osgids regarding use of Service Component Annotations

### ISSUE THREAD

**Issue by Hilbrand** [openhab/openhab-docs#610]
On the page: https://github.com/openhab/openhab-docs/blob/gh-pages/developers/prerequisites/osgids.md It states the following in https://github.com/openhab/openhab-docs/blob/gh-pages/developers/prerequisites/osgids.md#1-service-component-description:

    Note! Please keep in mind that the Service Component Description might be
    automatically generated using SCR Annotations like @Component, @Reference,
    @Activate, @Deacticate and etc that are supported e.g. in Apache Felix. Currently
    these annotations are not used in the openHAB project, so please ignore examples where they are used.

Regarding that last sentence:
> Currently these annotations are not used in the openHAB project, so please ignore examples where they are used.

In openHAB bindings I believe the use of the annotations is preferred nowadays. Should this line be replace with something like: `For openHAB bindings it's preferred to use annotations to generate the XML component files.`? Or does it still apply for openhab-core?

If this needs to be updated and we can come up with an improved description I'll create a pr for this with the new text.

**Comment by Confectrician** [comment]
Hey @Hilbrand,

Late pickup of this issue i know. 😄 

I think the question can't be answered here at all.
Maybe @kaikreuzer (sorry for pinging you so frequently last days^^) could give a statement and we could go on then.

BR
Jerome

**Comment by kaikreuzer** [comment]
Yeah, this is indeed outdated. @svilenvul (or someone from your team), do you already have an updated version of this content from which you could create a PR?

**Comment by Confectrician** [comment]
Thanks for the feedback to all. 😃 

I have assigned @Hilbrand and we can go on in an upcoming PR then.

**Comment by Confectrician** [comment]
Hey @Hilbrand,

Anything new from your side here?
