### ISSUE TITLE
Images on apps/android.html are not shown

### ISSUE THREAD

**Issue by mueller-ma** [openhab/openhab-docs#617]
See http://docs.openhab.org/addons/uis/apps/android.html

**Comment by ThomDietrich** [comment]
Right. Seems like I was a bit sloppy during integration. I'll fix this in conjunction with #613

**Comment by bgilmer77** [comment]
@ThomDietrich I picked this up also.  From what I can see, the names in the source `images` directory match what is in the article, but when I look in uis/apps/images, the appropriate file names are `android_01.png` and `android_02.png`.  I am guessing you already know this...

**Comment by ThomDietrich** [comment]
The whole issue is related to the process of retrieving external resources and the regular "Update generated content" commits you are seeing from Kai. At some point I should give you and @Confectrician a short overview on that.

**Comment by bgilmer77** [comment]
I thought so. For now I will leave this to you. And Happy New Year!

**Comment by ThomDietrich** [comment]
Thanks Brad! All the best wishes for you as well! 🍀

**Comment by Confectrician** [comment]
I think there is still a lot of "internal documentation" missing, which makes it hard for "newbies like us" to get an overview of the whole process.
But experience will come with the time. 😃 

Maybe at least some (more) comments in the corresponding scripts could be useful in the nearer future. 
But that's of course a bit too off topic for this issue now.

**Comment by ThomDietrich** [comment]
Works now: http://docs.openhab.org/addons/uis/apps/android.html
