### ISSUE TITLE
Clarify the relation beteen "System Integration" and "Misc" in Paper UI

### ISSUE THREAD

**Issue by ThomDietrich** [openhab/openhab-docs#634]
https://docs.openhab.org/addons/io.html
https://github.com/openhab/openhab2-addons/pull/3162

The "System Integration" category is more or less the same as the Misc add-ons category in Paper UI. Important: It is not the same!

In the introduction of https://docs.openhab.org/addons/io.html it should e.g. be stated that most of the mentioned systems are integrated via a "Misc" add-on. *Just a first idea and the details of this are up to the author!*

In addition the way how add-ons are installed should be explained in more detail here: https://docs.openhab.org/addons/index.html
I'd suggest a new headline (maybe below the table) explaining all options in detail.

@bgilmer77 @Confectrician who wants to go at it? 😃

**Comment by Confectrician** [comment]
> In addition the way how add-ons are installed should be explained in more detail here: https://docs.openhab.org/addons/index.html
I'd suggest a new headline (maybe below the table) explaining all options in detail.

Just to be sure:
I know installing from Paper UI, Karaf and dropping a .jar somewhere.
Did I miss some option, that i simply didn't use myself yet?

**Comment by bgilmer77** [comment]
> I know installing from Paper UI, Karaf and dropping a .jar somewhere.
>Did I miss some option, that i simply didn't use myself yet
Those are the options I am aware of...

**Comment by Confectrician** [comment]
OK. I will provide a WIP PR in the next minutes.

The System Integration part is a quick fix.
Add on installation needs a bit more attention, but i have some idea already.
