### ISSUE TITLE
openhab-genertor command not found

### ISSUE THREAD

**Issue by michaelrice** [openhab/openhab-docs#641]
Following this: https://docs.openhab.org/installation/openhabian.html#what-next it says 

```After your first setup is done, you might want to generate Items, Sitemap and HABPanel dashboard for your home. Simply log in to your Raspberry PI with SSH and type openhab-generator. ```

But using `Version:     2.2.0 (Build)` you get `openhab-generator: command not found`

**Comment by Confectrician** [comment]
Hey @michaelrice,

thanks for pointing us to that issue.
I don#t think that the documentation here is wrong.
It seems like something went wrong with the implementation of openhab-generator in openhabian.

I have moved the issue to openhab/openhabian#329 and will close this one later.

BR
Jerome

**Comment by ThomDietrich** [comment]
Hey @michaelrice, thanks for triggering this issue. The generator is the successor to the Home Builder: https://docs.openhab.org/configuration/homebuilder.html
Please use this one ;)

Let's track the task in the other issue.
