### ISSUE TITLE
Broken links with ZWave documentation

### ISSUE THREAD

**Issue by cdjackson** [openhab/openhab-docs#642]
Hey @ThomDietrich thanks for updating the docs with the latest version of ZWave readme, although it doesn't look to have copied over all the new thing files. This means that the link to the list of things is currently broken and docs.openhab goes 404 as a result.

When you get a chance could you take a look at this.

Thanks (and I hope the writing is otherwise going well ;) ).

**Comment by kaikreuzer** [comment]
The generation was actually done by me, but the files end up in `_addons_bindings` and I assume that some copy-task needs to be adjusted. As I am not fully aware of all this copying mechanism anymore, I'd rather leave it to @ThomDietrich to adjust it...

**Comment by BClark09** [comment]
I had a look at this, the links are correct for github as they link directly to the .md files. But since they're served as .html files then the website will generate a 404.

e.g:
https://docs.openhab.org/addons/bindings/zwave/doc/things.html
https://docs.openhab.org/addons/bindings/zwave/doc/aeon_zw100_01_010.html

Either at the generation stage, or at the serving stage, `.md` needs to be replaced with `.html`.

**Comment by kaikreuzer** [comment]
Ah, thanks!
Yes, I think it should be html at generation stage already (as we have all links as html in the docs repo).
@cdjackson Could you adapt your generation accordingly? I'd then deploy an updated version.

**Comment by cdjackson** [comment]
> Either at the generation stage, or at the serving stage, .md needs to be replaced with .html.

I thought about that when I was looking at it yesterday and thought that the doc generation system must change the links from md to html. It has to change the link anyway as MD links are completely different to html hyperlinks.

It's a shame if we have to do this as it will means that the readme on github will have broken links, but if you confirm that that's how it works I can update and we just live with the broken readme on github.

**Comment by kaikreuzer** [comment]
Afaik, we have to live with the broken links on Github.

**Comment by BClark09** [comment]
Is https://github.com/openhab/openhab-docs/blob/gh-pages/process_addons.groovy the file used to copy over the task? IMO it would be better to add a replace all ".md)" with ".html)" for each line in each file taken in, but I understand this might be a resource intensive action.

**Comment by cdjackson** [comment]
I would also prefer to fix it in the processor if possible...
