### ISSUE TITLE
Telegram action documentation

### ISSUE THREAD

**Issue by vzorglub** [openhab/openhab-docs#643]
I had a hard time with the configuration of the telegram action.
One issue is getting the chatId! But this is Telegram's fault and not very well documented and pretty unreliable.
It appears that Group chats have a chatId that is prefixed with a "-". On node red, the telegram node ignores that and "it just works" but OH needs the prefix. So I propose the following amendment (In Bold).

-     Open a new chat with your new Bot and post a message on the chat
-     Open a browser and invoke https://api.telegram.org/bot<token>/getUpdates (where <token> is the authentication token previously obtained)
-     Look at the JSON result and write down the value of result[0].message.chat.id. That is the chatId. **(Please note that Group Chats have a chatId prefixed by "-". Include the "-" in the conf file eg: bot1.chatId=-22334455)**

**Comment by bgilmer77** [comment]
Hi @vzorglub, thank you for posting this issue.  I do not use Telegram, but I will open a Pull Request and post your suggested fix.

However, I need to ask a favor please.  If I am not mistaken, the Telegram Action is from OH1, and so it is part of the openhab/openhab1-addons repository.  Could you please repost this issue in that repository and close this one?  Once I see it posted there I will work on the Pull Request.

Best regards,
Brad

**Comment by vzorglub** [comment]
I think I have created a pull request myself directly on the readme file

Please check and let me know if I did it right!

Thanks

**Comment by bgilmer77** [comment]
I looked but I do not see it.  I also did not get a notification of a new PR.  Where did you post this?

**Comment by vzorglub** [comment]
In the openhab1-addons report, I believe.

Regards

**Comment by bgilmer77** [comment]
Interesting - I am in /openhab/openhab1-addons, and the PR at the top is openhab/openhab1-addons/#5490, which has to do with Telegram, but it is not your PR, and the subject of the PR is not your work.

**Comment by vzorglub** [comment]
Ok
I must have done it wrong then.
I am new at github.
I'll try again.

Regards

**Comment by bgilmer77** [comment]
Ok. Let me know if I can help.

**Comment by Confectrician** [comment]
telegram Action can be found here:
https://github.com/openhab/openhab1-addons/tree/master/bundles/action/org.openhab.action.telegram

**Comment by vzorglub** [comment]
I think I got it right this time....
My pull request is on the list this time

Regards

**Comment by vzorglub** [comment]
I think I got it right this time....
My pull request is on the list this time

Regards

**Comment by bgilmer77** [comment]
I see your PR!!!  Thank you for being persistent, and congratulations.  I am still learning a lot about GitHub and Git myself, so I know that it can take a lot of work to understand how to do things.

I will comment on your PR `openhab/openhab1-addons#5497` now.

**Comment by bgilmer77** [comment]
I am closing this issue since there is now a PR openhab/openhab1-addons#5497.
