### ISSUE TITLE
XLST documentation lost.

### ISSUE THREAD

**Issue by Josar** [openhab/openhab-docs#647]
https://docs.openhab.org/addons/transformations/xslt/readme.html
https://github.com/openhab/openhab1-addons/wiki/Samples-XSLT-Transformations

In the old wiki there is almost perfectly explained how the XLST transfomation works and how to solve basic probles like namespace.

Somehow the new page does not reflect anything of that. Is this on Purpose?

This question rises up as there are people asking questions adressed on the old wiki.

https://community.openhab.org/t/xsl-transform-in-a-rule/40410/5

**Comment by Confectrician** [comment]
Maybe it simply hasn't been ported yet.
I don't think that this was on purpose.

Im not working with xlst.
Would you like to add this content to the docs and file a PR here?
I can of course help on GitHub and contributing topics.

**Comment by Confectrician** [comment]
And maybe we have to add this change to the eclipse smarthome repo.
I have ported the JSONPATH article some time ago and had to move my contribution to that repo too.

**Comment by Josar** [comment]
https://github.com/eclipse/smarthome/pull/5137

**Comment by Confectrician** [comment]
Wow, that was fast.

I will make a review over there.
