### ISSUE TITLE
Add-ons: DMX binding manual missing options and error in example

### ISSUE THREAD

**Issue by c5n** [openhab/openhab-docs#650]
Please add missing thing options:

fadetime, dimtime
I guess "fade" is obsolete?

**Issue in Full Example / demo.item**

`Color MyColorItem "My Color Item" { channel="dmx:dimmer:rgb:color" }`
should be
`Color MyColorItem "My Color Item" { channel="dmx:dimmer:mybridge:rgb:color" }`

**Comment by Confectrician** [comment]
Hi @c5n,

Binding Docs are maintaned in the corresponding binding source folder.
This is done this way to keep the docs up to date according to changes in the binding itself.

In this case, the corrext place for a fix would be 
https://github.com/openhab/openhab1-addons/blob/master/bundles/binding/org.openhab.binding.dmx/README.md
Maybe you could create a **pull request** there with the added and correct informations.

If there's anything confusing about how to do this and what has to be done additionally ([Contribution Guide(lines)](https://github.com/openhab/openhab-distro/blob/master/CONTRIBUTING.md) and especially sign-off), feel free to poke me here.
I will answer all questions, as far as i am able to do so. 😃

**Comment by c5n** [comment]
Hi @Confectrician 
thanks for the hint, but it is a OH2 binding and I only could find the documentation in
https://github.com/openhab/openhab-docs/tree/2.2-patch/_addons_bindings/dmx 
so I thought this would be the right place.
I'm unable to locate the dmx binding at https://github.com/openhab/openhab2-addons/tree/2.2.x/addons/binding

Sorry for the confusion, I'd like to contribute if I'm able to find and understand the (non familiar java) binding code.

Regards,
Carsten

**Comment by Confectrician** [comment]
Hi Carsten, i just recognized that.

If it is OH2 and it isn't in the openhab2-addons repo, it is always worth to have a look into the eclipse smarthome repo which has some bindings too beneath the meain framwework part.

https://github.com/eclipse/smarthome/tree/master/extensions/binding/org.eclipse.smarthome.binding.dmx

Here we go.
Updates will then be included with one of the next OH releases and after a stable smarthome version has been fetched into OH core.

**Comment by c5n** [comment]
Thank you very much for pointing that out. And there it is: The documentation is up to date over there.

But that's weird. The DMX binding I use with raspbian on my Pi already accepts the options described at the eclipse smarthome site but the documentation over here is outdated. It took me many hours of double and triple checking my definitions word by word, and lots of readings in the forum until I've found a code snipped of well formed definitions in one of the posts to get the clue. That was a lot of misspend time. :( I guess I was not the only one. 

To be honest, now I'm aware of possible wrong documentation and will double check before I search an error on my side.

Do you see any chance to avoid such situations?

Thanks,
Carsten

**Comment by Confectrician** [comment]
Unfortunately no. 

That's the open source way.
"It's done when it's done."

The mechanism itself is pretty good and logical. 
It makes sense to maintain the documentation in a place where the binding code is maintained too. 

As said, all Readme files are fetched from time to time and then the homepage gets all meanwhile made updates in one run. 

We could of course check if there's something wrong with the smart home repo fetch on the next run.
