### ISSUE TITLE
Paper UI: Add action should show the thing name

### ISSUE THREAD

**Issue by uhafner** [openhab/openhab-docs#651]
When I create a new rule using Paper UI and create a new 'Then'->'Send Command' element, then the dialog 'Add Action' shows for the Select box (Configurations -> Item) the Type Name of the Thing (e.g., Blinds Control) and the internal ID. It would be more user friendly to show the actual name of the thing here. Otherwise it is hard to choose the correct one.

![bildschirmfoto 2018-03-05 um 23 45 56](https://user-images.githubusercontent.com/503338/37004262-19d1de56-20d0-11e8-8d7c-6287ac4744ff.png)

**Comment by kaikreuzer** [comment]
Why is that a documentation issue? Is there anything wrong in the docs?
The list that is shown is that of your Items, not Things. For Items, their label and their name are shown, which is the correct information to clearly identify them.

**Comment by uhafner** [comment]
Sorry, wrong project, should have been the main project. 

Is the item label and name configurable using the Paper UI? Seems that I can only edit Things.

**Comment by kaikreuzer** [comment]
Yes, it is configurable, but the "Items" menu entry is only visible if you disable the "simple mode" for item creation (you find it in the Paper UI under Configuration->System->Item Linking).

For the simple mode, I agree that the default item names/labels are not ideal when being used in the rule engine, but I don't have any much better suggestion than showing the item name, which is at least unique.

**Comment by uhafner** [comment]
I see, I found the settings. I can't change the names but this is something different what I need to investigate (Error 405 - Item is not editable). Thanks for the pointers.

**Comment by kaikreuzer** [comment]
Right, you cannot edit the ones that had been automatically created from simple mode - only the items that you create manually (e.g. by activating a new channel) can be edited.
