### ISSUE TITLE
broken link pointing to openHab documentation

### ISSUE THREAD

**Issue by digicos** [openhab/openhab-docs#652]
I was reading about the openHab Cloud Connector on below URL
[http://www.myopenhab.org](http://www.myopenhab.org)
Under section 

> openHAB Runtime
link to openHAB 2.0 results in 404.

**Comment by kaikreuzer** [comment]
> I think the mentioned page is under your control.

No, as almost anything, this is also available on Github 😎 : https://github.com/openhabfoundation/myopenhab.github.io/pull/8
