### ISSUE TITLE
FR: Client certificate authentication Howto

### ISSUE THREAD

**Issue by mueller-ma** [openhab/openhab-docs#656]
The Android client supports authentication via client cert, but there is no explanation how to configure it server side. I think it should be on this page: https://docs.openhab.org/installation/security.html

See https://github.com/openhab/openhab-android/issues/333

**Comment by Confectrician** [comment]
Great idea.

Do we have a tutorial or something similar in the community for that, we could reference too in a fist step?

**Comment by slawekjaranowski** [comment]
Hi, 
I started some discussion on https://community.openhab.org/t/using-nginx-reverse-proxy-for-client-certificate-authentication-start-discussion/43064

**Comment by Confectrician** [comment]
Hey @slawekjaranowski,

Would you like to take over this issue and file a PR, when the discussion produces some results and we have a content base for a tutorial?

BR
Jerome

**Comment by slawekjaranowski** [comment]
Ok, if we will have some content I can prepare PR.

**Comment by gitMiguel** [comment]
Forum discussion didn't give much but I think that @slawekjaranowski 's tutorial is quite enough. As this depends on nginx it should be added under [running-openhab-behind-a-reverse-proxy](https://www.openhab.org/docs/installation/security.html#running-openhab-behind-a-reverse-proxy).

And it should be mentioned here [ssl-certificates](https://www.openhab.org/docs/installation/security.html#ssl-certificates) with a link.
