### ISSUE TITLE
openHAB & ESH contributing guidelines out-of-sync

### ISSUE THREAD

**Issue by martinvw** [openhab/openhab-docs#658]
@triller-telekom I noted today that especially the current vision of null handling is not reflected in the openHAB coding guidelines, AFAIK they should remain alligned, there also seem to be other differences. So it would be great if they could be re-alligned:

ESH has a more extensive A.12
openHAB has B.9 which is not available in ESH

It would be great if someone, maybe @triller-telekom could give this some love :-)

**Comment by triller-telekom** [comment]
Good point! I have created #659 to sync them again. Thanks for noticing.
