### ISSUE TITLE
Wrong alt property for presence.png (Prupose)

### ISSUE THREAD

**Issue by ItIsFelix** [openhab/openhab-docs#660]
Wrong alt property for Purpose->presence.png
[_addons_iconsets/classic/readme.md](https://github.com/openhab/openhab-docs/blob/gh-pages/_addons_iconsets/classic/readme.md)

`<img src="icons/presence.png" alt="presence-off " title="presence-off ">`

**Comment by Confectrician** [comment]
Hi @ItIsFelix 

Thanks for reporting, but the iconset comes from eclipse smarthome and is generated into our docs.
So we would have to fix and report it over there.

I will leave this issue open and have a look where to report this in the original source.

BR
Jerome

**Comment by Confectrician** [comment]
Hi @ItIsFelix,

I have opened eclipse/smarthome#5416 and will close this issue now.
