### ISSUE TITLE
Bindings Page broken.

### ISSUE THREAD

**Issue by Confectrician** [openhab/openhab-docs#661]
Somehow the build does somethign weird with the bindings page.
There are dozens of empty table rows and tbh i don't know from what they are generated.

The table rwos should rather be generated based on the addons_bindings folder,
but i can't see something wrong there.

cc: @kaikreuzer, @ThomDietrich

**Comment by Confectrician** [comment]
could maybe be related to #642

**Comment by kaikreuzer** [comment]
What exactly is the issue (where are the tables that you mention)? https://docs.openhab.org/addons/bindings.html looks all right to me...

**Comment by Confectrician** [comment]
If you scroll down long enough you should be able to See something like this:
![screenshot_20180407-235334](https://user-images.githubusercontent.com/7161177/38460730-05c82550-3ac0-11e8-9815-df1462725f65.png)

**Comment by kaikreuzer** [comment]
Oh, indeed :-)
As it happens right above Z-Wave, I agree that it could be related to #642.
I'd hope that @ThomDietrich has some input here...

**Comment by Confectrician** [comment]
Addition which i was too lazy to write from mobile:

I was working on a fix for the bindings selection javascript and noticed that it doesn't seem to broken in the v2.2 and v2.1 docs versions. So some of the newer changes have to break something.

**Comment by kaikreuzer** [comment]
It indeed is related to #642 as all those entries refer to Z-Wave devices:

<img width="645" alt="screen shot 2018-04-09 at 10 39 54" src="https://user-images.githubusercontent.com/3244965/38488017-65d6c302-3be2-11e8-8773-432bbfb598aa.png">

I have to admit that I have no clue how the bindings.html is generated - I hope @ThomDietrich can shed some light on this.

**Comment by Confectrician** [comment]
Would be very cool indeed.
I would have to dig into that special case from scratch too.
At leeast some overview of how it works would be nice to provide a fix myself maybe.

**Comment by kaikreuzer** [comment]
@ThomDietrich Any chance you could share your wisdom here? This bug is pretty annoying...

**Comment by BClark09** [comment]
I had a look at this while I was looking at #678, there's my best guess as to why this happens in the PR above.

**Comment by Confectrician** [comment]
@kaikreuzer @BClark09 

I think this one is outdated due to the website relaunch and we can close?

**Comment by BClark09** [comment]
Yep, this isn't an issue with the new website.
