### ISSUE TITLE
Add info/warning to old wiki articles

### ISSUE THREAD

**Issue by ThomDietrich** [openhab/openhab-docs#67]
This is a task for whoever wants to contribute and is looking for a starting point:

New updated articles for openHAB 2 are written here, while the old articles in the wiki are still valid for openHAB 1.8. The problem is, that a user searching for a topic in the forum or via google may end up in the 2.0-vise outdated wiki article.
That's why, we need to add an information (highlighted, ...) at the beginning of each wiki article, informing users about the openHAB 2 article over at docs.openHAB.org.

Example: https://github.com/openhab/openhab/wiki/Astro-binding --> http://docs.openhab.org/addons/bindings/astro/readme.html
##

**Comment by ThomDietrich** [comment]
Example: https://github.com/openhab/openhab/wiki/Astro-binding
I'm asking for feedback, before this is copied to (nearly) all wiki articles.
As you can see, there are two options:

@rkoshak @kaikreuzer @joergkling 

## openHAB 2

This wiki article is only valid for **openHAB 1.8**.
For an updated documentation on the use with **openHAB 2**, please visit:

http://docs.openhab.org/addons/bindings/astro/readme.html

## openHAB 2

This wiki article is only valid for **openHAB 1.8**.
An updated **version for openHAB 2 is not yet available**.

* If you were are looking for a documentation on openHAB 2, please visit: http://docs.openhab.org

* If you are interested in a specific topic, not yet documented for openHAB 2, please handle the following information with care and refer to the community forum for any questions: https://community.openhab.org

**Comment by rkoshak** [comment]
So the change only has to be made once and to avoid confusion I would say "openHAB 1.x" instead of the specific 1.8 version. The confusion comes in as there are in work updates to bindings labeled and referred to as version 1.9.

I personally like the first option if for no other reason then we will not have to come back and change it again later. With the latter option as the openHAB 2 documentation matures it will need to be updated to remove the second bullet.

We might consider a hybrid where we point them to the OH 2 docs and suggest asking a question on the forum if they still have questions. That nicely deals with the problem of missing docs yet is generic enough to not require changing every article twice.

Also, saying "is only valid for" is a little strong. If an OH 2 user is running OH 1.x bindings through the compatibility layer, these wiki pages, especially the binding pages, are indeed valid. Also certain pages like sitemap and rules are also still valid. So maybe we need to make that statement less strong. Something like

> This wiki article was written for openHAB 1.x. For openHAB 2 documentation please visit:

**Comment by ThomDietrich** [comment]
Having a hybrid to not come back sounds reasonable. Sadly collides with my wish to directly link to the corresponding article (like shown for astro).

1.x - check
less strong - check

I guess there is a difference regarding the compatibility layer: While sitemap and such are slowly adopted to docs, the OH 1.x bindings will stay in the wiki. We would confuse users if the wiki told them to search for a corresponding article in docs...

**Comment by rkoshak** [comment]
I don't know if it completely collides with providing a direct link to the corresponding article, where possible. I think this particularly makes sense for the bindings pages. I think there are a lot of really good reasons to do that, particularly for those bindings where there is a 1.x version and a 2 version and those the two work differently.

So maybe we do need to plan on coming back and editing twice.

**Comment by ThomDietrich** [comment]
Re-edited once. You can just add whatever you feel is right: https://github.com/openhab/openhab/wiki/Astro-binding

**Comment by Clocker** [comment]
I prefer the first option, the direkt link from 1.x binding to the correspondent 2.x binding is enough.

A user who starts to play with bindings, allready knows about that there exists two implementation philosophies. (At least during installation time he decided which server to install)

The problem at the moment is when you search openhab together with a binding option you will land mostly on the 1.x wiki. (This will change automatically in the near future when openhab2 becomes more popular)
If a user follows the link he will land on the oh2 binding. At the same time the user takes notice about the new documentation philosophy and starts browsing within the new structure.

The question for me is: Will all 1.x bindings be moved to the oh2 philosophy? When yes, then you should create for every binding an oh2 landing page. 
If the binding is allready ported to oh2 it will contain the help, if not it will contain an link to the correspondend [http://docs.openhab.org/addons/1xaddons.html](url) page. If the binding will not be ported and its not compatible than the landing page is just telling the user that.

**Comment by rkoshak** [comment]
> The question for me is: Will all 1.x bindings be moved to the oh2 philosophy? 

No.

> you should create for every binding an oh2 landing page. 

That is the plan and the acceptance of a PR will be contingent on the author updating their binding's documentation page. Documentation for OH 2 bindings has not started yet as far as I'm aware. But the main point is that the writing of the binding page for each binding is the responsibility of the binding authors, if I understand Kai's intent correctly.

> If the binding will not be ported and its not compatible than the landing page is just telling the user that.

All OH 1 bindings are compatible with OH 2 through the compatibility layer. So there really isn't such a thing as an incompatible binding. Instead there are OH 2 native bindings and legacy OH 1 bindings. In many cases the developers have created an OH 2 version of a binding but what that really means is there is now two bindings, both of which are compatible with OH 2 but only one of which is OH 2 native.

**Comment by ThomDietrich** [comment]
This is still an important TODO.
Yet another example: https://community.openhab.org/t/how-to-organise-group-items-in-paper-ui-dashboard-layout/13634

**Comment by dmcwhinnie** [comment]
We should also add details about the configuration files for the bindings.  
in 1.x we prefixed the settings with the add-on name.  in 2.x we use a separate file for each binding.

for example using weather binding.

1.x
weather.location.home.latitude=35.0906884
2. 
location.home.latitude=35.0906884

**Comment by ThomDietrich** [comment]
Also see https://github.com/openhab/openhab-docs/issues/190

**Comment by dmcwhinnie** [comment]
I agree, it makes sense to not put it in the 1.x binding docs.

**Comment by svenb** [comment]
Is this still a "thing", I would like to contribute.

**Comment by Confectrician** [comment]
Hi @svenb,

Yes this is still a "thing" and you could start contributing over there.

Personally i would prefer the warning to be somewhere on top of the wiki articles and not at the botton like it is dine in the example article @ThomDietrich linked in the first post here.

I think it would be frustrating to try "wrong things" and then realize you where at the wrong place after reading all of the article.

Feel free to answer here or contact me, if you need some advice or help. :)

**Comment by Confectrician** [comment]
Search and find. (Sorry)

There is no list as far as i know.

**Comment by blilleike** [comment]
At the moment all wiki pages seem to have a 2.0 note at the bottom of the page.
I can't edit those pages so I can't check if this is generated or by hand.

If by hand, I did not find any page by randomly picking them, where it was missing.
I would agree to putting it on top and would volunteer to do so when given the needed rights.

**Comment by Confectrician** [comment]
@kaikreuzer do you know if wiki write access was refused?
I could imagine that this was done on purpose to force people to contribute to the docs instead of contributing to an outdated wiki.

**Comment by kaikreuzer** [comment]
Yes, afair, this was the reason.

**Comment by Confectrician** [comment]
Should we then leave it as is and close this issue?

**Comment by kaikreuzer** [comment]
What is open? The question whether it is at the top of the bottom?
I'd think it is good enough to have it at the bottom, so if you ask me, we can close it.
If somebody wants to go through the effort and move the notice to the top on all pages, we can also temporarily re-enable editing of the wiki - fine for me as well!

**Comment by Confectrician** [comment]
I would then also vote for closing this issue and focus on improving the docs.
