### ISSUE TITLE
Identify channels on Things

### ISSUE THREAD

**Issue by digicos** [openhab/openhab-docs#674]
I read through the documentation on this page
[https://docs.openhab.org/configuration/things.html](url)

point 4. of below link specifies to identify channels of the Thing to be added.
[https://docs.openhab.org/configuration/things.html#defining-things](url)
I was trying to find how exactly can I specify the "channel" in the "Thing" definition (using files). This is where it get confusing, whether the Thing has a channel?, if it has then where do I define it. Does the "channel" definition come into picture when defining "items"?

The below paragraph adds to more confusion

> It is important to note, that Channels of discovered Things can also be linked to Items defined in .items files. In order to link a Thing to an Item in an .items file, open the Thing in Paper UI under Configuration → Things. In the list of Thing Channels, look for the Channel you wish to link to an Item and copy the Channel’s ID. For instance, a Z-Wave switch might have a Switch Channel that has an ID like this

the above suggested that I had to somehow create a channel for my Light Switch Hardware.

I am using MQTT 1.1 binding, so in this case it was very confusing initially, how do I go about defining a channel for the  Hardware Switch and linking that to the OH Switch Item declared in the .items file. I have my own switch hardware which I want to setup with OH, using MQTT binding.

This [Community Post](https://community.openhab.org/t/channel-mqtt-formatting/31214/4) helped me identify the integration approach.

**Comment by udo1toni** [comment]
For OH1 Bindings, there aren't no things and no channels. Things and Channels are OH2-Binding-only.

**Comment by digicos** [comment]
Thanks @udo1toni for clarification. This becomes evident though when you start experimenting with the bindings.. Initially when I read the documentation, I thought we have to specify channels on "Thing" definition and I couldn't find a place..I feel the documentation lacks some pointers and example there..

**Comment by bgilmer77** [comment]
@digicos, thank you for pointing this out.  We tried to not carry too much over from OH1 when we moved to the OH2 documentation.  A lot has changed between these two major releases.  At some point it became quite difficult to document both releases in a single document; we found people were getting very confused about what worked in one version but not the other.  We on the documentation team need to think this through.  I know how frustrating it can be when things don't match what you are reading.  We can leave this issue open and see if others have any suggestions.

**Comment by JueBag** [comment]
I know I'm bit with this comment, however shouldn't something like the "Defining Channels" chapter  from the [Eclipse Smarthome Documentation](https://www.eclipse.org/smarthome/documentation/features/dsl.html#defining-channels)   be added to the openHAB docs?
I could do that!

**Comment by Confectrician** [comment]
Hey @JueBag 

Great idea, may i invite you to join the discussion here:
https://community.openhab.org/t/migration-due-to-esh-reintegration/64754?u=confectrician

This is indeed one aspect we should move into the oh docs, but there will be others for sure.
We appreciate any help with orga, looking through esh docs, maing proposals and of course provide pull requests.

BR
Jerome
