### ISSUE TITLE
Misspelling in Further Configuration Steps in openHABian - Hassle-free openHAB Setup

### ISSUE THREAD

**Issue by bdollerup** [openhab/openhab-docs#676]
In the " Further Configuration Steps" section of the  openHABian - Hassle-free openHAB Setup article there's minor grammar/speliing issues. The paragraph Passwords contains the text "This is especially important of your system is accessible from outside your private subnet." it should be "This is especially important if your system is accessible from outside your private subnet."

**Comment by Confectrician** [comment]
Hi @bdollerup 

Thanks for pointing out this issue.
The openHABian article is maintained in the [openhabian repo](https://github.com/openhab/openhabian).
We grab it from time to time and update all Binding docs and content like this in one run.

For openHABian the file would be:
https://github.com/openhab/openhabian/blob/master/docs/openhabian.md

## What does that mean now?

The issue you are pointing out has to be filed in the right place.

I have filed openhab/openhabian#394 to bring it to the right place and corrected it immediately.

**Comment by Confectrician** [comment]
Fix has already been merged.
