### ISSUE TITLE
Add setup description for existing installation of Eclipse IDE

### ISSUE THREAD

**Issue by claell** [openhab/openhab-docs#677]
Currently https://docs.openhab.org/developers/development/ide.html only covers new installations. I'd like to have also a guide for setting up existing installations.

There is also a forum entry: https://community.openhab.org/t/add-openhab-to-existing-eclipse-setup/44070 but I am not sure whether that covers everything and also think that an official entry in the docs would be nice.

**Comment by amosk** [comment]
Agreed. After cloning openhab-core and adding to Eclipse there are many dependency errors that can dissuade users from getting started. 

I would add that a full tutorial for how to clone and compile from the command line would be useful for people running and building Openhab on headless systems.

**Comment by claell** [comment]
> I would add that a full tutorial for how to clone and compile from the command line would be useful for people running and building Openhab on headless systems.

Since that is a separate topic I'd also create a separate issue for that.

**Comment by Confectrician** [comment]
We are reworking the complete developers section, which will then cover this.
There will be new issues for left ToDo's.
If there's still something missing/wrong after the refactoring, we should document that in a new issue.
Therefore i will close this one now.
