### ISSUE TITLE
Pushbullet Binding Configuration

### ISSUE THREAD

**Issue by fuslwusl** [openhab/openhab-docs#682]
I had trouble finding the correct pushbullet binding configuration - but now it's working.
The following infos would have been helpful for me on this page:
https://docs.openhab.org/addons/actions/pushbullet/readme.html#creating-an-account-for-your-bots

**Please add this additional info on the binding page to help others:**

The Example on the page shows this code for use in rules:
`sendPushbulletNote("mybot", "someone@somewhere.com", "this is the title", "And this is the body of the message")`

**You do not need a specific bot like "mybot" - you can just use "DEFAULT".**

### EXAMPLE (for use in rules)
`sendPushbulletNote("DEFAULT", "someone@somewhere.com", "this is the title", "And this is the body of the message")`

In my case the file services/pushbullet.cfg was missing after installing the binding.
It the file ist missing just create one with the following content:

### EXAMPLE (configuration file services/pushbullet.cfg):

```
#################################
# PushBullet Binding
#################################
#
# accesstoken can be found under settings, when you login to www.pushbullet.com 
accesstoken=??????????????????????????????????
# choose a device name for your openHAB-Client
devicename=OpenHAB
# defaultreceiver of your pushes (Nickname of one of your devices)
defaultreceiver=Honor8
```

This example configuration is working with the lates version of OpenHAB.

**Comment by Confectrician** [comment]
Hi @fuslwusl 

Thanks for pointing out this issue and sorry for the late response.
All of our Binding Documentation is maintained in the corresponding Add-on Repos beneath the Binding code.
We grab it from time to time and update all Binding docs in one run.

For pushbullet the file would be:
https://github.com/openhab/openhab1-addons/blob/master/bundles/action/org.openhab.action.pushbullet/README.md

## What does that mean now?

The issue you are pointing out has to be filed in the right place.
In your case this would be the **openhab1-addons** Repository.
https://github.com/openhab/openhab1-addons/issues

I have filed openhab/openhab1-addons#5581 to bring it to the right place.
