### ISSUE TITLE
Update-external-resource: Google Assistant USAGE

### ISSUE THREAD

**Issue by ThomDietrich** [openhab/openhab-docs#690]
Thanks to @marziman there is now a USAGE.md to be pulled over (or integrated. I'm currently not in ther loop regarding the whole `website` endeavor)

All details: https://github.com/openhab/openhab-google-assistant/issues/33

**Comment by Confectrician** [comment]
@ghys can we pull this directly through website generation or do we need to pull it over to the docs first?

Or do i rush too fast and should we wait for a/the new generation process to be finished?

**Comment by ghys** [comment]
It should transit through here like the Alexa & Mycroft skills I think - so they can be versioned, tagged along with the rest of the docs.
IMO It seems counterintuitive to treat those external skills as "io" add-ons though (they're not add-ons), maybe that's something to improve in the process along with the automation, but it's not too important either: the website prepare-docs script knows about them and moves them in the "ecosystem" section as appropriate.

**Comment by ThomDietrich** [comment]
@ghys at the time there was no better place to put them and from the end users perspective they are "integrations" just as the others (addons). I was btw never really satisfied with the "Add-ons" menu title. It is a technical term and excludes a lot of valid candidates (like the Google Assistant or let's say loosely linked integration of Grafana, maybe not the best example)

Anyhow. For now I'd say let's just add it to the update-external-resources script. @Confectrician would you like to try?
