### ISSUE TITLE
New documents system - Bindings?

### ISSUE THREAD

**Issue by pmknowles** [openhab/openhab-docs#701]
New documents system is great. Well done!
But...
Bindings are missing from the side menu of the Configuration Guide and the Bindings [link](https://www.openhab.org/docs/addons/bindings.html) gives a 404 error

**Comment by ghys** [comment]
This page (https://docs.openhab.org/addons/bindings.html) was only a list and the equivalent is now at https://www.openhab.org/addons/ along with the other types.

@Confectrician this made me realize the _Installation of Add-ons_ (https://docs.openhab.org/addons/#installation-of-add-ons) paragraph is not of the website, it would be good to move it to the Configuration Guide (/configuration/addons.md), this is valuable content.

> the Bindings link gives a 404 error

Might still happen, on which page?

**Comment by Confectrician** [comment]
I think this one is solved due to the last commits today.

Thanks for pointing us in the right direction.
