### ISSUE TITLE
what's the senaro for two channels connect one item

### ISSUE THREAD

**Issue by wilfredvon** [openhab/openhab-docs#703]
AS shown in the following link "https://www.eclipse.org/smarthome/documentation/concepts/index.html#things-channels-bindings-items-and-links".
"Channels may be linked to multiple Items and **Items may be linked to multiple Channels**."

when should we connection two channels to one ITEM?  are there any misunderstanding?

**Comment by Confectrician** [comment]
Hey @wilfredvon,

This only state, that it is possible to do so but not needed strictly.

I think a good example for this is the [expire binding](https://www.openhab.org/addons/bindings/expire1/).
You can attach the expire binding channel to an item that already uses some other channel for its working purpose.

Does that clarify the text for you?
