### ISSUE TITLE
Update to CONTRIBUTING.md needed

### ISSUE THREAD

**Issue by eikowagenknecht** [openhab/openhab-docs#709]
I recently started getting a feel for openhab and since am new to this community. Reading the documentation, I found some minor problems and opened pull requests to correct them. In this process, I stumbled over a few things that are imho not explained well and would best be put in the CONTRIBUTING.md file. Those things are:

# Overview over documentation generation

I would like to see a quick overview of how the docs are generated. This would be especially useful to understand why some files have to be edited in this project and others have to be edited in the respective source repositories (e.g https://github.com/openhab/openhab-docs/blob/gh-pages/installation/openhabian.md vs. https://github.com/openhab/openhabian/blob/master/docs/openhabian.md). I am still not sure where exactly to edit this file, because **both** contain a tag  

> 

I know the structure might change in the future (#665), but until then a documentation would be a first step to stop people from editing files in the wrong places.

# Internal Links

I would like to read there how the internal linking should be structured, especially since it is used in various ways throughout the documentation. Which one should it be? Seen here are for example:
- {{base}}/administration/logging.html
- {{docu}}/addons/uis/habmin/readme.html
- ../addons/uis/habmin/readme.html

# Style Guide

There is a file **styleguide.md** but it is not referenced from the contribution guidelines. Should it be followed? Is it up to date? Then I suggest linking to it from the guidelines. 

In the style guide, There is a link to http://www.cirosantilli.com/markdown-style-guide/. This gives some options. It would be nice to know which options especially should be applied in this project. For example:
- wrap:sentence (As @Confectrician told me to do in #707 but I can't find another source). I would suggest adding this to the styleguide.md.
- header:atx
- list-space:1
- code:fenced
- ...

What do you think?

**Comment by Confectrician** [comment]
Thanks for your effort.
I will answer later in detail, cause i am not at home now.

But one thing on the run:
The contribution guidelines are "one" document for many repos/parts of openhab and eclipse smarthome which is shared and we have to keep that in mind.

there were already thoughts about this but i need some time to look for the correct issue.

**Comment by Confectrician** [comment]
Here you go: #648

So we have those contribution guideline files for every repo and we are already thinking about a sync process.
The main problem is that there is some type of _generic content_ and always some type of _dedicated content_ which we have to keep in mind.

So yes: 
I think it is good to bring up this topic, but i don't know if the docs are the right place to start with it.

**Comment by eikowagenknecht** [comment]
Closing my issues with openHAB that seem to have gone stale.
