### ISSUE TITLE
[installation] Restructure the whole area and adapt it to the download page?!

### ISSUE THREAD

**Issue by Confectrician** [openhab/openhab-docs#711]
I have already seen some "my download was wrong, but i used the links from the docs" posts in the community.

We should from now on only point to our download page.
If something changes, we only have to fix it there and all doc pages will be fine without the need to touch them again.

**Comment by Confectrician** [comment]
i was nearly already starting with fixing some urls when i struggled a bit.

Since we have got "short installation instructions" already on the download page
it maybe would make sence to rework the installation section in complete, to adapt it to the new website structure.

I would like to have some feedback first.

**Comment by MyRaceData** [comment]
I think we have two issues here. 
1. dead or incorrect links to downloads being mentioned in the documentation. I agree all links for downloading openHAB in the documentation should point to the download page only so bad links don't ruin the experience for a new user attempting to install the program and easier maintaining of the documentation. If I find any such links, I will create PR to fix
2. What you refer to as "short installation instructions" which are included on the download page are for Linux installations and may confuse users of other systems. I feel this section should be relocated in the Linux installation section and leave the download page just for download links and download instructions

**Comment by Confectrician** [comment]
>None the less, I'm still not convinced the download page is a good place for installation instuctions

Hey @ghys do you have an ide how we could deal with that?
@MyRaceData has a point here and we could simplify the website with providing only download relted information.

Maybe point to the corresponding docs section for each download type?

**Comment by ghys** [comment]
Sorry for missing this. I believe a lot of people just click on the Download page and want to get started quickly without skimming through the docs (although they probably will have to, hence the warning). That's why the download page has _simplified_ instructions.
