### ISSUE TITLE
Move the sidebar navigation definition for the website to this repo

### ISSUE THREAD

**Issue by ghys** [openhab/openhab-docs#717]
Instead of having to modify the website's [config](https://github.com/openhab/website/blob/743f0b867e4d26a5a6a3116a12f6344295ef25d6/.vuepress/config.js#L177) when e.g. a new page is added to the navigation, define it in a file in this repo and import it in the config during the website's build (like it's done for the add-ons except the file isn't generated but copied).

**Comment by Confectrician** [comment]
Maybe we should combine this with some changes for #665 and #700

**Comment by Confectrician** [comment]
@ghys can i help you with this somehow already?

**Comment by ThomDietrich** [comment]
@ghys (after a cleanup of the docs repo) why is a element-wise list needed? Can't you just import he whole repo...

**Comment by ghys** [comment]
> @ghys can i help you with this somehow already?

Actually I indended to do it while building the "preview" VuePress site we talked about, and put that into the resulting ".vuepress" folder - basically it's just a matter of copying https://github.com/openhab/website/blob/743f0b867e4d26a5a6a3116a12f6344295ef25d6/.vuepress/config.js#L177-L307 into a .js file and `require()`-ing it at the top.
Building the preview site would also require a refactoring [`prepare-docs.rb`](https://github.com/openhab/website/blob/master/prepare-docs.rb) (mainly put everything into subroutines with parameters for target folder etc., the website build script would import and reuse those subroutines), and moving it here as well.
I'll start working on it after #700 is in place.

> @ghys (after a cleanup of the docs repo) why is a element-wise list needed? Can't you just import he whole repo...

Ordering the sidebar links and controlling the title of certain entries which might differ from the title of the pages themselves - and generally staying in control :). This config is only for building the sidebar, basically it's the equivalent of https://github.com/openhab/openhab-docs/blob/gh-pages/_includes/user-menu.html

**Comment by ThomDietrich** [comment]
> basically it's the equivalent of https://github.com/openhab/openhab-docs/blob/gh-pages/_includes/user-menu.html

I see.
I'll have to do a deep dive once I am finished with my thesis and back in the game ;)

**Comment by Confectrician** [comment]
Hey @ghys if i am right this issue should have been solved by you some time ago correct?

We could close it then.

**Comment by ghys** [comment]
yep!
