### ISSUE TITLE
Remove GuessMainPID from installation systemd-file

### ISSUE THREAD

**Issue by sateffen** [openhab/openhab-docs#746]
The systemd file written in https://docs.openhab.org/installation/linux.html contains the config-field `GuessMainPID=yes`, even though `Type=simple` is set. According to systemd documentation https://www.freedesktop.org/software/systemd/man/systemd.service.html#GuessMainPID=GuessMainPID is ignored in this case and could be omitted.

**Comment by Confectrician** [comment]
Thanks for pointing this out. :+1:

**Comment by BClark09** [comment]
I think this file should be updated further, there's a couple of other issues which mean that it doesn't follow documentation:

- User created service files should be written in `/etc/systemd/system/`
- The start executable can bypass `start.sh` running `/opt/openhab2/runtime/bin/karaf server` (or `daemon`)
- The stop executable does not need to kill a PID. Instead use: `/opt/openhab2/runtime/bin/karaf stop`
- The documentation website is incorrect: use "https://www.openhab.org/docs/"

This would keep it similar to the the [service file installed by the apt package](https://github.com/openhab/openhab-linuxpkg/blob/master/resources/systemd/openhab2.service). I can create a PR when I test the following works:

```
[Unit]
Description=openHAB 2 - empowering the smart home
Documentation=https://www.openhab.org/docs/
Documentation=https://community.openhab.org
Wants=network-online.target
After=network-online.target

[Service]
Type=simple
User=openhab
Group=openhab
WorkingDirectory=/opt/openhab2
#EnvironmentFile=/etc/default/openhab2
ExecStart=/opt/openhab2/runtime/bin/karaf server
ExecStop=/opt/openhab2/runtime/bin/karaf stop

SuccessExitStatus=0 143
RestartSec=5
Restart=on-failure
TimeoutStopSec=120

LimitNOFILE=102642

[Install]
WantedBy=multi-user.target
```

**Comment by Confectrician** [comment]
> I can create a PR

I would appreciate that, since i am not that deep into the linux installation. :+1:
