### ISSUE TITLE
Links in navigation bar brocken.

### ISSUE THREAD

**Issue by Josar** [openhab/openhab-docs#750]
In the new Openhab documentation pages when pressing the sharp at the left side of the sections i would expect the adress to be shown at the top in the navigation bar. This helps generating links for referencing.

Somehow when i click at the sharp now it brings the sub/section to the top and changes the adress but than jumps back to the section address. Scrolling along the page also only lists the sections and no subsections in the adress bar.

I would like to have all clicked links to be keptin the address bar, no matter which hierarchy, so i can copy it for referencing.

**Comment by Confectrician** [comment]
cc @ghys this seems to be a https://github.com/openhab/website issue

**Comment by ghys** [comment]
This is caused by https://vuepress.vuejs.org/default-theme-config/#active-header-links

Debatable whether it should be disabled or not. I kind of like it.

You can right-click on the sharp symbol and select "Copy link address" or similar to get the actual address of the section.

**Comment by Josar** [comment]
@ghys I am not in favor of disabling it. But it only considers sections not sub or subsub sections. So basically I would like this feature to be extended.

Thank you for the hint with the link. 
This helps me, but sometimes I find references from other people which copied the address line, this will point far away from the solution when the section has multiple subsections and so it will confuse someone which does not know what he actually is searched to find the right spot.

**Comment by Josar** [comment]
maybe someone with some insight will take care see https://github.com/vuejs/vuepress/issues/674
