### ISSUE TITLE
Broken Docs for Bindings

### ISSUE THREAD

**Issue by BrutalBirdie** [openhab/openhab-docs#761]
If you visit https://docs.openhab.org/addons/bindings.html after the ZoneMinder binding there is a void of empty bindings.
I tested this with Firefox and Chromium on Linux, Android Chrome, Firefox and Dolphin, MAC OSX Safari, Firefox and Chrome.

**Comment by kaikreuzer** [comment]
docs.openhab.org is outdated, you should follow the links to the new website - the old one is not maintained anymore.

**Comment by BrutalBirdie** [comment]
Ah.. Forgot about that one
