### ISSUE TITLE
The Actions Page is missing executeCommandLine

### ISSUE THREAD

**Issue by rkoshak** [openhab/openhab-docs#768]
The page the documents the core actions is missing executeCommandLine. I must have inadvertently left it out back when I copied the docs over from the old wiki.

**Comment by Confectrician** [comment]
Hey @rkoshak 

If you want to help us out a bit, you could write `Closes #XYZ` instead of `Adresses #XYZ` when you open a PR.
Seems GitHub doesn't understand the adresses keyword and we have to clos the issue by hand every time.
No big deal, but a smal improvement. :)

**Comment by rkoshak** [comment]
I didn't know. I'll do that from now on.
