### ISSUE TITLE
openHAB-Documentation: Updated Section DateTime Item

### ISSUE THREAD

**Issue by imtheuser** [openhab/openhab-docs#785]
The program code suggested in the documentation in section "[// Convert DateTimeType to Joda DateTime](https://www.openhab.org/docs/configuration/rules-dsl.html#datetime-item)" did not work for me.
@rkoshak proposed two options in this post:
https://community.openhab.org/t/error-timeinmillis-is-not-a-member-of-java-time-zoneddatetime/53079/3
Both worked for me.
I have therefore created a pullrequest (https://github.com/openhab/openhab-docs/pull/784) and replaced the existing code with @rkoshak 's two options.

As this is my first contribution to the docs I hope I did everything right. Also the first time I use github.

I'm asking for a maintainer to review my PR.
Thanks.

**Comment by Confectrician** [comment]
Hi @imtheuser,

Sorry for the delay.
All our docs people are very busy those days, so the time for a review can be a bit longer.

I will close this issue and we can then go on with dicussion in your relating pull request.

BR
Jerome
