### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by pfink** [openhab/openhab-docs#794]
@kaikreuzer: The license of this project is missing. I guess that's not intended, right?

**Comment by kaikreuzer** [comment]
Do you have a good suggestion under which license to put documentation?

**Comment by pfink** [comment]
I think we do not have so much options as it has to be compatible with EPL 2.0 because we copy some stuff from the ESH documentation...

**Comment by bgilmer77** [comment]
FWIW, I use the CC-BY-ND 4.0 license for documentation in some technical trade associations I am involved with.  But we may not have that option here.

**Comment by Confectrician** [comment]
>I think we do not have so much options

Is there an overview for the possible options available?
I have found the general license faq, but its really big an di didn't find any information like this on a quick look.

**Comment by kaikreuzer** [comment]
> because we copy some stuff from the ESH documentation...

That's a good point. So actually EPLv2 should be the only/best option then. Good thing about it is that it was designed to also cover documentation (which EPLv1 didn't).

**Comment by Confectrician** [comment]
Ok then EPLv2 it is. :+1:
Will you add the necessary stuff yourself?

**Comment by kaikreuzer** [comment]
Do we need anything more than https://github.com/openhab/openhab-docs/pull/796?

**Comment by Confectrician** [comment]
Looks ok to me.

**Comment by pfink** [comment]
> Is there an overview for the possible options available?

License compatibility is a quite complex topic. There is no comprehensive overview and as in many law topics, they can always be different opinions and court decisions about it. The best overview I know is [this site](https://www.gnu.org/licenses/license-list.de.html) by the GNU project. Basically my hint was a decent way of saying that we should use EPL 2.0 because we have the highest legal certainty there.

> Do we need anything more than #796?

Yes, we should also ensure that all branches do have the license as well (probably some of them can be deleted as well, but I don't know).

**Comment by Confectrician** [comment]
I will leave this one open and take care of the other branches.

**Comment by ghys** [comment]
> I will leave this one open and take care of the other branches.

You probably should leave the "final" branch alone though because the next merge by Jenkins will take care of it and add the file from master.

**Comment by Confectrician** [comment]
Weird.
Other repos work with a LICENSE file, alltough help mentions to give it a `.txt` or ´.md` extension.

https://help.github.com/articles/licensing-a-repository/

Anyways i think Kai could edit the repository settings and add the License there manually.

**Comment by kaikreuzer** [comment]
I did exactly what is described here: https://help.github.com/articles/adding-a-license-to-a-repository/#including-an-open-source-license-in-your-repository.

The only change I did was to remove [this part](https://github.com/openhab/openhab-docs/pull/796/commits/e66a79dee91a4a8ec48c5ea820d236b06723965f), which is not part of the license, but rather a template to be filled out if you use a secondary license - I thus don't think this should be kept there. Maybe this removal confuses the Github automatic license detection...

**Comment by Confectrician** [comment]
Did you set it up by hand now @kaikreuzer or did it just needed some time?

**Comment by kaikreuzer** [comment]
I didn't do a thing - so it was apparently just a matter of time.

**Comment by Confectrician** [comment]
I have added the license for the 3 version patch branches now.

I think most of the additional branches will get deleted on mid term.

**Comment by Confectrician** [comment]
@kaikreuzer have you any information about the structure branch?

It was updated 3 years ago and could be removed maybe.
wdyt?

**Comment by kaikreuzer** [comment]
Looked very outdated indeed, I have removed it.

**Comment by wborn** [comment]
> The only change I did was to remove this part, which is not part of the license, but rather a template to be filled out if you use a secondary license - I thus don't think this should be kept there. Maybe this removal confuses the Github automatic license detection.

Most certainly that change causes GitHub to not properly recognize the EPL-2.0 license. GitHub has no troubles to recognize the license on ESH as well as several OH repos that have a LICENSE file with the "Exhibit A" part.

**Comment by wborn** [comment]
According to [Detecting a license](https://help.github.com/en/articles/licensing-a-repository#detecting-a-license) GitHub uses [licensee](https://github.com/licensee/licensee) for this. The [EPL-2.0 license](https://github.com/licensee/licensee/blob/master/vendor/choosealicense.com/_licenses/epl-2.0.txt) in their repo also has the "Exhibit A" part. Based on the output posted in [issues](https://github.com/licensee/licensee/issues/312) it gives a confidence for the licenses. So changing the license will lower the confidence and may cause the license to be not correctly detected. If it's common to also have EPL-2.0 licenses without the "Exhibit A" part, it's probably best to create an issue for it in that repo. Then it also needs to be fixed and GitHub needs to update that Ruby Gem. :hourglass_flowing_sand:
