### ISSUE TITLE
docker instructions seem to be missing some steps

### ISSUE THREAD

**Issue by maxandersen** [openhab/openhab-docs#797]
trying to follow guide on https://www.openhab.org/docs/installation/docker.html and https://hub.docker.com/r/openhab/openhab/ but I keep getting:

`hab_openhab_1 exited with code 1`

and in the logs I see things like:

```
cmp: /openhab/userdata/etc/version.properties: No such file or directory
KARAF_ETC is not valid: /openhab/userdata/etc
```

seems like these files are assumed to be there.

I've committed my directory structure and docker-compose.yml to https://github.com/maxandersen/hab in case you want to take a look.

note: I did remove the reference to `/etc/timezone` since that does not exist on synology where I'm trying to get this to run - not sure if that can be the cause...I would have expected some other error though.

If I can figure out what is missing in the docs on this I'll happily submit PR's to fix/add to the docs :)

**Comment by maxandersen** [comment]
digged a bit deeper and I think it has something to do with user and group permissions.

docs explains how to create a user/group openhab with ids 9001 - that is not feasible/possible on synology.

I tried overriding user and group id of my own openhab user (i.e. 1027 and 65538) but in that case
the startup errors with:

```
 echo 'Starting with openhab user id: 1027 and group id: 65538'
+ id -u openhab
Starting with openhab user id: 1027 and group id: 65538
+ echo 'Create group openhab with id 65538'
+ groupadd -g 65538 openhab
Create group openhab with id 65538
groupadd: Permission denied.
groupadd: cannot lock /etc/group; try again later.
```

**Comment by kaikreuzer** [comment]
@cniweb Can you potentially assist here?

**Comment by maxandersen** [comment]
my thinking is that if I provided uid/groupids then it should not try create them.

**Comment by cniweb** [comment]
@maxandersen In you docker-compose file no user is set!
See: https://github.com/openhab/openhab-docker#user-and-group-identifiers

**Comment by maxandersen** [comment]
yes, since if i do it fails even harder. Thats my problem - no matter if I put a user or not it fails to start. frst comment is with user defined, second comment is without user.

**Comment by sapkra** [comment]
I have the same problem (running on a pi zero w). Have you found any solution for it?

**Comment by maxandersen** [comment]
No, unfortunately not.

**Comment by hannibal85** [comment]
Here is a write-up of my setup on Synology that works
https://community.openhab.org/t/docker-install-on-synology-how-to-create-use-with-no-home-and-no-shell/49815/6

I think the important step is to set the user ID as environment variable and NOT as user flag. This took me some time to find out as the docs on [dockerhub](https://hub.docker.com/r/openhab/openhab) state something different. I’m not sure if this is a Synology specific issue or just an issue in the docs. Can someone confirm this for any other OS?

If yes I'm happy to write a PR to fix this.

**Comment by cniweb** [comment]
@wborn Can you contribute something?

**Comment by wborn** [comment]
I get the same error with your [Git repo](https://github.com/maxandersen/hab):

```
openhab_1  | Launching the openHAB runtime...
openhab_1  | KARAF_ETC is not valid: /openhab/userdata/etc
```

But that's because you shouldn't mount empty directories into the container. If you mount empty dirs into the container it will not initialize them with the default content.

So if you remove them with `rm -rf config/openhab/*` at the root of the repo, it will initialize them with the default content and it works fine for me.

**Comment by wborn** [comment]
Also using --user causes permissions issues (https://github.com/openhab/openhab-docker/issues/221) and the an already existing  GROUP_ID in the container could cause issues (https://github.com/openhab/openhab-docker/pull/222).

I've also created a PR to update the installation docs for this https://github.com/openhab/openhab-docs/pull/856.

**Comment by Confectrician** [comment]
Can this be closed now @wborn ?

**Comment by wborn** [comment]
I think so. It should explain/resolve all issues @maxandersen has.

For some reason you need to create empty directories for volumes to be properly initialized when using Docker on a Synology NAS. Although according to the [docker run documentation](https://docs.docker.com/engine/reference/commandline/run/#mount-volume--v---read-only) this should not be necessary:

> When the host directory of a bind-mounted volume doesn’t exist, Docker will automatically create this directory on the host for you.

**Comment by maxandersen** [comment]
I haven't had time to try yet, but I would suggest to either update the broken synology docs or link to the blog from https://github.com/openhab/openhab-docs/issues/797 that explains it working on synology.

**Comment by Confectrician** [comment]
Hey @maxandersen 

Please see https://github.com/openhab/openhab-docs/issues/797#issuecomment-452638624
>I've also created a PR to update the installation docs for this #856.

@wborn already did an update of the docs, that why i asked if this issue can be closed then.
Could you verify the docs changes from #856 and give feedback if this is the "update" you suggested?
