### ISSUE TITLE
Create Experimental Next-Generation Rules Engine User's Guide

### ISSUE THREAD

**Issue by rkoshak** [openhab/openhab-docs#800]
The NGRE is complete enough to start some user's guides. This is is to track the work. An intial go at a first draft can be found on the forum at

https://community.openhab.org/t/working-with-paperui-rules-experiments/54669

I'm following the same approach I used to create the migration tutorial.

1. Create an initial version through collaboration on the forum
2. Incorporate suggestions and changes.
3. Summit a PR.

**Comment by rkoshak** [comment]
Agreed. I'm mainly focusing on writing everything I learn. It will need at least one round of editing before submitting the PR, maybe two. It is already extended to five posts and I expect at least two more.

**Comment by Confectrician** [comment]
I was on my way to play a bit with the experimental rule engine too and decided to wait, to test those guide according to my own usecases. :)

**Comment by Confectrician** [comment]
Outdated already.
We have to do somethign new for oepnHAB 3
