### ISSUE TITLE
Fix broken Links in PaperUI / Add-ons / Persistence tab

### ISSUE THREAD

**Issue by AngelosF** [openhab/openhab-docs#817]
OH 2.4.0 S1443

URL: http://OH2_IP:8080/paperui/index.html#/extensions?tab=persistence

Most of the doc links result to 404

Broken:
```
https://www.openhab.org/addons/persistence/gcal/
https://www.openhab.org/addons/persistence/jdbc-derby/
https://www.openhab.org/addons/persistence/jdbc-h2/
https://www.openhab.org/addons/persistence/jdbc-hsqldb/
https://www.openhab.org/addons/persistence/jdbc-mariadb/
https://www.openhab.org/addons/persistence/jdbc-mysql/
https://www.openhab.org/addons/persistence/jdbc-postgresql/
https://www.openhab.org/addons/persistence/jdbc-sqlite/
```

Hopefully this is the right place to open this issue...
I have no idea how to fix it... I will search and if I find, I will open PRs, but don't wait for me :)

**Comment by ghys** [comment]
Interesting... Those all seem to be OH1 addons.

1. gcal has no documentation: https://github.com/openhab/openhab1-addons/tree/master/bundles/persistence/org.openhab.persistence.gcal

2. the jdbc addons seem to be coming from the same addon: https://github.com/openhab/openhab1-addons/tree/master/bundles/persistence/org.openhab.persistence.jdbc and thus dont follow the convention
