### ISSUE TITLE
Replace links to the Cloudbees CI

### ISSUE THREAD

**Issue by ghys** [openhab/openhab-docs#825]
With the Cloudbees CI server gone, references to https://openhab.ci.cloudbees.com/ should be updated to https://ci.openhab.org/ (and mentions of Cloudbees should be removed).

This includes mentions in addon documentations from other repos (modbus1 has one, for example).

**Comment by kaikreuzer** [comment]
Addon documentation should actually never contain links to the Jenkins, so if those are found, I'd suggest to remove them completely.

**Comment by MyRaceData** [comment]
The installation overview of all places has a dead link pointing at cloudbees.com in Setup variants section. See here:
https://www.openhab.org/docs/installation/#setup-variants
Although this is not the addon documentation it is a very prevalent document with a dead link
