### ISSUE TITLE
openHAB 2 on Linux - var/log not as share in SAMBA config

### ISSUE THREAD

**Issue by ClausAngermeier** [openhab/openhab-docs#831]
It might make sense to have a share for the logs in the Samba config example also.

**Comment by MyRaceData** [comment]
Please add link to the Samba config example that needs edited

**Comment by ClausAngermeier** [comment]
Yes the section you linked is the right one.

I'm not an linux expert, I just used the repository installation as per this instruction on Debian. And in my installation the openhab logs are stored at: /var/log/openhab2


My SAMBA config:

```
[openHAB2-userdata]
  comment=openHAB2 userdata
  path=/var/lib/openhab2
  browseable=Yes
  writeable=Yes
  only guest=no
  public=no
  create mask=0777
  directory mask=0777

[openHAB2-conf]
  comment=openHAB2 site configuration
  path=/etc/openhab2
  browseable=Yes
  writeable=Yes
  only guest=no
  public=no
  create mask=0777
  directory mask=0777

[openHAB2-logs]
  comment=openHAB2 logs
  path=/var/log/openhab2
  browseable=Yes
  writeable=Yes
  only guest=no
  public=no
  create mask=0777
  directory mask=0777

```

**Comment by Maurits28** [comment]
This issue can be closed.
Regards, Maurits

**Comment by Confectrician** [comment]
Totally right. Good catch. Thank you.
