### ISSUE TITLE
Add supported Eclipse versions to IDE Installation

### ISSUE THREAD

**Issue by amosk** [openhab/openhab-docs#834]
https://github.com/openhab/openhab-docs/blob/master/developers/development/ide.md has a screenshot showing Eclipse Mars. In my experience Mars did not work and Photon was required for a successful installation (Mac OS Mojave). See also https://community.openhab.org/t/conflicting-dependencies-fresh-ide-install-on-mac-mojave/60715/3

If the supported Eclipse versions were specified in step 4 that would be a benefit to newcomers. Also, textual data are also easier to update than screenshots. 

Note that https://www.eclipse.org/smarthome/documentation/development/ide.html has a screenshot showing Eclipse Proton is selected, so ESH and OH are out of sync.

Is there a reliable source for the officially supported version of Eclipse? And can this be leveraged to automatically update the IDE installation guide?

**Comment by Confectrician** [comment]
#1927 adresses this partly.

I am not sure how we can do this long term with an "easy to maintain" solution.
