### ISSUE TITLE
yahooweather binding example - extra quotation marks

### ISSUE THREAD

**Issue by hynekprokop** [openhab/openhab-docs#84]
Hi,

[Here](http://docs.openhab.org/addons/bindings/yahooweather/readme.html#full-example) is a small mistake I think. 

Instead of:
`yahooweather:weather:berlin [ location="638242" ]`

should be:
`yahooweather:weather:berlin [ location=638242 ]`

**Comment by kaikreuzer** [comment]
Thanks for the report, this will be fixed with https://github.com/eclipse/smarthome/pull/2130.
