### ISSUE TITLE
Search returns incomplete results

### ISSUE THREAD

**Issue by LightIsLife** [openhab/openhab-docs#842]
Just noticed that searching the docs for "Profile" does not deliver the link where this new concept is explained. Using the search function, I was expecting to find this link: https://www.openhab.org/docs/configuration/items.html#profiles 

However, this link was not returned by the search, see screenshot below:
<img width="597" alt="screen shot 2018-12-31 at 10 10 02 am" src="https://user-images.githubusercontent.com/24855935/50557312-63536f80-0ce4-11e9-8808-5782b731c3b0.png">

**Comment by Confectrician** [comment]
@ghys can you jump in here.
This issue should be transferred to the website repo. I don#t think that we can do much here in the docs repo.

**Comment by LightIsLife** [comment]
Oops, Apologies and thanks @Confectrician, posted it here https://github.com/openhab/website/issues/140 will close this issue

**Comment by Confectrician** [comment]
No need for apologies and thanks for moving the issue. 🙂
