### ISSUE TITLE
Add link "How to ask a good question" to the openHAB introduction page

### ISSUE THREAD

**Issue by Maurits28** [openhab/openhab-docs#845]
There is an excellent post on the forum on how to ask a good question from @vzorglub : "How to ask a good question: Help us help you" [https://community.openhab.org/t/how-to-ask-a-good-question-help-us-help-you/58396](url). 

I suggest to add a link to this post on the introduction page:
[https://www.openhab.org/docs/#the-openhab-community](url)

**Comment by Maurits28** [comment]
@Confectrician If you agree with it, I can make a PR for this.

**Comment by Confectrician** [comment]
Yeah of course. :)

Provide a PR.
I am not yet sure about the phrasing but we can discuss/improve/edit this in the PR then. 🙂

**Comment by Maurits28** [comment]
Ok, I try to find this page (it does not have Github link on the website) but I do not know which page to fork to create a PR. Maybe we should add the Github link to this page as well.

**Comment by Confectrician** [comment]
You are looking for:
https://github.com/openhab/openhab-docs/blob/master/introduction.md


The links are generated automatically.
I don't know what is the limitation, that caused the behavior (no link present) in this page.

@ghys can we add an edit link if we give some front matter/metadata for this page?

**Comment by LightIsLife** [comment]
Thought you may want to know about my proposed revisions of the whole Intro section, addressing also this issue:  https://community.openhab.org/t/introduction-in-docs-proposed-rewrite/62772

**Comment by Maurits28** [comment]
Excellent, works for me.
