### ISSUE TITLE
IFTTT Integration (part of Ecosystem) has no basic activation instructions 

### ISSUE THREAD

**Issue by Maurits28** [openhab/openhab-docs#846]
If you look at the IFTTT page [()](https://www.openhab.org/docs/ecosystem/ifttt/) it is part of  EcoSystem but does not give general configuration information like Apple HomeKit. You will find the information when you go to the link to myopenhab.org, where it shows the following information:

_Activating the IFTTT integration is easy. Just log in to your IFTTT account and activate the openHAB channel. You will be forwarded to the myopenHAB website to authorize the IFTTT channel connection. Before you start creating IFTTT recipes you need to make sure that you have your runtime configured to expose certain items to myopenHAB. Only those items will be visible to IFTTT. You will also be able to send commands to those items from IFTTT Applets. Items will appear in myopenHAB and thus in IFTTT only after at least one state update has been received by myopenHAB from your runtime._

This will already be a good start for users to understand what to do.
As a 2nd point, more aesthetic, all the images are quite large and make that you loose track of where you are on the page. 

If people see this also as an improvement, I'll submit a PR.

**Comment by Maurits28** [comment]
I submitted a PR, would be great to get some feedback from maintainers.

Regards

**Comment by Maurits28** [comment]
@Confectrician This issue can be closed as it is solved with
[https://github.com/openhab/website/pull/142](url)

**Comment by Confectrician** [comment]
AH thanks for the catch @Maurits28 👍
