### ISSUE TITLE
Coding tasks' implementation

### ISSUE THREAD

**Issue by kirilAtan** [openhab/openhab-docs#85]
Hello I think it would be a good idea to add implementations to the OSGI Coding tasks in http://docs.openhab.org/developers/prerequisites/osgitasks.html because it will be very beneficial for the beginners to see sample code with the tasks. I would like to implement them.

I want to align where will be the most appropriate place to store them. I would suggest to create a new repository named "openhab-osgi-samples"

I believe it would be best if there is a different PR for every task.

Awaiting your response

**Comment by kaikreuzer** [comment]
I wouldn't mind if we'd simply create a "sample" branch within this repo here - no need for a separate repo, I guess.

**Comment by kirilAtan** [comment]
Could you create a sample branch "osgi-coding-tasks-samples" for me? Then I will submit my implementations as pull requests to it.

**Comment by ThomDietrich** [comment]
Are you really talking about a git branch? Why not just create a subfolder at the appropriate place :question:

**Comment by kaikreuzer** [comment]
@ThomDietrich Everything that is in the (default) gh-pages branch ends up being processed by Jekyll for the docs.openhab.org website - that's why I would prefer a "code" branch for this. Ok for you?

**Comment by ThomDietrich** [comment]
I would rather stay with one branch.
If this is the solution you wanna go with, I will not steer against it.
My preferred solution would be a non-jekyll-folder exluded in the config file with `exclude: foldername`

**Comment by kaikreuzer** [comment]
> I would rather stay with one branch.

Ok for me, I don't really have a strong opinion about that.

So @kirilAtan No need for me to create a new branch then.
