### ISSUE TITLE
Add information about Add-On source to the documentation

### ISSUE THREAD

**Issue by MHerbst** [openhab/openhab-docs#876]
The documentation contains information about Add-Ons that are maintained in different repositories. We have 
* Eclipse Smarthome
* openHAB 
* openHAB 1

Especially for new users it is not obvious where an add-on is developed and in which repo he has to create issues. This leads quite often to issues in the wrong repo.

I would therefore suggest to add some information to the documentation about the add-on's source. 
The tool used to generate the docs from the repos knows about the sources and therefore be able to automatically supplement such information

One option could be adding a "badge" to the add-on list in the sidebar, e.g.
![image](https://user-images.githubusercontent.com/616792/51342633-ad827200-1a94-11e9-96e1-0e3ec40c9156.png)

**Comment by Confectrician** [comment]
Hey @ghys, 

I think the addons-sidebar is still configured within the website repo, so this would be something for over there.
Maybe you can point me to the correct file and i could give it a try.

**Comment by ghys** [comment]
You're right about the add-ons sidebar, it's generated during the website build, not here.

It's also true we're able to determine the source of an add-on with this code (for the "edit" link) and could add info or a link to the issues list of the proper repo.
It's not possible to add badges in the sidebar however. Only in headers (https://v0.vuepress.vuejs.org/guide/using-vue.html#badge). Could be done on the fly by the script (it already adds the logo to the page if found).

**Comment by MHerbst** [comment]
> Could be done on the fly by the script

Sounds good. I think this would definitely help. We would probably have to add some remarks about this information. Maybe on the "Add-On Reference" start page.

**Comment by Confectrician** [comment]
Meanwhile outdated, because we have only one source left after OH3.
