### ISSUE TITLE
[MQTT Binding] Inconsistency between documentation and example

### ISSUE THREAD

**Issue by marcelerkel** [openhab/openhab-docs#880]
https://www.openhab.org/addons/bindings/mqtt/

The documentation states:

> * secure: Uses TLS/SSL to establish a secure connection to the broker. Can be "OFF","ON","AUTO".     The AUTO setting prefers a secure connection but will fall-back to an insecure one. Default is ON.

However, the examples use true/false instead of ON/OFF. 

> mqtt:broker:mySecureBroker [ host="192.168.0.41", secure=true, certificatepin=true, publickeypin=true ]
> mqtt:broker:myUnsecureBroker [ host="192.168.0.42", secure=false ]

I can create a PR for this, but I need to know what it should be:

1. true/false are correct
2. ON/OFF/AUTO are correct
3. Both true/false and ON/OFF/AUTO are correct

@davidgraeff Could you give me a hint?

**Comment by Confectrician** [comment]
> A PR would be marvelous.

Here is the correct readme location for improvements:
https://github.com/openhab/openhab2-addons/blob/master/addons/binding/org.openhab.binding.mqtt/README.md
