### ISSUE TITLE
Buggy IDE setup

### ISSUE THREAD

**Issue by mnlipp** [openhab/openhab-docs#887]
I went through [the instructions](https://www.openhab.org/docs/developer/development/ide.html#setting-up-an-ide-for-openhab) twice, but all I end up with is a "partially" working openHAB. I have NTP and AstroTime, but the Add-ons page looks like this:
![grafik](https://user-images.githubusercontent.com/1446020/52047180-bcfbc380-2548-11e9-8636-b456502f111e.png)

It seems like the available add-ons from the workspace aren't detected but there are some "left-overs" in the prepared configuration.

**Comment by kaikreuzer** [comment]
The setup is all fine. The add-ons in the Paper UI are dummy ones - the distro shows add-ons from Karaf features, which simply do not exist in the IDE.
If you want to launch with certain add-ons active, simply select them in your launch configuration and see Paper UI -> Configuration -> Bindings to see whether they are active or not.

**Comment by mnlipp** [comment]
Okay, got it. The "Add-ons" is basically a GUI for installing bundles/features into the OSGi-Runtime. And when I start the runtime with the bundle, it's already there.

Having tried the distribution first and seen the "real" page, it's a bit irritating, though.
