### ISSUE TITLE
Docker Installation Instructions

### ISSUE THREAD

**Issue by rkoshak** [openhab/openhab-docs#90]
Is it reasonable and feasible to simple replace the contents of installation/Docker.md with the README.md on the Docker's GitHub repo? Or maybe we should just point there? Or we could even just change the link for the Docker instructions to go directly to the Docker Hub site.

I started to add the docker pull instructions to the documents and realized that the entire page is basically lifted from the README.md anyway. In the interest of only having this documented once...
##

**Comment by ThomDietrich** [comment]
https://github.com/openhab/openhab-docker

You make a fair point. The instructions that can be found in the README should not be repeated in docs.openhab.org - this also means we should not sync them to docs I think.
I looked through the README and it only contains the minimum information required for someone acquainted with docker. I would suggest an article like the one for the [Raspberry Pi](http://docs.openhab.org/installation/rasppi.html) for Docker, linking the README for specifics on installation and usage.

"Docker is a system for ... (links and stuff). The advantages and disadvantages are... If you want to use openhab-docker, follow the instructions in the README."

What do you think?

**Comment by rkoshak** [comment]
I'm good with that. There are also some caveats with using Docker that people should be aware of. For instance, the Exec binding is executing within the context of the Docker container. So if you want to do something like your Speedtest-cli example, you either need to change the Exec command to ssh out of the container and into your main machine or install Python and everything else you need into the Docker Image. I'm finding more such gotchas as I experiment and transition my config over.

**Comment by rkoshak** [comment]
I've written the article here:

https://community.openhab.org/t/running-openhab-2-in-docker/14267

There have been no comments thus far. If everyone here is happy with the content I'll create the PR.

**Comment by cniweb** [comment]
Hi @rkoshak,

LGTM!
But consider this: openhab/openhab-distro#318

Thanks,
Chris

**Comment by ThomDietrich** [comment]
@rkoshak what's the status here?

**Comment by rkoshak** [comment]
Reworking the article based on new experience I gained rebuilding my system from scratch. Plan on submitting a PR this weekend.

**Comment by cniweb** [comment]
@ThomDietrich I think ou can close this issue, thanks.

**Comment by ThomDietrich** [comment]
Wonderful. Thanks!
