### ISSUE TITLE
The UIs and classic iconset have disappeared from the final branch

### ISSUE THREAD

**Issue by ghys** [openhab/openhab-docs#904]
As of https://github.com/openhab/openhab-docs/commit/f59c6dd5a62e5c99198409c6b72e8b585a9e7edd and Jenkins build https://ci.openhab.org/view/Documentation/job/gather-external-docs/170/

**Comment by ghys** [comment]
This is in part caused by the removal of the UIs from the openhab-bundles repo.
https://github.com/openhab/openhab-bundles/commit/d7728a8575134a497c6f2d54e6b092d153bb27ce

Need to review and update [update-external-resources.sh](https://github.com/openhab/openhab-docs/blob/final/update-external-resources.sh) and/or [process_addons.groovy](https://github.com/openhab/openhab-docs/blob/final/process_addons.groovy).

**Comment by Confectrician** [comment]
Hey @ghys,

I was busy the whole week but will try to provide a fix within the weekend.
Moving the ui part to that new repo shouldn't be that difficult.

**Comment by ghys** [comment]
Hi @Confectrician,

Did you have time to take a look? The website build is broken because of this, so it's kind of important ;)
If this requires a change to the Ruby script on the website side please let me know!

**Comment by Confectrician** [comment]
Hey @ghys 

I am on it.
Hopefully i can provide a WIP pr tonight.

**Comment by martinvw** [comment]
It seems that this issue can be closed

cc: @openhab/documentation-maintainers

**Comment by Confectrician** [comment]
Hm i mentioned it in the pr.
Maybe wrong keyword.
