### ISSUE TITLE
Add-on documentation missing due to repo layout changes

### ISSUE THREAD

**Issue by wborn** [openhab/openhab-docs#918]
As part of https://github.com/openhab/openhab2-addons/issues/5005 the openhab2-addons layout is changed. This causes the documentation of the migrated add-ons (astro, avmfritz, dmx, openweathermap) to be unavailable (see https://github.com/openhab/openhab2-addons/issues/5108).

I.e. the following links result in a 404 Not Found:
* https://www.openhab.org/addons/bindings/astro/
* https://www.openhab.org/addons/bindings/avmfritz/

All add-on bundles are moved to this [bundles](https://github.com/openhab/openhab2-addons/tree/master/bundles) directory. Similarly to this openhab-core [bundles](https://github.com/openhab/openhab-core/tree/master/bundles) directory. The directory layout will be flat and the bundles of other add-on types (extensionservice, io, persistence, transform, voice) are also added to this directory.

**Comment by Confectrician** [comment]
Hi,

First:
I have to touch the maven build again to include the bundles folder.

Second:
Are there any other plans for structural changes?
Maybe it would be cool to get this info before moving stuff,
so i could prepare the necessary changes and launch them at time of change in the corresponding addon repo.
Maybe there are already planned cahnges in the pipe. 🙂

**Comment by Confectrician** [comment]
I see another Problem here.

Is it correct, that we will have to identify the type each bundle with its folder name (org.openhab.BINDING or org.openhab.PERSISTENCE) ?

**Comment by wborn** [comment]
Thanks for working on this @Confectrician! :+1: 

Using the folder name is indeed the most logical way to do the identify the add-on types.

> Are there any other plans for structural changes?

When other add-on repositories are migrated to a bnd build they are most likely also restructured using the the same bundles layout. See https://github.com/openhab/openhab-webui/issues/38.

**Comment by Confectrician** [comment]
Maybe one of the maven pros can give me some guidance then in this ant pattern stuff.
Are you familiar with the pom.xml files?

**Comment by wborn** [comment]
Yes I have probably seen thousands. :-)

**Comment by Confectrician** [comment]
Yeah, i have seen hundreds too already. 😄 
But i would not call me an expert.

I think i've found a solution which should do the trick. (It seems to work on my machine)
I will provide a WIP PR now and if you agree with my idea, we can prepare taht for other addon types too directly. :)

**Comment by Confectrician** [comment]
Latest build works and fetche the correct repos from the bundles folder.

**Comment by wborn** [comment]
Thanks for the prompt resolution @Confectrician ! It's working great again. :trophy::1st_place_medal:

**Comment by Confectrician** [comment]
Hopefully we are also a bit future aware now, when other bundle types get mirgrated.
We should have an eye on that.
