### ISSUE TITLE
Anchors {: #name} don't work

### ISSUE THREAD

**Issue by MrWaZZup** [openhab/openhab-docs#923]
Steps to reproduce:
0. Disable all plugins
1\. Go to https://www.openhab.org/docs/installation/openhabian.html
2\. In the "Features" section try links in the following lines: 
- Hassle-free setup without a display or keyboard, connected via [Ethernet or Wi-Fi](https://www.openhab.org/docs/installation/openhabian.html#wifi-setup)
- [openHABian Configuration Tool](https://www.openhab.org/docs/installation/openhabian.html#openhabian-config) including updater functionality

These links don't navigate to a desired paragraph. While links in the "Table of Content" actually work (notice that anchors differ):
- [Wi-Fi based Setup Notes](https://www.openhab.org/docs/installation/openhabian.html#wi-fi-based-setup-notes)
- [openHABian Configuration Tool](https://www.openhab.org/docs/installation/openhabian.html#openhabian-configuration-tool)

The _openhab-docs/installation/openhabian.md_ file contains corresponding anchors for the first kind of links:
`{: #wifi-setup}`
`{: #openhabian-config}`
The problem is they don't appear in the HTML source of [openhabian.html](https://www.openhab.org/docs/installation/openhabian.html)

Same issue for all other anchors with {: #name} syntax.

**Comment by ghys** [comment]
This syntax was for the previous docs, and is not supported anymore, they should be removed and links to specific paragraphs adapted to the autogenerated anchors.
