### ISSUE TITLE
Problem with mapdb persistence addon processing

### ISSUE THREAD

**Issue by ghys** [openhab/openhab-docs#926]
See https://github.com/openhab/openhab-docs/tree/final/_addons_persistences.

There's a mapdb and a new oh2/org.openhab.persistence.mapdb that shouldn't be there like that.

**Comment by Confectrician** [comment]
Seems that somethigns gone wrong while updating the scripts for the new bnd builds.

**Comment by Confectrician** [comment]
Maybe related openhab/openhab2-addons#5352

**Comment by ghys** [comment]
> Maybe related openhab/openhab2-addons#5352

Yes it is - we talked about it on Slack with Kai.
We might also still need to remove the oh2 folder from the final branch manually (with a PR/commit).

**Comment by Confectrician** [comment]
I will look for a solution and remove the folder while provding the solution PR.

**Comment by ghys** [comment]
No need, it seems it has been fixed after all in https://github.com/openhab/openhab-docs/commit/f4be7d63fac279bceb1fba93c4be3068497b29f5. So I will close this.

**Comment by Confectrician** [comment]
Then the deleted readme already did the trick. :)
