### ISSUE TITLE
Developer guide to logger configuration

### ISSUE THREAD

**Issue by svilenvul** [openhab/openhab-docs#93]
I would like to add a short page about how to configure the logger during development:

- a few words about the logger that is used - logback;
- required bundles;
- creating an individual logback config file (or modifying the existing one);
- some example patterns and link to the logback official site with more information.

I will appreciate any comments. Do you think this page will be helpful? Where will be the right place to add it - maybe in the "Basics" tab?

**Comment by kaikreuzer** [comment]
Yes, sounds helpful.
Not sure what is the best place - for now "Basics" sounds best. Once we get more topics, we will probably have to think about some improvements on the menu.

**Comment by svilenvul** [comment]
I think this can be closed now.
