### ISSUE TITLE
Web UIs structure changed

### ISSUE THREAD

**Issue by ghys** [openhab/openhab-docs#937]
The structure of the openhab-webui repo has changed with https://github.com/openhab/openhab-webui/pull/44 which must be reflected in the gathering of the UI docs; the script should be adapted to look in the "bundles" directory. 

Note that the website build is currently broken because of this (https://app.netlify.com/sites/openhab-website/deploys/5cb11abca6961bec08533044).

**Comment by Confectrician** [comment]
I'm very glad, when bnd migration is done finally^^

Will take care of this tomorrow, when time fits.

**Comment by Confectrician** [comment]
![image](https://user-images.githubusercontent.com/7161177/56089818-1a8d8400-5e99-11e9-9f74-64cc3a5a15d5.png)

**Comment by ghys** [comment]
Nice work @Confectrician!
There's one small problem with the iconset:
```
9:28:29 AM: [...] No such file or directory @ rb_file_s_stat - .vuepress/openhab-docs/_addons_iconsets/classic/src/main/resources/icons (Errno::ENOENT)
```
The classic iconset used to end up in `_addons_iconsets/classic` and is now in `_addons_iconsets`.
If it's not an easy fix to bring it back like before I can adapt the script on the website side.

**Comment by Confectrician** [comment]
Gnah, seems i missed that one, since they changed something more with the icons.
Give me 10 Minutes. 🙂

**Comment by Confectrician** [comment]
OK. I have to look that up in detail.
Seems this one is done in the groovy script.

I will try to check it tonight and roll back if i can't find an easy solution.

**Comment by Confectrician** [comment]
Hey @ghys,

I have invested some time and we should have a working solution in the next minutes.
