### ISSUE TITLE
Developer section: Thing specific discovery

### ISSUE THREAD

**Issue by davidgraeff** [openhab/openhab-docs#953]
There is currently only a placeholder on how to write thing specific discovery.

This is a very common pattern in openHAB bindings. The old way was to register/unregister such services in the thing factory. The new way is to use `getServices()`. 

Unfortunately there are still shortcomings in openHAB core that prevent this to work correctly. Those need to be addressed first before this part of the documentation can be finalized.

**Comment by Confectrician** [comment]
#1262
