### ISSUE TITLE
Developer section: New buildsystem IDE setup

### ISSUE THREAD

**Issue by davidgraeff** [openhab/openhab-docs#955]
We have no working IDE setup at the moment and therefore no complete guide in the developer section on how to setup a proper build environment.

As soon as the bnd migration is finished and the openHAB distro is fully bnd centric this section need to be (re)written.

I propose to guide in a pictureful way through setting up:

* Eclipse
* Intellij
* Visual Studio Code

**Comment by mvalla** [comment]
working on a very first version of the Eclipse section with images

**Comment by mvalla** [comment]
completed a first version of the guide for the Eclipse IDE see #968

**Comment by tmrobert8** [comment]
FYI - first version on the VSCode instructions:

https://github.com/openhab/openhab-docs/pull/994

**Comment by mvalla** [comment]
new version of the Eclipse IDE instructions using Eclipse Installer & openhab-distro 
(not depending on maggu2810/openhab-demo anymore).

#995

**Comment by Jochen1980** [comment]
The Link zu OpenJDK installation brings you to Oracle and I guess the most preferred way is to install Zulu? 
see https://www.openhab.org/v2.4/docs/developer/development/ide.html

**Comment by zephod77** [comment]
> completed a first version of the guide for the Eclipse IDE see #968

Can I add a request that there be an Eclipse IDE setup guide for when you are not installing Eclipse from scratch? In other words assume that a user already has a Java development environment set up and they just want to import the openHAB sources.

**Comment by kaikreuzer** [comment]
@zephod77 I'd think this would easily get complicated. The whole idea of the Oomph setup is to simplify and homogenize the IDE setup and by this, simplify the support.

**Comment by zephod77** [comment]
@kaikreuzer My issue is that I have several other projects besides openHAB and so I use a C++ development plugin, a Python development plugin and a modeling plugin to name a few as well as the Java development plugin. In fact, before this reorganization started, I was using the modeling tool to generate the Java code for a binding. To have to reload and reconfigure those each time is not a viable solution for me. 

It might well be very complicated but the requirements to a "working" system must be known and so it should be possible.

**Comment by openhab-5iver** [comment]
> To have to reload and reconfigure those each time is not a viable solution for me.

Why couldn't you use a separate Eclipse installation for OH?

**Comment by zephod77** [comment]
I could but that's not the ideal solution. I would probably make a separate user with separate .m2 and .git directories just to develop openHAB but I would still have to reload the other plugin I want to use during development. Either way, I'd still like to know what the requirements are for setting up an openHAB development system.

**Comment by lsteelandt** [comment]
Is there Any move on Eclipse Build Environment ?
By following the [step-by-step guides for Eclipse](https://www.openhab.org/docs/developer/ide/eclipse.html), I am not able to launch a debug session of the add-on example (astro).

I get an error on pom.xml file concerning **biz.aQute.bnd:bnd-maven-plugin**. 

Excepting modifying the pom.xml as describe on the guide (to specify  "astro" in the <articfactID> entry), I did not change any file. 

I am working on Mac OS X and my Maven environnement is this one :
mvn --version

Apache **Maven 3.6.3**** (cecedd343002696d0abb50b32b541b8a6ba2883f)
Maven home: _<somes folders>_/apache-maven-3.6.3
**Java version: 1.8.0_163**, vendor: Azul Systems, Inc., runtime: /Library/Java/JavaVirtualMachines/**zulu-8.jdk**/Contents/Home/jre
Default locale: fr_FR, platform encoding: UTF-8
OS name: "mac os x", version: "10.15.1", arch: "x86_64", family: "mac"


Did the step-by-step guides for Eclipse miss something ?

**Comment by Hilbrand** [comment]
I think this issue can be closed. There is documentation for all 3 IDE's.

**Comment by Hilbrand** [comment]
And it cal also be unpinned :smile:
