### ISSUE TITLE
nginx example is missing two configurations

### ISSUE THREAD

**Issue by BClark09** [openhab/openhab-docs#98]
I believe that the documentation for the nginx reverse proxy is misconfigured: I believe that proxy_buffering by default should be disabled, since the server will try to wait for the full message recieved from event source objects such as //rest/events?topics=smarthome/items/*/state.
```
proxy_buffering                         off;
```

Secondly, the server at that configuration will not forward https links in REST unless the following is specified:
```
proxy_set_header X-Forwarded-Proto      $scheme;
```
In the documentation "X-Forwarded-Scheme" is set but I don't think this is a valid header. I will send a pull request for the above but wanted to bring it as an issue in case I've missed any reasoning behind this.

Finally, would it be worth it to make a full tutorial on using an nginx reverse proxy with openhab, which includes setup, basic authentication and ssh encryption/renewal?

**Comment by ThomDietrich** [comment]
Thanks for your addition! I'm no expert in that field but it seems like you know what you are doing. Could you post one-two URLs regarding these topics?

"Tutorial" - absolutely! Are you talking about this page? http://docs.openhab.org/configuration/jetty.html
Please extend it as far as you like :wink: Especially interested in a writeup on authentication. Remember that there are already postings regarding that topic in the community forum. Please have a look to cover everything.

On a side note: I wanted to add both authentication and SSL to openHABian as optional steps. When you are in the process of collecting the needed steps, feel free to report them here: https://github.com/ThomDietrich/openhabian/issues/12 Thanks! ;)

**Comment by BClark09** [comment]
Not a problem! I'm actually fairly new to nginx, but I was having a couple of issues with it to try and investigate the cause:

Firstly, when doing a simple benchmark on the Basic UI, I found that items were taking ages to update using the debugging tools you can see that one of the items gets stuck on pending:

![image](https://cloud.githubusercontent.com/assets/8983584/18717579/3f5878e2-8018-11e6-8ba4-52452498aa24.png)

Secondly, `curl -X GET --header "Accept: application/json" "https://xxx.xx.xx/rest/sitemaps"` always returned: ` "link": "http://xxx.xx.xx/rest/sitemaps/default",`

After reading up on how nginx caches the response from the server: https://www.nginx.com/blog/nginx-caching-guide/ I assumed that the server was holding the request until it completed, setting proxy_buffering to off cleared the first issue.

After trying to find out what X-Forwarded-Scheme does, I couldn't find any documentation, but I do know X-Forwarded-Proto is the useful header here (https://en.wikipedia.org/wiki/List_of_HTTP_header_fields) and setting it so solved the second issue, as well as a problem I was having with HABDroid, where I could only a sitemap once per login. 

Hope this helps explain my reasoning. I should have some time on my hands to complete a tutorial this weekend, fortuantely I am using the RPi so these steps will translate very well for openHABian, including automatic renewal.

**Comment by ThomDietrich** [comment]
@kaikreuzer Is this in any way related to https://github.com/eclipse/smarthome/pull/2030 ?

**Comment by resetnow** [comment]
@BClark09 the one “stuck” request is a server-side event stream, it's supposed to be stuck and it never ends under normal circumstances.

**Comment by BClark09** [comment]
@resetnow This is still the case when proxy buffering is off, but the server at least sends an "OK" response for the item.

![image](https://cloud.githubusercontent.com/assets/8983584/18724602/eaa69e60-8034-11e6-8a73-a4e386285d25.png)

It might be coincidental, but I'm definitely getting performance issues with it left on.

**Comment by ThomDietrich** [comment]
On a side note: It would be reasonable to rename the file `jetty.md` while you are in the process of rewriting it. Be it "nginx", "security" or whatever you think suits best ;)

**Comment by BClark09** [comment]
Currently I've kept jetty.md and added nginx.md as a separate page, whilst I don't know much about Jetty, I still think it'll be worth writing about the configuration of Jetty itself. I wouldn't elect myself to write this though, so would you rather me remove the page until someone else has some input to it, or should I keep the page with a "To Do:" label.

**Comment by BClark09** [comment]
@ThomDietrich I assumed the former, and have pushed the tutorial to the PR. I hope formatting/style/spelling is correct!
