### ISSUE TITLE
Missing content for Profiles

### ISSUE THREAD

**Issue by 5iver** [openhab/openhab-docs#981]
I was trying to look up how to up how to use profiles. I found this through an Internet search...

https://www.openhab.org/docs/developer/transformations/#profile-properties

... but this is not displayed in the sidebar or in the docs search, and it is incomplete. There is some more detail in...

https://www.openhab.org/docs/developer/transformations/#existing-profiles

... but this list is also not complete. I don't have time ATM to document this, so I thought I'd just create the issue to bring it to everyone's attention.

**Comment by Confectrician** [comment]
I think this could be closed.

We have an overviwe on https://www.openhab.org/docs/configuration/items.html#profiles now.
