### ISSUE TITLE
[windows.md] Windows installation not correct

### ISSUE THREAD

**Issue by tmrobert8** [openhab/openhab-docs#996]
The windows installation page is incorrect.  I'll be submitting a PR shortly to fix it

**Comment by nwilson1412** [comment]
Not exactly sure what is incorrect from your issue. 

Windows installation page is incorrect for me though, due to the default port showing 8080, not 8443

**Comment by tmrobert8** [comment]
"There is currently no automatic update script for Windows" - that whole section needs to be rewritten since backup/update scripts have been available for awhile (they atleast match the linux ones and have a few more features actually).  The windows installation will eventually need to be rewritten as well for the new installer once it get's accepted
